<?php
// Extend the TCPDF class to create custom Header and Footer
$configFile = CONFIG_PATH . DIRECTORY_SEPARATOR . "label.php";
$fileContents=file_get_contents($configFile);
//Convert the JSON string back into an array.
$decoded = json_decode($fileContents, true);
$language = $configData['language'];
class MYPDF extends TCPDF {
    
    public function setSchemeName($header,$logo) {
	$this->header = $header;
	$this->logo = $logo;
    }
	
    //Page header
    public function Header() {
        // Logo
        if(trim($this->logo)!="" && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo'. DIRECTORY_SEPARATOR.$this->logo)){
	    $image_file = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo'. DIRECTORY_SEPARATOR.$this->logo;
	    $this->Image($image_file, 12,3,20, '', 'PNG', '', 'T', false, 300, 'L', false, false, 0, false, false, false);
	}
        // Set font
        $this->SetFont('helvetica', 'B', 12);
        // Title
        $this->writeHTMLCell(0,'',54,10,$this->header,0,1,false,true,'C',true);
        $this->writeHTMLCell(180,'',15,'','<br/><hr/>',0,1,false,true,'C',true);
    }

    // Page footer
    public function Footer() {
        // Position at 15 mm from bottom
        $this->SetY(-15);
        // Set font
        $this->SetFont('helvetica', 'I', 8);
        // Page number
        $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
    }
}

// create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

$pdf->setSchemeName(ucwords($configData['header']),$configData['logo']);
// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Nicola Asuni');
$pdf->SetTitle('SPI-RT Checklist');
$pdf->SetSubject('TCPDF Tutorial');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');


// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}
// ---------------------------------------------------------

// set font
$pdf->SetFont('times', '', 10);

// add a page
$pdf->AddPage();
//$pdf->SetY(20,true,false);

$partA='<p style="font-weight:bold;line-height:24px;">'.$decoded[$language]['/SPI_RT/TESTSITE/FACILITY/info2:label'].'</p>';
//$partA.='<br/>';

$pdf->writeHTML($partA, true, 0, true, 0);

$pdf->writeHTMLCell('',12,'','','<p>Before completing the checklist, it is important to characterize the testing point to be audited. Please provide relevant information in the summary table below.</p>',0,1,false,true,'L',true);

$testingTab='<table border="1" cellspacing="0" cellpadding="5">';

$testingTab.='<tr>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/assesmentofaudit:label'].'</b>(dd/mm/yyyy): '.$this->humanDateFormat($formData['assesmentofaudit']).'</td>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/auditroundno:label'].'</b> '.$formData['auditroundno'].'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/facilityname:label'].'</b> '.$formData['facilityname'].'</td>';
$testingTab.='<td><b>Testing Facility ID</b>(if applicable) : '.$formData['facilityid'].'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/testingpointname:label'].'</b> '.$formData['testingpointname'].'</td>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/testingpointtype:label'].'</b>'.$formData['testingpointtype'];
$testingTab.=((isset($formData['testingpointtype_other']) && $formData['testingpointtype_other'] != "") ? " - " . $formData['testingpointtype_other']: "").'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td colspan="2"><b>'.$decoded[$language]['/SPI_RT/TESTSITE/locationaddress:label'].'</b> '.$formData['locationaddress'].'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/level:label'].'</b> <br/>'.$formData['level'];
$testingTab.=((isset($formData['level_other']) && $formData['level_other'] != "") ? " Other - " . $formData['level_other'] : "").':'.$formData['level_name'];
$testingTab.='</td>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/affiliation:label'].'</b><br/>'.$formData['affiliation'];
$testingTab.=((isset($formData['affiliation_other']) && $formData['affiliation_other'] != "") ? " Other : " . $formData['affiliation_other'] : "");
$testingTab.='</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/NumberofTester:label'].'</b>'.$formData['NumberofTester'].'</td>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/avgMonthTesting:label'].'</b>'.$formData['avgMonthTesting'].'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/name_auditor_lead:label'].'</b>'.$formData['name_auditor_lead'].'</td>';
$testingTab.='<td><b>'.$decoded[$language]['/SPI_RT/TESTSITE/name_auditor2:label'].'</b>'.$formData['name_auditor2'].'</td>';
$testingTab.='</tr>';

$testingTab.='</table>';

$pdf->writeHTML($testingTab, true, 0, true, 0);

$partBHeading='<b>'.$decoded[$language]['/SPI_RT/SPIRT/info4:label'].'</b>';

$pdf->writeHTML($partBHeading, true, 0, true, 0);


$partBCont='<br/><div>'.$decoded[$language]['/SPI_RT/SPIRT/info4:hint'].'State N/A in the comments section if "not applicable" where appropriate (*).</div>';

$pdf->writeHTML($partBCont, true, 0, true, 0);

$partBTable='<table border="1" cellspacing="0" cellpadding="5" style="width:100%;">';
$partBTable.="<tr>";
$partBTable.='<td style="text-align:center;font-weight:bold;width:52%;">SECTION</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;width:7%;">YES</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;width:8%;">Partial</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;width:7%;">NO</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;width:18%;">Comments</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;width:8%;">Score</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;background-color:#dddbdb;">'.$decoded[$language]['/SPI_RT/PERSONAL:label'].'</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">10</td>';
$partBTable.='</tr>';

    for($i=1;$i<11;$i++)
    {
	$partBTable.='<tr>';
	
	$partBTable.='<td style="width:52%;">'.$decoded[$language]['/SPI_RT/PERSONAL/PER_G_1_'.$i.'/PERSONAL_Q_1_'.$i.':label'].'</td>';
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['PERSONAL_Q_1_'.$i]) && $formData['PERSONAL_Q_1_'.$i] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['PERSONAL_Q_1_'.$i]) && $formData['PERSONAL_Q_1_'.$i] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['PERSONAL_Q_1_'.$i]) && $formData['PERSONAL_Q_1_'.$i] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td>'.($formData['PERSONAL_C_1_'.$i]).'</td>';
	$partBTable.='<td style="text-align:center;">'.($formData['PERSONAL_Q_1_'.$i]).'</td>';
	$partBTable.='</tr>';
    }

$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;">'.$decoded[$language]['/SPI_RT/PERSONAL/PERSONAL_Display:label'].'</td>';
$partBTable.='<td style="text-align:center;">'.$formData['PERSONAL_SCORE'].'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;background-color:#dddbdb;">'.$decoded[$language]['/SPI_RT/PHYSICAL:label'].'</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">5</td>';
$partBTable.='</tr>';

    for($i=1;$i<6;$i++)
    {
	
	$partBTable.='<tr>';
	
	$partBTable.='<td>'.$decoded[$language]['/SPI_RT/PHYSICAL/PHY_G_2_'.$i.'/PHYSICAL_Q_2_'.$i.':label'].'</td>';
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['PHYSICAL_Q_2_'.$i]) && $formData['PHYSICAL_Q_2_'.$i] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['PHYSICAL_Q_2_'.$i]) && $formData['PHYSICAL_Q_2_'.$i] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['PHYSICAL_Q_2_'.$i]) && $formData['PHYSICAL_Q_2_'.$i] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td>'.($formData['PHYSICAL_C_2_'.$i]).'</td>';
	$partBTable.='<td style="text-align:center;">'.($formData['PHYSICAL_Q_2_'.$i]).'</td>';
	$partBTable.='</tr>';

    }

$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;">'.$decoded[$language]['/SPI_RT/PHYSICAL/PHYSICAL_Display:label'].'</td>';
$partBTable.='<td style="text-align:center;">'.$formData['PHYSICAL_SCORE'].'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;background-color:#dddbdb;">'.$decoded[$language]['/SPI_RT/SAFETY:label'].'</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">11</td>';
$partBTable.='</tr>';

    for($i=1;$i<12;$i++)
    {
	$partBTable.='<tr>';
	
	$partBTable.='<td>'.$decoded[$language]['/SPI_RT/SAFETY/SAF_3_'.$i.'/SAFETY_Q_3_'.$i.':label'].'</td>';
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['SAFETY_Q_3_'.$i]) && $formData['SAFETY_Q_3_'.$i] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['SAFETY_Q_3_'.$i]) && $formData['SAFETY_Q_3_'.$i] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['SAFETY_Q_3_'.$i]) && $formData['SAFETY_Q_3_'.$i] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td>'.($formData['SAFETY_C_3_'.$i]).'</td>';
	$partBTable.='<td style="text-align:center;">'.($formData['SAFETY_Q_3_'.$i]).'</td>';
	$partBTable.='</tr>';
    }
$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;">'.$decoded[$language]['/SPI_RT/SAFETY/SAFETY_DISPLAY:label'].'</td>';
$partBTable.='<td style="text-align:center;">'.$formData['SAFETY_SCORE'].'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;background-color:#dddbdb;">'.$decoded[$language]['/SPI_RT/PRETEST:label'].'</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">12</td>';
$partBTable.='</tr>';
    
    for($i=1;$i<13;$i++)
    {
    $partBTable.='<tr>';
    
    $partBTable.='<td>'.$decoded[$language]['/SPI_RT/PRETEST/PRE_4_'.$i.'/PRE_Q_4_'.$i.':label'].'</td>';
    $partBTable.='<td style="text-align:center;">';
    $partBTable.=(isset($formData['PRE_Q_4_'.$i]) && $formData['PRE_Q_4_'.$i] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
    $partBTable.='</td>';
    
    $partBTable.='<td style="text-align:center;">';
    $partBTable.=(isset($formData['PRE_Q_4_'.$i]) && $formData['PRE_Q_4_'.$i] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
    $partBTable.='</td>';
    
    $partBTable.='<td style="text-align:center;">';
    $partBTable.=(isset($formData['PRE_Q_4_'.$i]) && $formData['PRE_Q_4_'.$i] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
    $partBTable.='</td>';
    
    $partBTable.='<td>'.($formData['PRE_C_4_'.$i]).'</td>';
    $partBTable.='<td style="text-align:center;">'.($formData['PRE_Q_4_'.$i]).'</td>';
    $partBTable.='</tr>';
    }

$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;">'.$decoded[$language]['/SPI_RT/PRETEST/PRETEST_Display:label'].'</td>';
$partBTable.='<td style="text-align:center;">'.$formData['PRETEST_SCORE'].'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;background-color:#dddbdb;">'.$decoded[$language]['/SPI_RT/TEST:label'].'</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">9</td>';
$partBTable.='</tr>';

    for($i=1;$i<10;$i++)
    {
	$partBTable.='<tr>';
	
	$partBTable.='<td>'.$decoded[$language]['/SPI_RT/TEST/TEST_5_'.$i.'/TEST_Q_5_'.$i.':label'].'</td>';
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['TEST_Q_5_'.$i]) && $formData['TEST_Q_5_'.$i] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['TEST_Q_5_'.$i]) && $formData['TEST_Q_5_'.$i] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['TEST_Q_5_'.$i]) && $formData['TEST_Q_5_'.$i] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td>'.($formData['TEST_C_5_'.$i]).'</td>';
	$partBTable.='<td style="text-align:center;">'.($formData['TEST_Q_5_1']).'</td>';
	$partBTable.='</tr>';
    }
$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;">'.$decoded[$language]['/SPI_RT/TEST/TEST_DISPLAY:label'].'</td>';
$partBTable.='<td style="text-align:center;">'.$formData['TEST_SCORE'].'</td>';
$partBTable.='</tr>';


$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;background-color:#dddbdb;">'.$decoded[$language]['/SPI_RT/POSTTEST:label'].'</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">9</td>';
$partBTable.='</tr>';

    for($i=1;$i<10;$i++)
    {
    $partBTable.='<tr>';
    
    $partBTable.='<td>'.$decoded[$language]['/SPI_RT/POSTTEST/POST_6_'.$i.'/POST_Q_6_'.$i.':label'].'</td>';
    $partBTable.='<td style="text-align:center;">';
    $partBTable.=(isset($formData['POST_Q_6_'.$i]) && $formData['POST_Q_6_'.$i] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
    $partBTable.='</td>';
    
    $partBTable.='<td style="text-align:center;">';
    $partBTable.=(isset($formData['POST_Q_6_'.$i]) && $formData['POST_Q_6_'.$i] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
    $partBTable.='</td>';
    
    $partBTable.='<td style="text-align:center;">';
    $partBTable.=(isset($formData['POST_Q_6_'.$i]) && $formData['POST_Q_6_'.$i] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
    $partBTable.='</td>';
    
    $partBTable.='<td>'.($formData['POST_C_6_'.$i]).'</td>';
    $partBTable.='<td style="text-align:center;">'.($formData['POST_Q_6_'.$i]).'</td>';
    $partBTable.='</tr>';
    }
$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;">'.$decoded[$language]['/SPI_RT/POSTTEST/POST_DISPLAY:label'].'</td>';
$partBTable.='<td style="text-align:center;">'.$formData['POST_SCORE'].'</td>';
$partBTable.='</tr>';

$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;background-color:#dddbdb;">'.$decoded[$language]['/SPI_RT/EQA:label'].'</td>';
$partBTable.='<td style="text-align:center;font-weight:bold;background-color:#dddbdb;">8/14</td>';
$partBTable.='</tr>';

    for($i=1;$i<9;$i++)
    {
	$partBTable.='<tr>';
	
	$partBTable.='<td>'.$decoded[$language]['/SPI_RT/EQA/EQA_7_'.$i.'/EQA_Q_7_'.$i.':label'].'</td>';
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['EQA_Q_7_'.$i]) && $formData['EQA_Q_7_'.$i] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['EQA_Q_7_'.$i]) && $formData['EQA_Q_7_'.$i] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['EQA_Q_7_'.$i]) && $formData['EQA_Q_7_'.$i] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td>'.($formData['EQA_C_7_'.$i]).'</td>';
	$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_'.$i]).'</td>';
	$partBTable.='</tr>';
    }

$partBTable.='<tr>';
$partBTable.='<td colspan="6" style="text-align:center;font-weight:bold;background-color:#dddbdb;">'.$decoded[$language]['/SPI_RT/EQA/sampleretesting:label'].'</td>';
$partBTable.='</tr>';

    for($i=9;$i<15;$i++)
    {
	$partBTable.='<tr>';
	
	$partBTable.='<td>'.$decoded[$language]['/SPI_RT/EQA/SAMPLEREF/EQA_7_'.$i.'/EQA_Q_7_'.$i.':label'].'</td>';
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['EQA_Q_7_'.$i]) && $formData['EQA_Q_7_'.$i] == 1 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['EQA_Q_7_'.$i]) && $formData['EQA_Q_7_'.$i] == 0.5 ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td style="text-align:center;">';
	$partBTable.=(isset($formData['EQA_Q_7_'.$i]) && $formData['EQA_Q_7_'.$i] == "0" ) ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "";
	$partBTable.='</td>';
	
	$partBTable.='<td>'.($formData['EQA_C_7_'.$i]).'</td>';
	$partBTable.='<td style="text-align:center;">'.($formData['EQA_Q_7_'.$i]).'</td>';
	$partBTable.='</tr>';
    }
$partBTable.='<tr>';
$partBTable.='<td colspan="5" style="font-weight:bold;">'.$decoded[$language]['/SPI_RT/EQA/EQA_DISPLAY:label'].'</td>';
$partBTable.='<td style="text-align:center;">'.$formData['EQA_SCORE'].'</td>';
$partBTable.='</tr>';

$partBTable.='</table>';
$partBTable.='<p>*Those marked with an asterisk are only applicable to sites where sample retesting is performed.</p>';

$pdf->writeHTML($partBTable, true, 0, true, 0);

$partC='<br/><p style="font-weight:bold;">'.$decoded[$language]['/SPI_RT/scoring/info5:label'].'</p>';
$partC.='<br/><span>'.$decoded[$language]['/SPI_RT/scoring/info6:label'].'</span>';
$partC.='<p>'.$decoded[$language]['/SPI_RT/scoring/info10:label'].'</p>';
$partC.='<p>The overall total points obtained by each HIV testing point audited will be weighed to correspond to a specific performance level.</p>';

$pdf->writeHTML($partC, true, 0, true, 0);

$partCTable='<table border="1" cellspacing="0" cellpadding="5">';

$partCTable.='<tr style="font-weight:bold;text-align:center;">';
$partCTable.='<td style="width:15%">Levels</td>';
$partCTable.='<td  style="width:20%">% Score</td>';
$partCTable.='<td  style="width:65%">Description of results</td>';
$partCTable.='</tr>';

$partCTable.='<tr>';
$partCTable.='<td style="background-color:#C00000;">Level 0</td>';
$partCTable.='<td>Less than 40%</td>';
$partCTable.='<td>Needs improvement in all areas and immediate remediation</td>';
$partCTable.='</tr>';

$partCTable.='<tr>';
$partCTable.='<td style="background-color:#E36C0A;">Level 1</td>';
$partCTable.='<td>40% - 59%</td>';
$partCTable.='<td>Needs improvement in specific areas</td>';
$partCTable.='</tr>';

$partCTable.='<tr>';
$partCTable.='<td style="background-color:#FFFF00;">Level 2</td>';
$partCTable.='<td>60% - 79%</td>';
$partCTable.='<td>Partially eligible</td>';
$partCTable.='</tr>';

$partCTable.='<tr>';
$partCTable.='<td style="background-color:#92D050;">Level 3</td>';
$partCTable.='<td>80% - 89%</td>';
$partCTable.='<td>Close to national site certification</td>';
$partCTable.='</tr>';

$partCTable.='<tr>';
$partCTable.='<td style="background-color:#00B050;">Level 4</td>';
$partCTable.='<td>90% or higher</td>';
$partCTable.='<td>Eligible to national site certification</td>';
$partCTable.='</tr>';

$partCTable.='</table>';

$pdf->writeHTML($partCTable,true,0,true,0);

$partDTitle='<p style="font-weight:bold;line-height:30px;">Part D. Auditor\'s Summation Report for SPI-RT Audit</p>';
$pdf->writeHTML($partDTitle,true,0,true,0);

$partDtableBox1='<table cellspacing="0" cellpadding="2">';
$partDtableBox1.="<tr><td>Facility Name:".$formData['facilityname']."</td></tr><tr><td>Site Type:".$formData['testingpointtype'];
$partDtableBox1.=((isset($formData['testingpointtype_other']) && $formData['testingpointtype_other'] != "") ? " - " . $formData['testingpointtype_other']: "");
$partDtableBox1.="</td></tr>";
$partDtableBox1.="<tr><td>Staff Audited Name: ".$formData['staffaudited']."</td></tr>";
$partDtableBox1.='</table>';
$pdf->writeHTMLCell(50,26,'','',$partDtableBox1,1, 0, 0, true, 'L');

$partDtableBox2='<table cellspacing="0" cellpadding="5">';
$partDtableBox2.="<tr><td>No. of Tester(s): ".$formData['NumberofTester']."</td></tr><tr><td>Duration of Audit: ".$formData['durationaudit']."</td></tr>";
$partDtableBox2.='</table>';

$pdf->writeHTMLCell(50,26,70,'',$partDtableBox2,1,0, 0, true, 'L',true);

$scorePer=round($formData['AUDIT_SCORE_PERCANTAGE']);
$level='';
$colorCode='';
if($scorePer<40){
  $level="Level 0";
  $colorCode="background-color:#C00000";
}elseif($scorePer>=40 && $scorePer<=59){
  $level="Level 1";
  $colorCode="background-color:#E36C0A";
}elseif($scorePer>=60 && $scorePer<=79){
  $level="Level 2";
  $colorCode="background-color:#FFFF00";
}elseif($scorePer>=80 && $scorePer<=89){
  $level="Level 3";
  $colorCode="background-color:#92D050";
}elseif($scorePer>=90){
  $level="Level 4";
  $colorCode="background-color:#00B050";
}
					  
$partDtableBox3='<table cellspacing="0" cellpadding="5">';
$partDtableBox3.="<tr><td>Total points scored (exclude N/A) = ".$formData['FINAL_AUDIT_SCORE']."</td></tr>";
$partDtableBox3.="<tr><td>Total score expected = ".$formData['MAX_AUDIT_SCORE']."</td></tr>";
$partDtableBox3.='<tr><td>% Score = '.round($formData['AUDIT_SCORE_PERCANTAGE'],2).'% &nbsp; <span style="'.$colorCode.'">  &nbsp;&nbsp;'.$level.'  &nbsp;&nbsp;</span></td></tr>';
$partDtableBox3.='</table>';

$pdf->writeHTMLCell(70,26,125,'',$partDtableBox3,1,1, 0, true, 'L',true);

// set recommend
$recommend = explode("-",$decoded[$language]['/SPI_RT/correctiveaction/action:label']);
$timeLine = explode("-",$decoded[$language]['/SPI_RT/correctiveaction/timeline:label']);

$partDTable='<br/><br/><table border="1" cellspacing="0" cellpadding="5" style="width:100%">';
$partDTable.='<tr>';
$partDTable.='<td rowspan="2" style="font-weight:bold;text-align:center;width:9%"><br/><br/>'.$decoded[$language]['/SPI_RT/correctiveaction/sectionno:label'].'</td>';
$partDTable.='<td rowspan="2" style="font-weight:bold;text-align:center;width:22%"><br/><br/>'.$decoded[$language]['/SPI_RT/correctiveaction/deficiency:label'].'</td>';
$partDTable.='<td colspan="2" style="font-weight:bold;text-align:center;width:20%">'.$decoded[$language]['/SPI_RT/correctiveaction/correction:label'].'</td>';
$partDTable.='<td rowspan="2" style="font-weight:bold;text-align:center;width:23%">'.$decoded[$language]['/SPI_RT/correctiveaction/auditorcomment:label'].'</td>';
$partDTable.='<td colspan="2" style="font-weight:bold;text-align:center;width:26%">'.$recommend[0].'</td>';
$partDTable.='</tr>';
$partDTable.='<tr>';
$partDTable.='<td style="font-weight:bold;text-align:center;width:12%;">'.$decoded[$language]['/SPI_RT/correctiveaction/correction/Immediate:label'].'</td>';
$partDTable.='<td style="font-weight:bold;text-align:center;width:8%;">'.$decoded[$language]['/SPI_RT/correctiveaction/correction/Followup:label'].'</td>';
$partDTable.='<td style="font-weight:bold;text-align:center;">'.$recommend[1].'</td>';
$partDTable.='<td style="font-weight:bold;text-align:center;">'.$timeLine[1].'</td>';
$partDTable.='</tr>';
if(isset($formData['correctiveaction']) && $formData['correctiveaction'] != ""  && $formData['correctiveaction'] != "[]"){
    $correctiveActions = json_decode($formData['correctiveaction'],true);
    foreach($correctiveActions as $ca) {
        $partDTable.='<tr>';
        $partDTable.='<td style="text-align:center;">'.$ca['sectionno'].'</td>';
        $partDTable.='<td>'.$ca['deficiency'].'</td>';
        $partDTable.='<td style="text-align:center;">';
        $partDTable.=($ca['correction'] == 'Immediate' ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "" );
        $partDTable.='</td>';
        $partDTable.='<td style="text-align:center;">';
        $partDTable.=($ca['correction'] == 'Followup' ? '<img src="'.$this->basePath('assets/img/black-tick.png').'" width="20">' : "" );
        $partDTable.='</td>';
        $partDTable.='<td>'.$ca['auditorcomment'].'</td>';
        $partDTable.='<td>'.$ca['action'].'</td>';
        $partDTable.='<td>'.$ca['timeline'].'</td>';
        $partDTable.='</tr>';
    }
}else {
    $partDTable.='<tr>';
    $partDTable.='<td colspan="7">No Corrective Actions</td>';
    $partDTable.='</tr>';
}
$partDTable.='</table><br/><br/><br/>';
$pdf->writeHTML($partDTable,true,0,true,0);

$signBox1='<table cellspacing="0" cellpadding="4">';
$signBox1.='<tr><td>'.$decoded[$language]['/SPI_RT/staffaudited:label'].'</td></tr>';
$signBox1.='<tr><td>'.$decoded[$language]['/SPI_RT/personincharge:label'].$formData["personincharge"].'</td></tr>';
$signBox1.='</table>';
$pdf->writeHTMLCell(90,18,'','',$signBox1,1, 0, 0, true, 'L');

$signBox2='<table cellspacing="0" cellpadding="4">';
$signBox2.='<tr><td>'.$decoded[$language]['/SPI_RT/SUMMARY/info26:label'].'</td></tr>';
$signBox2.="<tr><td>Date (dd/mm/yyyy):</td></tr>";
$signBox2.='</table>';
$pdf->writeHTMLCell(80,18,115,'',$signBox2,1,1, 0, true, 'L');

//Close and output PDF document
$fileName = "SPI-RT-CHECKLIST-".date('d-M-Y-H-i-s').".pdf";
$filePath = TEMP_UPLOAD_PATH . DIRECTORY_SEPARATOR.$fileName;
//$pdf->Output('example_003.pdf', 'I');
$pdf->Output($filePath, "I");
//echo $fileName;
//============================================================+
// END OF FILE
//============================================================+
