<?php
// Extend the TCPDF class to create custom Header and Footer
class MYPDF extends TCPDF {

    //Page header
    public function Header() {
        // Logo
        //$image_file = K_PATH_IMAGES.'logo_example.jpg';
        //$this->Image($image_file, 10, 10, 15, '', 'JPG', '', 'T', false, 300, '', false, false, 0, false, false, false);
        // Set font
        $this->SetFont('helvetica', 'B', 12);
        // Title
        $this->Cell(0, 15, 'Stepwise Process for Improving the Quality of HIV Rapid Testing (SPI-RT) Checklist', 0, false, 'C', 0, '', 0, false, 'M', 'M');
    }

    // Page footer
    public function Footer() {
        // Position at 15 mm from bottom
        $this->SetY(-15);
        // Set font
        $this->SetFont('helvetica', 'I', 8);
        // Page number
        $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
    }
}

// create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Nicola Asuni');
$pdf->SetTitle('TCPDF Example 003');
$pdf->SetSubject('TCPDF Tutorial');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');


// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}

// ---------------------------------------------------------

// set font
$pdf->SetFont('Helvetica', '', 12);

// add a page
$pdf->AddPage();


$testingTab='<table border="1" cellspacing="0" cellpadding="5">';

$testingTab.='<tr>';
$testingTab.='<td><b>Date of Audit</b>(dd/mm/yyyy): '.$this->humanDateFormat($formData['today']).'</td>';
$testingTab.='<td><b>Audit Round No:</b> '.$formData['auditroundno'].'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>Testing Facility Name:</b> '.$formData['facilityname'].'</td>';
$testingTab.='<td><b>Testing Facility ID</b>(if applicable) : '.$formData['facilityid'].'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>Testing Point Name:</b> '.$formData['testingpointname'].'</td>';
$testingTab.='<td><b>Type of testing point : </b>'.$formData['testingpointtype'];
$testingTab.=((isset($formData['testingpointtype_other']) && $formData['testingpointtype_other'] != "") ? " - " . $formData['testingpointtype_other']: "").'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td colspan="2"><b>Location/Address:</b> '.$formData['locationaddress'].'</td>';
$testingTab.='</tr>';

$testingTab.='<tr>';
$testingTab.='<td><b>Level</b> <br/>Other Other - ACTION HOLDINGS  :'.$formData['level'].'</td>';
$testingTab.='<td><b>Testing Facility ID</b>(if applicable) : '.$formData['facilityid'].'</td>';
$testingTab.='</tr>';

$testingTab.='</table>';

$pdf->writeHTML($testingTab, true, 0, true, 0);


//Close and output PDF document
$fileName = "form-response-".date('d-M-Y-H-i-s').".pdf";
$filePath = TEMP_UPLOAD_PATH . DIRECTORY_SEPARATOR.$fileName;
//$pdf->Output('example_003.pdf', 'I');
$pdf->Output($filePath, "FD");
//echo $fileName;
//============================================================+
// END OF FILE
//============================================================+