<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/t/bs/jqc-1.12.0,dt-1.10.11,r-2.0.2,sc-1.4.1/datatables.min.css"/>
 


<div class="am-content">
        <div class="page-head">
          <h2>SPI RT Version 3</h2>
        </div>
        
        
        <div class="main-content">
            
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">


        <div class="row">
            <div class="col-sm-12">
              <div class="panel panel-default">
                <div class="panel-body">
                  <form role="form">
                    <div class="form-group col-lg-6">
                      <label>Date</label>
                      <input type="text" placeholder="Enter Date" class="form-control">
                    </div>
                    <div class="form-group col-lg-6">
                      <label>Audit Round No.</label>
                      <select class="form-control">
                        <option>--Select--</option>
                          <option>1</option>
                          <option>2</option>
                          <option>3</option>
                          <option>4</option>
                          <option>5</option>
                        </select>
                    </div>
                    <div class="form-group col-lg-6">
                      <label>Type of testing point</label>
                      <select class="form-control">
                        <option>--Select--</option>
                        <option>VCT/HTC</option>          
                        <option>PITC</option>            
                        <option>PMTCT</option>        
                        <option>TB clinic</option>
                        <option>Laboratory</option>
                        <option>Treatment Center</option>
                        <option>Other</option>
                        </select>
                    </div>
                    <div class="form-group col-lg-6">
                      <label>Level</label>
                      <select class="form-control">
                        <option>--Select--</option>
                        <option>Region/Province/Zone</option>         
                        <option>District</option>
                        <option>Referral center</option>
                        <option>Health center</option>
                        <option>Dispensary</option>
                        <option>Health Post</option>
                        <option>Other</option>
                        </select>
                    </div>
                    <div class="form-group col-lg-6">
                      <label>Affiliation</label>
                      <select class="form-control">
                        <option>--Select--</option>
                        <option>Government</option>
                        <option>Private</option>
                        <option>Faith-based Organization</option>
                        <option>Non-governmental organization</option>
                        <option>Other</option>
                        </select>
                    </div>
                    
                    <div class="spacer  col-lg-12">
                      <button type="button" onclick="alert('Under Construction')" class="btn btn-space btn-primary">Search</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
        </div>



                <table class="table table-bordered table-striped table-hover table-fw-widget">
                  <thead>
                    <tr>
                      <th>Form ID</th>
                      <th>Form Version</th>
                      <th>Facility Name</th>
                      <th>Audit Round No.</th>
                      <th>Testing Point Type</th>
                      <th>Level</th>
                      <th>Affiliation</th>
                      <th>Audit Score Percentage</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                  <?php foreach ($allSubmissions as $row) { ?>
                    <tr>
                      <td><?php echo $row['formId']; ?></td>
                      <td><?php echo $row['formVersion']; ?></td>
                      <td><?php echo $row['facilityname']; ?></td>
                      <td><?php echo $row['auditroundno']; ?></td>
                      <td><?php echo $row['testingpointtype']; ?></td>
                      <td><?php echo $row['level']; ?> <?php echo isset($row['level_other']) ? " - ".$row['level_other'] : ""; ?></td>
                      <td><?php echo $row['affiliation']; ?></td>
                      <td><?php echo round($row['AUDIT_SCORE_PERCANTAGE'],2); ?></td>
                      <td><a href="/spi-v3/print/<?php echo $row['id']; ?>" target="_blank"><i class="fa fa-print"></i> Print</a></td>
                    </tr>
                    <?php } ?>
                  </tbody>
                </table>
            </div>
            
            
            
        </div>
</div>
<script type="text/javascript" src="https://cdn.datatables.net/t/bs/jqc-1.12.0,dt-1.10.11,r-2.0.2,sc-1.4.1/datatables.min.js"></script>
<script type="text/javascript">
       $(document).ready(function() {
    $('.table').DataTable();
} ); 
</script>