<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/t/bs/jqc-1.12.0,dt-1.10.11,r-2.0.2,sc-1.4.1/datatables.min.css"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>
<style>

 td.details-control {
    background: url('<?php echo $this->basePath('assets/img/details_open.png'); ?>') no-repeat center center;
    cursor: pointer;
}
tr.shown td.details-control {
    background: url('<?php echo $this->basePath('assets/img/details_close.png'); ?>') no-repeat center center;
}
</style> 


<div class="am-content">
        <div class="page-head">
          <h2>SPI RT Version 3</h2>
        </div>
        
        
        <div class="main-content">
            
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">


        <div class="row">
            <div class="col-sm-12">
              <div class="panel panel-default">
                <div class="panel-body">
                  <form role="form">
                    <div class="form-group col-lg-6">
                      <label>Date</label>
                      <input type="text" placeholder="Enter Date" class="form-control" id="date">
                    </div>
                    <div class="form-group col-lg-6">
                      <label>Audit Round No.</label>
                      <select class="form-control" id="auditRndNo">
                        <option value=''>--Select--</option>
                          <option value="1">1</option>
                          <option value="2">2</option>
                          <option value="3">3</option>
                          <option value="4">4</option>
                          <option value="5">5</option>
                        </select>
                    </div>
                    <div class="form-group col-lg-6">
                      <label>Type of testing point</label>
                      <select class="form-control" id="testPoint">
                        <option value="">--Select--</option>
                        <option value="VCT/HTC">VCT/HTC</option>          
                        <option value="PITC">PITC</option>            
                        <option value="PMTCT">PMTCT</option>        
                        <option value="TB clinic">TB clinic</option>
                        <option value="Laboratory">Laboratory</option>
                        <option value="Treatment Center">Treatment Center</option>
                        <option value="other">Other</option>
                        </select>
                    </div>
                    <div class="form-group col-lg-6">
                      <label>Level</label>
                      <select class="form-control" id="level">
                        <option value="">--Select--</option>
                        <option value="Region/Province/Zone">Region/Province/Zone</option>         
                        <option value="District">District</option>
                        <option value="Referral center">Referral center</option>
                        <option value="Health center">Health center</option>
                        <option value="Dispensary">Dispensary</option>
                        <option value="Health Post">Health Post</option>
                        <option value="Other">Other</option>
                        </select>
                    </div>
                    <div class="form-group col-lg-6">
                      <label>Affiliation</label>
                      <select class="form-control" id="affiliation">
                        <option value="">--Select--</option>
                        <option value="Government">Government</option>
                        <option value="Private">Private</option>
                        <option value="Faith-based Organization">Faith-based Organization</option>
                        <option value="Non-governmental organization">Non-governmental organization</option>
                        <option value="Other">Other</option>
                        </select>
                    </div>
                    
                    <div class="spacer  col-lg-12">
                      <button type="button" onclick="search()" class="btn btn-space btn-primary">Search</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
        </div>

                <table id="example" class="table table-bordered table-striped table-hover table-fw-widget">
                  <thead>
                    <tr>
                      <th></th>
                      <th>Facility Name</th>
                      <th>Form ID</th>
                      <th>Form Version</th>
                      <th>Audit Round No.</th>
                      <th>Testing Point Type</th>
                      <th>Level</th>
                      <th>Affiliation</th>
                      <th>Audit Score Percentage</th>
                      <th>Status</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                  <tr>
                                <td colspan="10" class="dataTables_empty">Loading data from server</td>
                            </tr>
                  </tbody>
                </table>


            </div>
        <div class="spacer col-lg-12">
                <button type="button" onclick="window.location.href='<?php echo $this->url('spi-v3-form',array('action'=>'export')); ?>'" class="btn btn-space btn-primary">Export All Data</button>
        </div>
        <br>
        <br>
        <br>
        <br>
            
            
        </div>
</div>
<script type="text/javascript" src="https://cdn.datatables.net/t/bs/jqc-1.12.0,dt-1.10.11,r-2.0.2,sc-1.4.1/datatables.min.js"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
    table = null;
    function format(value) {
      return '<a href="/spi-v3/print/'+value+'" target="_blank"><i class="fa fa-print"></i> Print Full Survey</a>'
                        +
                '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
                        + 
             '<a href="javascript:alert(\'Under Construction\')" target="_blank"><i class="fa fa-print"></i> Print Corrective Actions</a>';
  }
  $(document).ready(function () {
   var startDate = "";
        var endDate = "";
        $('#date').daterangepicker({
                format: 'DD-MMM-YYYY',
                startDate: moment().subtract('days', 29),
                endDate: moment(),
                maxDate: moment(),
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                    'Last 7 Days': [moment().subtract('days', 6), moment()],
                    'Last 30 Days': [moment().subtract('days', 29), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                }
            },
            function(start, end) {
                startDate = start.format('YYYY-MM-DD');
                endDate = end.format('YYYY-MM-DD');
            });
   table = $('#example').DataTable({
        "bProcessing": true,
        "bServerSide": true,
         "aoColumns": [
		{"sClass":"center details-control","bSortable":false},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center","bSortable":false}
            ],
         "iDisplayLength": 50,
         "aaSorting": [[ 1, "desc" ]],
        "sAjaxSource": "<?php echo $this->url('spi-v3-form',array('action' => 'index')); ?>",
         "fnServerData": function ( sSource, aoData, fnCallback ) {
          aoData.push( { "name":"testPoint","value": $("#testPoint").val()} );
          aoData.push( { "name":"level","value": $("#level").val()} );
          aoData.push( { "name":"affiliation","value": $("#affiliation").val()} );
          aoData.push( { "name":"auditRndNo","value": $("#auditRndNo").val()} );
          aoData.push( { "name":"date","value": $("#date").val()} );
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
    } );
      //
      //var table = $('#example').DataTable({"order": [[1, 'asc']]});
      //
      // Add event listener for opening and closing details
      $('#example').on('click', 'td.details-control', function () {
          var tr = $(this).closest('tr');
          var row = table.row(tr);
      
          if (row.child.isShown()) {
              // This row is already open - close it
              row.child.hide();
              tr.removeClass('shown');
          } else {
              // Open this row
              row.child(format(tr.data('child-value'))).show();
              tr.addClass('shown');
          }
      });
  });
  
  function approveStatus(id) {
    conf=confirm("Are you sure,you want approved this form");
    if (conf) {
      $.post("<?php echo $this->url('spi-v3-form',array('action'=>'approve-status')); ?>",{id: id},
       function(data) {
        if (data>0) {
            alert("Form status updated successfully");
            table.draw();
        }
         
      });
    }
  }
  
  function downloadPdf(formId){
   window.open('<?php echo $this->url('spi-v3-form',array('action' => 'download-pdf'))?>'+formId);
   return false;
  }
  
  function search()
  {
   table.draw();
  }
</script>