
<style>
.link {
    font-size: 16px;
    padding-left:7%;
    line-height:2.428571;
}
</style>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<div class="am-content">
  <div class="page-head">
    <h2><?= $this->translate('View Bulk Downloads'); ?></h2>
  </div>

  <div class="main-content">
    <div class="widget widget-fullwidth widget-small" style="padding:5px;">
    <?php
        if(count($result)>0){ 
            $tempPath = "/temporary/bulk-pdf/";
            foreach($result as $file){
                echo '<a href="' . $tempPath . $file . '" class="link">' . $file . '</a><br>';
            }
        }
        ?>
    </div>
  </div>
</div>