<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>" />
<style>
	.select2-container .select2-selection--single {
		height: 40px;
	}

	.select2-container--default.select2-container--open .select2-selection--single .select2-selection__arrow b:after {
		content: ""
	}

	.select2-container--default .select2-selection--single .select2-selection__arrow b:after {
		content: ""
	}

	.select2-container--default .select2-selection--single .select2-selection__arrow b:before {
		content: ""
	}

	.select2-container--default .select2-selection--single .select2-selection__arrow b {
		margin-top: 8px;
	}
</style>
<div class="am-content">
	<div class="page-head">
		<h2>Add Facility</h2>
	</div>

	<div class="main-content">
		<div class="widget widget-fullwidth widget-small" style="padding:5px;">
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default">
						<div class="panel-body">
							<form role="form" name="addFacilityInfo" id="addFacilityInfo" method="post" action="<?php echo $this->url('spi-facility', array('action' => 'add')); ?>" autocomplete="off">
								<div class="form-group col-lg-6">
									<label>Facility Id</label>
									<input type="text" placeholder="Facility Id" class="form-control isRequired" name="facilityId" id="facilityId" title="Please enter the facility id">
								</div>
								<div class="form-group col-lg-6">
									<label>Facility Name</label>
									<input type="text" placeholder="Facility Name" class="form-control isRequired" name="facilityName" id="facilityName" title="Please enter the facility name" onblur="checkNameValidation('spi_rt_3_facilities','facility_name', this, null,'This name already exists. Please choose another name.')">
								</div>
								<div class="form-group col-lg-6">
									<label>Email</label>
									<input type="text" placeholder="Email" class="form-control isEmail" name="email" id="email">
								</div>
								<div class="form-group col-lg-6">
									<label>Name of the Contact Person</label>
									<input type="text" placeholder="Name of the Contact Person" class="form-control" name="contactPerson" id="contactPerson" value="">
								</div>
								<div class="form-group col-lg-6">
									<label>Province</label>
									<select class="form-control" name="province" id="province" title="Please select province" onchange="getDistrict()">
										<option value="">--Select--</option>
										<?php
										foreach ($provinceResult as $val) {
										?>
										<option value="<?php echo base64_encode($val['geo_id']); ?>"><?php echo ucwords($val['geo_name']); ?></option>
										<?php
										}
										?>
										<option value="other">Other</option>
									</select>
									<input type="text" placeholder="Enter Province Name" class="form-control" name="provinceName" id="provinceName" style="display:none;" data-type="Province" onblur="checkExistName(this)" title="Please enter the province name">
								</div>
								<div class="form-group col-lg-6">
									<label>District</label>
									<select class="form-control" name="district" id="district" title="Please select district" onchange="checkDistrict()">
										<option value="">--Select--</option>
									</select>
									<input type="text" placeholder="Enter District Name" class="form-control" name="districtName" id="districtName" data-type="District" onblur="checkExistName(this)" style="display:none;" title="Please enter the district name">
								</div>

								
								<div class="form-group col-lg-6">
									<label>Latitude</label>
									<input type="text" placeholder="Latitude" class="form-control" name="latitude" id="latitude" value="">
								</div>
								<div class="form-group col-lg-6">
									<label>Longitude</label>
									<input type="text" placeholder="Longitude" class="form-control" name="longitude" id="longitude" value="">
								</div>
								<div class="spacer  col-lg-12">
									<button type="button" onclick="validateNow()" class="btn btn-space btn-primary">Submit</button>
									<a href="<?php echo $this->url('spi-facility', array('action' => 'index')); ?>" class="btn btn-space btn-default">Cancel</a>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		<br>
		<br>
	</div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
<script type="text/javascript">
	duplicateName = true;
	$(document).ready(function() {
        //initialize the javascript
        $("#province").select2({
            width: '100%',
            placeholder: '--Select--',
            allowClear: true,
            tags: false
        });

		$("#district").select2({
            width: '100%',
            placeholder: '--Select--',
            allowClear: true,
            tags: false
        });
	});

	function validateNow() {
		flag = deforayValidator.init({
			formId: 'addFacilityInfo'
		});
		if (flag) {
			if (duplicateName) {
				document.getElementById('addFacilityInfo').submit();
			}
		}
	}

	function getDistrict(){
		province=$("#province").val();
		if(province!=""){
			if(province=='other'){
				$("#provinceName").show();
				$("#provinceName").addClass("isRequired");
				$('#district').html('<option value="">--Select--</option><option value="other">Other</option>');
			}else{
				$("#provinceName").hide();
				$("#provinceName").val('');
				$("#provinceName").removeClass("isRequired");
				$.blockUI();
				$.post("<?php echo $this->url('provinces', array('action' => 'getDistrictByProvince')); ?>", {
					provinceId: province,
				},
				function(data) {
					$('#district').html(data);
					$("#districtName").hide();
					$("#districtName").val('');
					$("#districtName").removeClass("isRequired");
					$.unblockUI();
				});
			}
		}else{
			$("#provinceName").hide();
			$("#provinceName").val('');
			$("#provinceName").removeClass("isRequired");
			$('#district').html('<option value="">--Select--</option>');
		}
	}

	function checkDistrict(){
		district=$("#district").val();
		if(district=='other'){
			$("#districtName").show();
			$("#districtName").addClass("isRequired");
		}else{
			$("#districtName").hide();
			$("#districtName").val('');
			$("#districtName").removeClass("isRequired");
		}
	}

	// function checkExistName(inputElement) {
	// 	var geo_name = inputElement.value;
	// 	var type = $(inputElement).data('type');
	// 	if(geo_name != '') {
	// 			$.post("<?php echo $this->url('spi-facility', array('action' => 'check-province-district')); ?>", {
	// 				geo_name: geo_name
	// 			},
	// 			function(result) {
	// 				if (result == 1) {
	// 					alert("<?= $this->translate('" + type + " already exists. please type another one.'); ?>");
	// 					inputElement.value = '';
	// 					inputElement.focus();
	// 					return false;
	// 				}
	// 			});
	// 	} else {
	// 		alert("<?= $this->translate('" + type + " can not be empty'); ?>");
	// 		inputElement.value = '';
	// 		inputElement.focus();
	// 		return false;
	// 	}
	// }
	
	function checkExistName(inputElement) {
		var geo_name = inputElement.value;
		var type = $(inputElement).data('type');
		$.post("<?php echo $this->url('spi-facility', array('action' => 'check-province-district')); ?>", {
			geo_name: geo_name
		},
		function(result) {
			if (result == 1) {
				alert("<?= $this->translate('" + type + " already exists. please type another one.'); ?>");
				inputElement.value = '';
				inputElement.focus();
				return false;
			}
		});
	}
</script>