<style>
    .moveButtons{line-height: 35px;}
    /*.updateButton{padding:15px 0px 0px 45px;}*/
    .btn{font-weight: bold;}
    .ui-multiselect-filter input{color: #333 !important;}
    #upFaciltyName{width: 75%;}
    #facilityName{width: 100%;}
    .main-content{margin-top:15px;}
    .panel-body{height: 250px;}
</style>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<div class="main-content">
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">
                <div class="row" id="pendingFacilityName" >
                    <div class="col-sm-12">
                      <div class="panel panel-default">
                        <div class="panel-body">
                            <table class="col-lg-12">
                                <tr>
                                    <td class="col-lg-6">
                                        <b>Unqiue Facility Name</b><span class="mandatory">*</span>
                                    </td>
                                    <td class="col-lg-6" align="center">
                                        <select id="facilityName" name="facilityName" class="form-control" >
                                            <option value="">--select--</option>
                                            <?php
                                            foreach($facilityName['uniqueName'] as $name)
                                            {
                                                ?>
                                                <option value="<?php echo $name['facilityname'];?>"><?php echo $name['facilityname'];?></option>
                                                <?php
                                            }
                                            ?>
                                        </select>
                                   </td>
                                </tr>
                                <tr>
                                    <td colspan="2"><hr></td>
                                </tr>
				<tr>
                                    <td class="col-lg-6">
                                        <b>All Facility Name</b><span class="mandatory">*</span>
                                    </td>
                                    <td class="col-lg-6">
                                        <select id="upFaciltyName" name="upFaciltyName[]" class="" multiple="multiple">
                                            <?php
                                            foreach($facilityName['allName'] as $name)
                                            {
                                                $facilityId = '';
                                                if($name['facilityid']!=''){
                                                 $facilityId = $name['facility_name']." - ".$name['facility_id'];   
                                                }else{
                                                    $facilityId = $name['facility_name'];   
                                                }
                                                ?>
                                                <option value="<?php echo $name['facility_name'];?>"><?php echo $facilityId;?></option>
                                                <?php
                                            }
                                            ?>
                                        </select>
                                   </td>
                                </tr>
                                <tr>
                                    <td colspan="2"><hr>&nbsp;&nbsp;</td>
                                </tr>
                                <tr>
				    <td class="updateButton">
					<button type="button" onclick="updateFacilityName()" class="btn btn-space btn-primary">Merge Facility Name</button>
				    </td>
				</tr>
                            </table>
                        </div>
                      </div>
                    </div>
		    
                </div>
            </div>
            </div>
<script>
    $(document).ready(function(){
	$('#upFaciltyName').multipleSelect({
	    filter: true,
	    minimumCountSelected:'2',
	    placeholder:'Please select facility name',
            width: '100%'
        });
    });
    function updateFacilityName()
    {
        var fName = $("#facilityName").val();
        var upFaciltyName = $("#upFaciltyName").val();
	
	console.log(upFaciltyName);
	
        if(fName!='' && upFaciltyName!='' && upFaciltyName!=null){
        var cnfm = confirm("Do you wish to merge facility names?");
        if(cnfm){
        $.post("<?php echo $this->url('spi-v3-form',array('action'=>'merge-facility-name')); ?>",{fName:fName,upFaciltyName:upFaciltyName},
        function(data) {
        if (data>0) {
        alert("Facility name merged successfully");
        parent.closeModal();
        parent.window.location.href=window.parent.location.href;
        }
        });
        }
        }else{
            alert("Please choose facility name");
        }
    }
    
</script>