<style>
	/*.updateButton{padding:15px 0px 0px 45px;}*/
	.btn {
		font-weight: bold;
	}

	.ui-multiselect-filter input {
		color: #333 !important;
	}

	#facility {
		width: 100%;
	}

	#province {
		width: 300px !important;
	}

	.main-content {
		margin-top: 15px;
	}

	.panel-body {
		height: 250px;
	}

	ul li span {
		padding: 4px;
		vertical-align: middle;
	}

	body {
		overflow-x: hidden;
	}
</style>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<div class="main-content">
	<div class="widget widget-fullwidth widget-small" style="padding:5px;">
		<div class="row">
			<div class="col-sm-12">
				<div class="panel panel-default">
					<div class="panel-body" style="height:auto !important;">
						<table class="col-lg-12">
							<tr>
								<td class="col-lg-4">
									<b><?= $this->translate('Province'); ?></b><span class="mandatory">*</span>
								</td>
								<td class="col-lg-8" align="center">
									<select class="form-control" name="province" id="province" title="Please select province" onchange="getDistrict()">
										<option value="">--Select--</option>
										<?php
										foreach ($provinces as $val) {
										?>
										<option value="<?php echo base64_encode($val['geo_id']); ?>"><?php echo ucwords($val['geo_name']); ?></option>
										<?php
										}
										?>
										<option value="other">Other</option>
									</select>
									<input type="text" placeholder="Enter Province Name" class="form-control" name="provinceName" id="provinceName" style="display:none;" title="Please enter the province name">
									</td>
							</tr>
							<tr>
								<td colspan="2">
									<hr>
								</td>
							</tr>
							<tr>
								<td class="col-lg-4">
									<b><?= $this->translate('District'); ?></b>
								</td>
								<td class="col-lg-8" align="center">
									<select class="form-control" name="district" id="district" title="Please select district" onchange="checkDistrict()">
										<option value="">--Select--</option>
									</select>
									<input type="text" placeholder="Enter District Name" class="form-control" name="districtName" id="districtName" style="display:none;" title="Please enter the district name">
									</td>
							</tr>
							<tr>
								<td colspan="2">
									<hr>
								</td>
							</tr>
							<tr>
								<td class="col-lg-4">
									<b><?= $this->translate('Facility List'); ?></b><span class="mandatory">*</span>
								</td>
								<td class="col-lg-8">
									<select id="facility" name="facility[]" multiple="multiple">
										<?php
										foreach ($facilityName['allName'] as $name) {
											if (trim($name['facility_id']) != '') {
												$facility = $name['facility_id'] . " - " . ucwords($name['facility_name']);
											} else {
												$facility = ucwords($name['facility_name']);
											}
										?>
											<option value="<?php echo $name['facility_name']; ?>"><?php echo $facility; ?></option>
										<?php
										}
										?>
									</select>
								</td>
							</tr>
							<tr>
								<td colspan="2">
									<hr>&nbsp;&nbsp;</td>
							</tr>
							<tr>
								<td colspan="2">
									<input type="hidden" class="form-control" id="province" name="province" />
									<input type="hidden" class="form-control" id="district" name="district" />
									<button type="button" onclick="mapProvinceFacility()" class="btn btn-space btn-primary"><?= $this->translate('Map Province to Facility'); ?></button>
								</td>
							</tr>
						</table>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
<script>
	$(document).ready(function() {
	
		$('#facility').multipleSelect({
			filter: true,
			minimumCountSelected: '1',
			placeholder: '<?= $this->translate('Please select Facility'); ?>',
			width: '100%'
		});
	});

	function mapProvinceFacility() {
		var facility = $("#facility").val();
		var province = $("#province").val();
		var district = $("#district").val();
		var provinceName = $("#provinceName").val();
		var districtName = $("#districtName").val();
		if (facility != null && facility != '' && province != '') {
			var cnfm = confirm("<?= $this->translate('Do you wish to merge the selected province with the selected facility?'); ?>");
			if (cnfm) {
				$.blockUI();
				$.post("<?php echo $this->url('spi-facility', array('action' => 'map-province')); ?>", {
						province: province,
						district: district,
						facility: facility,
						provinceName: provinceName,
						districtName: districtName	
					},
					function(data) {
						$.unblockUI();
						if (data > 0) {
							alert("<?= $this->translate('Province mapped successfully'); ?>");
							parent.closeModal();
							parent.window.location.href = window.parent.location.href;
						} else {
							alert("<?= $this->translate('We have experienced some problem. Please try again later.'); ?>");
							parent.closeModal();
							parent.window.location.href = window.parent.location.href;
						}
					});
			}
		} else {
			if ($.trim(facility) == '') {
				alert("<?= $this->translate('Please choose atleast one facility to continue'); ?>");
				$("#facility").focus();
				return false;
			} else if ($.trim(province) == '') {
				alert("<?= $this->translate('Province can not be empty'); ?>");
				return false;
			}
		}
	}

	function getDistrict(){
		province=$("#province").val();
		if(province!=""){
			if(province=='other'){
				$("#provinceName").show();
				$("#provinceName").addClass("isRequired");
				$('#district').html('<option value="">--Select--</option><option value="other">Other</option>');
			}else{
				$("#provinceName").hide();
				$("#provinceName").val('');
				$("#provinceName").removeClass("isRequired");
				$.blockUI();
				$.post("<?php echo $this->url('provinces', array('action' => 'getDistrictByProvince')); ?>", {
					provinceId: province,
				},
				function(data) {
					$('#district').html(data);
					$("#districtName").hide();
					$("#districtName").val('');
					$("#districtName").removeClass("isRequired");
					$.unblockUI();
				});
			}
		}else{
			$("#provinceName").hide();
			$("#provinceName").val('');
			$("#provinceName").removeClass("isRequired");
			$('#district').html('<option value="">--Select--</option>');
		}
	}

	function checkDistrict(){
		district=$("#district").val();
		if(district=='other'){
			$("#districtName").show();
			$("#districtName").addClass("isRequired");
		}else{
			$("#districtName").hide();
			$("#districtName").val('');
			$("#districtName").removeClass("isRequired");
		}
	}
</script>