<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/t/bs/jqc-1.12.0,dt-1.10.11,r-2.0.2,sc-1.4.1/datatables.min.css"/>



<div class="am-content">
        <div class="page-head">
          <div class="row">
				<div class="col-sm-8">
				<h2>SPI RT Facilities</h2>
				</div>
				<div class="col-sm-4">
					<a href="<?php echo $this->url('spi-facility',array('action' => 'add'));?>" class="btn btn-dark pull-right" style="margin-left: 5px;"><i class="fa fa-plus"></i>&nbsp;Add Facility</a>
					<a href="javascript:void(0);" class="btn btn-primary pull-right" onclick="showModal('/facility/get-facility-name',800,400);"><i class="fa fa-file-o"></i>&nbsp;Merge Facilities</a>
				</div>
		  </div>
		  
		 
        </div>
        
        
        <div class="main-content">
             
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">

                <table  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed" id="facilityDataTable">
					<thead>
					<tr>
						<th>Facility Id</th>
						<th>Facility Name</th>
						<th>Email</th>
						<th>Contact Person</th>
						<th>Action</th>
					</tr>
					</thead>
					<tbody>
					<tr>
						 <td colspan="6" class="dataTables_empty">Loading data from server</td>
					</tr>
					</tbody>
				</table>


            </div>
       
        <br>
      
            
            
        </div>
</div>
<script type="text/javascript" src="https://cdn.datatables.net/t/bs/jqc-1.12.0,dt-1.10.11,r-2.0.2,sc-1.4.1/datatables.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70/jquery.blockUI.min.js"></script>
<script type="text/javascript">
    var oTable = null;

 $(document).ready(function() {
	
        oTable = $('#facilityDataTable').DataTable({
            "bScrollCollapse": true,
            "bRetrieve": true,                        
            "aoColumns": [
				{"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center","bSortable":false}
            ],
            "aaSorting": [[ 0, "desc" ]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url('spi-facility',array('action' => 'index')); ?>",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
       
	} );
	
</script>