<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl=$this->layout()->acl;
if ($acl->isAllowed($role, 'Application\Controller\Facility', 'edit')) {
    $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false}';
}else{
    $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
}
?>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/t/bs/jqc-1.12.0,dt-1.10.11,r-2.0.2,sc-1.4.1/datatables.min.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<style>
    .highcharts-tooltip span {
	width:250px;
	overflow:auto;
	white-space:normal !important;
    }

    .select2{
      width:200px !important;
    }

    .title h3{
      display:inline;
    }
    
    .highcharts-legend{display: block !important;}
</style>
<div class="am-content">
        <div class="page-head">
          <div class="row">
				<div class="col-sm-8">
				<h2>SPI RT Facilities</h2>
				</div>
				<div class="col-sm-4">
						<?php if ($acl->isAllowed($role, 'Application\Controller\Facility', 'add')) { ?>
						<a href="<?php echo $this->url('spi-facility',array('action' => 'add'));?>" class="btn btn-dark pull-right" style="margin-left: 5px;"><i class="fa fa-plus"></i>&nbsp;Add Facility</a>
						<?php } ?>
						<?php if ($acl->isAllowed($role, 'Application\Controller\Facility', 'get-facility-name')) { ?>
						<a href="javascript:void(0);" class="btn btn-primary pull-right" onclick="showModal('/facility/get-facility-name',800,450);"><i class="fa fa-file-o"></i>&nbsp;Merge Facilities</a>
						<?php } ?>
				</div>
		  </div>
		  
		 
        </div>
        
        
        <div class="main-content">
             
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">

                <table  cellpadding="0" cellspacing="0" border="0" class="datatables table table-striped table-bordered table-condensed" id="facilityDataTable">
					<thead>
					<tr>
						<th>Facility ID</th>
						<th>Facility Name</th>
						<th>Email</th>
						<th>Contact Person</th>
						<?php if ($acl->isAllowed($role, 'Application\Controller\Facility', 'edit')) { ?>
						<th>Action</th>
						<?php } ?>
					</tr>
					</thead>
					<tbody>
					<tr>
						 <td colspan="6" class="dataTables_empty">Loading data from server</td>
					</tr>
					</tbody>
				</table>
            </div>
       
        <br>
        </div>
		
	<div class="audit-section main-content" style="display:none;">
	  <input type="hidden" name="fieldName" id="fieldName"/>
	  <input type="hidden" name="fieldVal" id="fieldVal"/>
	  <div class="row">
	       <div class="col-md-6" id="lefter">
		  <div class="widget widget-radar widget-pie">
                    <div class="widget-head">
                      <span class="title"><h3>Audit Performance</h3></span>
		      <label style="margin-left:5%;">Audit Round</label>
			<select class="" id="auditRndNo" name="auditRndNo[]" multiple="multiple" onchange="getAuditData('','');">
			</select>
                    </div>
		    <div id="radarChart"></div>
		   </div>
	       </div>
	  </div>
	</div>
	
	<div class="main-content">
             
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">

                <table  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed" id="testingPointDataTable">
					<thead>
					<tr>
						<th>Facility Id</th>
						<th>Facility Name</th>
						<th>Testing Point Type</th>
						<th>Date of Audit</th>
						<th>Score(%)</th>
						<th>Report</th>
						
					</tr>
					</thead>
					<tbody>
					<tr>
						 <td colspan="6" class="dataTables_empty">Loading data from server</td>
					</tr>
					</tbody>
				</table>
            </div>
       
        <br>
            
        </div>
</div>
<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>

<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://highcharts.github.io/pattern-fill/pattern-fill.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.11/js/dataTables.bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70/jquery.blockUI.min.js"></script>
<script type="text/javascript">
    var oTable = null;

 $(document).ready(function() {
        oTable = $('#facilityDataTable').DataTable({
            "bScrollCollapse": true,
            "bRetrieve": true,
			"pageLength": 50,
            "aoColumns": [
		<?php echo $editAction;?>
            ],
            "aaSorting": [[ 0, "desc" ]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url('spi-facility',array('action' => 'index')); ?>",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
	
	$(".select2").select2({
	    width: '100%',
		placeholder: '',
		allowClear: true,
		tags : false
	});
	} );
	
	function getTestingPoint(val,fieldName) {
        fTable = $('#testingPointDataTable').DataTable({
            "bScrollCollapse": false,
            "bRetrieve": false,
            "bDestroy": true,
			"pageLength": 50,
            "aoColumns": [
				{"sClass":"center noWrap"},
				{"sClass":"center noWrap"},
				{"sClass":"center noWrap"},
				{"sClass":"center noWrap"},
				{"sClass":"center noWrap"},
				{"sClass":"center noWrap"},
            ],
            "aaSorting": [[ 0, "desc" ]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url('spi-facility',array('action' => 'get-testing-point')); ?>",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
				aoData.push({"name": "val", "value": val});
				aoData.push({"name": "fieldName", "value": fieldName});
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
    }
	
    function downloadPdf(formId){
	window.open('<?php echo $this->url('spi-v3-form',array('action' => 'download-pdf'))?>'+formId);
	return false;
    }
    
    function getAuditData(val,fieldName){
      getFacilityAuditRounds(val,fieldName);	
      if($.trim(fieldName)!= ''){
	$("#fieldName").val(fieldName); 	
        $("#fieldVal").val(val);
      }
      
      roundno = $("#auditRndNo").val();
      $.post("<?php echo $this->url('spi-v3-form', array('action' => 'audit-performance')); ?>", {val:$("#fieldVal").val(),fieldName:$("#fieldName").val(),roundno:roundno},
      function (data) {
	  $("#radarChart").html(data);
	  $(".audit-section").show();
      });
    }
    
    function getFacilityAuditRounds(val,fieldName){
	 if($.trim(fieldName)!= ''){
	    $.post("<?php echo $this->url('spi-facility', array('action' => 'get-facility-audit-round')); ?>", {val:val,fieldName:fieldName},
	    function (data) {
	      $("#auditRndNo").html(data);
	      $("#auditRndNo").multipleSelect({placeholder:'Select Audit round(s)',width: '31%',minimumCountSelected:'2'});
	   });
	 }
    }
</script>