<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
if ($acl->isAllowed($role, 'Certification\Controller\Trainer', 'edit')) {
    $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false}';
} else {
    $editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
}
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>list of Candidate for certification</h2>
            </div>
            
           
        </div>
    </div>

        <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="col-sm-12">          
                <form class="navbar-form navbar-right" action="<?php echo $this->url('examination', array('action' => 'search')); ?>" method="POST">
                    <div style="display: inline"><input class="form-control" type="text" name="motCle" placeholder="Search..."/></div>
                    <button style="display: inline;height: 40px;" type="submit" class="btn-space btn-default" ><span class="glyphicon glyphicon-eye-open">Search</span>

                    </button>

                </form>
            </div>

            <table id="example" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget">
                <thead>
                    <tr>
                       <th>Provider ID (if available)  </th>
                       <th>Certification ID  </th>
                       <th>Provider</th>
                       <th> Final Score (≥80%)</th>
                       <th>Practical Exam</th>



                        <?php // if ($acl->isAllowed($role, 'Certification\Controller\Examination', 'edit') || $acl->isAllowed($role, 'Application\Controller\SpiV3', 'approve-status')) { ?>
                            <th style="width:6%;">Action</th>
                        <?php // } ?>
                    </tr>

                </thead>
                <tbody>
                    <tr>
                        <td colspan="10" class="dataTables_empty">Loading data from server</td>
                    </tr>
                    <?php foreach ( $this->paginator as $exam) : ?>
                        <tr>
                            <td><div style="width:100px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($exam->provider_id); ?></div></td>
                             <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($exam->certification_id); ?></div></td>
                            <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($exam->last_name . ' ' . $exam->first_name . ' ' . $exam->middle_name); ?></div></td>
                            <td><div style="color: red"><?php echo $this->escapeHtml($exam->final_score . ' %'); ?></div></td>
                            <td><div style="color: red"><?php echo $this->escapeHtml($exam->practical_total_score. ' %'); ?></div></td>

                            <td>
                                <div style="width:100px;height:40px;overflow:auto;">  <a href="<?php echo $this->url('certification', array('action' => 'add', 'id' => $exam->id), array('query' => 
        array('written' => $exam->final_score,'practical' => $exam->practical_total_score))); ?>"> <span class="glyphicon glyphicon-edit"></span>&nbsp;&nbsp;Approve</a> </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            
            <?php
 
 echo $this->paginationControl(
     // the paginator object
     $this->paginator,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     'partial/paginator.phtml',
     // the route to link to when a user clicks a control link
     array(
         'route' => 'examination'
     )
 );
 ?>

        </div>
    </div>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>









