<?php

use Zend\Session\Container;
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>list of Candidate for certification</h2>
            </div>


        </div>
    </div>

    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">

            <table id="example" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget">
                <thead>
                    <tr>
                        <th  style="width:10%;"> Professional Registration No(if available </th>
                        <th  style="width:10%;"> Certification Registration no </th>
                        <th  style="width:10%;">Certification ID  </th>
                        <th  style="width:10%;">Provider</th>
                        <th  style="width:10%;"> Final Score (≥80%)</th>
                        <th  style="width:10%;">Practical Exam</th>



                        <?php // if ($acl->isAllowed($role, 'Certification\Controller\Examination', 'edit') || $acl->isAllowed($role, 'Application\Controller\SpiV3', 'approve-status')) {  ?>
                        <th style="width:6%;">Action</th>
                        <?php // } ?>
                    </tr>

                </thead>
                <tbody>
                    <?php foreach ($this->examinations as $exam) : ?>
                        <tr>
                            <td><div style="width:100px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($exam->professional_reg_no); ?></div></td>
                            <td><div style="width:100px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($exam->certification_reg_no); ?></div></td>
                            <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($exam->certification_id); ?></div></td>
                            <td><div style="width:180px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($exam->last_name . ' ' . $exam->first_name . ' ' . $exam->middle_name); ?></div></td>
                            <td><div style="color: red"><?php echo $this->escapeHtml($exam->final_score . ' %'); ?></div></td>
                            <td><div style="color: red"><?php echo $this->escapeHtml($exam->practical_total_score . ' %'); ?></div></td>
                            <td>
                                <?php if(empty($exam->final_score) || empty($exam->practical_total_score)) { 
                              echo   '<div style="width:100px;height:40px;overflow:auto;">  
                                        
                                    <span class="glyphicon glyphicon-edit"></span>&nbsp;&nbsp;Approve</a> </div>';
                                }else {
                                    echo   '<div style="width:100px;height:40px;overflow:auto;">  
                                        
                                    <a href='.$this->url("certification", array("action" => "add", "id" => $exam->id), array("query" =>
                                        array("written" => $exam->final_score, "practical" => $exam->practical_total_score, "direct" => $exam->direct_observation_score, "sample" => $exam->Sample_testing_score, "provider" => $exam->provider)))
                                    .'> <span class="glyphicon glyphicon-edit"></span>&nbsp;&nbsp;Approve</a> </div>';
                                 
                                    
                                }; ?>
                            </td></tr>
                    <?php endforeach; ?>
                </tbody> 
            </table>


        </div>
    </div>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>

<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>


<script type="text/javascript" language="javascript" >
    $(document).ready(function () {

        $('#example').dataTable({
            "aProcessing": true,
            "aServerSide": true,
        })
    });
</script>






