<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/jasny-bootstrap.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<div class="am-content">
	<div class="page-head">
		<h2>Edit Global Config</h2>
	</div>
	<div class="main-content">
		<div class="widget widget-fullwidth widget-small" style="padding:5px;">
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default">
						<div class="panel-body">
							<form role="form" class="form-horizontal" name="editConfig" id="editConfig" method="post" action="<?php echo $this->url('config', array('action' => 'edit-global')); ?>" enctype="multipart/form-data" autocomplete="off">
								<div class="form-group">
									<label for="header" class="col-sm-2 control-label">Header</label>
									<div class="col-lg-4">
										<textarea row="3" name="header" id="header" class="form-control" placeholder="Header" title="Please enter header"><?php echo $config['header'] ?></textarea>
									</div>
								</div>
								<div class="form-group">
									<label for="" class="col-sm-2 control-label">Logo</label>
									<div class="col-lg-4">
										<div class="fileinput fileinput-new" data-provides="fileinput">
											<div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
												<?php
												if (isset($config['logo']) && trim($config['logo']) != '' && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo" . DIRECTORY_SEPARATOR . $config['logo'])) {
												?>
													<img src="/uploads/logo/<?php echo $config['logo']; ?>" alt="Logo image" />
												<?php } else { ?>
													<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=No image" />
												<?php } ?>
											</div>
											<div>
												<span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span>
													<input type="file" id="logo" name="logo" title="Please select logo image" onchange="getNewImage('<?php echo $config['logo']; ?>');">
												</span>
												<?php
												if (isset($config['logo']) && trim($config['logo']) != '' && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo" . DIRECTORY_SEPARATOR . $config['logo'])) {
												?>
													<a id="clearImage" href="javascript:void(0);" class="btn btn-default" data-dismiss="fileupload" onclick="clearImage('<?php echo $config['logo']; ?>')">Clear</a>
												<?php } ?>
												<a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
											</div>
										</div>
										<div class="box-body">
											Please make sure logo image size of: <code>170x175</code>
										</div>
									</div>
								</div>
								<div class="form-group">
									<label for="" class="col-sm-2 control-label">Template File</label>
									<div class="col-lg-4">
										<div class="tempfileinput fileinput-new" data-provides="fileinput">
											<div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
												<?php
												if (isset($config['template_file']) && trim($config['template_file']) != '' && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "template" . DIRECTORY_SEPARATOR . $config['template_file'])) {
												?>
												<?php echo "template file present"; ?>
													<!-- <img src="/uploads/template/<?php echo $config['template_file']; ?>" alt="Template File" /> -->
												<?php } else { ?>
													<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=No image" />
												<?php } ?>
											</div>
											<div>
												<span class="btn btn-default btn-file"><span class="fileinput-new">Select File</span><span class="fileinput-exists">Change</span>
													<input type="file" id="template_file" name="template_file" accept=".pdf" title="Please select Template File" onchange="getNewTempFile('<?php echo $config['template_file']; ?>');">
												</span>
												<?php
												if (isset($config['template_file']) && trim($config['template_file']) != '' && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "template" . DIRECTORY_SEPARATOR . $config['template_file'])) {
												?>
													<a id="clearTempFile" href="javascript:void(0);" class="btn btn-default" data-dismiss="fileupload" onclick="clearTempFile('<?php echo $config['template_file']; ?>')">Clear</a>
												<?php } ?>
												<a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
											</div>
										</div>
									</div>
								</div>
								<div class="form-group">
									<label for="country-name" class="col-sm-2 control-label">Country or Instance Name<span class="mandatory">*</span></label>
									<div class="col-lg-4">
										<input name="country-name" id="country-name" class="form-control isRequired" placeholder="Country/Instance Name" title="Please enter country/instance name" value="<?php echo $config['country-name']; ?>" />
									</div>
								</div>
								<div class="form-group">
									<label for="approve_status" class="col-sm-2 control-label">Auto Approval<span class="mandatory">*</span></label>
									<div class="col-lg-4">
										<select name="approve_status" id="approve_status" class="form-control isRequired" title="Please select audit approval status">
											<option value="">--select</option>
											<option value="yes" <?php echo ($config['approve_status'] == 'yes' ? " selected='selected'" : ""); ?>>Yes</option>
											<option value="no" <?php echo ($config['approve_status'] == 'no' ? " selected='selected'" : ""); ?>>No</option>
										</select>
									</div>
								</div>
								<div class="form-group">
									<label for="embed_signatures_in_pdf" class="col-sm-2 control-label">Embed Signatures In PDF<span class="mandatory">*</span></label>
									<div class="col-lg-4">
										<select name="embed_signatures_in_pdf" id="embed_signatures_in_pdf" class="form-control isRequired" title="Please select audit approval status">
											<option value="">--select</option>
											<option value="yes" <?php echo ($config['embed_signatures_in_pdf'] == 'yes' ? " selected='selected'" : ""); ?>>Yes</option>
											<option value="no" <?php echo ($config['embed_signatures_in_pdf'] == 'no' ? " selected='selected'" : ""); ?>>No</option>
										</select>
									</div>
								</div>
								<div class="form-group">
									<label for="dashboard_map_display" class="col-sm-2 control-label">Dashboard Map Display<span class="mandatory">*</span></label>
									<div class="col-lg-4">
										<select name="dashboard_map_display" id="dashboard_map_display" class="form-control isRequired" title="Please select dashboard map display" onchange="checkMapDisplay()">
											<option value="">--select</option>
											<option value="horizontal" <?php echo ($config['dashboard_map_display'] == 'horizontal' ? " selected='selected'" : ""); ?>>Horizontal</option>
											<option value="vertical" <?php echo ($config['dashboard_map_display'] == 'vertical' ? " selected='selected'" : ""); ?>>Vertical</option>
										</select>
										<input type="text" value="<?php echo $config['dashboard_map_height']; ?>" placeholder="Enter map display height" class="form-control" name="dashboard_map_height" id="dashboard_map_height" style="<?php echo ($config['dashboard_map_display'] == 'vertical' ?  'display:none;' : '')?>" title="Please enter the map display height">
									</div>
								</div>
								<div class="form-group">
									<label for="dashboard_map_zoomlevel" class="col-sm-2 control-label">Dashboard Map Zoom Level<span class="mandatory">*</span></label>
									<div class="col-lg-4">
										<input name="dashboard_map_zoomlevel" id="dashboard_map_zoomlevel" class="form-control isRequired" placeholder="Enter dashboard map zoomlevel" title="Please enter dashboard map zoomlevel" value="<?php echo $config['dashboard_map_zoomlevel']; ?>" />
									</div>
								</div>
								<div class="form-group">
									<label for="approve_status" class="col-sm-2 control-label">Language <span class="mandatory">*</span></label>
									<div class="col-lg-4">
										<select name="language" id="language" class="form-control isRequired" title="Please select language">
											<option value="English" <?php echo ($config['language'] == 'English' ? " selected='selected'" : ""); ?>>English</option>
											<option value="French" <?php echo ($config['language'] == 'French' ? " selected='selected'" : ""); ?>>French</option>
											<option value="Spanish" <?php echo ($config['language'] == 'Spanish' ? " selected='selected'" : ""); ?>>Spanish</option>
											<option value="Portuguese" <?php echo ($config['language'] == 'Portuguese' ? " selected='selected'" : ""); ?>>Portuguese</option>
										</select>
									</div>
								</div>
								<div class="form-group">
									<label for="latitude" class="col-sm-2 control-label">Latitude<span class="mandatory">*</span></label>
									<div class="col-lg-4">
										<input name="latitude" id="latitude" class="form-control isRequired" placeholder="Latitude" title="Please enter Latitude" value="<?php echo $config['latitude']; ?>" />
									</div>
								</div>
								<div class="form-group">
									<label for="longitude" class="col-sm-2 control-label">Longitude<span class="mandatory">*</span></label>
									<div class="col-lg-4">
										<input name="longitude" id="longitude" class="form-control isRequired" placeholder="Longitude" title="Please enter Longitude" value="<?php echo $config['longitude']; ?>" />
									</div>
								</div>
								<div class="form-group">
									<label for="web_version" class="col-sm-2 control-label">Web Version <span class="mandatory">*</span></label>
									<div class="col-lg-4">
										<select name="web_version[]" id="web_version" class=" " title="Please select web version" multiple="multiple">
											<option value="v3" <?php if (preg_match("/v3/i", $config['web_version'])) {
																	echo "selected='selected'";
																}  ?>>Version 3 (SPI-RT)</option>
											<!-- <option value="v5" <?php if (preg_match("/v5/i", $config['web_version'])) {
																		echo "selected='selected'";
																	}  ?>>Version 5 (SPI-RRT)</option> -->
											<option value="v6" <?php if (preg_match("/v6/i", $config['web_version'])) {
																	echo "selected='selected'";
																}  ?>>Version 6 (SPI-RRT)</option>
										</select>
									</div>
								</div>
								<hr>
								<div class="spacer col-lg-5" align="center">
									<input type="hidden" name="removedLogoImage" id="removedLogoImage" />
									<input type="hidden" name="removedTempFile" id="removedTempFile" />
									<button type="button" onclick="validateNow();" class="btn btn-space btn-primary">Update</button>
									<a href="<?php echo $this->url('config', array('action' => 'index')); ?>" class="btn btn-space btn-default">Cancel</a>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<script>
	$(document).ready(function() {
		$("#web_version").multipleSelect({
			placeholder: 'Select Web Version',
			width: '100%'
		});

	});

	function validateNow() {
		flag = deforayValidator.init({
			formId: 'editConfig'
		});
		if (flag) {
			document.getElementById('editConfig').submit();
		}
	}

	function clearImage(img) {
		$('.fileinput').fileinput('clear');
		$('#clearImage').hide();
		$("#offerImage").addClass("isRequired");
		$("#removedLogoImage").val(img);
	}

	function getNewImage(img) {
		$('#clearImage').hide();
		$("#removedLogoImage").val(img);
	}

	function clearTempFile(img) {
		$('.tempfileinput').fileinput('clear');
		$('#clearTempFile').hide();
		$("#removedTempFile").val(img);
	}

	function getNewTempFile(img) {
		$('#clearTempFile').hide();
		$("#removedTempFile").val(img);
	}

	function checkMapDisplay(){
		dashboardMapDisplay=$("#dashboard_map_display").val();
		if(dashboardMapDisplay=='horizontal'){
			$("#dashboard_map_height").show();
			$("#dashboard_map_height").addClass("isRequired");
		}else{
			$("#dashboard_map_height").hide();
			$("#dashboard_map_height").removeClass("isRequired");
		}
	}
</script>