<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">
        <h2>Add an Exam Administrator</h2>
    </div>


    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body" >



                            <?php
                            $form->setAttribute('action', $this->url('exam-admin', array('action' => 'add')));
                            $form->prepare();
                            $form->get('admin_last_name')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Admin Last Name'
                            ]);

                            $form->get('admin_first_name')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Admin First Name']);
                            
                            $form->get('admin_middle_name')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'AdminMiddle Name']);

                            $form->get('region')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Region']);
                            $form->get('district')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'District']);
                           
                            $form->get('phone')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Phone']);
                            $form->get('email')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Email']);

                            $form->get('prefered_contact_method')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Prefered Contact Method']);
                            $form->get('current_job')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Current Job']);
                            $form->get('job_address')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Job Address']);
                          

                            echo $this->form()->openTag($form);
                            ?>
                            <?php echo $this->formHidden($form->get('exam_admin_by_id')->setAttribute('class', 'form-control')) ?>
                            <div class="form-group col-lg-6"> 
                                <?= $this->formLabel($form->get('admin_last_name')); ?>
                                <?= $this->formElement($form->get('admin_last_name')); ?>
                                <?= $this->formElementErrors($form->get('admin_last_name')); ?>
                            </div>
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('admin_first_name')); ?>
                                <?= $this->formElement($form->get('admin_first_name')); ?>
                                <?= $this->formElementErrors($form->get('admin_first_name')); ?>
                            </div>
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('admin_middle_name')); ?>
                                <?= $this->formElement($form->get('admin_middle_name')); ?>
                                <?= $this->formElementErrors($form->get('admin_middle_name')); ?>
                            </div>
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('region')); ?>
                                <?= $this->formElement($form->get('region')); ?>
                                <?= $this->formElementErrors($form->get('region')); ?>
                            </div>
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('district')); ?>
                                <?= $this->formElement($form->get('district')); ?>
                                <?= $this->formElementErrors($form->get('district')); ?></div>
                           
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('phone')); ?>
                                <?= $this->formElement($form->get('phone')); ?>
                                <?= $this->formElementErrors($form->get('phone')); ?>
                            </div>
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('email')); ?>
                                <?= $this->formElement($form->get('email')); ?>
                                <?= $this->formElementErrors($form->get('email')); ?>
                            </div>
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('prefered_contact_method')); ?>
                                <?= $this->formElement($form->get('prefered_contact_method')); ?>
                                <?= $this->formElementErrors($form->get('prefered_contact_method')); ?>       
                            </div>
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('current_job')); ?>
                                <?= $this->formElement($form->get('current_job')); ?>
                                <?= $this->formElementErrors($form->get('current_job')); ?>
                            </div>
                           
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('job_address')); ?>
                                <?= $this->formElement($form->get('job_address')); ?>
                                <?= $this->formElementErrors($form->get('job_address')); ?>
                            </div>
                            <div class="row" style="margin-left: 18px;"><?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                 <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('exam-admin', array('action' => 'index')); ?>" >CANCEL</a> </div>
                                <?php echo $this->form()->closeTag();
                                ?>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <br>
        <br>

    </div>

</div>

</script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>




