<?php
$tokenArray = [];
foreach ($tokenResults as $token) {
	$tokenArray[] = $token['token'];
}
?>
<link href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" type="text/css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/typeahead.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/tokenfield.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/jasny-bootstrap.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jasny-bootstrap.min.js'); ?>">
	type = "text/javascript" >
</script>
<div class="am-content">
	<div class="page-head">
		<h2>Add User</h2>
		<span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>
	</div>

	<div class="main-content">
		<div class="widget widget-fullwidth widget-small" style="padding:5px;">
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default">
						<div class="panel-body">
							<form role="form" name="addUserInformation" id="addUserInformation" enctype="multipart/form-data" method="post" action="<?php echo $this->url('users', array('action' => 'add')); ?>" autocomplete="off">
								<div class="form-group col-lg-6">
									<label>First Name <span class="mandatory">*</span> </label>
									<input type="text" placeholder="First Name" class="form-control isRequired" name="firstName" id="firstName" title="Please enter the first name">
								</div>
								<div class="form-group col-lg-6">
									<label>Last Name </label>
									<input type="text" placeholder="Last Name" class="form-control" name="lastName" id="lastName" title="Please enter the last name">
								</div>
								<div class="form-group col-lg-6">
									<label>Login ID <span class="mandatory">*</span></label>
									<input type="text" placeholder="Login ID" class="form-control isRequired" name="userName" id="userName" title="Please enter the user name" onblur="checkNameValidation('users','login', this, null, 'This name already exists. Please choose another name.')">
								</div>
								<div class="form-group col-lg-6">
									<label>Password <span class="mandatory">*</span></label>
									<input type="password" placeholder="Password" class="form-control isRequired" name="password" id="password" title="Please enter the password">
								</div>
								<div class="form-group col-lg-6">
									<label>Confirm Password <span class="mandatory">*</span></label>
									<input type="password" placeholder="Confirm Password" class="form-control confirmPassword isRequired" name="password" id="confirmPassword" title="Please check your password and confirm password are same">
								</div>
								<div class="form-group col-lg-6">
									<label>Mobile Number</label>
									<input type="tel" placeholder="Enter Mobile Number" maxlength="10" onkeypress="return isNumberKey(event);" class="form-control" name="mobile_no" id="mobile_no" title="Please enter the mobile number" onblur="checkNameValidation('users','contact_no', this,null,'Entered mobile number is already exist.')">
								</div>
								<div class="form-group col-lg-6">
									<label>Email</label>
									<input type="text" placeholder="Email" class="form-control isEmail" name="email" id="email" title="Please enter the email id" onblur="checkNameValidation('users','email', this,null,'Entered mail id is already exist.')">
								</div>
								<div class="form-group col-lg-6">
									<label>Role <span class="mandatory">*</span></label>
									<select class="form-control isRequired" name="roleId" id="roleId" title="Please select the role">
										<option value="">--Select--</option>
										<?php
										foreach ($roleResults as $role) {
										?>
											<option value="<?php echo $role['role_id']; ?>"><?php echo ucwords($role['role_name']); ?></option>
										<?php
										}
										?>
									</select>
								</div>
								<div class="form-group col-lg-6">
									<label>Token (Note: You can add multiple token by comma separator values)</label>
									<input type="text" placeholder="Enter token" class="form-control" name="token" id="token" title="Please enter token">
								</div>
								<div class="form-group col-lg-6">
									<label>Status <span class="mandatory">*</span></label>
									<select class="form-control isRequired" name="status" id="status" title="Please select the status">
										<option value="active">Active</option>
										<option value="inactive">Inactive</option>
									</select>
								</div>
								<div class="form-group col-lg-6">
									<label>Mapping Type</label>
									<select class="form-control" name="mappingType" id="mappingType" title="Please select the mappingType" onchange="getLocations()">
										<option value="">--Select--</option>	
										<option value="country">Country</option>
										<option value="province">Province</option>
										<option value="district">District</option>
									</select>
								</div>
								<div class="form-group col-lg-6 country" style="display:none">
									<label>Countries</label>
									<div class="form-control">
										<select multiple="multiple" name="country[]" id="country" title="Please select the country">
											<?php foreach($countries as $row){ ?>
												<option value="<?php echo $row['country_id'];?>"><?php echo ucwords($row['country_name']);?></option>
											<?php } ?>
										</select>
									</div>
								</div>
								<div class="form-group col-lg-6 province" style="display:none">
									<label>Provinces</label>
									<div class="form-control">
										<select multiple="multiple" name="province[]" id="province" title="Please select the province">
											<?php foreach($provinces as $row){ ?>
												<option value="<?php echo $row['geo_id'];?>"><?php echo ucwords($row['geo_name']);?></option>
											<?php } ?>
										</select>
									</div>
								</div>
								<div class="form-group col-lg-6 district" style="display:none">
									<label>Districts</label>
									<div class="form-control">
										<select multiple="multiple" name="district[]" id="district" title="Please select the district">
											<?php foreach($districts as $row){ ?>
												<option value="<?php echo $row['geo_id'];?>"><?php echo ucwords($row['geo_name']);?></option>
											<?php } ?>
										</select>
									</div>
								</div>
								<div class="form-group col-lg-6">
									<label>User Image</label>
									<div class="input-group col-sm-6" style="padding-left: 14px;width:66%;">
										<div class="controls">
											<div class="fileinput fileinput-new" data-provides="fileinput">
												<div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
													<img src="http://www.placehold.it/200x150/3c8dbc/fff&text=Image">
												</div>
												<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
												<div>
													<span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span>
														<input type="file" class="" name="user_image" id="user_image" title="Please choose image"></span>
													<a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="spacer col-lg-12">
									<button type="button" onclick="validateNow()" class="btn btn-space btn-primary">Submit</button>
									<a href="<?php echo $this->url('users', array('action' => 'index')); ?>" class="btn btn-space btn-default">Cancel</a>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		<br>
		<br>
	</div>
</div>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$("#country").multipleSelect({
			placeholder: '<?= $this->translate('Please select country.'); ?>',
			width: '100%',
			minimumCountSelected: '2'
		});

		$("#province").multipleSelect({
			placeholder: '<?= $this->translate('Please select province.'); ?>',
			width: '100%',
			minimumCountSelected: '2'
		});

		$("#district").multipleSelect({
			placeholder: '<?= $this->translate('Please select district.'); ?>',
			width: '100%',
			minimumCountSelected: '2'
		});

		$('#token').tokenfield({
			autocomplete: {
				source: <?php echo json_encode($tokenArray); ?>,
				delay: 100
			},
			showAutocompleteOnFocus: false
		})

		$('#token').on('tokenfield:createtoken', function(event) {
			var existingTokens = $(this).tokenfield('getTokens');
			$.each(existingTokens, function(index, token) {
				if (token.value === event.attrs.value)
					event.preventDefault();
			});
		});
	});

	function isNumberKey(evt) {
		var charCode = (evt.which) ? evt.which : evt.keyCode
		if (charCode > 31 && (charCode < 48 || charCode > 57))
			return false;
		return true;
	}

	duplicateName = true;

	function validateNow() {
		flag = deforayValidator.init({
			formId: 'addUserInformation'
		});
		if (flag) {
			if (duplicateName) {
				document.getElementById('addUserInformation').submit();
			}
		}
	}

	function checkNameValidation(tableName, fieldName, obj, fnct, msg) {
		checkValue = document.getElementById(obj.id).value;
		if (checkValue == null || checkValue == '') return false;
		$.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {
				tableName: tableName,
				fieldName: fieldName,
				value: checkValue,
				fnct: fnct
			},
			function(data) {
				if (data > 0) {
					alert(msg);
					duplicateName = false;
					document.getElementById(obj.id).value = "";
				} else {
					duplicateName = true;
				}
			});
	}

	function getLocations() {
		var mappingType = $("#mappingType").val();
		var types = ['country', 'province', 'district'];
		
		types.forEach(function(type) {
			if (mappingType === type) {
				$("." + type).show();
			} else {
				$("." + type).hide();
				$("." + type + " select").val([]).multipleSelect("refresh");
			}
		});
	}
</script>