<?php
$tokenArray = [];
foreach ($tokenResults as $token) {
	$tokenArray[] = $token['token'];
}
?>
<link href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" type="text/css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/typeahead.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/tokenfield.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/jasny-bootstrap.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jasny-bootstrap.min.js'); ?>">
	type = "text/javascript" >
</script>
<div class="am-content">
	<div class="page-head">
		<h2><?= $this->translate('Add User'); ?></h2>
		<span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> <?= $this->translate('indicates required field'); ?></span>
	</div>

	<div class="main-content">
		<div class="widget widget-fullwidth widget-small" style="padding:5px;">
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default">
						<div class="panel-body">
							<form role="form" name="addUserInformation" id="addUserInformation" enctype="multipart/form-data" method="post" action="<?php echo $this->url('users', array('action' => 'add')); ?>" autocomplete="off">
								<div class="form-group col-lg-6">
									<label><?= $this->translate('First Name'); ?><span class="mandatory">*</span> </label>
									<input type="text" placeholder="<?= $this->translate('First Name'); ?>" class="form-control isRequired" name="firstName" id="firstName" title="<?= $this->translate('Please enter the first name'); ?>">
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Last Name'); ?></label>
									<input type="text" placeholder="<?= $this->translate('Last Name'); ?>" class="form-control" name="lastName" id="lastName" title="<?= $this->translate('Please enter the last name'); ?>">
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Login ID'); ?> <span class="mandatory">*</span></label>
									<input type="text" placeholder="<?= $this->translate('Login ID'); ?>" class="form-control isRequired" name="userName" id="userName" title="<?= $this->translate('Please enter the user name'); ?>" onblur="checkNameValidation('users','login', this, null, 'This name already exists. Please choose another name.')">
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Password'); ?> <span class="mandatory">*</span></label>
									<input type="password" placeholder="<?= $this->translate('Password'); ?>" class="form-control isRequired" name="password" id="password" title="<?= $this->translate('Please enter the password'); ?>">
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Confirm Password'); ?> <span class="mandatory">*</span></label>
									<input type="password" placeholder="<?= $this->translate('Confirm Password'); ?>" class="form-control confirmPassword isRequired" name="password" id="confirmPassword" title="<?= $this->translate('Please check your password and confirm password are same'); ?>">
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Mobile Number'); ?></label>
									<input type="tel" placeholder="<?= $this->translate('Enter Mobile Number'); ?>" maxlength="10" onkeypress="return isNumberKey(event);" class="form-control" name="mobile_no" id="mobile_no" title="<?= $this->translate('Please enter the mobile number'); ?>" onblur="checkNameValidation('users','contact_no', this,null,'Entered mobile number is already exist.')">
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Email'); ?></label>
									<input type="text" placeholder="<?= $this->translate('Email'); ?>" class="form-control isEmail" name="email" id="email" title="<?= $this->translate('Please enter the email id'); ?>" onblur="checkNameValidation('users','email', this,null,'Entered mail id is already exist.')">
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Role'); ?> <span class="mandatory">*</span></label>
									<select class="form-control isRequired" name="roleId" id="roleId" title="<?= $this->translate('Please select the role'); ?>">
										<option value="">--<?= $this->translate('Select'); ?>--</option>
										<?php
										foreach ($roleResults as $role) {
										?>
											<option value="<?php echo $role['role_id']; ?>"><?php echo ucwords($role['role_name']); ?></option>
										<?php
										}
										?>
									</select>
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Token (Note: You can add multiple token by comma separator values)'); ?></label>
									<input type="text" placeholder="<?= $this->translate('Enter token'); ?>" class="form-control" name="token" id="token" title="<?= $this->translate('Please enter token'); ?>">
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Status'); ?> <span class="mandatory">*</span></label>
									<select class="form-control isRequired" name="status" id="status" title="<?= $this->translate('Please select the status'); ?>">
										<option value="active"><?= $this->translate('Active'); ?></option>
										<option value="inactive"><?= $this->translate('Inactive'); ?></option>
									</select>
								</div>
								<div class="form-group col-lg-6">
									<label for="language"><?= $this->translate('Language'); ?></label>
									<select name="language" id="language" class="form-control" title="<?= $this->translate('Please select language'); ?>">
										<option value="">--<?= $this->translate('Select'); ?>--</option>
										<option value="en_US"><?= $this->translate('English'); ?></option>
										<option value="fr_FR"><?= $this->translate('French'); ?></option>
										<option value="pt_BR"><?= $this->translate('Portuguese'); ?></option>
										<option value="es_ES"><?= $this->translate('Spanish'); ?></option>
									</select>
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Mapping Type'); ?></label>
									<select class="form-control" name="mappingType" id="mappingType" title="<?= $this->translate('Please select the mappingType'); ?>" onchange="getLocations()">
										<option value="">--<?= $this->translate('Select'); ?>--</option>
										<option value="country"><?= $this->translate('Country'); ?></option>
										<option value="province"><?= $this->translate('Province'); ?></option>
										<option value="district"><?= $this->translate('District'); ?></option>
									</select>
								</div>
								<div class="form-group col-lg-6 country" style="display:none">
									<label><?= $this->translate('Countries'); ?></label>
									<div class="form-control">
										<select multiple="multiple" name="country[]" id="country" title="<?= $this->translate('Please select the country'); ?>">
											<?php foreach($countries as $row){ ?>
												<option value="<?php echo $row['country_id'];?>"><?php echo ucwords($row['country_name']);?></option>
											<?php } ?>
										</select>
									</div>
								</div>
								<div class="form-group col-lg-6 province" style="display:none">
									<label><?= $this->translate('Provinces'); ?></label>
									<div class="form-control">
										<select multiple="multiple" name="province[]" id="province" title="<?= $this->translate('Please select the province'); ?>">
											<?php foreach($provinces as $row){ ?>
												<option value="<?php echo $row['geo_id'];?>"><?php echo ucwords($row['geo_name']);?></option>
											<?php } ?>
										</select>
									</div>
								</div>
								<div class="form-group col-lg-6 district" style="display:none">
									<label><?= $this->translate('Districts'); ?></label>
									<div class="form-control">
										<select multiple="multiple" name="district[]" id="district" title="<?= $this->translate('Please select the district'); ?>">
											<?php foreach($districts as $row){ ?>
												<option value="<?php echo $row['geo_id'];?>"><?php echo ucwords($row['geo_name']);?></option>
											<?php } ?>
										</select>
									</div>
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('User Image'); ?></label>
									<div class="input-group col-sm-6" style="padding-left: 14px;width:66%;">
										<div class="controls">
											<div class="fileinput fileinput-new" data-provides="fileinput">
												<div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
													<img src="http://www.placehold.it/200x150/3c8dbc/fff&text=Image">
												</div>
												<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
												<div>
													<span class="btn btn-default btn-file"><span class="fileinput-new"><?= $this->translate('Select image'); ?></span><span class="fileinput-exists"><?= $this->translate('Change'); ?></span>
														<input type="file" class="" name="user_image" id="user_image" title="<?= $this->translate('Please choose image'); ?>"></span>
													<a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput"><?= $this->translate('Remove'); ?></a>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="spacer col-lg-12">
									<button type="button" onclick="validateNow()" class="btn btn-space btn-primary"><?= $this->translate('Submit'); ?></button>
									<a href="<?php echo $this->url('users', array('action' => 'index')); ?>" class="btn btn-space btn-default"><?= $this->translate('Cancel'); ?></a>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		<br>
		<br>
	</div>
</div>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$("#country").multipleSelect({
			placeholder: '<?= $this->translate('Please select country.'); ?>',
			width: '100%',
			minimumCountSelected: '2'
		});

		$("#province").multipleSelect({
			placeholder: '<?= $this->translate('Please select province.'); ?>',
			width: '100%',
			minimumCountSelected: '2'
		});

		$("#district").multipleSelect({
			placeholder: '<?= $this->translate('Please select district.'); ?>',
			width: '100%',
			minimumCountSelected: '2'
		});

		$('#token').tokenfield({
			autocomplete: {
				source: <?php echo json_encode($tokenArray); ?>,
				delay: 100
			},
			showAutocompleteOnFocus: false
		})

		$('#token').on('tokenfield:createtoken', function(event) {
			var existingTokens = $(this).tokenfield('getTokens');
			$.each(existingTokens, function(index, token) {
				if (token.value === event.attrs.value)
					event.preventDefault();
			});
		});
	});

	function isNumberKey(evt) {
		var charCode = (evt.which) ? evt.which : evt.keyCode
		if (charCode > 31 && (charCode < 48 || charCode > 57))
			return false;
		return true;
	}

	duplicateName = true;

	function validateNow() {
		flag = deforayValidator.init({
			formId: 'addUserInformation'
		});
		if (flag) {
			if (duplicateName) {
				document.getElementById('addUserInformation').submit();
			}
		}
	}

	function checkNameValidation(tableName, fieldName, obj, fnct, msg) {
		checkValue = document.getElementById(obj.id).value;
		if (checkValue == null || checkValue == '') return false;
		$.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {
				tableName: tableName,
				fieldName: fieldName,
				value: checkValue,
				fnct: fnct
			},
			function(data) {
				if (data > 0) {
					alert(msg);
					duplicateName = false;
					document.getElementById(obj.id).value = "";
				} else {
					duplicateName = true;
				}
			});
	}

	function getLocations() {
		var mappingType = $("#mappingType").val();
		var types = ['country', 'province', 'district'];
		
		types.forEach(function(type) {
			if (mappingType === type) {
				$("." + type).show();
			} else {
				$("." + type).hide();
				$("." + type + " select").val([]).multipleSelect("refresh");
			}
		});
	}
</script>