<link href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" type="text/css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/typeahead.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/tokenfield.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/jasny-bootstrap.min.css'); ?>"/>
<script src="<?php echo $this->basePath('assets/js/jasny-bootstrap.min.js'); ?>"> type="text/javascript"></script>
<div class="am-content">
        <div class="page-head">
          <h2>Change Password</h2>
	    <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>
        </div>
        
        <div class="main-content">
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">
	    <div class="row">
            <div class="col-sm-12">
              <div class="panel panel-default">
                <div class="panel-body">
                  <form role="form" name="changePasswordInformation" id="changePasswordInformation" method="post" action="<?php echo $this->url('users', array('action' => 'change-password')); ?>" autocomplete="off" >
					<div class="form-group col-lg-6">
                      <label>Old Password <span class="mandatory">*</span></label>
                      <input type="password" placeholder="Old Password" class="form-control isRequired" name="password" id="password" title="Please enter the old password" onblur="checkNameValidation('users','password', this,'<?php echo "id##" .$result->id; ?>', 'Incorrect password.')" >
                    </div>
                    <div class="form-group col-lg-6">
                      <label>New Password <span class="mandatory">*</span></label>
                      <input type="password" placeholder="New Password" class="form-control isRequired" name="newpassword" id="newpassword" title="Please check your new password" onblur="checkNewPassword();">
                    </div>
					<div class="form-group col-lg-6">
                      <label>Confirm Password <span class="mandatory">*</span></label>
                      <input type="password" placeholder="Confirm Password" class="form-control isRequired" name="confirmpassword" id="confirmpassword" title="Please check your new password and confirm password are same" onblur="checkNewPassword();" >
                    </div>
                      <div class="spacer col-lg-12">
                      <button type="button" onclick="validateNow()" class="btn btn-space btn-primary">Submit</button>
                     <a href="<?php echo $this->url('dashboard', array('action' => 'index')); ?>" class="btn btn-space btn-default">Cancel</a> 
                    </div>
                  </form>
                </div>
              </div>
            </div>
        </div>
        </div>
        <br>
        <br>
        </div>
</div>
<script type="text/javascript">
		
		duplicateName = true;
		function validateNow() {
			   flag = deforayValidator.init({
				   formId: 'changePasswordInformation'
			   });
			   if (flag) {
				   if (duplicateName) {
					   document.getElementById('changePasswordInformation').submit();
				   }
			   }
		}
		
		function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if (checkValue!='') {
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
        function(data) {
            if (data == 0){
                alert(msg);
                duplicateName = false;
                document.getElementById(obj.id).value = "";
                document.getElementById(obj.id).focus();
            }
            else {
                duplicateName = true;
                document.getElementById("password").style.pointerEvents = "none";
                document.getElementById("newpassword").style.pointerEvents = "auto";
                document.getElementById("confirmpassword").style.pointerEvents = "auto";
            }
        });
      }
    }
        function checkNewPassword(){
        pwd = $('#password').val();
        newPwd = $('#newpassword').val();
        confirmPwd = $('#confirmpassword').val();
         if(newPwd != ''){
            if(pwd == newPwd){
                alert('New password should not same as an used password');
                $('#newpassword').val("");
                $('#newpassword').focus();
            }
        }
        
        if(newPwd != '' && confirmPwd != ''){
            if(newPwd != confirmPwd){
                alert('Confirm password should be same as new password');
                $('#confirmpassword').val("");
                $('#confirmpassword').focus();
            }
        }
        
    }
</script>