<?php
$tokenArray = [];
foreach ($tokenResults as $token) {
	$tokenArray[] = $token['token'];
}

$userCountryMapArray = array();
foreach ($userLocationMapResult as $ulMap) {
	if ($ulMap['mapping_type'] == 'country') {
		$userCountryMapArray[] = $ulMap['location_id'];
	}
}

$userProvinceMapArray = array();
foreach ($userLocationMapResult as $ulMap) {
	if ($ulMap['mapping_type'] == 'province') {
		$userProvinceMapArray[] = $ulMap['location_id'];
	}
}
//print_r($userProvinceMapArray);die;

$userDistrictMapArray = array();
foreach ($userLocationMapResult as $ulMap) {
	if ($ulMap['mapping_type'] == 'district') {
		$userDistrictMapArray[] = $ulMap['location_id'];
	}
}

$existMappingType = $userLocationMapResult[0]['mapping_type'];

$selectedTokenList = '';
if (isset($result->userToken) && count($result->userToken) > 0) {
	foreach ($result->userToken as $selectedToken) {
		$selectedTokenArray[] = $selectedToken['token'];
	}
	$selectedTokenList = implode(",", $selectedTokenArray);
}
?>
<link href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" type="text/css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/typeahead.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/tokenfield.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/jasny-bootstrap.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jasny-bootstrap.min.js'); ?>">
	type = "text/javascript" >
</script>
<div class="am-content">
	<div class="page-head">
		<h2><?= $this->translate('Edit User'); ?></h2>
		<span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> <?= $this->translate('indicates required field'); ?></span>
	</div>

	<div class="main-content">
		<div class="widget widget-fullwidth widget-small" style="padding:5px;">
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default">
						<div class="panel-body">
							<form role="form" name="editUserInformation" id="editUserInformation" enctype="multipart/form-data" method="post" action="<?php echo $this->url('users', array('action' => 'edit')); ?>" autocomplete="off">
								<div class="form-group col-lg-6">
									<label><?= $this->translate('First Name'); ?> <span class="mandatory">*</span> </label>
									<input type="text" placeholder="<?= $this->translate('First Name'); ?>" class="form-control isRequired" name="firstName" id="firstName" title="<?= $this->translate('Please enter the first name'); ?>" value="<?php echo $result->first_name; ?>">
									<input type="hidden" class="form-control isRequired" id="userId" name="userId" value="<?php echo base64_encode($result->id); ?>" />
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Last Name'); ?> </label>
									<input type="text" placeholder="<?= $this->translate('Last Name'); ?>" class="form-control" name="lastName" id="lastName" title="<?= $this->translate('Please enter the last name'); ?>" value="<?php echo $result->last_name; ?>">
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Login Id'); ?> <span class="mandatory">*</span></label>
									<input type="text" placeholder="<?= $this->translate('Login Id'); ?>" class="form-control" name="userName" id="userName" title="<?= $this->translate('Please enter the user name'); ?>" onblur="checkNameValidation('users','login', this,'<?php echo "id##" . $result->id; ?>', 'This name already exists. Please choose another name.')" value="<?php echo $result->login; ?>">
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Password'); ?> <span class="mandatory">*</span></label>
									<input type="password" placeholder="<?= $this->translate('Password'); ?>" class="form-control" name="password" id="password" title="<?= $this->translate('Please enter the password'); ?>">
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Confirm Password'); ?> <span class="mandatory">*</span></label>
									<input type="password" placeholder="<?= $this->translate('Confirm Password'); ?>" class="form-control confirmPassword" name="password" id="confirmPassword" title="<?= $this->translate('Please check your password and confirm password are same'); ?>">
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Mobile Number'); ?></label>
									<input type="tel" placeholder="<?= $this->translate('Mobile Number'); ?>" maxlength="10" onkeypress="return isNumberKey(event);" class="form-control" name="mobile_no" id="mobile_no" title="<?= $this->translate('Please enter the mobile number'); ?>" onblur="checkNameValidation('users','contact_no', this,'<?php echo "id##" . $result->id; ?>','Entered mobile number is already exist.')" value="<?php echo $result->contact_no; ?>">
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Email'); ?></label>
									<input type="text" placeholder="<?= $this->translate('Email'); ?>" class="form-control isEmail" name="email" id="email" title="<?= $this->translate('Please enter the email id'); ?>" onblur="checkNameValidation('users','email', this,'<?php echo "id##" . $result->id; ?>','Entered mail id is already exist.')" value="<?php echo $result->email; ?>">
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Role'); ?> <span class="mandatory">*</span></label>
									<select class="form-control isRequired" name="roleId" id="roleId" title="<?= $this->translate('Please select the role'); ?>">
										<option value="">--<?= $this->translate('Select'); ?>--</option>
										<?php
										foreach ($roleResults as $role) {
										?>
											<option value="<?php echo $role['role_id']; ?>" <?php if ($result->role_id == $role['role_id']) {
																								echo 'selected=selected';
																							} ?>><?php echo ucwords($role['role_name']); ?></option>
										<?php
										}
										?>
									</select>
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Token (Note: You can add multiple token by comma separator values)'); ?></label>
									<input type="text" placeholder="<?= $this->translate('Enter token'); ?>" class="form-control" name="token" id="token" title="><?= $this->translate('Please enter token'); ?>" value="<?php echo $selectedTokenList; ?>">
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Status'); ?> <span class="mandatory">*</span></label>
									<select class="form-control isRequired" name="status" id="status" title="><?= $this->translate('Please select the status'); ?>">
										<option value="active" <?php if ($result->status == 'active') {
																	echo 'selected=selected';
																} ?>><?= $this->translate('Active'); ?></option>
										<option value="inactive" <?php if ($result->status == 'inactive') {
																		echo 'selected=selected';
																	} ?>><?= $this->translate('Inactive'); ?></option>
									</select>
								</div>

								<div class="form-group col-lg-6">
									<label><?= $this->translate('Mapping Type'); ?></label>
									<select class="form-control" name="mappingType" id="mappingType" title="><?= $this->translate('Please select the mappingType'); ?>" onchange="getLocations()">
										<option value="">--<?= $this->translate('Select'); ?>--</option>	
										<option value="country" <?php echo $existMappingType == 'country' ? "selected=selected" : ""; ?>><?= $this->translate('Country'); ?></option>
										<option value="province" <?php echo $existMappingType == 'province' ? "selected=selected" : ""; ?>><?= $this->translate('Province'); ?></option>
										<option value="district" <?php echo $existMappingType == 'district' ? "selected=selected" : ""; ?>><?= $this->translate('District'); ?></option>
									</select>
								</div>
								<div class="form-group col-lg-6 country" style="display:none">
									<label><?= $this->translate('Countries'); ?></label>
									<div class="form-control">
										<select multiple="multiple" name="country[]" id="country" title="<?= $this->translate('Please select the country'); ?>">
										<?php foreach($countries as $row){ ?>
											<option value="<?php echo $row['country_id'];?>" <?php echo (in_array($row['country_id'], $userCountryMapArray))?"selected='selected'":"";?>><?php echo ucwords($row['country_name']);?></option>
											<?php } ?>
										</select>
									</div>
								</div>
								<div class="form-group col-lg-6 province" style="display:none">
									<label><?= $this->translate('Provinces'); ?></label>
									<div class="form-control">
										<select multiple="multiple" name="province[]" id="province" title="<?= $this->translate('Please select the province'); ?>">
											<?php foreach($provinces as $row){ ?>
												<option value="<?php echo $row['geo_id'];?>" <?php echo (in_array($row['geo_id'], $userProvinceMapArray))?"selected='selected'":"";?>><?php echo ucwords($row['geo_name']);?></option>
											<?php } ?>
										</select>
									</div>
								</div>
								<div class="form-group col-lg-6 district" style="display:none">
									<label><?= $this->translate('Districts'); ?></label>
									<div class="form-control">
										<select multiple="multiple" name="district[]" id="district" title="<?= $this->translate('Please select the district'); ?>">
											<?php foreach($districts as $row){ ?>
												<option value="<?php echo $row['geo_id'];?>" <?php echo (in_array($row['geo_id'], $userDistrictMapArray))?"selected='selected'":"";?>><?php echo ucwords($row['geo_name']);?></option>
											<?php } ?>
										</select>
									</div>
								</div>

								<div class="form-group col-lg-6" style="margin-right:50%;">
									<label><?= $this->translate('User Image'); ?></label>
									<div class="input-group col-sm-6" style="padding-left: 14px;width:66%;">
										<div class="controls">
											<div class="fileinput fileinput-new fileinputCat" data-provides="fileinput" id="fileinputDiv">
												<div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
													<?php
													if (isset($result->user_image) && $result->user_image != '') {
													?>
														<img src="<?php echo $result->user_image; ?>" />
													<?php } else {
													?>
														<img src="http://www.placehold.it/200x150/3c8dbc/fff&text= Image" />
													<?php
													}
													?>
												</div>
												<div>
													<span class="btn btn-default btn-file"><span class="fileinput-new"><?= $this->translate('Select image'); ?></span><span class="fileinput-exists"><?= $this->translate('Change'); ?></span>
														<input type="file" class="" name="user_image" id="user_image" title="<?= $this->translate('Please choose Testimonial image'); ?>" onclick="getImage()"></span>
													<?php
													if (isset($result->user_image) && $result->user_image != '') {
													?>
														<a href="javascript:void(0);" class="btn btn-default" data-dismiss="fileupload" id="oldImage" onclick="clearImage()"><?= $this->translate('Clear'); ?></a>
													<?php
													}
													?>
													<a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput"><?= $this->translate('Remove'); ?></a>
												</div>
												<?php if (isset($result->user_image) && $result->user_image != '') { ?>
													<input type="hidden" name="existImage" id="existImage" value="<?php echo $result->user_image; ?>" /><?php
																																					}
																																						?>
												<input type="hidden" name="removedImage" id="removedImage" value="<?php
																													if (isset($result->user_image) && $result->user_image != '') {
																														echo $result->user_image;
																													}
																													?>" />
											</div>
										</div>
									</div>
								</div>
								<div class="spacer  col-lg-12">
									<button type="button" onclick="validateNow()" class="btn btn-space btn-primary"><?= $this->translate('Submit'); ?></button>
									<a href="<?php echo $this->url('users', array('action' => 'index')); ?>" class="btn btn-space btn-default"><?= $this->translate('Cancel'); ?></a>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		<br>
		<br>

	</div>
</div>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
	$(document).ready(function() {

		$("#country").multipleSelect({
			placeholder: '<?= $this->translate('Please select country.'); ?>',
			width: '100%',
			minimumCountSelected: '2'
		});

		$("#province").multipleSelect({
			placeholder: '<?= $this->translate('Please select province.'); ?>',
			width: '100%',
			minimumCountSelected: '2'
		});

		$("#district").multipleSelect({
			placeholder: '<?= $this->translate('Please select district.'); ?>',
			width: '100%',
			minimumCountSelected: '2'
		});

		$('#token').tokenfield({
			autocomplete: {
				source: <?php echo json_encode($tokenArray); ?>,
				delay: 100
			},
			showAutocompleteOnFocus: false
		})

		$('#token').on('tokenfield:createtoken', function(event) {
			var existingTokens = $(this).tokenfield('getTokens');
			$.each(existingTokens, function(index, token) {
				if (token.value === event.attrs.value)
					event.preventDefault();
			});
		});

		getLocations();
	});

	function isNumberKey(evt) {
		var charCode = (evt.which) ? evt.which : evt.keyCode
		if (charCode > 31 && (charCode < 48 || charCode > 57))
			return false;
		return true;
	}

	function clearImage() {
		$('.fileinputCat').fileinput('clear');
		$("#oldImage").addClass("hide");
		document.getElementById('existImage').value = '';
	}

	function getImage() {
		$("#oldImage").addClass("hide");
		document.getElementById('existImage').value = '';
	}
	duplicateName = true;

	function validateNow() {
		flag = deforayValidator.init({
			formId: 'editUserInformation'
		});
		if (flag) {
			if (duplicateName) {
				document.getElementById('editUserInformation').submit();
			}
		}
	}

	function checkNameValidation(tableName, fieldName, obj, fnct, msg) {
		checkValue = document.getElementById(obj.id).value;
		$.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {
				tableName: tableName,
				fieldName: fieldName,
				value: checkValue,
				fnct: fnct
			},
			function(data) {
				if (data > 0) {
					alert(msg);
					duplicateName = false;
					document.getElementById(obj.id).value = "";
				} else {
					duplicateName = true;
				}
			});
	}

	function getLocations() {
		var mappingType = $("#mappingType").val();
		var types = ['country', 'province', 'district'];
		
		types.forEach(function(type) {
			if (mappingType === type) {
				$("." + type).show();
			} else {
				$("." + type).hide();
				$("." + type + " select").val([]).multipleSelect("refresh");
			}
		});
	}
</script>