<?php
$tokenArray = array();
foreach ($tokenResults as $token) {
	$tokenArray[] = $token['token'];
}

$userCountryMapArray = array();
foreach ($userCountryMapResult as $ucMap) {
	$userCountryMapArray[] = $ucMap['country_id'];
}

$selectedTokenList = '';
if (isset($result->userToken) && count($result->userToken) > 0) {
	foreach ($result->userToken as $selectedToken) {
		$selectedTokenArray[] = $selectedToken['token'];
	}
	$selectedTokenList = implode(",", $selectedTokenArray);
}
?>
<link href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" type="text/css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/typeahead.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/tokenfield.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/jasny-bootstrap.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jasny-bootstrap.min.js'); ?>">
	type = "text/javascript" >
</script>
<div class="am-content">
	<div class="page-head">
		<h2>Edit User</h2>
		<span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>
	</div>

	<div class="main-content">
		<div class="widget widget-fullwidth widget-small" style="padding:5px;">
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default">
						<div class="panel-body">
							<form role="form" name="editUserInformation" id="editUserInformation" enctype="multipart/form-data" method="post" action="<?php echo $this->url('users', array('action' => 'edit')); ?>" autocomplete="off">
								<div class="form-group col-lg-6">
									<label>First Name <span class="mandatory">*</span> </label>
									<input type="text" placeholder="First Name" class="form-control isRequired" name="firstName" id="firstName" title="Please enter the first name" value="<?php echo $result->first_name; ?>">
									<input type="hidden" class="form-control isRequired" id="userId" name="userId" value="<?php echo base64_encode($result->id); ?>" />
								</div>
								<div class="form-group col-lg-6">
									<label>Last Name </label>
									<input type="text" placeholder="Last Name" class="form-control" name="lastName" id="lastName" title="Please enter the last name" value="<?php echo $result->last_name; ?>">
								</div>
								<div class="form-group col-lg-6">
									<label>Login Id <span class="mandatory">*</span></label>
									<input type="text" placeholder="Login Id" class="form-control" name="userName" id="userName" title="Please enter the user name" onblur="checkNameValidation('users','login', this,'<?php echo "id##" . $result->id; ?>', 'This name already exists. Please choose another name.')" value="<?php echo $result->login; ?>">
								</div>
								<div class="form-group col-lg-6">
									<label>Password <span class="mandatory">*</span></label>
									<input type="password" placeholder="Password" class="form-control" name="password" id="password" title="Please enter the password">
								</div>
								<div class="form-group col-lg-6">
									<label>Confirm Password <span class="mandatory">*</span></label>
									<input type="password" placeholder="Confirm Password" class="form-control confirmPassword" name="password" id="confirmPassword" title="Please check your password and confirm password are same">
								</div>
								<div class="form-group col-lg-6">
									<label>Mobile Number</label>
									<input type="tel" placeholder="Enter Mobile Number" maxlength="10" onkeypress="return isNumberKey(event);" class="form-control" name="mobile_no" id="mobile_no" title="Please enter the mobile number" onblur="checkNameValidation('users','contact_no', this,'<?php echo "id##" . $result->id; ?>','Entered mobile number is already exist.')" value="<?php echo $result->contact_no; ?>">
								</div>
								<div class="form-group col-lg-6">
									<label>Email</label>
									<input type="text" placeholder="Email" class="form-control isEmail" name="email" id="email" title="Please enter the email id" onblur="checkNameValidation('users','email', this,'<?php echo "id##" . $result->id; ?>','Entered mail id is already exist.')" value="<?php echo $result->email; ?>">
								</div>
								<div class="form-group col-lg-6">
									<label>Role <span class="mandatory">*</span></label>
									<select class="form-control isRequired" name="roleId" id="roleId" title="Please select the role">
										<option value="">--Select--</option>
										<?php
										foreach ($roleResults as $role) {
										?>
											<option value="<?php echo $role['role_id']; ?>" <?php if ($result->role_id == $role['role_id']) {
																								echo 'selected=selected';
																							} ?>><?php echo ucwords($role['role_name']); ?></option>
										<?php
										}
										?>
									</select>
								</div>
								<div class="form-group col-lg-6">
									<label>Token (Note: You can add multiple token by comma separator values)</label>
									<input type="text" placeholder="Enter token" class="form-control" name="token" id="token" title="Please enter token" value="<?php echo $selectedTokenList; ?>">
								</div>
								<div class="form-group col-lg-6">
									<label>Status <span class="mandatory">*</span></label>
									<select class="form-control isRequired" name="status" id="status" title="Please select the status">
										<option value="active" <?php if ($result->status == 'active') {
																	echo 'selected=selected';
																} ?>>Active</option>
										<option value="inactive" <?php if ($result->status == 'inactive') {
																		echo 'selected=selected';
																	} ?>>Inactive</option>
									</select>
								</div>
								<div class="form-group col-lg-6">
									<label>Countries </label>
									<select class="form-control select2" multiple="multiple" name="country[]" id="country" title="Please select the country">
										<?php foreach($countries as $row){ ?>
											<option value="<?php echo $row['country_id'];?>" <?php echo (in_array($row['country_id'], $userCountryMapArray))?"selected='selected'":"";?>><?php echo ucwords($row['country_name']);?></option>
										<?php } ?>
									</select>
								</div>
								<div class="form-group col-lg-6" style="margin-right:50%;">
									<label>User Image</label>
									<div class="input-group col-sm-6" style="padding-left: 14px;width:66%;">
										<div class="controls">
											<div class="fileinput fileinput-new fileinputCat" data-provides="fileinput" id="fileinputDiv">
												<div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
													<?php
													if (isset($result->user_image) && $result->user_image != '') {
													?>
														<img src="<?php echo $result->user_image; ?>" />
													<?php } else {
													?>
														<img src="http://www.placehold.it/200x150/3c8dbc/fff&text= Image" />
													<?php
													}
													?>
												</div>
												<div>
													<span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span>
														<input type="file" class="" name="user_image" id="user_image" title="Please choose Testimonial image" onclick="getImage()"></span>
													<?php
													if (isset($result->user_image) && $result->user_image != '') {
													?>
														<a href="javascript:void(0);" class="btn btn-default" data-dismiss="fileupload" id="oldImage" onclick="clearImage()">Clear</a>
													<?php
													}
													?>
													<a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
												</div>
												<?php if (isset($result->user_image) && $result->user_image != '') { ?>
													<input type="hidden" name="existImage" id="existImage" value="<?php echo $result->user_image; ?>" /><?php
																																					}
																																						?>
												<input type="hidden" name="removedImage" id="removedImage" value="<?php
																													if (isset($result->user_image) && $result->user_image != '') {
																														echo $result->user_image;
																													}
																													?>" />
											</div>
										</div>
									</div>
								</div>
								<div class="spacer  col-lg-12">
									<button type="button" onclick="validateNow()" class="btn btn-space btn-primary">Submit</button>
									<a href="<?php echo $this->url('users', array('action' => 'index')); ?>" class="btn btn-space btn-default">Cancel</a>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		<br>
		<br>

	</div>
</div>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
	$(document).ready(function() {

		$("#country").multipleSelect({
			placeholder: '<?= $this->translate('Please select country.'); ?>',
			width: '100%',
			minimumCountSelected: '2'
		});

		$('#token').tokenfield({
			autocomplete: {
				source: <?php echo json_encode($tokenArray); ?>,
				delay: 100
			},
			showAutocompleteOnFocus: false
		})

		$('#token').on('tokenfield:createtoken', function(event) {
			var existingTokens = $(this).tokenfield('getTokens');
			$.each(existingTokens, function(index, token) {
				if (token.value === event.attrs.value)
					event.preventDefault();
			});
		});
	});

	function isNumberKey(evt) {
		var charCode = (evt.which) ? evt.which : evt.keyCode
		if (charCode > 31 && (charCode < 48 || charCode > 57))
			return false;
		return true;
	}

	function clearImage() {
		$('.fileinputCat').fileinput('clear');
		$("#oldImage").addClass("hide");
		document.getElementById('existImage').value = '';
	}

	function getImage() {
		$("#oldImage").addClass("hide");
		document.getElementById('existImage').value = '';
	}
	duplicateName = true;

	function validateNow() {
		flag = deforayValidator.init({
			formId: 'editUserInformation'
		});
		if (flag) {
			if (duplicateName) {
				document.getElementById('editUserInformation').submit();
			}
		}
	}

	function checkNameValidation(tableName, fieldName, obj, fnct, msg) {
		checkValue = document.getElementById(obj.id).value;
		$.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {
				tableName: tableName,
				fieldName: fieldName,
				value: checkValue,
				fnct: fnct
			},
			function(data) {
				if (data > 0) {
					alert(msg);
					duplicateName = false;
					document.getElementById(obj.id).value = "";
				} else {
					duplicateName = true;
				}
			});
	}
</script>