<link href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" type="text/css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/typeahead.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/tokenfield.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/jasny-bootstrap.min.css'); ?>"/>
<script src="<?php echo $this->basePath('assets/js/jasny-bootstrap.min.js'); ?>" type="text/javascript"></script>
<div class="am-content">
    <div class="page-head">
        <h2><?= $this->translate('User Profile'); ?></h2>
        <span class="muted pull-right" style="font-size:15px;">
            <span class="mandatory">*</span> <?= $this->translate('indicates required field'); ?>
        </span>
    </div>
    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <form role="form" name="editUserInformation" id="editUserInformation" enctype="multipart/form-data" method="post" 
                                action="<?php echo $this->url('users', array('action' => 'profile')); ?>" autocomplete="off">
                                <div class="form-group col-lg-6">
                                    <label><?= $this->translate('First Name'); ?> <span class="mandatory">*</span></label>
                                    <input type="text" placeholder="<?= $this->translate('First Name'); ?>" class="form-control isRequired" 
                                        name="firstName" id="firstName" 
                                        title="<?= $this->translate('Please enter the first name'); ?>" value="<?php echo $result->first_name; ?>">
                                    <input type="hidden" class="form-control isRequired" id="userId" name="userId" 
                                        value="<?php echo base64_encode($result->id); ?>"/>
                                </div>
                                <div class="form-group col-lg-6">
                                    <label><?= $this->translate('Last Name'); ?></label>
                                    <input type="text" placeholder="<?= $this->translate('Last Name'); ?>" class="form-control" 
                                        name="lastName" id="lastName" 
                                        title="<?= $this->translate('Please enter the last name'); ?>" value="<?php echo $result->last_name; ?>">
                                </div>
                                <div class="form-group col-lg-6">
                                    <label><?= $this->translate('Mobile Number'); ?></label>
                                    <input type="tel" placeholder="<?= $this->translate('Enter Mobile Number'); ?>" maxlength="10" 
                                        onkeypress="return isNumberKey(event);" class="form-control" name="mobile_no" id="mobile_no" 
                                        title="<?= $this->translate('Please enter the mobile number'); ?>" 
                                        onblur="checkNameValidation('users', 'contact_no', this, '<?php echo 'id##' . $result->id; ?>', '<?= $this->translate('Entered mobile number is already exist.'); ?>')" 
                                        value="<?php echo $result->contact_no; ?>">
                                </div>
                                <div class="form-group col-lg-6">
                                    <label><?= $this->translate('Email'); ?></label>
                                    <input type="text" placeholder="<?= $this->translate('Email'); ?>" class="form-control isEmail" name="email" id="email" 
                                        title="<?= $this->translate('Please enter the email id'); ?>" 
                                        onblur="checkNameValidation('users', 'email', this, '<?php echo 'id##' . $result->id; ?>', '<?= $this->translate('Entered mail id is already exist.'); ?>')" 
                                        value="<?php echo $result->email; ?>">
                                </div>
                                <div class="form-group col-lg-6" style="margin-right:50%;">
                                    <label><?= $this->translate('User Image'); ?></label>
                                    <div class="input-group col-sm-6" style="padding-left: 14px;width:66%;">
                                        <div class="controls">
                                            <div class="fileinput fileinput-new fileinputCat" data-provides="fileinput" id="fileinputDiv">
                                                <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
                                                    <?php if (isset($result->user_image) && $result->user_image != '') { ?>
                                                        <img src="<?php echo $result->user_image; ?>"/>
                                                    <?php } else { ?>
                                                        <img src="http://www.placehold.it/200x150/3c8dbc/fff&text=<?= $this->translate('Image'); ?>"/>
                                                    <?php } ?>
                                                </div>
                                                <div>
                                                    <span class="btn btn-default btn-file">
                                                        <span class="fileinput-new"><?= $this->translate('Select image'); ?></span>
                                                        <span class="fileinput-exists"><?= $this->translate('Change'); ?></span>
                                                        <input type="file" class="" name="user_image" id="user_image" 
                                                            title="<?= $this->translate('Please choose Testimonial image'); ?>" onclick="getImage()">
                                                    </span>
                                                    <?php if (isset($result->user_image) && $result->user_image != '') { ?>
                                                        <a href="javascript:void(0);" class="btn btn-default" data-dismiss="fileupload" 
                                                            id="oldImage" onclick="clearImage()"><?= $this->translate('Clear'); ?></a>
                                                    <?php } ?>
                                                    <a href="#" class="btn btn-default fileinput-exists" 
                                                        data-dismiss="fileinput"><?= $this->translate('Remove'); ?></a>
                                                </div>
                                                <?php if (isset($result->user_image) && $result->user_image != '') { ?>
                                                    <input type="hidden" name="existImage" id="existImage" value="<?php echo $result->user_image; ?>"/>
                                                <?php } ?>
                                                <input type="hidden" name="removedImage" id="removedImage" value="<?php echo $result->user_image ?? ''; ?>"/>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="spacer col-lg-12">
                                    <button type="button" onclick="validateNow()" class="btn btn-space btn-primary"><?= $this->translate('Submit'); ?></button>
                                    <a href="<?php echo $this->url('dashboard', array('action' => 'index')); ?>" 
                                        class="btn btn-space btn-default"><?= $this->translate('Cancel'); ?></a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function isNumberKey(evt) {
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
            return false;
        }
        return true;
    }

    function clearImage() {
        $('.fileinputCat').fileinput('clear');
        $("#oldImage").addClass("hide");
        document.getElementById('existImage').value = '';
    }

    function getImage() {
        $("#oldImage").addClass("hide");
        document.getElementById('existImage').value = '';
    }

    var duplicateName = true;
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'editUserInformation'
        });
        if (flag) {
            if (duplicateName) {
                document.getElementById('editUserInformation').submit();
            }
        }
    }

    function checkNameValidation(tableName, fieldName, obj, fnct, msg) {
        var checkValue = document.getElementById(obj.id).value;
        $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
        function(data) {
            if (data > 0) {
                alert(msg);
                duplicateName = false;
                document.getElementById(obj.id).value = "";
            } else {
                duplicateName = true;
            }
        });
    }
</script>