<style>
	.privilege-switch {
		display: flex;
		overflow: hidden;
	}

	.privilege-switch input {
		position: absolute !important;
		clip: rect(0, 0, 0, 0);
		height: 1px;
		width: 1px;
		border: 0;
		overflow: hidden;
	}

	.privilege-switch label {
		background-color: #e4e4e4;
		color: rgba(0, 0, 0, 0.6);
		font-size: 14px;
		line-height: 1;
		text-align: center;
		padding: 8px 16px;
		margin-right: -1px;
		border: 1px solid rgba(0, 0, 0, 0.2);
		box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.3), 0 1px rgba(255, 255, 255, 0.1);
		transition: all 0.1s ease-in-out;
	}

	.privilege-switch label:hover {
		cursor: pointer;
	}

	.privilege-switch input:checked+label {
		box-shadow: none;
	}

	.privilege-switch label:first-of-type {
		border-radius: 4px 0 0 4px;
	}

	.privilege-switch label:last-of-type {
		border-radius: 0 4px 4px 0;
	}

	.deny-label {
		background-color: #d9534f !important;
		color: white !important;
	}

	.allow-label {
		background-color: #398439 !important;
		color: white !important;
	}

	.normal-label {
		background-color: #e4e4e4 !important;
		color: black !important;
	}

	h2 {
		font-size: 18px;
		margin-bottom: 8px;
	}

	.privilege-div {
		margin-top: 5px;
		border: 1px solid #eee;
		padding: 10px;
	}
</style>
<?php
// echo "<pre>"; print_r($resourceResult); die;
?>
<div class="am-content">
	<div class="page-head">
		<h2><?= $this->translate('Edit Role'); ?></h2>
		<span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span><?= $this->translate(' indicates required field'); ?></span>
	</div>


	<div class="main-content">
		<div class="widget widget-fullwidth widget-small" style="padding:5px;">
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default">
						<div class="panel-body">
							<form role="form" name="addRoleInformation" id="addRoleInformation" method="post" action="<?php echo $this->url('roles', array('action' => 'edit')); ?>" autocomplete="off">
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Role Name'); ?> <span class="mandatory">*</span> </label>
									<input type="text" placeholder="<?= $this->translate('Role Name'); ?>" class="form-control isRequired" name="roleName" id="roleName" title="<?= $this->translate('Please enter the role name'); ?>" onblur="checkNameValidation('roles','role_name',this,'<?php echo "role_id##" . $result->role_id; ?>', 'This name already exists. Please choose another name.')" value="<?php echo $result->role_name; ?>">
									<input type="hidden" class="form-control isRequired" id="roleId" name="roleId" value="<?php echo base64_encode($result->role_id); ?>" />
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Role Code'); ?> <span class="mandatory">*</span></label>
									<input type="text" placeholder="<?= $this->translate('Role Code'); ?>" class="form-control isRequired" name="roleCode" id="roleCode" title="<?= $this->translate('Please enter role code'); ?>" onblur="checkNameValidation('roles', 'role_code', this,'<?php echo "role_id##" . $result->role_id; ?>', 'Already exist this code . Please choose another code.')" value="<?php echo $result->role_code; ?>">
								</div>
								<div class="form-group col-lg-6">
									<label><?= $this->translate('Description'); ?></label>
									<textarea class="form-control" placeholder="Description'); ?>" name="description" id="description"><?php echo $result->description; ?></textarea>
								</div>
								<div class="form-group col-lg-6">
									<label>Status <span class="mandatory">*</span></label>
									<select class="form-control isRequired" name="status" id="status">
										<option value="active" <?php if ($result->status == 'active') {
																	echo 'selected=selected';
																} ?>><?= $this->translate('Active'); ?></option>
										<option value="inactive" <?php if ($result->status == 'inactive') {
																		echo 'selected=selected';
																	} ?>><?= $this->translate('Inactive'); ?></option>
									</select>
								</div>
								<div class="form-group col-sm-12">
									<div class="form-group">
										<label class="col-sm-1 control-label"><?= $this->translate('Note :'); ?></label>
										<div class="col-sm-10">
											<p class=""><?= $this->translate('Unless you choose "access" the people belonging to this role will not be able to access other rights like "add", "edit" etc.'); ?></p>
										</div>
									</div>
									<div class="form-group col-sm-12" style="padding-left:14px;">
										<div class="privilege-switch super-switch">
											<input type="radio" class='' id="allowAllPrivileges" name="allPrivilegesRadio" value="yes" /></a>
											<label for="allowAllPrivileges"><?= $this->translate('Select All'); ?></label>
											<input type="radio" class='' name="allPrivilegesRadio" id="denyAllPrivileges" name="switch-one" value="no" checked/></a>
											<label for="denyAllPrivileges"><?= $this->translate('Unselect All'); ?></label>
										</div>
									</div>
									<table aria-describedby="table" class="table table-striped responsive-utilities">
										<tbody>
										<?php
										foreach ($rolesresult as $value) { ?>
											<tr class="togglerTr">
												<th style="background-color:#eee;">
													<div class="card-header">
														<h4 class="card-title" style="font-weight: bold;"><?php echo ucwords($value['display_name'])  ?></h4>
														<div class="card-actions">
															<div class="super-switch privilege-switch pull-right">
																<?php 
																	 $displayName = str_replace(' ', '', $value['display_name']);
																	 echo '<input type="radio" class="" id="all' . $displayName . '" 
																			name="' . $displayName . '" 
																			onclick="togglePrivilegesForThisResource(\'' . $displayName . '\', true);">
																		   <label for="all' . $displayName . '">' . $this->translate('All') . '</label>';
																 
																	 echo '<input type="radio" class="" id="none' . $displayName . '" 
																			name="' . $displayName . '" 
																			onclick="togglePrivilegesForThisResource(\'' . $displayName . '\', false);">
																		   <label for="none' . $displayName . '">' . $this->translate('None') . '</label>';
																?>
															</div>
														</div>
													</div>
												</th>
											</tr>
											<tr>
												<td style="text-align:center;vertical-align:middle;" class="privilegesNode" id="<?php echo $displayName; ?>">
													<div class="row ">
													<?php foreach ($value['privileges'] as $privilege) { 
														$isPrivilegeMatched = false;

														// Check if resourceResult is not empty
														if (!empty($resourceResult)) {
															// Loop through resourceResult to check for matching privilege_id
															foreach ($resourceResult as $result) {
																if (isset($result['privilege_id']) && $result['privilege_id'] == $privilege['privilege_id']) {
																	$isPrivilegeMatched = true;
																	break; // Exit loop as we found a match
																}
															}
														}
														if ($isPrivilegeMatched) {
															$allowActive = ' active ';
															$allowChecked = "checked";
															$denyActive = "";
															$denyChecked = "";
															$allowStyle = "allow-label";
															$denyStyle = "";
														} else {
															$denyActive = ' active ';
															$denyChecked = " checked='' ";
															$allowActive = "";
															$allowChecked = "";
															$denyStyle = "deny-label";
															$allowStyle = "";
														}
														?>
														
														<div class="col-md-3 privilege-div">
															<strong class="privilege-label"><?php echo ucwords($privilege['display_name'])  ?></strong>
															<br>
															<div class="privilege-switch" style="margin: 30px 0 36px 90px;">
																<?php
																	echo '<input type="radio" class="selectPrivilege" name="resource[' . $value['resource_id'] . '][' . $privilege['privilege_name'] . ']" value="allow" id="selectPrivilege[' . $value['resource_id'] . '][' . $privilege['privilege_name'] . ']" '.$allowChecked .'>';
																	echo '<label for="selectPrivilege[' . $value['resource_id'] . '][' . $privilege['privilege_name'] . ']" class="' .$allowStyle. '">' . $this->translate('Yes') . '</label>';
																	
																	echo '<input type="radio" class="unselectPrivilege" name="resource[' . $value['resource_id'] . '][' . $privilege['privilege_name'] . ']" value="deny" id="unselectPrivilege[' . $value['resource_id'] . '][' . $privilege['privilege_name'] . ']" '.$denyChecked.'>';
																	echo '<label for="unselectPrivilege[' . $value['resource_id'] . '][' . $privilege['privilege_name'] . ']" class="' .$denyStyle. '">' . $this->translate('No') . '</label>';
																?>
															</div>
														</div>
													<?php } ?>
													</div>
												</td>
											</tr>
											<?php } ?>
										</tbody>
									</table>
								</div>
								<div class="spacer  col-lg-12">
									<button type="button" onclick="validateNow()" class="btn btn-space btn-primary"><?= $this->translate('Submit'); ?></button>
									<a href="<?php echo $this->url('roles', array('action' => 'index')); ?>" class="btn btn-space btn-default"><?= $this->translate('Cancel'); ?></a>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

		</div>

		<br>
		<br>

	</div>
</div>

<script type="text/javascript">
	duplicateName = true;

	function validateNow() {
		flag = deforayValidator.init({
			formId: 'addRoleInformation'
		});
		if (flag) {
			if (duplicateName) {
				document.getElementById('addRoleInformation').submit();
			}
		}
	}

	function checkNameValidation(tableName, fieldName, obj, fnct, msg) {
		checkValue = document.getElementById(obj.id).value;
		$.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {
				tableName: tableName,
				fieldName: fieldName,
				value: checkValue,
				fnct: fnct
			},
			function(data) {
				if (data > 0) {
					alert(msg);
					duplicateName = false;
					document.getElementById(obj.id).value = "";
				} else {
					duplicateName = true;
				}
			});
	}
    $("#allowAllPrivileges").click(function() {
		$('.unselectPrivilege').prop('checked', false);
		$('.selectPrivilege').prop('checked', true);
		$('.unselectPrivilege').next('label').addClass('normal-label');
		$('.selectPrivilege').next('label').addClass('allow-label');
		$(this).next('label').addClass('allow-label');
		$("#denyAllPrivileges").next('label').addClass('normal-label');

		$('.unselectPrivilege').next('label').removeClass('deny-label');
		$('.selectPrivilege').next('label').removeClass('normal-label');
		$(this).next('label').removeClass('deny-label');
		$("#allowAllPrivileges").next('label').removeClass('normal-label');
	});

	$("#denyAllPrivileges").click(function() {
		$('.selectPrivilege').prop('checked', false);
		$('.unselectPrivilege').prop('checked', true);
		$('.unselectPrivilege').next('label').addClass('deny-label');
		$('.selectPrivilege').next('label').addClass('normal-label');
		$(this).next('label').addClass('deny-label');
		$("#allowAllPrivileges").next('label').addClass('normal-label');

		$('.unselectPrivilege').next('label').removeClass('normal-label');
		$('.selectPrivilege').next('label').removeClass('allow-label');
		$(this).next('label').removeClass('allow-label');
		$("#denyAllPrivileges").next('label').removeClass('normal-label');

	});

    $('.privilege-switch input').click(function() {
		val = $(this).val();
		if (val == "deny") {
			$(this).closest('.privilege-switch').find('.unselectPrivilege').next('label').addClass('deny-label');
			$(this).closest('.privilege-switch').find('.selectPrivilege').next('label').addClass('normal-label');
			$(this).closest('.privilege-switch').find('.unselectPrivilege').next('label').removeClass('normal-label');
			$(this).closest('.privilege-switch').find('.selectPrivilege').next('label').removeClass('allow-label');
		} else if (val == "allow") {
			$(this).closest('.privilege-switch').find('.unselectPrivilege').next('label').addClass('normal-label');
			$(this).closest('.privilege-switch').find('.selectPrivilege').next('label').addClass('allow-label');
			$(this).closest('.privilege-switch').find('.unselectPrivilege').next('label').removeClass('deny-label');
			$(this).closest('.privilege-switch').find('.selectPrivilege').next('label').removeClass('normal-label');
		}
	});

    function togglePrivilegesForThisResource(obj, checked) {
		if (checked == true) {
			$("#" + obj).find('.selectPrivilege').prop('checked', true);
			$("#" + obj).find('.unselectPrivilege').prop('checked', false);
			$("#" + obj).find('.unselectPrivilege').next('label').addClass('normal-label');
			$("#" + obj).find('.selectPrivilege').next('label').addClass('allow-label');
			$("#all" + obj).next('label').addClass('allow-label');
			$("#none" + obj).next('label').addClass('normal-label');

			$("#" + obj).find('.unselectPrivilege').next('label').removeClass('deny-label');
			$("#" + obj).find('.selectPrivilege').next('label').removeClass('normal-label');
			$("#all" + obj).next('label').removeClass('normal-label');
			$("#none" + obj).next('label').removeClass('deny-label');

		} else if (checked == false) {
			$("#" + obj).find('.selectPrivilege').prop('checked', false);
			$("#" + obj).find('.unselectPrivilege').prop('checked', true);
			$("#" + obj).find('.unselectPrivilege').next('label').addClass('deny-label');
			$("#" + obj).find('.selectPrivilege').next('label').addClass('normal-label');
			$("#all" + obj).next('label').addClass('normal-label');
			$("#none" + obj).next('label').addClass('deny-label');

			$("#" + obj).find('.unselectPrivilege').next('label').removeClass('normal-label');
			$("#" + obj).find('.selectPrivilege').next('label').removeClass('allow-label');
			$("#all" + obj).next('label').removeClass('allow-label');
			$("#none" + obj).next('label').removeClass('normal-label');
		}
	}
</script>