<?php

use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css" />
<div class="am-content">
        <div class="page-head">
          <div class="row">
				<div class="col-sm-8">
				<h2>Event Log History List</h2>
				</div>
		  </div>
        </div>
        
        <div class="main-content">
             
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">

            <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default">
            <div class="panel-body">
              <form role="form" class="form-horizontal">
                <div class="form-group">
                  <label for="date" class="col-sm-2 control-label"><?= $this->translate('Date Range'); ?></label>
                  <div class=" col-lg-4">
                    <input type="text" placeholder="Select Date Range" class="form-control" id="date" readonly>
                  </div>
                  <label for="eventType" class="col-sm-2 control-label"><?= $this->translate('Event Type'); ?></label>
                  <div class=" col-lg-4">
                    <input type="text" placeholder="Select Event Type" class="form-control" name="eventType" id="eventType">
                  </div>
                </div>

                <div class="form-group">
                  <div class="testPointNameSection"></div>
                </div>
                <div class="form-group" style="text-align:center;">
                  <button type="button" onclick="search();" class="btn btn-space btn-primary"><?= $this->translate('Search'); ?></button>&nbsp;
                  <button type="button" onclick="document.location.href = document.location" class="btn btn-space btn-default"><?= $this->translate('Cancel'); ?></button>
                </div>
              </form>
            </div>
           
          </div>
        </div>
      </div>

          <table  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed" id="eventLogDataTable">
					<thead>
					<tr>
            <th>Event Type</th>
            <th>Action</th>
            <th>Resource Name</th>
            <th>Date Time</th>
					</tr>
					</thead>
					<tbody>
					<tr>
						 <td colspan="4" class="dataTables_empty"><?= $this->translate('Loading data from server'); ?></td>
					</tr>
					</tbody>
				</table>
            </div>
        <br>
            
            
        </div>
</div>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/datatables.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>

<script type="text/javascript">
    var oTable = null;
   
 $(document).ready(function() {
	
        oTable = $('#eventLogDataTable').DataTable({
            "bScrollCollapse": true,
            "bRetrieve": true,                        
            "aaSorting": [[ 0, "desc" ]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url('event-log',array('action' => 'index')); ?>",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
              aoData.push({
                "name": "dateRange",
                "value": $("#date").val()
              }),
              aoData.push({
                "name": "eventType",
                "value": $("#eventType").val()
              }),
              $.ajax({
                  "dataType": 'json',
                  "type": "POST",
                  "url": sSource,
                  "data": aoData,
                  "success": fnCallback
              });
            }
        });

        $('#date').daterangepicker({
              format: 'DD-MMM-YYYY',
              autoUpdateInput: false,
              separator: ' to ',
              startDate: moment().subtract('days', 29),
              endDate: moment(),
              maxDate: moment(),
              ranges: {
                  'Today': [moment(), moment()],
                  'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                  'Last 7 Days': [moment().subtract('days', 6), moment()],
                  'Last 30 Days': [moment().subtract('days', 29), moment()],
                  'Last 60 Days': [moment().subtract('days', 59), moment()],
                  'Last 180 Days': [moment().subtract('days', 179), moment()],
                  'This Month': [moment().startOf('month'), moment().endOf('month')],
                  'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
              }
          },
          function(start, end) {
              startDate = start.format('YYYY-MM-DD');
              endDate = end.format('YYYY-MM-DD');
              $('input[name="date"]').on('apply.daterangepicker', function(ev, picker) {
                  $(this).val(picker.startDate.format('DD-MMM-YYYY') + ' to ' + picker.endDate.format('DD-MMM-YYYY'));
              });

        });
       
	} );

    function search() {
    oTable.draw();
  }
</script>