<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<div class="am-content">
    <div class="page-head">
        <h2>Email</h2>
        <span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> indicates required field</span>
    </div>

    <d<div class="main-content">
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="panel panel-default">
                            <div class="panel-body" >

                                <?php
                                $form->setAttribute('action', $this->url('certification-mail', array('action' => 'sendmail')));
                                $form->prepare();
                                $form->get('from_full_name')->setAttributes([
                                    'class' => 'form-control',
//                                'placeholder' => 'Training Organization Name',
                                    'autocomplete' => 'off'
                                ]);

                                $form->get('from_mail')->setAttributes([
                                    'class' => 'form-control',
                                ]);
                                $form->get('to_email')->setAttributes([
                                    'class' => 'form-control',
                                ]);

                                $form->get('cc')->setAttributes([
                                    'class' => 'form-control',
                                ]);
                                $form->get('bcc')->setAttributes([
                                    'class' => 'form-control',
                                ]);
                                $form->get('subject')->setAttributes([
                                    'class' => 'form-control',
                                ]);
                                $form->get('message')->setAttributes([
                                    'class' => 'form-control',
                                    'rows'=>4,
                                ]);
                                $form->get('status')->setAttributes([
                                    'class' => 'form-control',
                                ]);


                                echo $this->form()->openTag($form);
                                ?>
                                <?php echo $this->formHidden($form->get('mail_id')->setAttribute('class', 'form-control')) ?>
                                <div class="form-group col-lg-6"> 
                                    <?= $this->formLabel($form->get('from_full_name')); ?>
                                    <?= $this->formElement($form->get('from_full_name')); ?>
                                    <?= $this->formElementErrors($form->get('from_full_name')); ?>
                                </div>

                                <div class="form-group col-lg-6"> 
                                    <?= $this->formLabel($form->get('from_mail')); ?>
                                    <?= $this->formElement($form->get('from_mail')); ?>
                                    <?= $this->formElementErrors($form->get('from_mail')); ?>
                                </div>
                               
                                <div class="form-group col-lg-6">
                                    
                                    <?= $this->formLabel($form->get('to_email')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('to_email')); ?>
                                    <?= $this->formElementErrors($form->get('to_email')); ?>
                                </div>

                                 <div class="form-group col-lg-6"> 
                                    <?= $this->formLabel($form->get('cc')); ?>
                                    <?= $this->formElement($form->get('cc')); ?>
                                    <?= $this->formElementErrors($form->get('cc')); ?>
                                </div>

                                 <div class="form-group col-lg-6"> 
                                    <?= $this->formLabel($form->get('bcc')); ?>
                                    <?= $this->formElement($form->get('bcc')); ?>
                                    <?= $this->formElementErrors($form->get('bcc')); ?>
                                </div>

                                 <div class="form-group col-lg-6"> 
                                    <?= $this->formLabel($form->get('subject')); ?>
                                    <?= $this->formElement($form->get('subject')); ?>
                                    <?= $this->formElementErrors($form->get('subject')); ?>
                                </div>

                                 <div class="form-group col-lg-6"> 
                                    <?= $this->formLabel($form->get('message')); ?><span class="mandatory">*</span>
                                    <?= $this->formElement($form->get('message')); ?>
                                    <?= $this->formElementErrors($form->get('message')); ?>
                                </div>

                                 <div class="form-group col-lg-6"> 
                                    <?= $this->formLabel($form->get('status')); ?>
                                    <?= $this->formElement($form->get('status')); ?>
                                    <?= $this->formElementErrors($form->get('status')); ?>
                                </div>

                                <div class="row" style="margin-left: 18px;"><?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                    <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('certification-mail', array('action' => 'index')); ?>" >CANCEL</a> </div>
                                    <?php echo $this->form()->closeTag();
                                    ?>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <br>
            <br>

        </div>
</div>
<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">

</script>