<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">
        <h2>Add Provider</h2>
    </div>


    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body" >

                            <?php
                            $form->setAttributes(array(
                                'action'=> $this->url('provider', array('action' => 'add')),
                                'id'=>'form',
                                
                                ));
                            $form->prepare();
                            
                            $form->get('provider_id')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Provider ID (if available)',
                                'autocomplete' => 'off',
                            ]);
                            $form->get('last_name')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Last name',
                                'autocomplete' => 'off',
                                'required'=>true,
                                'id'=>'last',
                            ]);

                            $form->get('first_name')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'First name',
                                'autocomplete' => 'off',
                                'required'=>true,
                                ]);
                            
                            $form->get('middle_name')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Middle name',
                                'autocomplete' => 'off',
                                ]);

                            $form->get('region')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Region',
                                'autocomplete' => 'off',]);
                            $form->get('district')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'District',
                                'autocomplete' => 'off',]);
                            $form->get('type_vih_test')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Type of VIH Test']);
                            $form->get('phone')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Phone',
                                'autocomplete' => 'off',]);
                            $form->get('email')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Email',
                                'autocomplete' => 'off',]);

                            $form->get('prefered_contact_method')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Prefered Contact Method']);
                            $form->get('current_jod')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Current Job']);
                            $form->get('facility_id')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Facility Name']);
                            $form->get('test_site_in_charge')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Test Site In Charge',
                                'autocomplete' => 'off',]);
                            
                            $form->get('submit')->setAttributes([
                                'onclick'=>'validateForm()',
                            ]);


                            echo $this->form()->openTag($form);
                            ?>
                            <?php echo $this->formHidden($form->get('id')->setAttribute('class', 'form-control')) ?>
                             <div class="form-group col-lg-4"> 
                                <?= $this->formLabel($form->get('provider_id')); ?>
                                <?= $this->formElement($form->get('provider_id')); ?>
                                <?= $this->formElementErrors($form->get('provider_id')); ?>
                            </div>
                            <div class="form-group col-lg-4"> 
                                <?= $this->formLabel($form->get('last_name')); ?>
                                <?= $this->formElement($form->get('last_name')); ?>
                                <?= $this->formElementErrors($form->get('last_name')); ?>
                            </div>
                            <div class="form-group col-lg-4">
                                <?= $this->formLabel($form->get('first_name')); ?>
                                <?= $this->formElement($form->get('first_name')); ?>
                                <?= $this->formElementErrors($form->get('first_name')); ?>
                            </div>
                            <div class="form-group col-lg-4">
                                <?= $this->formLabel($form->get('middle_name')); ?>
                                <?= $this->formElement($form->get('middle_name')); ?>
                                <?= $this->formElementErrors($form->get('middle_name')); ?>
                            </div>
                            <div class="form-group col-lg-4">
                                <?= $this->formLabel($form->get('region')); ?>
                                <?= $this->formElement($form->get('region')); ?>
                                <?= $this->formElementErrors($form->get('region')); ?>
                            </div>
                            <div class="form-group col-lg-4">
                                <?= $this->formLabel($form->get('district')); ?>
                                <?= $this->formElement($form->get('district')); ?>
                                <?= $this->formElementErrors($form->get('district')); ?></div>
                            <div class="form-group col-lg-4">  
                                <?= $this->formLabel($form->get('type_vih_test')); ?>
                                <?= $this->formElement($form->get('type_vih_test')); ?>
                                <?= $this->formElementErrors($form->get('type_vih_test')); ?>
                            </div>
                            <div class="form-group col-lg-4">
                                <?= $this->formLabel($form->get('phone')); ?>
                                <?= $this->formElement($form->get('phone')); ?>
                                <?= $this->formElementErrors($form->get('phone')); ?>
                            </div>
                            <div class="form-group col-lg-4">
                                <?= $this->formLabel($form->get('email')); ?>
                                <?= $this->formElement($form->get('email')); ?>
                                <?= $this->formElementErrors($form->get('email')); ?>
                            </div>
                            <div class="form-group col-lg-4">
                                <?= $this->formLabel($form->get('prefered_contact_method')); ?>
                                <?= $this->formElement($form->get('prefered_contact_method')); ?>
                                <?= $this->formElementErrors($form->get('prefered_contact_method')); ?>       
                            </div>
                            <div class="form-group col-lg-4">
                                <?= $this->formLabel($form->get('current_jod')); ?>
                                <?= $this->formElement($form->get('current_jod')); ?>
                                <?= $this->formElementErrors($form->get('current_jod')); ?>
                            </div>
                            <div class="form-group col-lg-4">
                                <?= $this->formLabel($form->get('facility_id')); ?>
                                <?= $this->formElement($form->get('facility_id')); ?>
                                <?= $this->formElementErrors($form->get('facility_id'));?>
                            </div>
                            <div class="form-group col-lg-4">
                                <?= $this->formLabel($form->get('test_site_in_charge')); ?>
                                <?= $this->formElement($form->get('test_site_in_charge')); ?>
                                <?= $this->formElementErrors($form->get('test_site_in_charge')); ?>
                            </div>
                            <div class="form-group col-lg-4" style="margin-top: 30px"><?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                 <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('provider', array('action' => 'index')); ?>" >CANCEL</a> </div>
                                <?php echo $this->form()->closeTag();
                                ?>
                            </div>
                        
                    </div>
                </div>
            </div>

        </div>

        <br>
        <br>

    </div>

</div>

</script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>

<script>
function validateForm() {
    
}
</script>







