<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>Results of Search</h2>
            </div>
           
        </div>
    </div>


    <div class="main-content">
        
        <div class="widget widget-fullwidth widget-small" style="padding:5px;" >
       
            
            <table id="example" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" >
                <thead>
                    <tr>
                        <th>Provider Id</th>
                        <th>Certification ID</th>
                        <th>Provider</th>
                        <!--<th>First Name</th>-->
                        <!--<th ><div style="width:80px;">Middle Name (3rd name)</div></th>-->
                        <th>Region</th>
                        <th>District</th>
                        <th><div style="width:80px;">Type VIH Test Modality/ Point </div></th> 
                        <th>Phone</th>
                        <th >E-mail</th>
                        <th><div style="width:60px;">Prefered Contact Methode</div></th>
                        <th >Current Job</th>
                        <th >Facility</th>
                        <th>Name of Testing Site In charge (Supervisor)</th >

                        <?php // if ($acl->isAllowed($role, 'Application\Controller\SpiV3', 'download-pdf') || $acl->isAllowed($role, 'Application\Controller\SpiV3', 'approve-status')) {  ?>
                        <th >Edit</th>
                        <?php // }  ?>
                    </tr>

                </thead>
                <tbody>
                    <tr>
                        <td colspan="10" class="dataTables_empty">Loading data from server</td>
                    </tr>
                <pre>
                    <?PHP // print_r($providers) ?> </pre>
                <?php foreach ($providers as $provider) : ?>
                    <tr>
                        <td><div style="width:80px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->provider_id); ?></div></td>
                        <td><div style="width:80px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->certification_id); ?></div></td>
                        <td><div style="width:150px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->last_name . ' ' . $provider->first_name . ' ' . $provider->middle_name); ?></div></td>
                        <td><div style="width:100px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->region); ?></div></td>
                        <td><div style="width:100px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->district); ?></div></td>
                        <td><div style="width:70px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->type_vih_test); ?></div></td>
                        <td><div style="width:100px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->phone); ?></div></td>
                        <td><div style="width:150px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->email); ?></div></td>
                        <td><div style="width:50px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->prefered_contact_method); ?></div></td>
                        <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->current_jod); ?></div></td>
                        <td><div style="width:150px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->facility_name); ?></div></td>
                        <td><div style="width:100px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($provider->test_site_in_charge); ?></div></td>
                        <td>
                            <div style="width:40px;height:40px;overflow:auto;">
                                <a href="<?php echo $this->url('provider', array('action' => 'edit', 'certification_id' => $provider->certification_id)); ?>"><span class="glyphicon glyphicon-pencil">Edit</span></a> 
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <?php
            
            ?>
        </div>
    </div>
</div>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>








