<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>


<div class="am-content">

    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>Add Written Exam</h2>
            </div>
        </div>
    </div>

    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <?php
            $form->setAttribute('action', $this->url('written-exam', array('action' => 'add')));
            $form->prepare();
            $form->get('exam_type')->setAttributes([
                'class' => 'form-control',
                'placeholder' => 'Type of Exam',
                'autocomplete' => 'off'
            ]);

            $form->get('provider_id')->setAttributes([
                'class' => 'form-control',
                'placeholder' => 'Provider',
                'autocomplete' => 'off'
            ]);

            $form->get('exam_admin_by_id')->setAttributes([
                'class' => 'form-control',
                'placeholder' => 'Exam Admin By',
                'autocomplete' => 'off'
            ]);
            $form->get('date')->setAttributes([
                'class' => 'form-control',
                'placeholder' => 'date',
                'autocomplete' => 'off'
            ]);
            $form->get('qa_point')->setAttributes([
                'class' => 'form-control',
            ]);
            $form->get('rt_point')->setAttributes([
                'class' => 'form-control',
            ]);
            $form->get('safety_point')->setAttributes([
                'class' => 'form-control',
            ]);

            $form->get('specimen_point')->setAttributes([
                'class' => 'form-control',
            ]);
            $form->get('testing_algo_point')->setAttributes([
                'class' => 'form-control',
            ]);
            $form->get('report_keeping_point')->setAttributes([
                'class' => 'form-control',
            ]);
            $form->get('EQA_PT_points')->setAttributes([
                'class' => 'form-control',
            ]);
            $form->get('ethics_point')->setAttributes([
                'class' => 'form-control',
            ]);

            echo $this->form()->openTag($form);
            ?>
            <?php echo $this->formHidden($form->get('id_written_exam')->setAttribute('class', 'form-control')) ?>
            <div class="form-group col-lg-6"> 
            <?= $this->formLabel($form->get('exam_type')); ?>
            <?= $this->formElement($form->get('exam_type')); ?>
            <?= $this->formElementErrors($form->get('exam_type')); ?>
            </div>
            <div class="form-group col-lg-6">
            <?= $this->formLabel($form->get('provider_id')); ?>
            <?= $this->formElement($form->get('provider_id')); ?>
                <?= $this->formElementErrors($form->get('provider_id')); ?>
            </div>
            <div class="form-group col-lg-6">
                <?= $this->formLabel($form->get('exam_admin_by_id')); ?>
<?= $this->formElement($form->get('exam_admin_by_id')); ?>
                <?= $this->formElementErrors($form->get('exam_admin_by_id')); ?>
            </div>
            <div class="form-group col-lg-6">
                <?= $this->formLabel($form->get('date')); ?>
<?= $this->formElement($form->get('date')); ?>
                <?= $this->formElementErrors($form->get('date')); ?>
            </div>
            <div class="form-group col-lg-6">
                <?= $this->formLabel($form->get('qa_point')); ?>
<?= $this->formElement($form->get('qa_point')); ?>
                <?= $this->formElementErrors($form->get('qa_point')); ?>
            </div>
            <div class="form-group col-lg-6">
                <?= $this->formLabel($form->get('rt_point')); ?>
<?= $this->formElement($form->get('rt_point')); ?>
                <?= $this->formElementErrors($form->get('rt_point')); ?> </div>
            <div class="form-group col-lg-6">  
                <?= $this->formLabel($form->get('safety_point')); ?>
                <?= $this->formElement($form->get('safety_point')); ?>
<?= $this->formElementErrors($form->get('safety_point')); ?>
            </div>

            <div class="form-group col-lg-6">
                <?= $this->formLabel($form->get('specimen_point')); ?>
                <?= $this->formElement($form->get('specimen_point')); ?>
                <?= $this->formElementErrors($form->get('specimen_point')); ?>       
            </div>
            <div class="form-group col-lg-6">
                <?= $this->formLabel($form->get('testing_algo_point')); ?>
                <?= $this->formElement($form->get('testing_algo_point')); ?>
                <?= $this->formElementErrors($form->get('testing_algo_point')); ?>
            </div>
            <div class="form-group col-lg-6">
                <?= $this->formLabel($form->get('report_keeping_point')); ?>
                <?= $this->formElement($form->get('report_keeping_point')); ?>
                <?= $this->formElementErrors($form->get('report_keeping_point')); ?>
            </div>
            <div class="form-group col-lg-6">
                <?= $this->formLabel($form->get('EQA_PT_points')); ?>
                <?= $this->formElement($form->get('EQA_PT_points')); ?>
                <?= $this->formElementErrors($form->get('EQA_PT_points')); ?>
            </div>
            <div class="form-group col-lg-6">
                <?= $this->formLabel($form->get('ethics_point')); ?>
                <?= $this->formElement($form->get('ethics_point')); ?>
                <?= $this->formElementErrors($form->get('ethics_point')); ?>
            </div>

            <div class="row" style="margin-left: 18px;">
                <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('written-exam', array('action' => 'index')); ?>" >CANCEL</a> </div>
                <?php echo $this->form()->closeTag();
                ?>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>


<script>
    $(document).ready(function () {

        $("#date").datepicker(
                {
                    showButtonPanel: true
                    , dateFormat: 'yy/mm/dd'
                    , dayNamesMin: ['Di', 'Lu', 'Ma', 'Me', 'Je', 'Ve', 'Sa']
                    , dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi']
                    , monthNamesShort: ['Jan', 'Fev', 'Mar', 'Avr', 'Mai', 'Jun', 'Jul', 'Août', 'Sep', 'Oct', 'Nov', 'Déc']
                    , monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre']
                    , prevText: 'Précédent'
                    , nextText: 'Suivant'
                    , closeText: 'OK'
                    , currentText: "Aujourd'hui"
                });

    }); //EOf:: DOM isReady


</script>



