<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>Results of Search </h2>
            </div>

        </div>
    </div>


    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <table id="example" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" >
                <thead>
                    <tr>

                        <th style="width: 8%">Number of Attempts </th>
                        <th>Provider </th>
                        <th style="width: 10%" >Exam administered by </th>
                        <th style="width: 8%">Date </th>
                        <th style="width: 5%">1.<br> QA (points)<br><br> </th>
                        <th style="width: 5%">2. <br>RT (points) <br><br></th>
                        <th style="width: 5%">3.<br> Safety (points) <br><br></th>
                        <th style="width: 5%">4.<br> Specimen collection (points) </th>
                        <th style="width: 5%">5.<br> Testing algorithm (points) <br></th>
                        <th style="width: 5%">6.<br> Record keeping (points)</th>
                        <th style="width: 5%">7.<br> EQA/PT (points)<br><br></th>
                        <th style="width: 5%">8.<br> Ethics (points)<br><br> </th>
                        <th style="width: 5%">Total Points (=25)</th>
                        <th style="width: 5%"> Final Score (≥80%)</th>


                        <?php // if ($acl->isAllowed($role, 'Application\Controller\SpiV3', 'download-pdf') || $acl->isAllowed($role, 'Application\Controller\SpiV3', 'approve-status')) {  ?>
                        <th >Action</th>
                        <?php // }  ?>
                    </tr>

                </thead>
                <tbody>
                    <tr>
                        <td colspan="15" class="dataTables_empty">Loading data from server</td>
                    </tr>
                    <?php foreach ($writtens as $written) : ?>
                        <tr>
                            <td><div style="width:80px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($written->exam_type); ?></div></td>

                            <td><div style="width:150px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($written->last_name . ' ' . $written->first_name. ' ' . $written->middle_name); ?></div></td>
                            <td><div style="width:150px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($written->admin_last_name . ' ' . $written->admin_first_name. ' ' . $written->admin_middle_name); ?></div></td>
                            <td><?php echo $this->escapeHtml($written->date); ?></td>
                            <td><?php echo $this->escapeHtml($written->qa_point); ?></td>
                            <td><?php echo $this->escapeHtml($written->rt_point); ?></td>
                            <td><?php echo $this->escapeHtml($written->safety_point); ?></td>
                            <td><?php echo $this->escapeHtml($written->specimen_point); ?></td>
                            <td><?php echo $this->escapeHtml($written->testing_algo_point); ?></td>
                            <td><?php echo $this->escapeHtml($written->report_keeping_point); ?></td>
                            <td><?php echo $this->escapeHtml($written->EQA_PT_points); ?></td>
                            <td><?php echo $this->escapeHtml($written->ethics_point); ?></td>
                            <td><?php echo $this->escapeHtml($written->total_points); ?></td>
                            <td><?php echo $this->escapeHtml($written->final_score . ' %'); ?></td>

                            <td>
                                <a href="<?php echo $this->url('written-exam', array('action' => 'edit', 'id_written_exam' => $written->id_written_exam)); ?>"><span class="glyphicon glyphicon-pencil"></span> Edit</a> 
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>





