<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">
        <h2>Add Certification</h2>
    </div>


    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body" >



                            <?php
                            $form->setAttribute('action', $this->url('certification', array('action' => 'add')));
                            $form->prepare();
                            $practical_score = $this->practical;
                            $written_score = $this->written;
                             if ($written_score >= 80 && $practical_score >= 90) {
                                $form->get('final_decision')->setAttributes(['class' => 'form-control', 'value' => 'Certified', 'readonly' => TRUE]);
                            } elseif ($written_score < 80 && $practical_score < 90) {
                                $form->get('final_decision')->setAttributes(['class' => 'form-control', 'value' => 'failed','readonly' => TRUE]);
                            } else {
                                $form->get('final_decision')->setAttributes(['class' => 'form-control', 'value' => 'pending','readonly' => TRUE]);
                            }
                            

                            $form->get('certification_issuer_id')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Certification Issued By',
                                'required'=> true]);

                            $form->get('date_certificate_issued')->setAttributes([
                                'class' => 'form-control',
                                'value' => date('Y-m-d'),
                                'readonly' => TRUE]);
                           

                            $form->get('certification_type')->setAttributes([
                                'class' => 'form-control',
                                'placeholder' => 'Type of Certition',
                                'autocomplete' => 'off',
                                'value' => 'initial',
                                'readonly' => TRUE]);
                            
                            $form->get('submit')->setAttributes([
                               ]);


                            echo $this->form()->openTag($form);
                            ?>
                            <?php echo $this->formHidden($form->get('id')->setAttribute('class', 'form-control')) ?>
                           
                               <?php echo $this->formHidden($form->get('examination')->setAttributes(['class'=> 'form-control', 'value'=>$this->id])) ?>
                            
                            <div class="form-group col-lg-6"> 
                                <?= $this->formLabel($form->get('final_decision')); ?>
                                <?= $this->formElement($form->get('final_decision')); ?>
                                <?= $this->formElementErrors($form->get('final_decision')); ?>
                            </div>
                             <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('certification_type')); ?>
                                <?= $this->formElement($form->get('certification_type')); ?>
                                <?= $this->formElementErrors($form->get('certification_type')); ?></div>

                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('date_certificate_issued')); ?>
                                <?= $this->formElement($form->get('date_certificate_issued')); ?>
                                <?= $this->formElementErrors($form->get('date_certificate_issued')); ?>
                            </div>
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('certification_issuer_id')); ?>
                                <?= $this->formElement($form->get('certification_issuer_id')); ?>
                                <?= $this->formElementErrors($form->get('certification_issuer_id')); ?>
                            </div>
                            
                           
                           

                            <div class="form-group col-lg-6" style="margin-top: 30px"><?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('certification', array('action' => 'index')); ?>" >CANCEL</a> </div>
                                <?php echo $this->form()->closeTag();
                                ?>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <br>
        <br>

    </div>

</div>

</script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
