<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/responsive.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>list of Certification</h2>
            </div>

        </div>
    </div>


    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;" >
            <table id="example" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" >
                <thead>
                    <tr>
                        <th  style="width:10%;">Certification ID</th>
                        <th  style="width:10%;">Provider</th>
                        <th  style="width:10%;">Final Decision</th>
                        <th  style="width:10%;">Certificate Issuer</th>
                        <th  style="width:10%;">Date Certificate Issued</th>
                        <th style="width:10%;">Date Certificate Sent</th>
                        <th style="width:10%;">Type of Certification</th> 
                        <?php // if ($acl->isAllowed($role, 'Application\Controller\SpiV3', 'download-pdf') || $acl->isAllowed($role, 'Application\Controller\SpiV3', 'approve-status')) {  ?>
                        <th style="width:5%;">Edit</th>
                        <th style="width:5%;">PDF</th>
                        <?php // }  ?>
                    </tr>

                </thead>
                <tbody>
                           
                    <?php foreach ($certifications as $certification) : ?>
                                <tr>
                                    <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->certification_id); ?></div></td>
                                    <td><div style="width:160px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->last_name . ' ' . $certification->first_name . ' ' . $certification->middle_name); ?></div></td>
                                    <td><div style="width:100px;height:40px;overflow:auto; color: red"><?php echo $this->escapeHtml($certification->final_decision); ?></div></td>
                                    <td><div style="width:160px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->issuer_last_name . ' ' . $certification->issuer_first_name . ' ' . $certification->issuer_middle_name); ?></div></td>
                                    <td><div style="width:100px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->date_certificate_issued); ?></div></td>
                                    <td><div style="width:100px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->date_certificate_sent); ?></div></td>
                                    <td><div style="width:120px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->certification_type); ?></div></td>
                                    <td>
                                        <div style="width:80px;height:40px;overflow:auto;">
                                            <a href="<?php echo $this->url('certification', array('action' => 'edit', 'id' => $certification->id)); ?>"><span class="glyphicon glyphicon-pencil">Edit</span></a> 
                                        </div>
                                    </td>

                            <?php
                            if (strcasecmp($certification->final_decision, 'Certified') == 0) {

                                echo "<td><div style='width:80px;height:40px;overflow:auto;'>
                                        <a href=" . $this->url('certification', array('action' => 'pdf'), array('query' => array('last' => $certification->last_name, 'first' => $certification->first_name, 'middle' => $certification->middle_name)
                                )) .
                                " target='_blank'><span class='glyphicon glyphicon-download-alt'>PDF</span></a> 
                                    </div>
                                </td> ";
                            } else {

                                echo "<td><div style='width:80px;height:40px;overflow:auto;'>
                                        <span class='glyphicon glyphicon-download-alt'>PDF</span>
                                    </div>
                                </td> ";
                            }
                            ?>
                                   
                                </tr>
                    <?php
                    endforeach;
                    ;
                    ?>
                </tbody>
            </table>

        </div>
    </div>
</div>
</div>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery-1.12.4.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.responsive.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/responsive.bootstrap.min.js'); ?>"></script>

<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>


<script type="text/javascript" language="javascript" >
    $(document).ready(function () {

        $('#example').dataTable({
            "aProcessing": true,
            "aServerSide": true,
        })
    });
</script>






