<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">

        <div class="row">
            <div class="col-sm-8">
                <h2>list of Certifications</h2>
            </div>

        </div>
    </div>


    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <table id="example" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget" >
                <thead>
                    <tr>

                        <th>Provider </th>
                        <th>Score </th>
                        <th>Final Decision </th>
                         <th>Certificate Issued By</th>
                        <th>Date Certificate Issued</th>
                        <th>Date Certificate Sent</th>
                        <th>type Of Certificate</th>
                        <th>Approved</th>
                        
                        <?php // if ($acl->isAllowed($role, 'Application\Controller\SpiV3', 'download-pdf') || $acl->isAllowed($role, 'Application\Controller\SpiV3', 'approve-status')) {   ?>
                        <th style="width:30%;">Certification</th>
                        <?php // }   ?>
                    </tr>

                </thead>
                <tbody>
                    <tr>
                        <td colspan="10" class="dataTables_empty">Loading data from server</td>
                    </tr>
                    <?php foreach ($certifications as $certification) : ?>
                        <tr>
                            <td><div style="width:150px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->last_name.' '.$certification->first_name.' '.$certification->middle_name); ?></div></td>
                            <td><div style="width:80px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->score); ?></div></td>
                            <td><div style="width:80px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->final_decision); ?></div></td>
                            <td><div style="width:80px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->certificate_issued_by_id); ?></div></td>
                            <td><div style="width:80px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->date_certificate_issued); ?></div></td>
                            <td><div style="width:80px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->date_certificate_sent); ?></div></td>
                            <td><div style="width:80px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->certification_type); ?></div></td>
                            <td><div style="width:80px;height:40px;overflow:auto;"><?php echo $this->escapeHtml($certification->issued); ?></div></td>
                           

                            <td>
                                <a href="<?php echo $this->url('certification', array('action' => 'edit','provider_id' => $certification->provider_id)); ?>"> <span class="glyphicon glyphicon-list-alt"></span></a> 
                            </td>
                            <td><a href="<?php echo $this->url('certification', array('action' => 'pdf')); ?>"  style="white-space: nowrap" target="_blank"><i class="fa fa-download"></i> PDF</a></td>




                            
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>

<script>


</script>





