<?php

// Extend the TCPDF class to create custom Header and Footer
class MYPDF extends TCPDF {
    
}

// create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Dabre Adjaratou');
$pdf->SetTitle('Personnel Certificate');
$pdf->SetSubject('Certificate');
$pdf->SetKeywords('TCPDF, PDF, Certificate, test, guide');

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(0);
$pdf->SetFooterMargin(0);

// remove default footer
$pdf->setPrintFooter(false);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}

// ---------------------------------------------------------

// set font
$pdf->SetFont('times', '', 20);



// remove default header
$pdf->setPrintHeader(false);
//$pdf->SetMargins(10, 20, 10, true);
// add a page
$pdf->AddPage('L','A4');


// -- set new background ---

// get the current page break margin
$bMargin = $pdf->getBreakMargin();
// get current auto-page-break mode
$auto_page_break = $pdf->getAutoPageBreak();
// disable auto-page-break
$pdf->SetAutoPageBreak(false, 0);
// set bacground image
$img_file = dirname(__CLASS__).'public/assets/img/certificate-templates-for-word2-1_1.png';
$pdf->Image($img_file, 0, 0, 295, 210, '', '', '', false, 300, '', false, false, 0);
// restore auto-page-break status
//$pdf->SetAutoPageBreak($auto_page_break, $bMargin);
// set the starting point for the page content
$pdf->setPageMark();




//$pdf->SetDisplayMode('fullpage', 'SinglePage', 'UseNone');
//
// set font
//$pdf->SetFont('times', 'B', 20);
// add a page
//$pdf->AddPage('L', 'A4');

// set JPEG quality
//$pdf->setJPEGQuality(75);

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

// Stretching, position and alignment example



// create some HTML content
$html = '<div style="text-align:center;
    padding: 15px;">
   <h1>Certificate</h1>
    Ce certificate atteste que <br> <h1 style=" color:blue">'.strtoupper($last).' '.strtoupper($first).' '.strtoupper($middle).'</h1> <br>A  apte a faire les test de depistage rapide<br><br><br><br><br><br>
 </div>';


// output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

$html2='<div style="width:50px "><img src="'.dirname(__CLASS__).'public/assets/img/signature.png'.'"  width="150" style="text-align:right" ></div>';


$pdf->writeHTML($html2, true, false, true, false, '');
//$pdf->SetXY(250,100 );
 //---------------------------------------------------------

//Close and output PDF document
$pdf->Output('example_051.pdf', 'I');

//============================================================+
// END OF FILE
//============================================================+