<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css" />
<div class="am-content">
	<div class="page-head">
		<div class="row">
			<div class="col-sm-8">
				<h2><?= $this->translate('SPI-RT 5.0 Facility Report'); ?></h2>
			</div>
		</div>
	</div>
	<div class="main-content">
		<!--+general-chart("classes", "title", "height", "id", "counter value", "counter desc", tools enabled (use true or false))-->

		<div class="row">
			<div class="col-md-12 col-sm-12">
				<div class="widget widget-table">
					<div class="panel panel-default">
						<div class="panel-body">
							<form role="form" class="form-horizontal">
								<div class="form-group">
									<label for="date" class="col-sm-2 control-label"><?= $this->translate('Date Range'); ?></label>
									<div class=" col-lg-4">
										<input type="text" placeholder="<?= $this->translate('Select Date Range'); ?>" class="form-control" id="dateRange" readonly>
									</div>
									<label for="auditRndNo" class="col-sm-2 control-label"><?= $this->translate('Audit Round No.'); ?></label>
									<div class=" col-lg-4">
										<select class="form-control" id="auditRndNo">
											<option value=''><?= $this->translate('All'); ?></option>
											<?php
											foreach ($spiV3auditRoundNo as $auditRoundNo) {
											?>
												<option value="<?php echo $auditRoundNo['auditroundno']; ?>"> <?php echo $auditRoundNo['auditroundno']; ?></option>
											<?php
											}
											?>
										</select>
									</div>
								</div>

								<div class="form-group">
									<label for="level" class="col-sm-2 control-label"><?= $this->translate('Level'); ?></label>
									<div class=" col-lg-4">
									<select class="form-control" id="level">
                      <option value=""><?= $this->translate('All'); ?></option>
                      <option value="Level1"><?= $this->translate('Sub-national 1'); ?></option>
                      <option value="Level2"><?= $this->translate('Sub-national 2'); ?></option>
                      <option value="Level3"><?= $this->translate('Sub-national 3'); ?></option>
                      <option value="Level4"><?= $this->translate('Sub-national 4'); ?></option>
                      <option value="Other"><?= $this->translate('Other'); ?></option>
                      
                    </select>
									</div>
									<label for="affiliation" class="col-sm-2 control-label"><?= $this->translate('Affiliation'); ?></label>
									<div class=" col-lg-4">
									<select class="form-control" id="affiliation">
											<option value=""><?= $this->translate('All'); ?></option>
											<option value="Government"><?= $this->translate('Government'); ?></option>
											<option value="Private"><?= $this->translate('Private'); ?></option>
											<option value="faith"><?= $this->translate('Faith-based Organization'); ?></option>
											<option value="nongovt"><?= $this->translate('Non-governmental organization'); ?></option>
											<option value="Other"><?= $this->translate('Other'); ?></option>
										</select>
									</div>
								</div>
								
								<div class="form-group ">
									<label for="scoreLevel" class="col-sm-2 control-label"><?= $this->translate('Score Level'); ?></label>
									<div class=" col-lg-4">
										<select class="form-control" id="scoreLevel">
											<option value=""><?= $this->translate('All'); ?></option>
											<option value="0">0</option>
											<option value="1">1</option>
											<option value="2">2</option>
											<option value="3">3</option>
											<option value="4">4</option>
										</select>
									</div>
									<label for="testPoint" class="col-sm-2 control-label"><?= $this->translate('Type of Testing Point'); ?></label>
									<div class=" col-lg-4">
										<select class="form-control" id="testPoint" onchange="getTestingPointTypeNames();">
											<option value=""><?= $this->translate('All'); ?></option>
											<?php
                      foreach ($testingPointResult as $val) {
                      ?>
                        <option value="<?php echo $val['testingPointType']; ?>"><?php echo ucwords($val['testingPointType']); ?></option>
                      <?php
                      }
                      ?>
											<option value="other"><?= $this->translate('Other'); ?></option>
										</select>
									</div>
								</div>
								<div class="form-group ">
									<div class="testPointNameSection">
									</div>
								</div>
								<div class="form-group" style="text-align:center;">
									<button type="button" onclick="getReport()" class="btn btn-sm btn-success"><?= $this->translate('Get Report'); ?></button>
									&nbsp;<button class="btn btn-danger btn-sm" onclick="document.location.href = document.location"><span>Reset</span></button>
								</div>
							</form>
						</div>
					</div>

					
					<div class="widget-head">

						<br>


						<div class="row">
							<div class="col-sm-8">
								<?= $this->translate('Pending Audits (Audits not yet Accepted)'); ?> : <?php echo $pendingCount; ?>
							</div>
							<div class="col-sm-4">
								<a href="javascript:void(0);" class="btn btn-danger pull-right" onclick="exportFacility();"><i class="fa fa-file-excel-o"></i>&nbsp;<?= $this->translate('Export to Excel'); ?></a>
							</div>
						</div>
						<br>
						<br>
						<table class="datatables table-condensed table table-striped table-bordered">
							<thead>
								<tr>
									<th><?= $this->translate('Facility name'); ?></th>
									<th style="width:9%;"><?= $this->translate('Audit Date'); ?></th>
									<th><?= $this->translate('Testing Point'); ?></th>
									<th style="width:5%;"><?= $this->translate('Personnel Training & Certification'); ?></th>
									<th style="width:5%;"><?= $this->translate('Physical') ?></th>
									<th style="width:5%;"><?= $this->translate('Safety'); ?></th>
									<th style="width:5%;"><?= $this->translate('Pre-Testing'); ?></th>
									<th style="width:5%;"><?= $this->translate('Testing'); ?></th>
									<th style="width:5%;"><?= $this->translate('Post-Testing'); ?></th>
									<th style="width:5%;"><?= $this->translate('External QA'); ?></th>
									<th style="width:5%;"><?= $this->translate('RTRI'); ?></th>
									<th style="width:5%;"><?= $this->translate('Total'); ?></th>
								<th style="width:5%;"><?= $this->translate('% Scores'); ?></th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td colspan="12" class="dataTables_empty"><?= $this->translate('Loading data from server'); ?></td>
								</tr>
							</tbody>
						</table>


					</div>
				</div>

			</div>
		</div>

	</div>
</div>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>

<script type="text/javascript">
	var oTable = null;

	$(document).ready(function() {
		
		oTable = $('.datatables').dataTable({
			"bScrollCollapse": true,
			"bRetrieve": true,
			"pageLength": 50,
			"aoColumns": [{
				"sClass": "center"
			}, {
				"sClass": "center"
			}, {
				"sClass": "center"
			}, {
				"sClass": "center"
			}, {
				"sClass": "center"
			}, {
				"sClass": "center"
			}, {
				"sClass": "center"
			}, {
				"sClass": "center"
			}, {
				"sClass": "center"
			}, {
				"sClass": "center"
			}, {
				"sClass": "center"
			}, 
			{
				"sClass": "center"
			},
			{
				"sClass": "center"
			}
			],
			"aaSorting": [
				[1, "desc"]
			],
			"bProcessing": true,
			"bServerSide": true,
			"sAjaxSource": "<?php echo $this->url('spi-v5-reports', array('action' => 'facility-report')); ?>",
			"fnServerData": function(sSource, aoData, fnCallback) {
				aoData.push({
					"name": "auditRndNo",
					"value": $("#auditRndNo").val()
				});
				aoData.push({
					"name": "dateRange",
					"value": $("#dateRange").val()
				});
				aoData.push({
					"name": "testPoint",
					"value": $("#testPoint").val()
				});
				aoData.push({
					"name": "testPointName",
					"value": $("#testPointName").val()
				});

				aoData.push({
					"name": "level",
					"value": $("#level").val()
				});
				
				aoData.push({
					"name": "affiliation",
					"value": $("#affiliation").val()
				});
				aoData.push({
					"name": "scoreLevel",
					"value": $("#scoreLevel").val()
				});
				$.ajax({
					"dataType": 'json',
					"type": "POST",
					"url": sSource,
					"data": aoData,
					"success": function(json) {
						$.unblockUI();
						fnCallback(json);
					}
				});
			}
		});
		var startDate = "";
		var endDate = "";
		$('#dateRange').daterangepicker({
				format: 'DD-MMM-YYYY',
				startDate: moment().subtract('days', 29),
				endDate: moment(),
				maxDate: moment(),
				ranges: {
					'Today': [moment(), moment()],
					'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
					'Last 7 Days': [moment().subtract('days', 6), moment()],
					'Last 30 Days': [moment().subtract('days', 29), moment()],
					'This Month': [moment().startOf('month'), moment().endOf('month')],
					'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
				},
			},
			function(start, end) {
				startDate = start.format('YYYY-MM-DD');
				endDate = end.format('YYYY-MM-DD');
			});
	});

	function exportFacility() {
		$.blockUI({
			message: '<h1>Loading...</h1>'
		});
		var dateRange = $("#dateRange").val();
		$.post("<?php echo $this->url('spi-v5-reports', array('action' => 'export-facility-report')); ?>", {
				dateRange: dateRange
			},
			function(data) {
				if (data == "" || data == null || data == undefined) {
					alert('<?= $this->translate('Unable to generate download'); ?>');
				} else {
					document.location.href = '/temporary/' + data;
				}
				$.unblockUI();
			});

	}

	function getReport() {
		$.blockUI({
			message: '<h1>Loading...</h1>'
		});
		oTable.fnDraw();
	}

	function getTestingPointTypeNames() {
		$.blockUI();
		let testingPointType = $('#testPoint').val();
		
		$.post("<?php echo $this->url('spi-v5-form', array('action' => 'get-testing-point-type-names')); ?>", {
				testingPointType: testingPointType
			},
			function(data) {
				$('.testPointNameSection').html(data);
				$.unblockUI();
			});
	}

	
</script>