
<div class="am-content">
        <div class="page-head">
          <div class="row">
				<div class="col-sm-8">
				<h2>User Login History List</h2>
				</div>
		  </div>
        </div>
        
        <div class="main-content">
             
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">

                <table  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed" id="roleDataTable">
					<thead>
					<tr>
                    <th>Login Name</th>
            <th>Attempted Date Time</th>
            <th>IP Address</th>
            <th>Browser</th>
            <th>Operating System</th>
            <th>Status</th>
					</tr>
					</thead>
					<tbody>
					<tr>
						 <td colspan="4" class="dataTables_empty"><?= $this->translate('Loading data from server'); ?></td>
					</tr>
					</tbody>
				</table>
            </div>
        <br>
            
            
        </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/datatables.min.js'); ?>"></script>
<script type="text/javascript">
    var oTable = null;

 $(document).ready(function() {
	
        oTable = $('#roleDataTable').dataTable({
            "bScrollCollapse": true,
            "bRetrieve": true,                        
            "aaSorting": [[ 0, "desc" ]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url('user-login-history',array('action' => 'index')); ?>",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
       
	} );
</script>