<?php

use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
if ($acl->isAllowed($role, 'Application\Controller\SpiV6', 'download-pdf') || $acl->isAllowed($role, 'Application\Controller\SpiV6', 'approve-status')) {
  $editAction = '{"sClass":"center details-control","bSortable":false},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false}';
} else {
  $editAction = '{"sClass":"center details-control","bSortable":false},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
}
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css" />
<div class="am-content">
        <div class="page-head">
          <div class="row">
				<div class="col-sm-8">
				<h2>User Login History List</h2>
				</div>
		  </div>
        </div>
        
        <div class="main-content">
             
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">

            <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default">
            <div class="panel-body">
              <form role="form" class="form-horizontal">
                <div class="form-group">
                  <label for="date" class="col-sm-2 control-label"><?= $this->translate('Date Range'); ?></label>
                  <div class=" col-lg-4">
                    <input type="text" placeholder="Select Date Range" class="form-control" id="date" readonly>
                  </div>
                  <label for="auditRndNo" class="col-sm-2 control-label"><?= $this->translate('User Name'); ?></label>
                  <div class=" col-lg-4">
                  <input type="text" placeholder="Select User Name" class="form-control" name="userName" id="userName">
                  </div>
                </div>

                <div class="form-group">
                  <div class="testPointNameSection"></div>
                </div>
                <div class="form-group" style="text-align:center;">
                  <button type="button" onclick="search();" class="btn btn-space btn-primary"><?= $this->translate('Search'); ?></button>&nbsp;
                  <button type="button" onclick="document.location.href = document.location" class="btn btn-space btn-default"><?= $this->translate('Cancel'); ?></button>
                </div>
              </form>
            </div>
           
          </div>
        </div>
      </div>

          <table  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed" id="roleDataTable">
					<thead>
					<tr>
            <th>Login Name</th>
            <th>Attempted Date Time</th>
            <th>IP Address</th>
            <th>Browser</th>
            <th>Operating System</th>
            <th>Status</th>
					</tr>
					</thead>
					<tbody>
					<tr>
						 <td colspan="4" class="dataTables_empty"><?= $this->translate('Loading data from server'); ?></td>
					</tr>
					</tbody>
				</table>
            </div>
        <br>
            
            
        </div>
</div>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/datatables.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>

<script type="text/javascript">
    var oTable = null;
   
 $(document).ready(function() {
	
        oTable = $('#roleDataTable').DataTable({
            "bScrollCollapse": true,
            "bRetrieve": true,                        
            "aaSorting": [[ 0, "desc" ]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url('user-login-history',array('action' => 'index')); ?>",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
              aoData.push({
          "name": "dateRange",
          "value": $("#date").val()
        }),
        aoData.push({
          "name": "userName",
          "value": $("#userName").val()
        }),
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });

        $('#date').daterangepicker({
        format: 'DD-MMM-YYYY',
        startDate: moment().subtract('days', 29),
        endDate: moment(),
        maxDate: moment(),
        ranges: {
          'Today': [moment(), moment()],
          'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
          'Last 7 Days': [moment().subtract('days', 6), moment()],
          'Last 30 Days': [moment().subtract('days', 29), moment()],
          'This Month': [moment().startOf('month'), moment().endOf('month')],
          'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
        }
      },
      function(start, end) {
        startDate = start.format('YYYY-MM-DD');
        endDate = end.format('YYYY-MM-DD');
      });
       
	} );

    function search() {
    oTable.draw();
  }
</script>