<?php
if($id['id']!=''){
$nos=str_replace("'"," ",base64_decode($id['id']));
$round = explode(",",trim($nos));
}else{
$round = array();    
}
?>
<style>
/*multiselect*/
.ui-state-hover, .ui-widget-content .ui-state-hover{color: #1c94c4;border: 1px solid #cccccc;background:none;}
.ui-state-active{color: #1c94c4;border: 1px solid #cccccc;background:none;}
.ui-multiselect-header{display: none;}
</style>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
      <div class="am-content">
        <div class="main-content">
          <div class="row">
            <div class="col-md-12" id="righter">
                <div class="widget widget-map">
                <div class="widget-head"><span class="title"><b>Audit Locations</b></span>
		<div  style="float: right;">
		      <label>Audit Round</label>
                      <select class="" id="auditRndNoLocations" multiple="multiple" onchange="getAuditLocationDetails()">
                          <?php
			  foreach($spiV3auditRoundNo as $auditRoundNo)
			  {
			    ?>
			    <option value="<?php echo $auditRoundNo['auditroundno'];?>"<?php echo in_array($auditRoundNo['auditroundno'],$round) ? "selected=selected" : ""; ?>><?php echo $auditRoundNo['auditroundno'];?></option>
			    <?php
			  }
			  ?>
                        </select>
		      </div>
		</div>
                <div class="map-container" id="auditLocations">
                  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places">
</script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
    <script type="text/javascript">
      
    
  function getAuditLocationDetails()
  {
    value = $("#auditRndNoLocations").val();
      $.post("<?php echo $this->url('spi-v3-form', array('action' => 'audit-locations')); ?>", {roundno:value},
      function (data) {
	  $("#auditLocations").html(data);
      });
  }

      $(document).ready(function(){
	getAuditLocationDetails();
	$("#auditRndNoLocations").multiselect({height: 100, minWidth: 150,});
      });
    </script>