<?php
if($id['id']!=''){
$nos=str_replace("'"," ",base64_decode($id['id']));
$round = explode(",",trim($nos));
}else{
$round = array();    
}
?>
<style>
/*multiselect*/
.select2{
  width:350px !important;
}
</style>
<!--<link rel="stylesheet" type="text/css" href="< ?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>-->
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
      <div class="am-content">
        <div class="main-content">
          <div class="row">
            <div class="col-md-12" id="righter">
                <div class="widget widget-map">
                <div class="widget-head"><span class="title"><b>Audit Locations</b></span>
		  <span style="margin-left: 60%;">
		      <label>Audit Round</label>
			  <select class="" id="auditRndNoLocations" multiple="multiple" onchange="getAuditLocationDetails()">
			    <?php
			    foreach($spiV3auditRoundNo as $auditRoundNo)
			    {
				  ?>
				  <option value="<?php echo $auditRoundNo['auditroundno'];?>"<?php echo in_array($auditRoundNo['auditroundno'],$round) ? "selected=selected" : ""; ?>><?php echo $auditRoundNo['auditroundno'];?></option>
				  <?php
			    }
			    ?>
			  </select>
		  </span>
		      </div>
                <div class="map-container" id="auditLocations">
                  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
	  
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>	  
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places">
</script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
    <script type="text/javascript">
      
    
  function getAuditLocationDetails()
  {
    value = $("#auditRndNoLocations").val();
      $.post("<?php echo $this->url('spi-v3-form', array('action' => 'audit-locations')); ?>", {roundno:value},
      function (data) {
	  $("#auditLocations").html(data);
      });
  }

      $(document).ready(function(){
	getAuditLocationDetails();
	
	$("#auditRndNoLocations").multipleSelect({placeholder:'Please select audit round no.',width: '20%',minimumCountSelected:'2'});
//    $(".select2").select2({
//      width: '100%',
//	  placeholder: '',
//	  allowClear: true,
//	  tags : false
//    });		
	
	
      });
    </script>