<style>

</style>

<?php
if ($id['id'] != '') {
	$nos = str_replace("'", " ", base64_decode($id['id']));
	//$round = explode(",", trim($nos));
} else {
	//$round = [];
	$nos = '';
}

$config = $this->GlobalConfigHelper();
$web_version = $config['web_version'];
$isV3 = preg_match("/v3/i", $web_version);
$isV5 = preg_match("/v5/i", $web_version);
$isV6 = preg_match("/v6/i", $web_version);
?>
<style>
	/*multiselect*/
	.select2 {
		width: 350px !important;
	}
</style>
<!--<link rel="stylesheet" type="text/css" href="< ?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>-->
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/leaflet.css'); ?>" type="text/css" />
<div class="am-content">
	<div class="main-content">
		<div class="row">
			<div class="col-md-12" id="righter">
				<div class="widget widget-map">
					<div class="widget-head">
						<input type="hidden" name="inpId" id="inpId" value="<?php echo $nos; ?>" />

						<span class="title"><b><?= $this->translate('Audit Locations'); ?></b></span>

						<span style="margin-left: 3%;">
							<label><?= $this->translate('Form Version'); ?></label>
							<select class="" name="chooseFormVersion" id="chooseFormVersion" onchange="getAuditLocationsByForm(this.value)">
								<?php if ($isV6) { ?>
									<option value="v6">SPI-RRT</option>
								<?php } ?>
								<?php if ($isV3) { ?>
									<option value="v3">SPI-RT v3</option>
								<?php } ?>
							</select>

						</span>
						<span style="margin-left: 0%;">
							<label><?= $this->translate('Audit Round'); ?></label>
							<select style="display:none;" id="hiddenAuditRndNoLocations"></select>
							<select class="" id="auditRndNoLocations" multiple="multiple" onchange="getAuditLocationDetails()">

							</select>
							<label><?= $this->translate('Date Range'); ?></label>
							<input type="text" placeholder="<?= $this->translate('Enter Date'); ?>" class="datepicker" id="locationDateRange">
							<a style="" href="javascript:void(0)" class="btn btn-sm btn-primary" onclick="getAuditLocationDetails()"><?= $this->translate('OK'); ?></a>
						</span>
					</div>
					<div id="auditLocations" style="height:1135px;max-height:1500px;">

					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/leaflet.js'); ?>"></script>
<script type="text/javascript">
	function getAuditLocationDetails() {
		var formVersionId = $("#chooseFormVersion").val();
		value = $("#auditRndNoLocations").val();
		dateRange = $("#locationDateRange").val();
		if (formVersionId == 'v3') {
			$.post("<?php echo $this->url('spi-v3-form', array('action' => 'audit-locations')); ?>", {
					roundno: value,
					dateRange: dateRange
				},
				function(data) {
					$("#auditLocations").html(data);
				});
		}

		if (formVersionId == 'v6') {
			$.post("<?php echo $this->url('spi-v6-form', array('action' => 'audit-locations')); ?>", {
					roundno: value,
					dateRange: dateRange
				},
				function(data) {
					$("#auditLocations").html(data);
				});
		}

	}

	function getAuditLocationsByForm(formType) {
		let inpId = $("#inpId").val();
		$.post("<?php echo $this->url('common', array('action' => 'get-audit-location-based-on-form')); ?>", {
				formVersion: formType,
				inpId: inpId
			},
			function(data) {
				$("#auditRndNoLocations").html(data);
				//$("#hiddenAuditRndNoLocations").html(data);
				$("#auditRndNoLocations").multipleSelect({
					placeholder: '<?= $this->translate('Please select one or more audit round(s)'); ?>',
					width: '25%'
				});

				// let x = [];
				// var __OBJECTS = [];
				// let i=1;
				// $("#hiddenAuditRndNoLocations > option").each(function() {
				// 	__OBJECTS.push(this.value);
				// });

				// redrawMap();

				// function redrawMap() {
				// 	var $card = __OBJECTS.shift();
				// 	x.push($card);
				// 	$("#auditRndNoLocations").multipleSelect('setSelects', x)
				// 	if (__OBJECTS.length) {
				// 		setTimeout(redrawMap, 1500)
				// 	}
				// }
			});
	}
	$(document).ready(function() {
		let formVersionId = $("#chooseFormVersion").val();
		getAuditLocationsByForm(formVersionId);
		getAuditLocationDetails();


		var startDate = "";
		var endDate = "";
		$('#locationDateRange').daterangepicker({
				format: 'DD-MMM-YYYY',
				startDate: moment().subtract('days', 29),
				endDate: moment(),
				maxDate: moment(),
				ranges: {
					'Today': [moment(), moment()],
					'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
					'Last 7 Days': [moment().subtract('days', 6), moment()],
					'Last 30 Days': [moment().subtract('days', 29), moment()],
					'This Month': [moment().startOf('month'), moment().endOf('month')],
					'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
				},
			},
			function(start, end) {
				startDate = start.format('YYYY-MM-DD');
				endDate = end.format('YYYY-MM-DD');
			});

	});
</script>
