<?php
if (trim($id) != '') {
    $round = explode(",", trim($nos));
} else {
    $round = [];
}
$options = '';
if (!empty($result)) {
    foreach ($result as $auditRoundNo) {
        $selected = in_array($auditRoundNo['auditroundno'], $round) ? "selected=selected" : "";
        $options .= '<option value="' . $auditRoundNo['auditroundno'] . '" ' . $selected . '>' . $auditRoundNo['auditroundno'] . ' - ' . $this->humanReadableDateFormat($auditRoundNo['assesmentofaudit']) . '</option>';
    }
}
echo $options;
