<?php
return [
    'SA' => [
        'Application\\Controller\\CommonController' => [
            'audit-locations' => 'allow',
        ],
        'Application\\Controller\\ConfigController' => [
            'index' => 'allow',
            'edit-global' => 'allow',
        ],
        'Application\\Controller\\IndexController' => [
            'index' => 'allow',
        ],
        'Application\\Controller\\DashboardController' => [
            'index' => 'allow',
            'audit-details' => 'allow',
        ],
        'Application\\Controller\\DashboardV6Controller' => [
            'index' => 'allow',
        ],
        'Application\\Controller\\DashboardV5Controller' => [
            'index' => 'allow',
        ],
        'Application\\Controller\\DistrictController' => [
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ],
        'Application\\Controller\\EmailController' => [
            'index' => 'allow',
            'email-v5' => 'allow',
        ],
        'Application\\Controller\\EventController' => [
            'index' => 'deny',
        ],
        'Application\\Controller\\FacilityController' => [
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'export-facility' => 'allow',
            'get-province-list' => 'allow',
            'get-facility-name' => 'allow',
            'upload-facility' => 'allow',
        ],
        'Application\\Controller\\ProvincesController' => [
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ],
        'Application\\Controller\\RolesController' => [
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ],
        'Application\\Controller\\SpiV5Controller' => [
            'index' => 'deny',
            'manage-facility' => 'deny',
            'approve-status' => 'deny',
            'corrective-action-pdf' => 'deny',
            'delete' => 'deny',
            'download-pdf' => 'deny',
            'download-files' => 'deny',
            'duplicate' => 'deny',
            'edit' => 'deny',
            'export' => 'deny',
            'view-bulk-downloads' => 'deny',
            'view-data-v5' => 'deny',
        ],
        'Application\\Controller\\SpiV6Controller' => [
            'index' => 'allow',
            'manage-facility' => 'allow',
            'approve-status' => 'allow',
            'corrective-action-pdf' => 'allow',
            'delete' => 'allow',
            'download-pdf' => 'allow',
            'download-files' => 'allow',
            'duplicate' => 'allow',
            'edit' => 'allow',
            'email-v6' => 'deny',
            'export' => 'allow',
            'view-bulk-downloads' => 'deny',
            'view-data-v6' => 'allow',
            'view-data-section-zero-v6' => 'allow',
        ],
        'Application\\Controller\\SpiV3Controller' => [
            'index' => 'allow',
            'approve-status' => 'allow',
            'corrective-action-pdf' => 'allow',
            'view-data' => 'allow',
            'delete' => 'allow',
            'download-files' => 'allow',
            'duplicate' => 'allow',
            'edit' => 'allow',
            'manage-facility' => 'allow',
            'download-pdf' => 'allow',
            'view-bulk-downloads' => 'deny',
        ],
        'Application\\Controller\\UserLoginHistoryController' => [
            'index' => 'allow',
        ],
        'Application\\Controller\\UsersController' => [
            'index' => 'allow',
            'add' => 'allow',
            'change-password' => 'allow',
            'profile' => 'allow',
            'edit' => 'allow',
        ],
        'Application\\Controller\\SpiV3ReportsController' => [
            'facility-report' => 'allow',
        ],
        'Application\\Controller\\SpiV5ReportsController' => [
            'facility-report' => 'deny',
        ],
        'Application\\Controller\\SpiV6ReportsController' => [
            'facility-report' => 'allow',
        ],
    ],
    'VIEWER' => [
        'Application\\Controller\\CommonController' => [
            'audit-locations' => 'allow',
        ],
        'Application\\Controller\\ConfigController' => [
            'index' => 'allow',
            'edit-global' => 'allow',
        ],
        'Application\\Controller\\IndexController' => [
            'index' => 'allow',
        ],
        'Application\\Controller\\DashboardController' => [
            'index' => 'allow',
            'audit-details' => 'allow',
        ],
        'Application\\Controller\\DashboardV6Controller' => [
            'index' => 'allow',
        ],
        'Application\\Controller\\DashboardV5Controller' => [
            'index' => 'allow',
        ],
        'Application\\Controller\\DistrictController' => [
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ],
        'Application\\Controller\\EmailController' => [
            'index' => 'allow',
            'email-v5' => 'allow',
        ],
        'Application\\Controller\\EventController' => [
            'index' => 'deny',
        ],
        'Application\\Controller\\FacilityController' => [
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'export-facility' => 'deny',
            'get-province-list' => 'allow',
            'get-facility-name' => 'allow',
            'upload-facility' => 'deny',
        ],
        'Application\\Controller\\ProvincesController' => [
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ],
        'Application\\Controller\\RolesController' => [
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
        ],
        'Application\\Controller\\SpiV5Controller' => [
            'index' => 'deny',
            'manage-facility' => 'deny',
            'approve-status' => 'deny',
            'corrective-action-pdf' => 'deny',
            'delete' => 'deny',
            'download-pdf' => 'deny',
            'download-files' => 'deny',
            'duplicate' => 'deny',
            'edit' => 'deny',
            'export' => 'deny',
            'view-bulk-downloads' => 'deny',
            'view-data-v5' => 'deny',
        ],
        'Application\\Controller\\SpiV6Controller' => [
            'index' => 'allow',
            'manage-facility' => 'allow',
            'approve-status' => 'allow',
            'corrective-action-pdf' => 'allow',
            'delete' => 'allow',
            'download-pdf' => 'allow',
            'download-files' => 'allow',
            'duplicate' => 'allow',
            'edit' => 'allow',
            'email-v6' => 'deny',
            'export' => 'allow',
            'view-bulk-downloads' => 'deny',
            'view-data-v6' => 'deny',
            'view-data-section-zero-v6' => 'deny',
        ],
        'Application\\Controller\\SpiV3Controller' => [
            'index' => 'allow',
            'approve-status' => 'allow',
            'corrective-action-pdf' => 'allow',
            'view-data' => 'allow',
            'delete' => 'allow',
            'download-files' => 'allow',
            'duplicate' => 'allow',
            'edit' => 'allow',
            'manage-facility' => 'allow',
            'download-pdf' => 'allow',
            'view-bulk-downloads' => 'deny',
        ],
        'Application\\Controller\\UserLoginHistoryController' => [
            'index' => 'allow',
        ],
        'Application\\Controller\\UsersController' => [
            'index' => 'deny',
            'add' => 'deny',
            'change-password' => 'allow',
            'profile' => 'allow',
            'edit' => 'deny',
        ],
        'Application\\Controller\\SpiV3ReportsController' => [
            'facility-report' => 'allow',
        ],
        'Application\\Controller\\SpiV5ReportsController' => [
            'facility-report' => 'deny',
        ],
        'Application\\Controller\\SpiV6ReportsController' => [
            'facility-report' => 'allow',
        ],
    ],
    'DE' => [
        'Application\\Controller\\CommonController' => [
            'audit-locations' => 'allow',
        ],
        'Application\\Controller\\ConfigController' => [
            'index' => 'allow',
            'edit-global' => 'allow',
        ],
        'Application\\Controller\\IndexController' => [
            'index' => 'allow',
        ],
        'Application\\Controller\\DashboardController' => [
            'index' => 'deny',
            'audit-details' => 'deny',
        ],
        'Application\\Controller\\DashboardV6Controller' => [
            'index' => 'allow',
        ],
        'Application\\Controller\\DashboardV5Controller' => [
            'index' => 'deny',
        ],
        'Application\\Controller\\DistrictController' => [
            'index' => 'deny',
            'add' => 'deny',
            'edit' => 'deny',
        ],
        'Application\\Controller\\EmailController' => [
            'index' => 'allow',
            'email-v5' => 'deny',
        ],
        'Application\\Controller\\EventController' => [
            'index' => 'deny',
        ],
        'Application\\Controller\\FacilityController' => [
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'allow',
            'export-facility' => 'deny',
            'get-province-list' => 'deny',
            'get-facility-name' => 'allow',
            'upload-facility' => 'deny',
        ],
        'Application\\Controller\\ProvincesController' => [
            'index' => 'allow',
            'add' => 'deny',
            'edit' => 'deny',
        ],
        'Application\\Controller\\RolesController' => [
            'index' => 'allow',
            'add' => 'allow',
            'edit' => 'deny',
        ],
        'Application\\Controller\\SpiV5Controller' => [
            'index' => 'deny',
            'manage-facility' => 'deny',
            'approve-status' => 'deny',
            'corrective-action-pdf' => 'deny',
            'delete' => 'deny',
            'download-pdf' => 'deny',
            'download-files' => 'deny',
            'duplicate' => 'deny',
            'edit' => 'deny',
            'export' => 'deny',
            'view-bulk-downloads' => 'deny',
            'view-data-v5' => 'deny',
        ],
        'Application\\Controller\\SpiV6Controller' => [
            'index' => 'deny',
            'manage-facility' => 'deny',
            'approve-status' => 'deny',
            'corrective-action-pdf' => 'deny',
            'delete' => 'deny',
            'download-pdf' => 'deny',
            'download-files' => 'deny',
            'duplicate' => 'deny',
            'edit' => 'deny',
            'email-v6' => 'deny',
            'export' => 'deny',
            'view-bulk-downloads' => 'deny',
            'view-data-v6' => 'deny',
            'view-data-section-zero-v6' => 'deny',
        ],
        'Application\\Controller\\SpiV3Controller' => [
            'index' => 'allow',
            'approve-status' => 'allow',
            'corrective-action-pdf' => 'allow',
            'view-data' => 'deny',
            'delete' => 'allow',
            'download-files' => 'deny',
            'duplicate' => 'deny',
            'edit' => 'allow',
            'manage-facility' => 'allow',
            'download-pdf' => 'allow',
            'view-bulk-downloads' => 'deny',
        ],
        'Application\\Controller\\UserLoginHistoryController' => [
            'index' => 'allow',
        ],
        'Application\\Controller\\UsersController' => [
            'index' => 'allow',
            'add' => 'allow',
            'change-password' => 'allow',
            'profile' => 'allow',
            'edit' => 'allow',
        ],
        'Application\\Controller\\SpiV3ReportsController' => [
            'facility-report' => 'allow',
        ],
        'Application\\Controller\\SpiV5ReportsController' => [
            'facility-report' => 'deny',
        ],
        'Application\\Controller\\SpiV6ReportsController' => [
            'facility-report' => 'deny',
        ],
    ],
];
