"/SPI_RT/TESTSITE/FACILITY/info2:label": "PART A: CHARACTERISTICS OF THE FACILITY OR TESTING POINT AUDITED",                                          
    "/SPI_RT/PERSONAL/PER_G_1_8/PERSONAL_Q_1_8:label": "1.8 Have all testers been certified through a national certification program?",                                          
    "/SPI_RT/SAFETY/SAF_3_2/SAFETY_Q_3_2:label": "3.2 Are there SOPs and/or job aides in place to address accidental exposure to potentially infectious body fluids through a needle stick injury,                                           splash or other sharps injury?",                                          
    "/SPI_RT/SAFETY/SAF_3_6/SAFETY_Q_3_6:label": "3.6 Is there clean water and soap available for hand washing and is it consistently used?",                                          
    "/SPI_RT/SAFETY/SAF_3_8:label": ":",                                          
    "/SPI_RT/EQA/EQA_7_7/EQA_Q_7_7/1:label": "Yes",                                          
    "/SPI_RT/PRETEST/PRE_4_2/PRE_Q_4_2:label": "4.2 Is the national HIV testing algorithm(s) consistently being used at the testing site?",                                          
    "/SPI_RT/TEST/TEST_5_9/TEST_Q_5_9/0.5:label": "Partial",                                          
    "/SPI_RT/PRETEST/PRE_4_11:label": ":",                                          
    "/SPI_RT/EQA/EQA_7_6/EQA_Q_7_6/0.5:label": "Partial",                                          
    "/SPI_RT/SAFETY/SAF_3_5/SAFETY_Q_3_5/0.5:label": "Partial",                                          
    "/SPI_RT/info27:label": "Please summarize your finding and describe the corrective actions types,                                           the recommendations and timelines in next section.",                                          
    "/SPI_RT/EQA/EQA_7_6:label": ":",                                          
    "/SPI_RT/EQA/SAMPLEREF/EQA_7_14/EQA_Q_7_14/0.5:label": "Partial",                                          
    "/SPI_RT/POSTTEST/POST_6_6/POST_Q_6_6/1:label": "Yes",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_2/PHYSICAL_Q_2_2/0.5:label": "Partial",                                          
    "/SPI_RT/PERSONAL/PER_G_1_9/PERSONAL_Q_1_9:label": "1.9 Are only certified testers allowed to perform HIV testing?",                                          
    "/SPI_RT/SAFETY/SAFETYPHOTO:label": "Photo - Safety",                                          
    "/SPI_RT/correctiveaction:label": "Corrective Measures",                                          
    "/SPI_RT/correctiveaction/info27:hint": "Add another corrective action?",                                          
    "/SPI_RT/PRETEST/PRE_4_8/PRE_Q_4_8:label": "4.8 Is there a process in place for stock management?",                                          
    "/SPI_RT/PRETEST/PRE_4_6:label": ":",                                          
    "/SPI_RT/PRETEST/PRE_4_3:label": ":",                                          
    
    "/SPI_RT/lab_geopoint:label": "Collect the GPS coordinates of this site.",                                          
    "/SPI_RT/SUMMARY/info26:label": "Auditor Name:",                                          
    "/SPI_RT/PERSONAL/PER_G_1_4/PERSONAL_Q_1_4/1:label": "Yes",                                          
    "/SPI_RT/SAFETY/SAF_3_3/SAFETY_Q_3_3/0.5:label": "Partial",                                          
    "/SPI_RT/EQA/EQA_7_2/EQA_Q_7_2/1:label": "Yes",                                          
    "/SPI_RT/SAFETY/SAF_3_9/SAFETY_Q_3_9/0:label": "No",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_1/PHYSICAL_Q_2_1/1:label": "Yes",                                          
    "/SPI_RT/PRETEST/PRETEST_Display:hint": "Section Score = /12",                                          
    "/SPI_RT/EQA/SAMPLEREF/EQA_7_14:label": ":",                                          
    "/SPI_RT/POSTTEST/POST_6_1/POST_Q_6_1/0:label": "No",                                          
    "/SPI_RT/SAFETY/SAF_3_7/SAFETY_Q_3_7/1:label": "Yes",                                          
    "/SPI_RT/personincharge:label": "Person in Charge Name:",                                          
    "/SPI_RT/TEST/TEST_5_4/TEST_Q_5_4/1:label": "Yes",                                          
    "/SPI_RT/EQA/EQA_7_7/EQA_Q_7_7/0.5:label": "Partial",                                          
    "/SPI_RT/PRETEST/PRE_4_3/PRE_Q_4_3/0:label": "No",                                          
    "/SPI_RT/SAFETY/SAF_3_8/SAFETY_Q_3_8/0.5:label": "Partial",                                          
    "/SPI_RT/PHYSICAL/PHYSICALPHOTO:hint": "If needed,                                           please take photograph for evidence/corrective action",                                          
    "/SPI_RT/SAFETY/SAF_3_11/SAFETY_Q_3_11/0:label": "No",                                          
    "/SPI_RT/PRETEST/PRE_4_7/PRE_Q_4_7/1:label": "Yes",                                          
    "/SPI_RT/SAFETY/SAF_3_9/SAFETY_Q_3_9:label": "3.9 Are sharps,                                           infectious and non-infectious waste disposed of according to the segregation instructions?",                                          
    "/SPI_RT/PERSONAL/PER_G_1_8/PERSONAL_Q_1_8/0:label": "No",                                          
    "/SPI_RT/PERSONAL/PER_G_1_10/PERSONAL_Q_1_10/1:label": "Yes",                                          
    "/SPI_RT/TESTSITE/testingpointtype:hint": "Select One",                                          
    "/SPI_RT/TESTSITE/name_auditor2:hint": "Name of 2nd assessor if applicable",                                          
    "/SPI_RT/TESTSITE/level:hint": "Select One",                                          
    "/SPI_RT/EQA/EQA_DISPLAY:hint": "Section Score = /",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_1/PHYSICAL_C_2_1:label": "Comments",                                          
    
    "/SPI_RT/TESTSITE/testingpointtype/PostnatalConsultation:label": "Post-natal consultation",                                          
    "/SPI_RT/EQA/EQA_MAX_SCORE:hint": "Max Score of EQA",                                          
    "/SPI_RT/TEST/TEST_5_1:label": ":",                                          
    "/SPI_RT/EQA/EQA_7_1/EQA_C_7_1:label": "Comments",                                          
    "/SPI_RT/PRETEST/PRE_4_12/PRE_Q_4_12/0.5:label": "Partial",                                          
    "/SPI_RT/PRETEST/PRE_4_13/PRE_Q_4_13/0.5:label": "Partial",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_4/PHYSICAL_Q_2_4/1:label": "Yes",                                          
    "/SPI_RT/EQA/EQAPHOTO:hint": "If needed,                                           please take photograph for evidence/corrective action",                                          
    "/SPI_RT/TEST/TEST_5_5/TEST_Q_5_5/0:label": "No",                                          
    "/SPI_RT/PHYSICAL/PHYSICAL_SCORE:hint": "Assesment for Physical Facility",                                          
    "/SPI_RT/SPIRT/info4:hint": "For each of the sections listed below,                                           please check Yes,                                           Partial or No,                                           where applicable. Indicate “Yes” only when all elements are satisfactorily present. Provide comments for each “Partial” or “No” response.",                                          
    "/SPI_RT/PERSONAL/PER_G_1_1/PERSONAL_Q_1_1/1:label": "Yes",                                          
    "/SPI_RT/PERSONAL/PER_G_1_3/PERSONAL_Q_1_3:label": "1.3 Are the testers trained on external quality assessment (EQA) or proficiency testing (PT) process?",                                          
    "/SPI_RT/TEST/TEST_5_3/TEST_Q_5_3/0.5:label": "Partial",                                          
    "/SPI_RT/EQA/EQA_7_1/EQA_Q_7_1/1:label": "Yes",                                          
    "/SPI_RT/PRETEST/PRETEST_SCORE:hint": "Assesment for Pre-Testing Phase",                                          
    "/SPI_RT/SAFETY/SAF_3_2/SAFETY_C_3_2:label": "Comments",                                          
    "/SPI_RT/TESTSITE:label": "Testing Site Information",                                          
    "/SPI_RT/PERSONAL/PER_G_1_2/PERSONAL_Q_1_2:label": "1.2 Are the testers trained on the use of standardized HIV testing registers/logbooks?",                                          
    "/SPI_RT/SAFETY/SAF_3_4/SAFETY_Q_3_4:label": "3.4 Is personal protective equipment (PPE) always available to testers?",                                          
    "/SPI_RT/SAFETY/SAF_3_9/SAFETY_Q_3_9/1:label": "Yes",                                          
    "/SPI_RT/EQA/EQA_7_8/EQA_Q_7_8:label": "7.8 If testers need to be retrained,                                           are they being retrained during the supervisory visit?",                                          
    "/SPI_RT/EQA/EQA_7_3/EQA_Q_7_3/0.5:label": "Partial",                                          
    "/SPI_RT/PRETEST/PRE_4_10/PRE_C_4_10:label": "Comments",                                          
    "/SPI_RT/TESTSITE/affiliation/faith:label": "Faith-based Organization",                                          
    
    "/SPI_RT/SAFETY/SAF_3_5/SAFETY_Q_3_5:label": "3.5 Is PPE properly used by all testers consistently throughout the testing process?",                                          
    "/SPI_RT/auditorSignature:label": "Signature",                                          
    "/SPI_RT/EQA/EQA_7_1/EQA_Q_7_1:label": "7.1 Is the testing point enrolled in an EQA/PT program?",                                          
    "/SPI_RT/PERSONAL/PER_G_1_10/PERSONAL_Q_1_10/0:label": "No",                                          
    "/SPI_RT/EQA/EQA_OPT:hint": "Calculation of Opt fields",                                          
    "/SPI_RT/TEST/TEST_5_6/TEST_Q_5_6/1:label": "Yes",                                          
    "/SPI_RT/EQA/EQA_7_4:label": ":",                                          
    "/SPI_RT/TESTSITE/level_name:label": "Level () Name:",                                          
    "/SPI_RT/POSTTEST/POST_6_9/POST_Q_6_9/1:label": "Yes",                                          
    "/SPI_RT/EQA/SAMPLEREF/EQA_7_9:label": ":",                                          
    "/SPI_RT/SAFETY/SAF_3_10:label": ":",                                          
    "/SPI_RT/PERSONAL/PER_G_1_6/PERSONAL_Q_1_6/0:label": "No",                                          
    "/SPI_RT/PERSONAL/PER_G_1_9/PERSONAL_Q_1_9/0:label": "No",                                          
    "/SPI_RT/PERSONAL/PER_G_1_2/PERSONAL_Q_1_2/1:label": "Yes",                                          
    "/SPI_RT/TESTSITE/facilityid:label": "Testing Facility ID (if applicable)",                                          
    "/SPI_RT/TEST/TEST_5_3/TEST_C_5_3:label": "Comments",                                          
    "/SPI_RT/SUMMARY_NOT_AVL:label": "SUMMARY - Sorry You have not completed all required sections.",                                          
    "/SPI_RT/EQA/EQA_7_4/EQA_C_7_4:label": "Comments",                                          
    "/SPI_RT/SAFETY/SAF_3_2/SAFETY_Q_3_2/1:label": "Yes",                                          
    "/SPI_RT/SAFETY/SAF_3_6/SAFETY_Q_3_6/1:label": "Yes",                                          
    "/SPI_RT/PRETEST/PRE_4_4:label": ":",                                          
    "/SPI_RT/correctiveaction:hint": "List All Corrective Actions",                                          
    "/SPI_RT/SAFETY/SAF_3_9:label": ":",                                          
    "/SPI_RT/POSTTEST/POST_6_7/POST_Q_6_7/0.5:label": "Partial",                                          
    "/SPI_RT/SAFETY/SAF_3_1:label": ":",                                          
    "/SPI_RT/EQA/EQA_7_6/EQA_Q_7_6:label": "7.6 Does the testing point receive periodic supervisory visits?",                                          
    "/SPI_RT/EQA/EQA_DISPLAY:label": "7.0 EXTERNAL QUALITY AUDIT (PROFICIENCY TESTING/EQA AND SITE SUPERVISION) SCORE",                                          
    "/SPI_RT/PRETEST/PRE_4_12/PRE_Q_4_12:label": "4.12 Are there SOPs and/or job aides describing how client identification should be recorded in the HIV testing register?",                                          
    "/SPI_RT/PRETEST/PRE_4_13/PRE_Q_4_13:label": "4.13 Are client identifiers recorded in the HIV testing register and on test devices per SOPs and/or job aide?",                                          
    "/SPI_RT/PRETEST/PRE_4_12:label": ":",                                          
    "/SPI_RT/PRETEST/PRE_4_13:label": ":",                                          
    "/SPI_RT/TEST/TEST_5_7:label": ":",                                          
    "/SPI_RT/POSTTEST/POST_6_4/POST_Q_6_4:label": "6.4 Are invalid test results recorded properly in the register/logbook?",                                          
    "/SPI_RT/TEST/TEST_5_5/TEST_Q_5_5:label": "5.5 Are positive and negative quality control (QC) specimens routinely used (e.g.,                                           daily or weekly) according to country guidelines?",                                          
    "/SPI_RT/TESTSITE/testingpointtype/PITC:label": "PITC",                                          
    "/SPI_RT/TESTSITE/affiliation:hint": "Select One",                                          
    "/SPI_RT/EQA/EQA_7_6/EQA_Q_7_6/0:label": "No",                                          
    "/SPI_RT/TESTSITE/name_auditor_lead:label": "Name of the Auditor 1:",                                          
    "/SPI_RT/EQA/EQA_7_4/EQA_Q_7_4/1:label": "Yes",                                          
    
    "/SPI_RT/POSTTEST/POST_6_7/POST_Q_6_7:label": "6.7 Are all client documents and records securely kept throughout all phases of the testing process?",                                          
    "/SPI_RT/EQA/EQA_7_2/EQA_Q_7_2/0:label": "No",                                          
    "/SPI_RT/PERSONAL/PERSONAL_Display:label": "1.0 PERSONNEL TRAINING AND CERTIFICATION SCORE",                                          
    "/SPI_RT/EQA/SAMPLEREF/EQA_7_12:label": ":",                                          
    "/SPI_RT/TEST/TEST_SCORE:hint": "Assesment for Testing Phase",                                          
    "/SPI_RT/PERSONAL/PER_G_1_5/PERSONAL_Q_1_5/0:label": "No",                                          
    "/SPI_RT/EQA/SAMPLEREF/EQA_7_11/EQA_C_7_11:label": "Comments",                                          
    "/SPI_RT/SAFETY/SAF_3_11:label": ":",                                          
    "/SPI_RT/PRETEST/PRE_4_7/PRE_Q_4_7:label": "4.7 Are all required test kit components (i.e. test device,                                           buffer,                                           sample collection device,                                           etc.) and supplies available prior to testing?",                                          
    "/SPI_RT/SAFETY/SAF_3_4/SAFETY_C_3_4:label": "Comments",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_3:label": ":",                                          
    "/SPI_RT/correctiveaction/timeline:label": "Recommendations - Timeline / Person responsible :",                                          
    "/SPI_RT/TEST/TEST_5_6/TEST_Q_5_6:label": "5.6 Are QC results properly recorded?",                                          
    "/SPI_RT/PRETEST/PRE_4_1:label": ":",                                          
    "/SPI_RT/TEST/TEST_5_6/TEST_Q_5_6/0.5:label": "Partial",                                          
    "/SPI_RT/POSTTEST/POST_6_5/POST_C_6_5:label": "Comments",                                          
    "/SPI_RT/correctiveaction/deficiency:label": "Deficiency/Issue observed :",                                          
    "/SPI_RT/correctiveaction/correction/Immediate:label": "Immediate",                                          
    "/SPI_RT/correctiveaction/correction:label": "Correction Actions :",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_2:label": ":",                                          
    "/SPI_RT/POSTTEST/POST_6_8/POST_Q_6_8/0:label": "No",                                          
    "/SPI_RT/PERSONAL/PER_G_1_5/PERSONAL_C_1_5:label": "Comments",                                          
    "/SPI_RT/POSTTEST/POST_6_5/POST_Q_6_5:label": "6.5 Are appropriate steps taken and documented when a result is invalid?",                                          
    
    "/SPI_RT/PHYSICAL/PHY_G_2_3/PHYSICAL_Q_2_3/0.5:label": "Partial",                                          
    "/SPI_RT/PRETEST/PRETESTPHOTO:label": "Photo - Pre-Testing",                                          
    "/SPI_RT/SAFETY/SAF_3_7:label": ":",                                          
    "/SPI_RT/EQA/EQA_7_7/EQA_C_7_7:label": "Comments",                                          
    "/SPI_RT/PERSONAL/PERSONAL_SCORE:hint": "Assesment for Personal Training & Sertification",                                          
    "/SPI_RT/POSTTEST/POST_6_3:label": ":",                                          
    "/SPI_RT/EQA/EQA_7_2:label": ":",                                          
    "/SPI_RT/POSTTEST/POST_6_8/POST_C_6_8:label": "Comments",                                          
    "/SPI_RT/PRETEST/PRE_4_9/PRE_Q_4_9/0:label": "No",                                          
    "/SPI_RT/EQA/EQA_REQ:hint": "Calculation of Required fields",                                          
    "/SPI_RT/EQA/EQA_7_3/EQA_Q_7_3:label": "7.3 Does the person in charge at the testing point review the EQA/PT results before submission to NRL or designee?",                                          
    "/SPI_RT/endofsurvey:label": "You have completed all questions for SPI-RT Checklist.",                                          
    "/SPI_RT/TESTSITE/testingpointtype/PMTCT:label": "PMTCT",                                          
    
    "/SPI_RT/POSTTEST/POST_6_3/POST_Q_6_3/0.5:label": "Partial",                                          
    "/SPI_RT/TESTSITE/level_name:hint": "Specify Level Name",                                          
    "/SPI_RT/TESTSITE/testingpointtype/Laboratory:label": "Laboratory",                                          
    "/SPI_RT/SUMMARY/info22:label": "Level 1 - 40% - 59%",                                          
    "/SPI_RT/PHYSICAL/PHYSICAL_Display:label": "2.0 PHYSICAL FACILITY SCORE",                                          
    "/SPI_RT/PERSONAL/PER_G_1_4/PERSONAL_Q_1_4/0:label": "No",                                          
    "/SPI_RT/TESTSITE/name_auditor2:label": "Name of the Auditor 2:",                                          
    "/SPI_RT/TESTSITE/clients_tested_hiv:label": "Number of clients tested for HIV:",                                          
    "/SPI_RT/TESTSITE/per_month:label": "Per Month:",                                          
    "/SPI_RT/TESTSITE/per_quarter:label": "Per Quarter:",                                          

    "/SPI_RT/TESTSITE/new_hiv:label": "Number of newly identified HIV positives:",                                          
    "/SPI_RT/TESTSITE/per_month:label": "Per Month:",                                          
    "/SPI_RT/TESTSITE/per_quarter:label": "Per Quarter:",                                          

    "/SPI_RT/TESTSITE/hiv_negative:label": "Number of HIV negatives:",                                          
    "/SPI_RT/TESTSITE/per_month:label": "Per Month:",                                          
    "/SPI_RT/TESTSITE/per_quarter:label": "Per Quarter:",                                          


    "/SPI_RT/TESTSITE/newly_identified_positives:label": "Number of newly identified HIV positives tested by RTRI :",                                          
    "/SPI_RT/TESTSITE/per_month:label": "Per Month:",                                          
    "/SPI_RT/TESTSITE/per_quarter:label": "Per Quarter:",                                          

    "/SPI_RT/TESTSITE/recent_identified_positives:label": "Number of  Recent by RTRI or RITA :",                                          
    "/SPI_RT/TESTSITE/per_month:label": "Per Month:",                                          
    "/SPI_RT/TESTSITE/per_quarter:label": "Per Quarter:",                                          
    
    "/SPI_RT/POSTTEST/POST_SCORE:hint": "Assesment for Post Testing Phase",                                          
    "/SPI_RT/PERSONAL/PER_G_1_10/PERSONAL_C_1_10:label": "Comments",                                          
    "/SPI_RT/PRETEST/PRE_4_5/PRE_Q_4_5/0.5:label": "Partial",                                          
    "/SPI_RT/PHYSICAL:label": "2.0 PHYSICAL FACILITY - (Max Score 5)",                                          
    "/SPI_RT/scoring:label": "SCORING_CRITERIA",                                          
    "/SPI_RT/PERSONAL/PER_G_1_2/PERSONAL_Q_1_2/0.5:label": "Partial",                                          
    "/SPI_RT/PRETEST/PRE_4_6/PRE_Q_4_6:label": "4.6 Are all the test kits currently in use within the expiration date?",                                          
    "/SPI_RT/TESTSITE/testingpointtype/MedicalCheck:label": "Medical check",                                          
    "/SPI_RT/SAFETY/SAF_3_9/SAFETY_Q_3_9/0.5:label": "Partial",                                          
    
    "/SPI_RT/TESTSITE/auditroundno:label": "Audit Round No.:",                                          
    "/SPI_RT/SAFETY/SAF_3_4/SAFETY_Q_3_4/1:label": "Yes",                                          
    "/SPI_RT/TESTSITE/level/Dispensary:label": "Dispensary",                                          
    "/SPI_RT/EQA/EQA_7_2/EQA_C_7_2:label": "Comments",                                          
    "/SPI_RT/TEST/TEST_5_9/TEST_Q_5_9/0:label": "No",                                          
    "/SPI_RT/PERSONAL/PERSONAL_Display:hint": "Section Score = /10",                                          
    "/SPI_RT/SAFETY:label": "3.0 SAFETY - (Max Score - 10)",                                          
    "/SPI_RT/EQA/EQA_7_5/EQA_Q_7_5:label": "7.5 Does the testing point implement corrective action in case of unsatisfactory results?",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_1:label": ":",                                          
    "/SPI_RT/PRETEST/PRE_4_9/PRE_Q_4_9/0.5:label": "Partial",                                          
    "/SPI_RT/TESTSITE/FACILITY/info2:hint": "Before completing the checklist,                                           it is important to characterize the testing point to be audited. Please provide relevant information:",                                          
    "/SPI_RT/TESTSITE/locationaddress:label": "Location Address:",                                          
    "/SPI_RT/PERSONAL/PER_G_1_5/PERSONAL_Q_1_5/0.5:label": "Partial",                                          
    
    "/SPI_RT/TESTSITE/level:label": "Level:",                                          
    "/SPI_RT/PRETEST/PRE_4_5/PRE_Q_4_5:label": "4.5 Are only nationally approved HIV rapid test kits available for use?",                                          
    "/SPI_RT/PRETEST/PRE_4_9/PRE_Q_4_9/1:label": "Yes",                                          
    "/SPI_RT/SAFETY/SAF_3_7/SAFETY_C_3_7:label": "Comments",                                          
    "/SPI_RT/PERSONAL/PER_G_1_5/PERSONAL_Q_1_5/1:label": "Yes",                                          
    "/SPI_RT/PERSONAL/PER_G_1_10:label": ":",                                          
    "/SPI_RT/TESTSITE/testingpointtype/BloodBank:label": "Blood Bank",                                          
    "/SPI_RT/TEST/TEST_5_2:label": ":",                                          
    "/SPI_RT/TEST/TEST_5_1/TEST_Q_5_1/0.5:label": "Partial",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_1/PHYSICAL_Q_2_1:label": "2.1 Is there a designated area for HIV testing?",                                          
    "/SPI_RT/TEST/TEST_5_7/TEST_C_5_7:label": "Comments",                                          
    "/SPI_RT/TEST/TESTPHOTO:hint": "If needed,                                           please take photograph for evidence/corrective action",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_5/PHYSICAL_C_2_5:label": "Comments",                                          
    "/SPI_RT/PERSONAL/PER_G_1_8/PERSONAL_Q_1_8/1:label": "Yes",                                          
    "/SPI_RT/PERSONAL/PER_G_1_6/PERSONAL_Q_1_6:label": "1.6 Have all testers received a refresher training within the last two years?",                                          
    "/SPI_RT/PERSONAL/PER_G_1_7:label": ":",                                          
    "/SPI_RT/PERSONAL/PER_G_1_6:label": ":",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_5:label": ":",                                          
    "/SPI_RT/PRETEST/PRE_4_6/PRE_Q_4_6/0:label": "No",                                          
    "/SPI_RT/PRETEST/PRE_4_11/PRE_C_4_11:label": "Comments",                                          
    "/SPI_RT/EQA/EQA_7_8/EQA_Q_7_8/1:label": "Yes",                                          
    "/SPI_RT/POSTTEST/POSTTESTPHOTO:label": "Photo -Post Testing",                                          
    "/SPI_RT/PERSONAL/PER_G_1_3:label": ":",                                          
    "/SPI_RT/EQA/EQA_7_5/EQA_Q_7_5/0.5:label": "Partial",                                          
    
    "/SPI_RT/PHYSICAL/PHY_G_2_4:label": ":",                                          
    "/SPI_RT/TEST/TEST_5_4/TEST_Q_5_4/0:label": "No",                                          
    "/SPI_RT/PERSONAL/PER_G_1_9/PERSONAL_C_1_9:label": "Comments",                                          
    "/SPI_RT/TEST:label": "5.0 TESTING PHASE - (Max Score 9)",                                          
    "/SPI_RT/TESTSITE/testingpointtype/TB:label": "TB clinic",                                          
    "/SPI_RT/SAFETY/SAF_3_10/SAFETY_Q_3_10/0.5:label": "Partial",                                          
    "/SPI_RT/SAFETY/SAF_3_1/SAFETY_Q_3_1/0:label": "No",                                          
    "/SPI_RT/PRETEST/PRE_4_11/PRE_Q_4_11/0.5:label": "Partial",                                          
    "/SPI_RT/SAFETY/SAF_3_11/SAFETY_C_3_11:label": "Comments",                                          
    "/SPI_RT/SAFETY/SAF_3_5/SAFETY_C_3_5:label": "Comments",                                          
    "/SPI_RT/PRETEST/PRE_4_11/PRE_Q_4_11/1:label": "Yes",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_3/PHYSICAL_Q_2_3:label": "2.3 Is sufficient lighting available in the designated testing area?",                                          
    "/SPI_RT/TEST/TEST_5_8/TEST_Q_5_8/1:label": "Yes",                                          
    "/SPI_RT/PRETEST/PRE_4_5:label": ":",                                          
    "/SPI_RT/TEST/TEST_5_1/TEST_Q_5_1/1:label": "Yes",                                          
    "/SPI_RT/POSTTEST/POST_6_9/POST_Q_6_9/0:label": "No",                                          
    "/SPI_RT/SAFETY/SAF_3_8/SAFETY_Q_3_8/1:label": "Yes",                                          
    "/SPI_RT/EQA/sampleretesting:label": "If the country has implemented HIV-1 Recent Infection Surveillance and the testing site is performing the Rapid Test for Recent Infection (RTRI)",                                          
    "/SPI_RT/SAFETY/SAF_3_4/SAFETY_Q_3_4/0:label": "No",                                          
    "/SPI_RT/PERSONAL/PER_G_1_7/PERSONAL_Q_1_7/0.5:label": "Partial",                                          
    "/SPI_RT/EQA/EQA_7_8:label": ":",                                          
    "/SPI_RT/EQA/EQA_7_1/EQA_Q_7_1/0.5:label": "Partial",                                          
    "/SPI_RT/TEST/TEST_5_1/TEST_C_5_1:label": "Comments",                                          
    
    "/SPI_RT/POSTTEST/POST_6_3/POST_Q_6_3/0:label": "No",                                          
    "/SPI_RT/PERSONAL/PER_G_1_1:label": ":",                                          
    "/SPI_RT/SAFETY/SAF_3_11/SAFETY_Q_3_11/0.5:label": "Partial",                                          
    "/SPI_RT/POSTTEST/POST_6_4:label": ":",                                          
    "/SPI_RT/EQA/EQA_7_1:label": ":",                                          
    "/SPI_RT/scoring/info10:label": "Total points scored for each section should be tallied and recorded at the end of the section.",                                          
    "/SPI_RT/SAFETY/SAF_3_8/SAFETY_Q_3_8:label": "3.8 Is the disinfectant solution available properly labeled with content,                                           date of preparation and date of expiration?",                                          
    "/SPI_RT/TESTSITE/testingpointtype/AntenatalConsultation:label": "Antenatal consultation",                                          
    "/SPI_RT/POSTTEST/POST_6_1/POST_C_6_1:label": "Comments",                                          
    "/SPI_RT/POSTTEST/POST_6_4/POST_Q_6_4/0:label": "No",                                          
    "/SPI_RT/EQA/EQA_7_5:label": ":",                                          
    "/SPI_RT/PRETEST/PRE_4_4/PRE_Q_4_4/0:label": "No",                                          
    "/SPI_RT/TEST/TESTPHOTO:label": "Photo -Testing",                                          
    "/SPI_RT/POSTTEST/POST_6_2/POST_Q_6_2/0.5:label": "Partial",                                          
    "/SPI_RT/EQA/EQA_7_7/EQA_Q_7_7/0:label": "No",                                          
    "/SPI_RT/PRETEST/PRE_4_6/PRE_C_4_6:label": "Comments",                                          
    "/SPI_RT/SAFETY/SAF_3_3/SAFETY_Q_3_3/1:label": "Yes",                                          
    "/SPI_RT/EQA/EQA_7_7:label": ":",                                          
    "/SPI_RT/sitephoto:hint": "Picture of Facility/Testing Point",                                          
    "/SPI_RT/TESTSITE/testingpointtype/MedicineCheckConsultation:label": "Medicine Check (consultation)",                                          
    "/SPI_RT/PRETEST/PRE_4_2/PRE_Q_4_2/1:label": "Yes",                                          
    "/SPI_RT/PRETEST/PRE_4_7:label": ":",                                          
    "/SPI_RT/POSTTEST/POST_6_5/POST_Q_6_5/1:label": "Yes",                                          
    "/SPI_RT/POSTTEST/POST_6_6/POST_Q_6_6/0.5:label": "Partial",                                          
    "/SPI_RT/TESTSITE/level/ReferralCenter:label": "Referral Center",                                          
    
    "/SPI_RT/SAFETY/SAFETY_DISPLAY:label": "3.0 SAFETY SCORE",                                          
    "/SPI_RT/PERSONAL/PERSONALPHOTO:hint": "If needed,                                           please take photograph for evidence/corrective action",                                          
    "/SPI_RT/SAFETY/SAF_3_7/SAFETY_Q_3_7/0.5:label": "Partial",                                          
    "/SPI_RT/PERSONAL/PER_G_1_6/PERSONAL_Q_1_6/0.5:label": "Partial",                                          
    "/SPI_RT/POSTTEST/POST_6_2/POST_C_6_2:label": "Comments",                                          
    "/SPI_RT/TEST/TEST_5_5:label": ":",                                          
    "/SPI_RT/POSTTEST/POST_6_8/POST_Q_6_8/0.5:label": "Partial",                                          
    "/SPI_RT/EQA/SAMPLEREF/EQA_7_13:label": ":",                                          
    "/SPI_RT/POSTTEST/POST_6_4/POST_C_6_4:label": "Comments",                                          
    "/SPI_RT/TEST/TEST_5_4/TEST_Q_5_4:label": "5.4 Are testing procedures adequately followed?",                                          
    "/SPI_RT/EQA:label": "7.0  EXTERNAL QUALITY AUDIT (PROFICIENCY TESTING/EQA AND SITE SUPERVISION) - (Max Score 8 )",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_4/PHYSICAL_Q_2_4:label": "2.4  Are the test kits stored according to manufacturers’ instructions?",                                          
    "/SPI_RT/PRETEST/PRE_4_5/PRE_Q_4_5/0:label": "No",                                          
    "/SPI_RT/PRETEST/PRE_4_7/PRE_Q_4_7/0.5:label": "Partial",                                          
    "/SPI_RT/EQA/EQA_7_3/EQA_Q_7_3/1:label": "Yes",                                          
    "/SPI_RT/EQA/EQA_7_3/EQA_Q_7_3/0:label": "No",                                          
    "/SPI_RT/EQA/SAMPLEREF:label": "Retesting - serum or DBS",                                          
    "/SPI_RT/SAFETY/SAF_3_3/SAFETY_C_3_3:label": "Comments",                                          
    "/SPI_RT/scoring/info5:label": "PART C: SCORING CRITERIA",                                          
    "/SPI_RT/TEST/TEST_5_2/TEST_Q_5_2/0.5:label": "Partial",                                          
    "/SPI_RT/SAFETY/SAF_3_11/SAFETY_Q_3_11/1:label": "Yes",                                          
    "/SPI_RT/SAFETY/SAF_3_10/SAFETY_Q_3_10/1:label": "Yes",                                          
    "/SPI_RT/PERSONAL/PER_G_1_7/PERSONAL_Q_1_7/1:label": "Yes",                                          
    "/SPI_RT/POSTTEST/POST_6_4/POST_Q_6_4/1:label": "Yes",                                          
    
    "/SPI_RT/TEST/TEST_5_2/TEST_C_5_2:label": "Comments",                                          
    "/SPI_RT/sitephoto:label": "Site Photo",                                          
    "/SPI_RT/correctiveaction/sectionno:label": "Section No. :",                                          
    "/SPI_RT/PRETEST/PRE_4_1/PRE_Q_4_1:label": "4.1 Are there national HIV testing guidelines available at the testing point?",                                          
    "/SPI_RT/TESTSITE/level/region:label": "Region/Province/Zone",                                          
    "/SPI_RT/PRETEST/PRE_4_2/PRE_Q_4_2:hint": "-",                                          
    "/SPI_RT/TEST/TEST_5_8/TEST_C_5_8:label": "Comments",                                          
    "/SPI_RT/POSTTEST/POST_6_2/POST_Q_6_2/0:label": "No",                                          
    "/SPI_RT/PERSONAL/PER_G_1_7/PERSONAL_C_1_7:label": "Comments",                                          
    "/SPI_RT/PERSONAL/PERSONALPHOTO:label": "Photo - Personal Training and Certification",                                          
    "/SPI_RT/PERSONAL/PER_G_1_9/PERSONAL_Q_1_9/0.5:label": "Partial",                                          
    "/SPI_RT/EQA/EQA_7_3:label": ":",                                          
    "/SPI_RT/TESTSITE/testingpointtype/YouthCons:label": "Adolescent and youth counseling services",                                          
    "/SPI_RT/TESTSITE/level/HealthCenter:label": "Health Center",                                          
    "/SPI_RT/POSTTEST/POST_6_9/POST_Q_6_9:label": "6.9 Are registers/logbooks properly labeled and archived when full?",                                          
    "/SPI_RT/SUMMARY/info24:label": "Level 3 - 80%-89%",                                          
    "/SPI_RT/SUMMARY/info21:label": "Level 0 - Less than 40%",                                          
    "/SPI_RT/SUMMARY:label": "SUMMARY",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_2/PHYSICAL_Q_2_2/1:label": "Yes",                                          
    "/SPI_RT/TEST/TEST_5_1/TEST_Q_5_1:label": "5.1 Are SOPs and/or job aides on HIV testing procedures and the national testing algorithm being referred to and followed during testing?",                                          
    "/SPI_RT/PERSONAL/PER_G_1_7/PERSONAL_Q_1_7:label": "1.7 Are there records indicating all testers have demonstrated competency in HIV rapid testing prior to client testing?",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_4/PHYSICAL_Q_2_4/0.5:label": "Partial",                                          
    "/SPI_RT/PRETEST/PRE_4_1/PRE_Q_4_1/1:label": "Yes",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_2/PHYSICAL_Q_2_2/0:label": "No",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_1/PHYSICAL_Q_2_1/0:label": "No",                                          
    "/SPI_RT/PRETEST/PRE_4_12/PRE_C_4_12:label": "Comments",                                          
    
    "/SPI_RT/PRETEST/PRE_4_13/PRE_C_4_13:label": "Comments",                                          
    "/SPI_RT/PERSONAL/PER_G_1_9/PERSONAL_Q_1_9/1:label": "Yes",                                          
    "/SPI_RT/PERSONAL/PER_G_1_2/PERSONAL_C_1_2:label": "Comments",                                          
    "/SPI_RT/TEST/TEST_5_4:label": ":",                                          
    "/SPI_RT/POSTTEST/POST_DISPLAY:hint": "Section Score = /9",                                          
    "/SPI_RT/EQA/EQA_7_2/EQA_Q_7_2:label": "7.2 Do all testers at the testing point test the EQA/PT samples?",                                          
    "/SPI_RT/PRETEST/PRE_4_8/PRE_C_4_8:label": "Comments",                                          
    "/SPI_RT/PERSONAL/PER_G_1_1/PERSONAL_C_1_1:label": "Comments",                                          
    "/SPI_RT/PERSONAL/PER_G_1_10/PERSONAL_Q_1_10/0.5:label": "Partial",                                          
    "/SPI_RT/SAFETY/SAF_3_2/SAFETY_Q_3_2/0:label": "No",                                          
    "/SPI_RT/POSTTEST/POST_6_8/POST_Q_6_8:label": "6.8 Are all registers/logbooks and other documents kept in a secure location when not in use?",                                          
    "/SPI_RT/correctiveaction:label": "Corrective Actions",                                          
    "/SPI_RT/TEST/TEST_5_2/TEST_Q_5_2/1:label": "Yes",                                          
    "/SPI_RT/PERSONAL/PER_G_1_2/PERSONAL_Q_1_2/0:label": "No",                                          
    "/SPI_RT/POSTTEST/POST_6_8/POST_Q_6_8/1:label": "Yes",                                          
    "/SPI_RT/POSTTEST/POST_6_6/POST_C_6_6:label": "Comments",                                          
    "/SPI_RT/SAFETY/SAF_3_8/SAFETY_Q_3_8/0:label": "No",                                          
    "/SPI_RT/TEST/TEST_5_8:label": ":",                                          
    "/SPI_RT/PERSONAL/PER_G_1_9:label": ":",                                          
    "/SPI_RT/POSTTEST/POST_6_3/POST_C_6_3:label": "Comments",                                          
    "/SPI_RT/TEST/TEST_5_4/TEST_C_5_4:label": "Comments",                                          
    "/SPI_RT/PERSONAL/PER_G_1_4/PERSONAL_Q_1_4:label": "1.4 Are the testers trained on quality control (QC) process?",                                          
    "/SPI_RT/TEST/TEST_5_8/TEST_Q_5_8/0:label": "No",                                          
    "/SPI_RT/SAFETY/SAF_3_6/SAFETY_C_3_6:label": "Comments",                                          
    "/SPI_RT/POSTTEST/POST_6_7/POST_C_6_7:label": "Comments",                                          
    "/SPI_RT/POSTTEST/POST_6_9:label": ":",                                          
    "/SPI_RT/POSTTEST/POST_6_1/POST_Q_6_1:label": "6.1 Is there a national standardized HIV rapid testing register/logbook that includes all of the key quality elements available and in use?",                                          
    "/SPI_RT/POSTTEST/POST_6_7/POST_Q_6_7/0:label": "No",                                          
    "/SPI_RT/EQA/sampleretesting/Yes:label": "Yes",                                          
    "/SPI_RT/PRETEST/PRE_4_4/PRE_Q_4_4/1:label": "Yes",                                          
    "/SPI_RT/SAFETY/SAF_3_7/SAFETY_Q_3_7/0:label": "No",                                          
    "/SPI_RT/PERSONAL/PER_G_1_3/PERSONAL_Q_1_3/0.5:label": "Partial",                                          
    "/SPI_RT/EQA/EQA_7_8/EQA_C_7_8:label": "Comments",                                          
    "/SPI_RT/SAFETY/SAF_3_8/SAFETY_C_3_8:label": "Comments",                                          
    "/SPI_RT/PRETEST/PRE_4_8/PRE_Q_4_8/0.5:label": "Partial",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_3/PHYSICAL_Q_2_3/1:label": "Yes",                                          
    "/SPI_RT/SAFETY/SAF_3_6:label": ":",                                          
    "/SPI_RT/PRETEST/PRE_4_11/PRE_Q_4_11/0:label": "No",                                          
    "/SPI_RT/TEST/TEST_5_9:label": ":",                                          
    "/SPI_RT/TESTSITE/testingpointtype/ObstetricClinic:label": "Obstetric clinic",                                          
    "/SPI_RT/POSTTEST/POSTTESTPHOTO:hint": "If needed,                                           please take photograph for evidence/corrective action",                                          
    "/SPI_RT/TESTSITE/FACILITY:label": "Facility Information",                                          
    "/SPI_RT/subscriberid:label": "Label",                                          
    "/SPI_RT/EQA/EQA_7_6/EQA_C_7_6:label": "Comments",                                          
    "/SPI_RT/TESTSITE/assesmentofaudit:label": "Date of Audit:",                                          
    "/SPI_RT/TEST/TEST_5_9/TEST_Q_5_9/1:label": "Yes",                                          
    "/SPI_RT/SUMMARY/info12:label": "Part D. Auditor’s Summation Report for SPI-RT Audit\n\nFacility Name: \nAuditor Name:\nTesting Point Name: Type of testing point:\nStaff Audited Name: No. of Tester(s):",                                          
    "/SPI_RT/PRETEST/PRE_4_1/PRE_Q_4_1/0:label": "No",                                          
    "/SPI_RT/PRETEST/PRE_4_12/PRE_Q_4_12/1:label": "Yes",                                          
    "/SPI_RT/PRETEST/PRE_4_13/PRE_Q_4_13/1:label": "Yes",                                          
    "/SPI_RT/PERSONAL/PER_G_1_5:label": ":",                                          
    "/SPI_RT/EQA/SAMPLEREF/EQA_7_9/EQA_C_7_9:label": "Comments",                                          
   
    "/SPI_RT/TESTSITE/affiliation:label": "Affiliation :",                                          
    "/SPI_RT/TEST/TEST_DISPLAY:hint": "Section Score = /9",                                          
    "/SPI_RT/PERSONAL/PER_G_1_5/PERSONAL_Q_1_5:label": "1.5 Are the testers trained on safety and waste management procedures and practices?",                                          
    "/SPI_RT/PERSONAL/PER_G_1_2:label": ":",                                          
    "/SPI_RT/PRETEST/PRE_4_11/PRE_Q_4_11:label": "4.11 Are there sufficient supplies available for finger prick or venous blood collection (i.e. lancet,                                           gauze,                                           alcohol swab,                                           etc.)?",                                          
    "/SPI_RT/PRETEST/PRE_4_7/PRE_C_4_7:label": "Comments",                                          
    "/SPI_RT/EQA/SAMPLEREF/EQA_7_10:label": ":",                                          
    "/SPI_RT/correctiveaction/info27:label": "Please add more corrective action if needed.",                                          
    "/SPI_RT/SAFETY/SAF_3_9/SAFETY_C_3_9:label": "Comments",                                          
    "/SPI_RT/PRETEST/PRE_4_9/PRE_Q_4_9:label": "4.9 Is there a documented inventory system in place at the testing point for test kits received (i.e. who received them,                                           date of receipt,                                           etc.)?",                                          
    "/SPI_RT/SUMMARY/info23:label": "Level 2 - 60%-79%",                                          
    "/SPI_RT/PRETEST/PRE_4_8/PRE_Q_4_8/0:label": "No",                                          
    "/SPI_RT/POSTTEST/POST_6_6:label": ":",                                          
    "/SPI_RT/PRETEST/PRE_4_3/PRE_C_4_3:label": "Comments",                                          
    "/SPI_RT/SPIRT/info4:label": "PART B. SPI - RRT Checklist",                                          
    "/SPI_RT/POSTTEST/POST_6_2/POST_Q_6_2:label": "6.2 Are all the elements in the register/ logbook recorded/captured correctly?  (e.g.,                                           client demographics,                                           kit names,                                           lot numbers,                                           expiration dates,                                           tester name,                                           individual and final HIV results,                                           etc.)?",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_5/PHYSICAL_Q_2_5:label": "2.5 Is there sufficient and secure storage space for test kits and other consumables?",                                          
    "/SPI_RT/TEST/TEST_5_3/TEST_Q_5_3/0:label": "No",                                          
    "/SPI_RT/TEST/TEST_5_6/TEST_Q_5_6/0:label": "No",                                          
    "/SPI_RT/TEST/TEST_5_8/TEST_Q_5_8:label": "5.8 Are appropriate steps taken and documented when QC results are incorrect and/or invalid?",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_2/PHYSICAL_Q_2_2:label": "2.2 Is the testing area clean and organized for HIV rapid testing?",                                          
    "/SPI_RT/TESTSITE/NumberofTester:label": "Number of Testers:",                                          
    "/SPI_RT/PRETEST/PRE_4_5/PRE_C_4_5:label": "Comments",                                          
    "/SPI_RT/POSTTEST/POST_6_5/POST_Q_6_5/0.5:label": "Partial",                                          
    "/SPI_RT/POSTTEST/POST_6_5:label": ":",                                          
    "/SPI_RT/SAFETY/SAF_3_7/SAFETY_Q_3_7:label": "3.7 Is there an appropriate disinfectant to clean the work area available?",                                          
    "/SPI_RT/PERSONAL/PER_G_1_7/PERSONAL_Q_1_7/0:label": "No",                                          
    "/SPI_RT/SPIRT:label": "SPI -RT - Checklist",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_4/PHYSICAL_C_2_4:label": "Comments",                                          
    "/SPI_RT/POSTTEST/POST_6_7/POST_Q_6_7/1:label": "Yes",                                          
    "/SPI_RT/POSTTEST/POST_6_3/POST_Q_6_3/1:label": "Yes",                                          
    "/SPI_RT/TEST/TEST_5_5/TEST_Q_5_5/0.5:label": "Partial",                                          
    "/SPI_RT/POSTTEST/POST_6_1/POST_Q_6_1/0.5:label": "Partial",                                          
    "/SPI_RT/PRETEST/PRE_4_2/PRE_Q_4_2/0:label": "No",                                          
    "/SPI_RT/SAFETY/SAF_3_1/SAFETY_Q_3_1:label": "3.1 Are there SOPs and/or job aides in place to implement safety practices?",                                          
    "/SPI_RT/EQA/SAMPLEREF/EQA_7_14/EQA_C_7_14:label": "Comments",                                          
    "/SPI_RT/PRETEST/PRE_4_2/PRE_C_4_2:label": "Comments",                                          
    "/SPI_RT/text_image:label": "SPI -RT Checklist Version 3.0",                                          
    "/SPI_RT/PERSONAL/PER_G_1_4:label": ":",                                          
    "/SPI_RT/PRETEST/PRE_4_12/PRE_Q_4_12/0:label": "No",                                          
    "/SPI_RT/PRETEST/PRE_4_13/PRE_Q_4_13/0:label": "No",                                          
    "/SPI_RT/EQA/EQA_7_3/EQA_C_7_3:label": "Comments",                                          
    "/SPI_RT/info27:hint": "Add a new corrective action?",                                          
    "/SPI_RT/SUMMARY/info17:label": "Audit Score:\n1.0 PERSONAL TRAINING & CERTIFICATION SCORE=/10 \n2.0 PHYSICAL FACILITY SCORE =/5 \n3.0 SAFETY SCORE =/11 \n4.0 PRE-TESTING PHASE SCORE = /12 \n5.0 TESTING PHASE SCORE =/9 \n6.0 POST TESTING PHASE =/9 \n7.0 EXTERNAL QUALITY AUDIT = /\nTotal points scored = \nTotal score expected = \n% Score = round(,                                          2)",                                          
    "/SPI_RT/correctiveaction/auditorcomment:label": "Auditor’s Comments :",                                          
    "/SPI_RT/PERSONAL/PER_G_1_3/PERSONAL_Q_1_3/0:label": "No",                                          
    "/SPI_RT/PRETEST/PRE_4_9/PRE_C_4_9:label": "Comments",                                          
    "/SPI_RT/SAFETY/SAF_3_5:label": ":",                                          
    "/SPI_RT/PRETEST/PRE_4_10:label": ":",                                          
    "/SPI_RT/PRETEST/PRE_4_4/PRE_C_4_4:label": "Comments",                                          
    
    "/SPI_RT/PRETEST/PRETEST_Display:label": "4.0 PRE-TESTING PHASE",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_3/PHYSICAL_C_2_3:label": "Comments",                                          
    "/SPI_RT/TESTSITE/affiliation/Private:label": "Private",                                          
    "/SPI_RT/SAFETY/SAF_3_4:label": ":",                                          
    "/SPI_RT/PHYSICAL/PHYSICALPHOTO:label": "Photo - Physical Facility",                                          
    "/SPI_RT/EQA/SAMPLEREF/EQA_7_13/EQA_C_7_13:label": "Comments",                                          
    "/SPI_RT/TEST/TEST_5_3/TEST_Q_5_3/1:label": "Yes",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_5/PHYSICAL_Q_2_5/0:label": "No",                                          
    "/SPI_RT/POSTTEST/POST_6_2:label": ":",                                          
    "/SPI_RT/POSTTEST/POST_6_1/POST_Q_6_1/1:label": "Yes",                                          
    "/SPI_RT/PRETEST/PRE_4_6/PRE_Q_4_6/1:label": "Yes",                                          
    "/SPI_RT/SAFETY/SAF_3_6/SAFETY_Q_3_6/0:label": "No",                                          
    "/SPI_RT/EQA/SAMPLEREF/EQA_7_11:label": ":",                                          
    "/SPI_RT/staffaudited:label": "Staff Audited Name:",                                          
    "/SPI_RT/TESTSITE/testingpointtype/VCT:label": "VCT/HTC",                                          
    "/SPI_RT/TESTSITE/level/HealthPost:label": "Health Post",                                          
    "/SPI_RT/TEST/TEST_5_7/TEST_Q_5_7/0.5:label": "Partial",                                          
    "/SPI_RT/scoring/info6:label": "Each element marked will be assigned a point value: \n• Items marked “Yes” receive 1 point each.\n• Items marked “Partial” receive 0.5 point each. \n• Items marked “No” receive 0 point each.",                                          
    "/SPI_RT/EQA/EQA_7_4/EQA_Q_7_4/0:label": "No",                                          
    "/SPI_RT/EQA/EQA_SCORE:hint": "Assesment for Post Testing Phase",                                          
    "/SPI_RT/POSTTEST/POST_6_1:label": ":",                                          
    "/SPI_RT/SAFETY/SAFETYPHOTO:hint": "If needed,                                           please take photograph for evidence/corrective action",                                          
    "/SPI_RT/PRETEST/PRE_4_9:label": ":",                                          
    "/SPI_RT/PRETEST/PRE_4_3/PRE_Q_4_3/1:label": "Yes",                                          
    "/SPI_RT/EQA/EQA_7_4/EQA_Q_7_4:label": "7.4 Is an EQA/PT report received from NRL and reviewed by testers and/or the person in charge at the testing point?",                                          
    "/SPI_RT/TEST/TEST_5_5/TEST_C_5_5:label": "Comments",                                          
    "/SPI_RT/SAFETY/SAF_3_3/SAFETY_Q_3_3/0:label": "No",                                          
    "/SPI_RT/POSTTEST/POST_6_6/POST_Q_6_6/0:label": "No",                                          
    "/SPI_RT/PRETEST/PRE_4_6/PRE_Q_4_6/0.5:label": "Partial",                                          
    "/SPI_RT/TEST/TEST_5_8/TEST_Q_5_8/0.5:label": "Partial",                                          
    "/SPI_RT/PRETEST/PRE_4_10/PRE_Q_4_10/1:label": "Yes",                                          
    "/SPI_RT/PERSONAL/PER_G_1_8/PERSONAL_C_1_8:label": "Comments",                                          
    "/SPI_RT/SAFETY/SAF_3_4/SAFETY_Q_3_4/0.5:label": "Partial",                                          
    "/SPI_RT/TEST/TEST_5_4/TEST_Q_5_4/0.5:label": "Partial",                                          
    
    "/SPI_RT/EQA/EQA_7_2/EQA_Q_7_2/0.5:label": "Partial",                                          
    "/SPI_RT/EQA/EQA_7_8/EQA_Q_7_8/0:label": "No",                                          
    "/SPI_RT/TEST/TEST_5_3/TEST_Q_5_3:label": "5.3 Are sample collection devices (e.g.,                                           capillary tube,                                           loop,                                           disposable pipettes,                                           etc.) used accurately?",                                          
    "/SPI_RT/SAFETY/SAF_3_1/SAFETY_Q_3_1/0.5:label": "Partial",                                          
    "/SPI_RT/SAFETY/SAF_3_5/SAFETY_Q_3_5/1:label": "Yes",                                          
    "/SPI_RT/correctiveaction/correction/Followup:label": "Follow up",                                          
    "/SPI_RT/TESTSITE/level/District:label": "District",                                          
    "/SPI_RT/correctiveaction/action:label": "Recommendations - Actions :",                                          
    "/SPI_RT/PERSONAL/PER_G_1_6/PERSONAL_Q_1_6/1:label": "Yes",                                          
    "/SPI_RT/TEST/TEST_5_3:label": ":",                                          
    "/SPI_RT/TESTSITE/affiliation/Government:label": "Government",                                          
    "/SPI_RT/PERSONAL/PER_G_1_3/PERSONAL_C_1_3:label": "Comments",                                          
    "/SPI_RT/POSTTEST/POST_6_2/POST_Q_6_2/1:label": "Yes",                                          
    "/SPI_RT/PERSONAL/PER_G_1_4/PERSONAL_C_1_4:label": "Comments",                                          
    "/SPI_RT/PRETEST/PRE_4_10/PRE_Q_4_10:label": "4.10 Are job aides on finger prick or venous blood collection available and posted at the testing point?",                                          
    
    "/SPI_RT/EQA/EQA_7_5/EQA_Q_7_5/0:label": "No",                                          
    "/SPI_RT/PRETEST/PRE_4_3/PRE_Q_4_3/0.5:label": "Partial",                                          
    "/SPI_RT/SAFETY/SAF_3_10/SAFETY_C_3_10:label": "Comments",                                          
    "/SPI_RT/EQA/EQAPHOTO:label": "Photo - External Quality Audit",                                          
    "/SPI_RT/TEST/TEST_DISPLAY:label": "5.0 TESTING PHASE",                                          
    "/SPI_RT/PERSONAL/PER_G_1_1/PERSONAL_Q_1_1/0.5:label": "Partial",                                          
    "/SPI_RT/PRETEST/PRE_4_4/PRE_Q_4_4/0.5:label": "Partial",                                          
    "/SPI_RT/SUMMARY/info25:label": "Level 4 - 90% or higher",                                          
    "/SPI_RT/PERSONAL/PER_G_1_10/PERSONAL_Q_1_10:label": "1.10 Are all testers required to be re-certified periodically (e.g.,                                           every two years)?",                                          
    "/SPI_RT/TEST/TEST_5_9/TEST_C_5_9:label": "Comments",                                          
    "/SPI_RT/TESTSITE/affiliation/nongovt:label": "Non-governmental organization",                                          
    "/SPI_RT/PRETEST/PRE_4_2:label": ":",                                          
    "/SPI_RT/TEST/TEST_5_2/TEST_Q_5_2:label": "5.2 Are timers available and used routinely for HIV rapid testing?",                                          
    "/SPI_RT/EQA/EQA_7_6/EQA_Q_7_6/1:label": "Yes",                                          
    "/SPI_RT/TESTSITE/testingpointtype:label": "Type of testing point",                                          
    "/SPI_RT/TEST/TEST_5_6:label": ":",                                          
    "/SPI_RT/TEST/TEST_5_6/TEST_C_5_6:label": "Comments",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_3/PHYSICAL_Q_2_3/0:label": "No",                                          
    "/SPI_RT/TEST/TEST_5_7/TEST_Q_5_7/1:label": "Yes",                                          
    "/SPI_RT/EQA/EQA_7_7/EQA_Q_7_7:label": "7.7 Is feedback provided during supervisory visit and documented?",                                          
    "/SPI_RT/TEST/TEST_5_5/TEST_Q_5_5/1:label": "Yes",                                          
    "/SPI_RT/info1:label": "Stepwise Process for Improving the Quality of HIV Rapid and Recency Testing (SPI-RRT) Checklist",                                          
    "/SPI_RT/summarypage:label": "Summary Score",                                          
    "/SPI_RT/PRETEST/PRE_4_8:label": ":",                                          
    "/SPI_RT/SAFETY/SAFETY_DISPLAY:hint": "Section Score = /11",                                          
    "/SPI_RT/scoring/info11:label": "The overall total points obtained by each HIV testing point audited will be weighed to correspond to a specific performance level.",                                          
    
    "/SPI_RT/POSTTEST/POST_6_4/POST_Q_6_4/0.5:label": "Partial",                                          
    "/SPI_RT/durationaudit:label": "Duration of Audit:",                                          
    "/SPI_RT/SAFETY/SAF_3_5/SAFETY_Q_3_5/0:label": "No",                                          
    "/SPI_RT/PERSONAL/PER_G_1_4/PERSONAL_Q_1_4/0.5:label": "Partial",                                          
    "/SPI_RT/PERSONAL/PER_G_1_1/PERSONAL_Q_1_1/0:label": "No",                                          
    "/SPI_RT/PERSONAL/PER_G_1_8/PERSONAL_Q_1_8/0.5:label": "Partial",                                          
    "/SPI_RT/TESTSITE/testingpointtype/TreatmentCenter:label": "Treatment Center",                                          
    "/SPI_RT/PRETEST/PRE_4_1/PRE_C_4_1:label": "Comments",                                          
    "/SPI_RT/PRETEST/PRE_4_1/PRE_Q_4_1/0.5:label": "Partial",                                          
    "/SPI_RT/POSTTEST/POST_6_3/POST_Q_6_3:label": "6.3 Is the total summary at the end of each page of the register/logbooks complied accurately?",                                          
    "/SPI_RT/POSTTEST/POST_6_6/POST_Q_6_6:label": "6.6 Are the register/logbook pages routinely reviewed for accuracy and completeness by the person in charge?",                                          
    "/SPI_RT/SAFETY/SAF_3_6/SAFETY_Q_3_6/0.5:label": "Partial",                                          
    "/SPI_RT/SAFETY/SAF_3_3/SAFETY_Q_3_3:label": "3.3 Are testers and those visiting the testing area following the safety practices outlined in the SOPs and/or job aides?",                                          
    "/SPI_RT/POSTTEST/POST_6_9/POST_C_6_9:label": "Comments",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_2/PHYSICAL_C_2_2:label": "Comments",                                          
    "/SPI_RT/EQA/sampleretesting/No:label": "No",                                          
    "/SPI_RT/EQA/EQA_7_4/EQA_Q_7_4/0.5:label": "Partial",                                          
    "/SPI_RT/TESTSITE/testingpointtype/ExposedInfantConsultation:label": "Exposed Infant consultation",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_5/PHYSICAL_Q_2_5/0.5:label": "Partial",                                          
    "/SPI_RT/PRETEST:label": "4.0 PRE-TESTING PHASE - (Max Score 13)",                                          
    "/SPI_RT/PRETEST/PRETESTPHOTO:hint": "If needed,                                           please take photograph for evidence/corrective action",                                          
    "/SPI_RT/PRETEST/PRE_4_10/PRE_Q_4_10/0.5:label": "Partial",                                          
    "/SPI_RT/info1:hint": "SPI-RT Checklist Version 3.0",                                          
    "/SPI_RT/SAFETY/SAF_3_2/SAFETY_Q_3_2/0.5:label": "Partial",                                          
    "/SPI_RT/PRETEST/PRE_4_3/PRE_Q_4_3:label": "4.3 Are SOPs and/or job aides on HIV rapid test procedures and the national HIV rapid test algorithm(s) available and easily accessible at the testing site?",                                          
    "/SPI_RT/SAFETY/SAF_3_10/SAFETY_Q_3_10:label": "3.10 Are infectious and non-infectious waste containers emptied regularly per the SOP and/or job aides?",                                          
    "/SPI_RT/SAFETY/SAF_3_10/SAFETY_Q_3_10/0:label": "No",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_5/PHYSICAL_Q_2_5/1:label": "Yes",                                          
    "/SPI_RT/SAFETY/SAF_3_1/SAFETY_Q_3_1/1:label": "Yes",                                          
    "/SPI_RT/EQA/EQA_7_1/EQA_Q_7_1/0:label": "No",                                          
    "/SPI_RT/EQA/EQA_7_5/EQA_C_7_5:label": "Comments",                                          
    "/SPI_RT/POSTTEST/POST_DISPLAY:label": "6.0 POST-TESTING PHASE - DOCUMENTS AND RECORDS",                                          
    "/SPI_RT/TESTSITE/name_auditor_lead:hint": "Name of auditor in-charge of the audit",                                          
    "/SPI_RT/EQA/SAMPLEREF/EQA_7_12/EQA_C_7_12:label": "Comments",                                          
    
    "/SPI_RT/EQA/EQA_7_5/EQA_Q_7_5/1:label": "Yes",                                          
    "/SPI_RT/PRETEST/PRE_4_8/PRE_Q_4_8/1:label": "Yes",                                          
    "/SPI_RT/PRETEST/PRE_4_2/PRE_Q_4_2/0.5:label": "Partial",                                          
    "/SPI_RT/TEST/TEST_5_7/TEST_Q_5_7/0:label": "No",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_1/PHYSICAL_Q_2_1/0.5:label": "Partial",                                          
    "/SPI_RT/POSTTEST:label": "6.0 POST-TESTING PHASE - DOCUMENTS AND RECORDS (Max Score 9)",                                          
    "/SPI_RT/PERSONAL/PER_G_1_3/PERSONAL_Q_1_3/1:label": "Yes",                                          
    "/SPI_RT/PHYSICAL/PHYSICAL_Display:hint": "Section Score = /5",                                          
    "/SPI_RT/TEST/TEST_5_1/TEST_Q_5_1/0:label": "No",                                          
    "/SPI_RT/TEST/TEST_5_7/TEST_Q_5_7:label": "5.7 Are incorrect/invalid QC results properly recorded?",                                          
    "/SPI_RT/SAFETY/SAF_3_2:label": ":",                                          
    "/SPI_RT/TEST/TEST_5_9/TEST_Q_5_9:label": "5.9 Are QC records reviewed by the person in charge routinely?",                                          
    "/SPI_RT/EQA/SAMPLEREF/EQA_7_10/EQA_C_7_10:label": "Comments",                                          
    "/SPI_RT/TEST/TEST_5_2/TEST_Q_5_2/0:label": "No",                                          
    "/SPI_RT/PERSONAL/PER_G_1_1/PERSONAL_Q_1_1:label": "1.1 Have all testers received a comprehensive training on HIV rapid testing using the nationally approved curriculum?",                                          
    
    "/SPI_RT/EQA/EQA_7_8/EQA_Q_7_8/0.5:label": "Partial",                                          
    "/SPI_RT/SAFETY/SAF_3_1/SAFETY_C_3_1:label": "Comments",                                          
    "/SPI_RT/POSTTEST/POST_6_7:label": ":",                                          
    "/SPI_RT/PERSONAL/PER_G_1_6/PERSONAL_C_1_6:label": "Comments",                                          
    "/SPI_RT/PERSONAL:label": "1.0 PERSONNEL TRAINING AND CERTIFICATION - (Max Score 10)",                                          
    "/SPI_RT/PHYSICAL/PHY_G_2_4/PHYSICAL_Q_2_4/0:label": "No",                                          
    "/SPI_RT/TESTSITE/facilityname:label": "Testing Facility Name:",                                          
    "/SPI_RT/durationaudit:hint": "Hour/Minute",                                          
    "/SPI_RT/POSTTEST/POST_6_8:label": ":",                                          
    "/SPI_RT/PRETEST/PRE_4_5/PRE_Q_4_5/1:label": "Yes",                                          
    "/SPI_RT/POSTTEST/POST_6_9/POST_Q_6_9/0.5:label": "Partial",                                          
    "/SPI_RT/PRETEST/PRE_4_7/PRE_Q_4_7/0:label": "No",                                          
    "/SPI_RT/POSTTEST/POST_6_5/POST_Q_6_5/0:label": "No",                                          
    "/SPI_RT/SAFETY/SAF_3_3:label": ":",                                          
    "/SPI_RT/SAFETY/SAFETY_SCORE:hint": "Assesment for Safety",                                          
    "/SPI_RT/PERSONAL/PER_G_1_8:label": ":",                                          
    "/SPI_RT/PRETEST/PRE_4_10/PRE_Q_4_10/0:label": "No",                                          
    "/SPI_RT/PRETEST/PRE_4_4/PRE_Q_4_4:label": "4.4 Are SOPs and/or job aides on HIV rapid test procedures and the national testing algorithm up-to-date and accurate?",                                          

    "/SPI_RT/INFECTIONSUR:label": "8.0 HIV-1 RECENT INFECTION SURVEILLANCE USING THE RAPID TEST FOR RECENT INFECTION  - (Max Score 11)",                                          
    "/SPI_RT/INFECTIONSUR/RTRI_8_1/RTRI_Q_8_1:label": "8.1 Have all testers received a comprehensive training on RTRI?",                                          
    "/SPI_RT/INFECTIONSUR/RTRI_8_2/RTRI_Q_8_2:label": "8.2 Are there records indicating all testers have demonstrated competency in RTRI prior to testing?",                                          
    "/SPI_RT/INFECTIONSUR/RTRI_8_3/RTRI_Q_8_3:label": "8.3 Are all current versions of recency/RTRI SOPs and/or job aids readily available at the site? ",                                          
    "/SPI_RT/INFECTIONSUR/RTRI_8_4/RTRI_Q_8_4:label": "8.4 Is there a sufficient supply of RTRI tests available at the site?Please provide number of tests currently available…….",                                          
    "/SPI_RT/INFECTIONSUR/RTRI_8_5/RTRI_Q_8_5:label": "8.5 Are the test kits kept in a temperature controlled environment based on the manufacturers instructions?",                                          
    "/SPI_RT/INFECTIONSUR/RTRI_8_6/RTRI_Q_8_6:label": "8.6 Are RTRI testing procedures being followed (i.e. right volume of sample using correct sample application device,                                           correct read time,                                           correct result interpretation)?",                                          
    "/SPI_RT/INFECTIONSUR/RTRI_8_7/RTRI_Q_8_7:label": "8.7 Are the RTRI results documented in the data capture form or logbook correctly (e.g. client demographics,                                           kit name,                                           lot number,                                           expiration dates,                                           tester name,                                           RTRI visual results and recency interpretation) and reviewed by the person in charge?",                                          
    "/SPI_RT/INFECTIONSUR/RTRI_8_8/RTRI_Q_8_8:label": "8.8 Are external quality control (QC) specimens (i.e. long-term (LT),                                           recent and negative) routinely used (i.e. monthly) for RTRI?",                                          
    "/SPI_RT/INFECTIONSUR/RTRI_8_9/RTRI_Q_8_9:label": "8.9 Are QC results for RTRI properly recorded (e.g. kit name,                                           lot number,                                           expiration dates,                                           tester name,                                           RTRI visual results and recency interpretation for each level of QC)  and reviewed by person in charge?",                                          
    "/SPI_RT/INFECTIONSUR/RTRI_8_10/RTRI_Q_8_10:label": "8.10 Are appropriate steps taken and documented when RTRI QC results are incorrect?",                                          
    "/SPI_RT/INFECTIONSUR/RTRI_8_11/RTRI_Q_8_11:label": "8.11 Are appropriate steps taken and documented according to the SOP or guidelines for invalid RTRI test results? If yes,                                           how many in the last 3 months…………(use comments)",                                          
    "/SPI_RT/INFECTIONSUR/RTRI_DISPLAY:label": "8.0 HIV-1 RECENT INFECTION SURVEILLANCE USING THE RAPID TEST FOR RECENT INFECTION SCORE"