<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/img/favicon.png">
    <title>Malawi – Dashboard for Quality Improvement of HIV Rapid Testing </title>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/stroke-7/style.css'); ?>"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/jquery.nanoscroller/css/nanoscroller.css'); ?>"/><!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/css/style.css'); ?>" type="text/css"/>
  </head>
  <body class="am-splash-screen">
    <div class="am-wrapper am-login">
      <div class="am-content">
        <div class="main-content">
          <div class="login-container" style="text-align:center;">
            <div class="panel panel-default">
              <div class="panel-heading"><img src="<?php echo $this->basePath('assets/img/logo.png'); ?>" alt="logo" class="logo-img"><span>Malawi – Dashboard for Quality Improvement of HIV Rapid Testing </span></div>
              <div class="panel-body">
                <form action="<?php echo $this->url('login'); ?>" method="post" class="form-horizontal">
                  <div class="login-form">
                    <div class="form-group">
                      <div class="input-group"><span class="input-group-addon"><i class="icon s7-user"></i></span>
                        <input id="username" name="username" type="text" placeholder="Username" autocomplete="off" class="form-control">
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="input-group"><span class="input-group-addon"><i class="icon s7-lock"></i></span>
                        <input id="password" name="password" type="password" placeholder="Password" class="form-control">
                      </div>
                    </div>
                    <div class="form-group login-submit">
                      <button data-dismiss="modal" type="submit" class="btn btn-primary btn-lg">Log me in</button>
                    </div>
					
                    <div class="form-group footer row" style="display:none;">
                      <div class="col-xs-6"><a href="#">Forgot Password?</a></div>
                      <div class="col-xs-6 remember">
                        <label for="remember">Remember Me</label>
                        <div class="am-checkbox">
                          <input type="checkbox" id="remember">
                          <label for="remember"></label>
                        </div>
                      </div>
                    </div>
					
                  </div>
                </form>
              </div>
            </div>
			<a href="http://apps.who.int/iris/bitstream/10665/199799/1/9789241508179_eng.pdf" style="text-decoration:underline;">
						Improving the quality of HIV-Related Point-of Care Testing
						<br>
						1 December 2015
					  </a>

          </div>
        </div>
      </div>
    </div>
    <script src="<?php echo $this->basePath('assets/lib/jquery/jquery.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery.nanoscroller/javascripts/jquery.nanoscroller.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/js/main.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/bootstrap/dist/js/bootstrap.min.js'); ?>" type="text/javascript"></script>
    <script type="text/javascript">
      $(document).ready(function(){
      	//initialize the javascript
      	App.init();
      });
      
    </script>
  </body>
</html>