<div class="am-content">
	<div class="page-head">
		<h2><?= $this->translate('Add District'); ?></h2>
		<span class="muted pull-right" style="font-size:15px;"><span class="mandatory">*</span> <?= $this->translate('indicates required field'); ?></span>
	</div>

	<div class="main-content">
		<div class="widget widget-fullwidth widget-small" style="padding:5px;">
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default">
						<div class="panel-body">
							<form role="form" name="addDistrictInformation" id="addDistrictInformation" method="post" action="<?php echo $this->url('district', array('action' => 'add')); ?>" autocomplete="off">
								<div class="form-group col-lg-6">
									<label><?= $this->translate('District Name '); ?><span class="mandatory">*</span> </label>
									<input type="text" class="form-control isRequired" id="districtName" name="districtName" placeholder="<?= $this->translate('District Name'); ?>" title="<?= $this->translate('Please enter district name'); ?>" onblur="checkNameValidation('geographical_divisions','geo_name',this,null,'The district name that you entered already exists.Enter another name')" />
								</div>
								<div class="form-group col-lg-6">
									<label for="districtCode"><?= $this->translate('District Code '); ?><span class="mandatory">*</span></label>
									<input type="text" class="form-control isRequired" id="districtCode" name="districtCode" placeholder="<?= $this->translate('District code'); ?>" title="<?= $this->translate('Please enter district code'); ?>" onblur="checkNameValidation('geographical_divisions','geo_name',this,null,'The district code that you entered already exists.Enter another code')" />
								</div>
								
								<div class="form-group col-lg-6">
									<label for="province"><?= $this->translate('Province '); ?><span class="mandatory">*</span></label>
									<select class="form-control isRequired" name="province" id="province" title="<?= $this->translate('Please select province'); ?>">
										<option value="">--Select--</option>
										<?php
										foreach ($provinceResult as $val) {
										?>
										<option value="<?php echo base64_encode($val['geo_id']) ?>"><?php echo $val['geo_name'] ?></option>
										<?php
										}
										?>
									</select>
								</div>

								<div class="form-group col-lg-6">
									<label for="status"><?= $this->translate('Status '); ?><span class="mandatory">*</span></label>
									<select class="form-control isRequired" name="status" id="status">
										<option value="active"><?= $this->translate('Active'); ?></option>
										<option value="inactive"><?= $this->translate('Inactive'); ?></option>
									</select>
								</div>

								<div class="spacer  col-lg-12">
									<button type="button" onclick="validateNow()" class="btn btn-space btn-primary"><?= $this->translate('Submit'); ?></button>
									<a href="<?php echo $this->url('district', array('action' => 'index')); ?>" class="btn btn-space btn-default"><?= $this->translate('Cancel'); ?></a>
								</div>
								
							</form>
						</div>
					</div>
				</div>
			</div>

		</div>

		<br>
		<br>

	</div>
</div>

<script type="text/javascript">
	duplicateName = true;

	function validateNow() {
		flag = deforayValidator.init({
			formId: 'addDistrictInformation'
		});
		if (flag) {
			if (duplicateName) {
				document.getElementById('addDistrictInformation').submit();
			}
		}
	}

	function checkNameValidation(tableName, fieldName, obj, fnct, msg) {
		checkValue = document.getElementById(obj.id).value;
		$.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {
				tableName: tableName,
				fieldName: fieldName,
				value: checkValue,
				fnct: fnct
			},
			function(data) {
				if (data > 0) {
					alert(msg);
					duplicateName = false;
					document.getElementById(obj.id).value = "";
				} else {
					duplicateName = true;
				}
			});
	}
	
</script>