<?php

use Laminas\Session\Container;

$container = new Container('alert');
$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$adminMenu = "";
$auditMenu = "";
$configMenu = "";
$emailMenu = "";

$config = $this->GlobalConfigHelper();
$web_version = $config['web_version'];
$totalVersions = count(explode(",", $web_version));
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <title>Index - OnePage Bootstrap Template</title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon" />
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
    <link
      href="<?php echo $this->basePath('assets/vendor/bootstrap/css/bootstrap.min.css'); ?>"
      rel="stylesheet"
    />
    <link
      href="<?php echo $this->basePath('assets/vendor/bootstrap-icons/bootstrap-icons.css'); ?>"
      rel="stylesheet"
    />
    <link href="<?php echo $this->basePath('assets/vendor/aos/aos.css'); ?>" rel="stylesheet" />

    <!-- Main CSS File -->
    <link href="<?php echo $this->basePath('assets/css/main.css'); ?>" rel="stylesheet" />

    <!-- =======================================================
  * Template Name: OnePage
  * Template URL: https://bootstrapmade.com/onepage-multipurpose-bootstrap-template/
  * Updated: Aug 07 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  </head>

  <body class="index-page">
    <header id="header" class="header d-flex align-items-center sticky-top">
      <div
        class="container-fluid container-xl position-relative d-flex align-items-center"
      >
        <a href="#" class="logo d-flex align-items-center me-auto">
          <!-- Uncomment the line below if you also wish to use an image logo -->
          <!-- <img src="assets/img/logo.png" alt=""> -->
          <?php
          // $config = $this->GlobalConfigHelper();
          if (!empty($config) && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo" . DIRECTORY_SEPARATOR . $config['logo'])) {
          ?>
            <img src="<?php echo $this->basePath('uploads/logo/' . $config['logo']); ?>" style="width:100%;" />
          <?php
          } else {
          ?>
            <img src="<?php echo $this->basePath('assets/img/logo.png') ?>" style="width:100%;" />
          <?php
          }
          ?>
        </a>

        <nav id="navmenu" class="navmenu">
          <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
        </nav>

        <a class="btn-getstarted" href="<?php echo $this->url('login', array('action' => 'index')); ?>">Login</a>
      </div>
    </header>

    <main class="main">
     
      <?php echo $this->content; ?>
    </main>

    <footer id="footer" class="footer light-background">
      <div class="container footer-top"></div>

      <div class="container copyright text-center mt-4">
        <p>
          © <span>Copyright</span>
          <strong class="px-1 sitename">RTCQI</strong>
          <span>All Rights Reserved</span>
        </p>
      </div>
    </footer>

    <!-- Scroll Top -->
    <a
      href="#"
      id="scroll-top"
      class="scroll-top d-flex align-items-center justify-content-center"
      ><i class="bi bi-arrow-up-short"></i
    ></a>

    <!-- Preloader -->
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="<?php echo $this->basePath('assets/vendor/bootstrap/js/bootstrap.bundle.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/vendor/aos/aos.js'); ?>"></script>

    <!-- Main JS File -->
    <script src="assets/vendor/main.js"></script>
  </body>
</html>
