<?php

use Laminas\Session\Container;

$container = new Container('alert');
$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$adminMenu = "";
$auditMenu = "";
$configMenu = "";
$emailMenu = "";

$config = $this->GlobalConfigHelper();
// \Zend\Debug\Debug::dump($commonVal->getGlobalConfigDetails());
// echo $commonVal->getGlobalConfigDetails();
// $config = $commonVal->getGlobalConfigDetails();
$web_version = $config['web_version'];
$totalVersions = count(explode(",", $web_version));

//print_r($acl->isAllowed($role, "Application\Controller\SpiV5ReportsController", "facility-report"));die;

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\RolesController", "index")) {
  $adminMenu .= "<li><a href=" . $this->url('roles', array('action' => 'index')) . ">" . $this->translate('Roles') . "</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\UsersController", "index")) {
  $adminMenu .= "<li><a href=" . $this->url('users', array('action' => 'index')) . ">" . $this->translate('Users') . "</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\ConfigController", "index")) {
  $adminMenu .= "<li><a href=" . $this->url('config', array('action' => 'index')) . ">" . $this->translate('Global Config') . "</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\UserLoginHistoryController", "index")) {
  $adminMenu .= "<li><a href=" . $this->url('user-login-history', array('action' => 'index')) . ">" . $this->translate('User Login History') . "</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Application\Controller\EventController", "index")) {
  $adminMenu .= "<li><a href=" . $this->url('event-log', array('action' => 'index')) . ">" . $this->translate('Event Log') . "</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV3Controller", "manage-facility") && preg_match("/v3/i", $config['web_version'])) {
  $configMenu .= "<li><a href=" . $this->url('spi-v3-form', array('action' => 'manage-facility')) . ">" . $this->translate('SPI-RT v3 Form Data') . "</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV6Controller", "manage-facility") && preg_match("/v6/i", $config['web_version'])) {
  $configMenu .= "<li><a href=" . $this->url('spi-v6-form', array('action' => 'manage-facility')) . ">" . $this->translate('SPI-RT v6 Form Data') . "</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\AuditTrailController", "index")) {
  $configMenu .= "<li><a href=" . $this->url('audit-trail', array('action' => 'index')) . ">" . $this->translate('Audit Trail') . "</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV3Controller", "validate-spiv3-data")) {
  $adminMenu .= "<li><a href=" . $this->url('spi-v3-form', array('action' => 'validate-spiv3-data')) . ">" . $this->translate('Validate SPI-RT Data')  . "</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV3Controller", "index")) {
  //$auditMenu.='<li><a href="javascript:alert(\'Under Construction\')">Logbook Data Analysis</a></li>';
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV3Controller", "index")) {
  // $auditMenu.='<li><a href="javascript:alert(\'Under Construction\')">SPI M&E</a></li>';
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV3Controller", "index")) {
  //$auditMenu.='<li><a href="javascript:alert(\'Under Construction\')">SPI RT 2.x</a></li>';
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV3Controller", "index")  && preg_match("/v3/i", $config['web_version'])) {
  $auditMenu .= "<li><a href=" . $this->url('spi-v3-form', ['action' => 'index']) . ">SPI-RT</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV6Controller", "index") && preg_match("/v6/i", $config['web_version'])) {
  $auditMenu .= "<li><a href=" . $this->url('spi-v6-form', ['action' => 'index']) . ">SPI-RRT</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\EmailController", "index") && preg_match("/v3/i", $config['web_version'])) {
  $emailMenu .= "<li><a href=" . $this->url('email', ['action' => 'index']) . ">SPI-RT</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\EmailController", "email-v6") && preg_match("/v6/i", $config['web_version'])) {
  $emailMenu .= "<li><a href=" . $this->url('email', ['action' => 'email-v6']) . ">SPI-RRT</a></li>";
}
$googleTag = "GTM-TSMNF9F9";
?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0 maximum-scale=1.0, user-scalable=no" name="viewport">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="keywords" content="">
  <title><?php echo $sessionLogin->countryName; ?> <?= $this->translate('Dashboard for Quality Improvement of HIV Rapid Testing'); ?> </title>

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="assets/css/main.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: OnePage
  * Template URL: https://bootstrapmade.com/onepage-multipurpose-bootstrap-template/
  * Updated: Aug 07 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  <!-- Latest compiled and minified CSS -->

  <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/bootstrap.min.css'); ?>" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous" />

  <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/datatables.min.css'); ?>" />
  <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/stroke-7/style.css'); ?>" />
  <link rel="stylesheet" href="<?php echo $this->basePath('assets/css/deforayModal.css'); ?>" type="text/css" />
  <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/jquery.nanoscroller/css/nanoscroller.css'); ?>" />
  <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/font-awesome.min.css'); ?>" />

    <!-- Google Tag Manager -->
    <script>
    (function(w,d,s,l,i){
      w[l]=w[l]||[];
      w[l].push({
        'gtm.start': new Date().getTime(),
        event:'gtm.js'
      });
      var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),
          dl=l!='dataLayer'?'&l='+l:'';
      j.async=true;
      j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;
      f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','<?php echo $googleTag; ?>');
  </script>
  <!-- End Google Tag Manager -->
</head>

<body class="index-page">

  <!-- Google Tag Manager (noscript) -->
  <noscript>
    <iframe src="https://www.googletagmanager.com/ns.html?id=<?php echo $googleTag; ?>" height="0" width="0" style="display:none;visibility:hidden"></iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->

  <header id="header" class="header d-flex align-items-center sticky-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center">

      <a href="index.html" class="logo d-flex align-items-center me-auto">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1 class="sitename">OnePage</h1>
      </a>

      <a class="btn-getstarted" href="#about">Login</a>

    </div>
  </header>
  
  <?php  echo $this->content; ?>

  <!-- Scroll Top -->



  <!-- Vendor JS Files -->
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>
  <script src="assets/vendor/purecounter/purecounter_vanilla.js"></script>
  <script src="assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="assets/vendor/imagesloaded/imagesloaded.pkgd.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>

  <!-- Main JS File -->
  <script src="assets/js/main.js"></script>
  
  <div id="dDiv" class="dialog">
    <div style="text-align:center"><span onclick="closeModal();" style="float:right;clear:both;" class="closeModal"></span></div>
    <iframe id="dFrame" src="" style="border:none;" scrolling='yes' marginwidth='0' marginheight='0' frameborder='0' vspace='0' hspace='0'>Oops! There seems to be a problem.</iframe>
  </div>

  <script src="<?php echo $this->basePath('assets/lib/jquery.nanoscroller/javascripts/jquery.nanoscroller.min.js'); ?>" type="text/javascript"></script>
  <script src="<?php echo $this->basePath('assets/js/main.js'); ?>" type="text/javascript"></script>
  <script src="<?php echo $this->basePath('assets/lib/bootstrap/dist/js/bootstrap.min.js'); ?>" type="text/javascript"></script>
  <script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>

  <script src="<?php echo $this->basePath('assets/lib/jquery-ui/jquery-ui.min.js'); ?>" type="text/javascript"></script>
  <script src="<?php echo $this->basePath('assets/js/jasny-bootstrap.min.js'); ?>" type="text/javascript" />
  <script src="<?php echo $this->basePath('assets/lib/countup/countUp.min.js'); ?>" type="text/javascript"></script>
  <script src="<?php echo $this->basePath('assets/js/tokenfield.min.js'); ?>" type="text/javascript" />
  <script src="<?php echo $this->basePath('assets/lib/chartjs/Chart.js?v=0.1'); ?>" type="text/javascript"></script>
  <script src="<?php echo $this->basePath('assets/js/deforayValidation.js'); ?>" type="text/javascript"></script>
  <script src="<?php echo $this->basePath('assets/js/deforayModal.js'); ?>" type="text/javascript"></script>
  <script src="<?php echo $this->basePath('assets/js/cookie.js'); ?>" type="text/javascript"></script>
</body>

</html>