<?php

use Laminas\Session\Container;

$container = new Container('alert');
$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$adminMenu = "";
$auditMenu = "";
$configMenu = "";
$emailMenu = "";

$config = $this->GlobalConfigHelper();
// \Zend\Debug\Debug::dump($commonVal->getGlobalConfigDetails());
// echo $commonVal->getGlobalConfigDetails();
// $config = $commonVal->getGlobalConfigDetails();
$web_version = $config['web_version'];
$totalVersions = count(explode(",", $web_version));

//print_r($acl->isAllowed($role, "Application\Controller\SpiV5ReportsController", "facility-report"));die;

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\RolesController", "index")) {
  $adminMenu .= "<li><a href=" . $this->url('roles', array('action' => 'index')) . ">" . $this->translate('Roles') . "</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\UsersController", "index")) {
  $adminMenu .= "<li><a href=" . $this->url('users', array('action' => 'index')) . ">" . $this->translate('Users') . "</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\ConfigController", "index")) {
  $adminMenu .= "<li><a href=" . $this->url('config', array('action' => 'index')) . ">" . $this->translate('Global Config') . "</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\UserLoginHistoryController", "index")) {
  $adminMenu .= "<li><a href=" . $this->url('user-login-history', array('action' => 'index')) . ">" . $this->translate('User Login History') . "</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Application\Controller\EventController", "index")) {
  $adminMenu .= "<li><a href=" . $this->url('event-log', array('action' => 'index')) . ">" . $this->translate('Event Log') . "</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV3Controller", "manage-facility") && preg_match("/v3/i", $config['web_version'])) {
  $configMenu .= "<li><a href=" . $this->url('spi-v3-form', array('action' => 'manage-facility')) . ">" . $this->translate('SPI-RT v3 Form Data') . "</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV6Controller", "manage-facility") && preg_match("/v6/i", $config['web_version'])) {
  $configMenu .= "<li><a href=" . $this->url('spi-v6-form', array('action' => 'manage-facility')) . ">" . $this->translate('SPI-RT v6 Form Data') . "</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\AuditTrailController", "index")) {
  $configMenu .= "<li><a href=" . $this->url('audit-trail', array('action' => 'index')) . ">" . $this->translate('Audit Trail') . "</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV3Controller", "validate-spiv3-data")) {
  $adminMenu .= "<li><a href=" . $this->url('spi-v3-form', array('action' => 'validate-spiv3-data')) . ">" . $this->translate('Validate SPI-RT Data')  . "</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV3Controller", "index")) {
  //$auditMenu.='<li><a href="javascript:alert(\'Under Construction\')">Logbook Data Analysis</a></li>';
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV3Controller", "index")) {
  // $auditMenu.='<li><a href="javascript:alert(\'Under Construction\')">SPI M&E</a></li>';
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV3Controller", "index")) {
  //$auditMenu.='<li><a href="javascript:alert(\'Under Construction\')">SPI RT 2.x</a></li>';
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV3Controller", "index")  && preg_match("/v3/i", $config['web_version'])) {
  $auditMenu .= "<li><a href=" . $this->url('spi-v3-form', array('action' => 'index')) . ">SPI-RT</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV6Controller", "index") && preg_match("/v6/i", $config['web_version'])) {
  $auditMenu .= "<li><a href=" . $this->url('spi-v6-form', array('action' => 'index')) . ">SPI-RRT</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\EmailController", "index") && preg_match("/v3/i", $config['web_version'])) {
  $emailMenu .= "<li><a href=" . $this->url('email', array('action' => 'index')) . ">SPI-RT</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\EmailController", "email-v5") && preg_match("/v5/i", $config['web_version'])) {
  $emailMenu .= "<li><a href=" . $this->url('email', array('action' => 'email-v5')) . ">SPI-RRT v5</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\EmailController", "email-v6") && preg_match("/v6/i", $config['web_version'])) {
  $emailMenu .= "<li><a href=" . $this->url('email', array('action' => 'email-v6')) . ">SPI-RRT</a></li>";
}

?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="<?php echo $this->basePath('assets/img/favicon.png'); ?>">
  <title><?php echo $sessionLogin->countryName; ?> <?= $this->translate('Dashboard for Quality Improvement of HIV Rapid Testing'); ?> </title>

  <style type="text/css">

  </style>
  <!-- Latest compiled and minified CSS -->

  <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/bootstrap.min.css'); ?>" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous" />

  <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/datatables.min.css'); ?>" />
  <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/stroke-7/style.css'); ?>" />
  <link rel="stylesheet" href="<?php echo $this->basePath('assets/css/deforayModal.css'); ?>" type="text/css" />
  <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/jquery.nanoscroller/css/nanoscroller.css'); ?>" />
  <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/font-awesome.min.css'); ?>" />

  <!--[if lt IE 9]>
    <script src="<?php echo $this->basePath('assets/js/html5shiv.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/js/respond.min.js'); ?>" type="text/javascript"></script>
    <![endif]-->

  <style>
    .widget {
      border: 2px solid #9edcff;
      border-radius: 5px;
    }

    .table thead tr th,
    .table thead tr td {
      background-color: #194f74;
      color: #ffffff;
      text-align: center;
      vertical-align: middle !important;
    }

    .datatables tbody tr td,
    .datatables tbody tr td a {
      font-size: 0.95em;
    }

    .mandatory {
      color: red;
    }

    a.mobLogin:hover {
      background-color: #194F74
    }

    .ms-drop input[type="checkbox"] {
      margin-left: -1.75rem !important;
      margin-top: 0.4rem !important;
    }
  </style>

  <link rel="stylesheet" href="<?php echo $this->basePath('assets/css/style.css?v=0.2'); ?>" type="text/css" />
  <script src="<?php echo $this->basePath('assets/lib/jquery/jquery.min.js'); ?>" type="text/javascript"></script>


</head>

<body>
  <div class="am-wrapper">
    <nav class="navbar navbar-default navbar-fixed-top am-top-header">
      <div class="container-fluid">
        <div class="navbar-header">
          <div class="page-title"><span>Dashboard</span></div>
          <?php if (isset($sessionLogin->userId)) { ?>
            <a class="mobLogin page-title btn btn-primary" style="font-size: 14px;float: right;margin-right: 3%; cursor: pointer; cursor: hand;" href="<?php echo $this->url('login', array('action' => 'logout')); ?>"> <span class="icon s7-power"></span><?= $this->translate('Sign Out'); ?></a>
          <?php } else { ?>
            <a class="mobLogin page-title btn btn-primary" style="font-size: 1
            4px;float: right;margin-right: 3%; cursor: pointer; cursor: hand;" style="color: #fff;" class="mobLogin" href="<?php echo $this->url('login', array('action' => 'index')); ?>"> <?= $this->translate('Login'); ?></a>
          <?php } ?>
          <a href="#" class="am-toggle-left-sidebar navbar-toggle collapsed">
            <span class="icon-bar"><span></span><span></span><span></span></span>
          </a>
          <a href="/" class="navbar-brand">
            <?php
            // $config = $this->GlobalConfigHelper();
            if (isset($config) && count($config) > 0 && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo" . DIRECTORY_SEPARATOR . $config['logo'])) {
            ?>
              <img src="<?php echo $this->basePath('uploads/logo/' . $config['logo']); ?>" style="width:100%;" />
            <?php
            } else {
            ?>
              <img src="<?php echo $this->basePath('assets/img/logo.png') ?>" style="width:100%;" />
            <?php
            }
            ?>

          </a>

        </div>

        <div id="am-navbar-collapse" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right am-user-nav">
            <?php if (isset($sessionLogin->userId)) { ?>
              <li class="dropdown">
                <?php if (!empty($sessionLogin->userImage)) { ?>
                  <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle"><img src="<?php echo $this->basePath($sessionLogin->userImage) ?>">
                  <?php } else {
                  ?>
                    <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle"><img src="/assets/img/nobody.jpg">
                    <?php
                  } ?>
                    <span class="user-name">John Doe</span><span class="angle-down s7-angle-down"></span></a>
                    <ul role="menu" class="dropdown-menu">
                      <?php
                      if (isset($sessionLogin->userId)) {
                      ?>
                        <li>
                          <a href="<?php echo $this->url('users', array('action' => 'profile', 'id' => base64_encode($sessionLogin->userId))); ?>"><i class="glyphicon glyphicon-user" style="color:#33333357;"></i>&nbsp;&nbsp;&nbsp;<?= $this->translate('Edit Profile'); ?></a>
                          <a href="<?php echo $this->url('users', array('action' => 'change-password', 'id' => base64_encode($sessionLogin->userId))); ?>"><i class="glyphicon glyphicon-user" style="color:#33333357;"></i>&nbsp;&nbsp;&nbsp;<?= $this->translate('Change Password'); ?></a>
                          <a href="<?php echo $this->url('login', array('action' => 'logout')); ?>"> <span class="icon s7-power"></span><?= $this->translate('Sign Out'); ?></a>
                        </li>
                      <?php } else {
                      ?>
                        <li><a href="<?php echo $this->url('login', array('action' => 'index')); ?>"> <?= $this->translate('Login'); ?></a></li>
                      <?php
                      } ?>
                    </ul>
              </li>
            <?php } else { ?>
              <li class=""><a href="<?php echo $this->url('spi-v3-form', array('action' => 'index')); ?>" class="btn btn-primary"><?= $this->translate('Login'); ?></a></li>
            <?php
            } ?>
          </ul>
          <ul class="nav navbar-nav am-nav-right">
            <li><a href="/" style="font-size:1.8em;"><?= $this->translate('Dashboard for Quality Improvement of HIV Rapid Testing'); ?></a></li>
          </ul>


        </div>
      </div>
    </nav>
    <div class="am-left-sidebar">
      <div class="content">
        <div class="am-logo"><img src="<?php echo $this->basePath('assets/img/logo.png') ?>" style="width:50px;margin-left:10px;" /></div>
        <ul class="sidebar-elements">
          <?php if (isset($acl) && $acl->isAllowed($role, "Application\Controller\IndexController", "index")) { ?>
            <?php if ($totalVersions == 1) { ?>
              <?php if (preg_match("/v3/i", $config['web_version']) && isset($acl) && $acl->isAllowed($role, "Application\Controller\DashboardController", "index")) { ?>
                <li class="parent"><a href="<?php echo $this->url('dashboard', array('action' => 'index')); ?>"><i class="icon s7-monitor"></i><span><?php echo $this->translate('Dashboard SPI-RT'); ?></span></a></li>
              <?php } elseif (preg_match("/v5/i", $config['web_version']) && isset($acl) && $acl->isAllowed($role, "Application\Controller\DashboardV5Controller", "index")) { ?>
                <li class="parent"><a href="<?php echo $this->url('dashboard-v5', array('action' => 'index')); ?>"><i class="icon s7-monitor"></i><span><?php echo $this->translate('Dashboard SPI-RRT v5'); ?></span></a></li>
              <?php } elseif (preg_match("/v6/i", $config['web_version']) && isset($acl) && $acl->isAllowed($role, "Application\Controller\DashboardV6Controller", "index")) { ?>
                <li class="parent"><a href="<?php echo $this->url('dashboard-v6', array('action' => 'index')); ?>"><i class="icon s7-monitor"></i><span><?php echo $this->translate('Dashboard SPI-RRT'); ?></span></a></li>
              <?php } ?>
            <?php } else { ?>
              <li class="parent"><a href="#"><i class="icon s7-ribbon"></i><span><?php echo $this->translate('Dashboard'); ?></span></a>
                <ul class="sub-menu">
                  <?php if (preg_match("/v3/i", $config['web_version']) && isset($acl) && $acl->isAllowed($role, "Application\Controller\DashboardController", "index")) { ?>
                    <li class=""><a href="<?php echo $this->url('dashboard', array('action' => 'index')); ?>"><span><?php echo $this->translate('Dashboard SPI-RT'); ?></span></a></li>
                  <?php } ?>
                  <?php if (preg_match("/v5/i", $config['web_version']) && isset($acl) && $acl->isAllowed($role, "Application\Controller\DashboardV5Controller", "index")) { ?>
                    <li class=""><a href="<?php echo $this->url('dashboard-v5', array('action' => 'index')); ?>"><span><?php echo $this->translate('Dashboard SPI-RRT v5'); ?></span></a></li>
                  <?php } ?>
                  <?php if (preg_match("/v6/i", $config['web_version']) && isset($acl) && $acl->isAllowed($role, "Application\Controller\DashboardV6Controller", "index")) { ?>
                    <li class=""><a href="<?php echo $this->url('dashboard-v6', array('action' => 'index')); ?>"><span><?php echo $this->translate('Dashboard SPI-RRT'); ?></span></a></li>
                  <?php } ?>
                </ul>
              </li>
            <?php } ?>
          <?php } ?>

          <?php if (trim($auditMenu) != "") { ?>
            <?php if ($totalVersions == 1) { ?>
              <?php if (preg_match("/v3/i", $config['web_version'])) { ?>
                <li class="parent"><a href="<?php echo $this->url('spi-v3-form', array('action' => 'index')); ?>"><i class="icon s7-display2"></i><span><?php echo $this->translate('Audit SPI-RT'); ?></span></a></li>
              <?php } elseif (preg_match("/v6/i", $config['web_version'])) { ?>
                <li class="parent"><a href="<?php echo $this->url('spi-v6-form', array('action' => 'index')); ?>"><i class="icon s7-display2"></i><span><?php echo $this->translate('Audit SPI-RRT'); ?></span></a></li>
              <?php } ?>
            <?php } else { ?>
              <li class="parent"><a href="#"><i class="icon s7-ribbon"></i><span><?php echo $this->translate('Audit'); ?></span></a>
                <ul class="sub-menu">
                  <?php echo $auditMenu; ?>
                </ul>
              </li>
            <?php } ?>
          <?php } ?>
          <?php
          if (isset($acl) && $acl->isAllowed($role, "Application\Controller\FacilityController", "index")) {
          ?>
            <li class="parent"><a href="<?php echo $this->url('spi-facility', array('action' => 'index')); ?>"><i class="icon s7-note2"></i><span><?php echo $this->translate('Facilities'); ?></span></a>
              <ul class="sub-menu">
                <li><a href="<?php echo $this->url('spi-facility', array('action' => 'index')); ?>"><?php echo $this->translate('Facilities'); ?></a></li>
                <li><a href="<?php echo $this->url('provinces', array('action' => 'index')); ?>"><?php echo $this->translate('Provinces'); ?></a></li>
                <li><a href="<?php echo $this->url('district', array('action' => 'index')); ?>"><?php echo $this->translate('Districts'); ?></a></li>

              </ul>
            </li>
          <?php } ?>

          <?php if (isset($acl) && ($acl->isAllowed($role, "Application\Controller\SpiV3ReportsController", "facility-report") || ($acl->isAllowed($role, "Application\Controller\SpiV6ReportsController", "facility-report")))) { ?>

            <li class="parent"><a href="#"><i class="icon s7-graph"></i><span><?php echo $this->translate('Reports'); ?></span></a>
              <ul class="sub-menu">
                <?php if (preg_match("/v3/i", $config['web_version']) && ($acl->isAllowed($role, "Application\Controller\SpiV3ReportsController", "facility-report"))) { ?>
                  <li><a href="<?php echo $this->url('spi-v3-reports', array('action' => 'facility-report')); ?>"><?php echo $this->translate('SPI-RT Facility Report'); ?></a></li>
                <?php } ?>
                <?php if (preg_match("/v6/i", $config['web_version']) && ($acl->isAllowed($role, "Application\Controller\SpiV6ReportsController", "facility-report"))) { ?>
                  <li><a href="<?php echo $this->url('spi-v6-reports', array('action' => 'facility-report')); ?>"><?php echo $this->translate('SPI-RRT Facility Report'); ?></a></li>
                <?php } ?>
              </ul>
            </li>

          <?php } ?>

          <?php if (trim($emailMenu) != "") { ?>
            <?php if ($totalVersions == 1) { ?>
              <?php if (preg_match("/v3/i", $config['web_version'])) { ?>
                <li class="parent"><a href="<?php echo $this->url('email', array('action' => 'index')); ?>"><span><?php echo $this->translate('Email SPI-RT'); ?></span></a></li>
              <?php } elseif (preg_match("/v5/i", $config['web_version'])) { ?>
                <li class="parent"><a href="<?php echo $this->url('email', array('action' => 'email-v5')); ?>"><span><?php echo $this->translate('Email SPI-RRT v5'); ?></span></a></li>
              <?php } elseif (preg_match("/v6/i", $config['web_version'])) { ?>
                <li class="parent"><a href="<?php echo $this->url('email', array('action' => 'email-v6')); ?>"><span><?php echo $this->translate('Email SPI-RRT'); ?></span></a></li>
              <?php } ?>
            <?php } else { ?>
              <li class="parent"><a href="#"><i class="icon s7-mail"></i><span><?php echo $this->translate('Email'); ?></span></a>
                <ul class="sub-menu">
                  <?php echo $emailMenu; ?>
                </ul>
              </li>
            <?php } ?>
          <?php } ?>

          <?php
          if (isset($acl) && $acl->isAllowed($role, "Application\Controller\CommonController", "audit-locations")) {
          ?>
            <li class="parent"><a href="/common/audit-locations"><i class="icon s7-map-marker"></i><span><?php echo $this->translate('Map'); ?></span></a></li>
          <?php } ?>
          <?php
          if (trim($adminMenu) != "") {
          ?>
            <?php if ($totalVersions == 1) { ?>
              <li class="parent"><a href="#"><i class="icon s7-config"></i><span><?php echo $this->translate('Configure'); ?></span></a>
                <ul class="sub-menu">
                  <?php if (preg_match("/v3/i", $config['web_version'])) { ?>
                    <?php echo $adminMenu; ?>
                    <li class=""><a href="<?php echo $this->url('spi-v3-form', array('action' => 'manage-facility')); ?>"><span><?php echo $this->translate('SPI-RT v3 Form Data'); ?></span></a></li>
                  <?php } elseif (preg_match("/v6/i", $config['web_version'])) { ?>
                    <?php echo $adminMenu; ?>
                    <li class=""><a href="<?php echo $this->url('spi-v6-form', array('action' => 'manage-facility')); ?>"><span><?php echo $this->translate('SPI-RT v6 Form Data'); ?></span></a></li>
                  <?php } ?>
                </ul>
              </li>
            <?php } else { ?>
              <li class="parent"><a href="#"><i class="icon s7-config"></i><span><?php echo $this->translate('Configure'); ?></span></a>
                <ul class="sub-menu">
                  <?php echo $adminMenu; ?>
                  <?php echo $configMenu; ?>
                </ul>
              </li>
            <?php } ?>
          <?php } ?>
        </ul>
        <!--Sidebar bottom content-->
      </div>
    </div>

    <?php echo $this->content; ?>

  </div>
  <div id="dDiv" class="dialog">
    <div style="text-align:center"><span onclick="closeModal();" style="float:right;clear:both;" class="closeModal"></span></div>
    <iframe id="dFrame" src="" style="border:none;" scrolling='yes' marginwidth='0' marginheight='0' frameborder='0' vspace='0' hspace='0'>Oops! There seems to be a problem.</iframe>
  </div>

  <script src="<?php echo $this->basePath('assets/lib/jquery.nanoscroller/javascripts/jquery.nanoscroller.min.js'); ?>" type="text/javascript"></script>
  <script src="<?php echo $this->basePath('assets/js/main.js'); ?>" type="text/javascript"></script>
  <script src="<?php echo $this->basePath('assets/lib/bootstrap/dist/js/bootstrap.min.js'); ?>" type="text/javascript"></script>

  <script src="<?php echo $this->basePath('assets/lib/jquery-ui/jquery-ui.min.js'); ?>" type="text/javascript"></script>
  <script src="<?php echo $this->basePath('assets/js/jasny-bootstrap.min.js'); ?>" type="text/javascript" />
  <script src="<?php echo $this->basePath('assets/lib/countup/countUp.min.js'); ?>" type="text/javascript"></script>
  <script src="<?php echo $this->basePath('assets/js/tokenfield.min.js'); ?>" type="text/javascript" />
  <script src="<?php echo $this->basePath('assets/lib/chartjs/Chart.js?v=0.1'); ?>" type="text/javascript"></script>
  <script src="<?php echo $this->basePath('assets/js/deforayValidation.js'); ?>" type="text/javascript"></script>
  <script src="<?php echo $this->basePath('assets/js/deforayModal.js'); ?>" type="text/javascript"></script>
  <script src="<?php echo $this->basePath('assets/js/cookie.js'); ?>" type="text/javascript"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      //initialize the javascript
      App.init();
    });

    $(document).ready(function() {
      <?php
      if (isset($container->alertMsg) && $container->alertMsg != "") {
      ?>
        alert("<?php echo $container->alertMsg; ?>");
      <?php
        $container->alertMsg = "";
        unset($container->alertMsg);
      }
      ?>
    });
  </script>

</body>

</html>
