<?php
use Zend\Session\Container;
$container = new Container('alert');
$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$adminMenu = "";
$auditMenu = "";

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\Roles", "index")) {
  $adminMenu.="<li><a href=".$this->url('roles',array('action' => 'index')).">Roles</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\Users", "index")) {
  $adminMenu.="<li><a href=".$this->url('users',array('action' => 'index')).">Users</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\Config", "index")) {
  $adminMenu.="<li><a href=" . $this->url('config',array('action' => 'index')) . ">Global Config</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV3", "manage-facility")) {
  $adminMenu.="<li><a href=".$this->url('spi-v3-form',array('action' => 'manage-facility')).">Manage SPI RT Form</a></li>";
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV3", "index")) {
  $auditMenu.='<li><a href="javascript:alert(\'Under Construction\')">Logbook Data Analysis</a></li>';
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV3", "index")) {
  $auditMenu.='<li><a href="javascript:alert(\'Under Construction\')">SPI M&E</a></li>';
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV3", "index")) {
  $auditMenu.='<li><a href="javascript:alert(\'Under Construction\')">SPI RT 2.x</a></li>';
}

if (isset($acl) && $acl->isAllowed($role, "Application\Controller\SpiV3", "index")) {
  $auditMenu.="<li><a href=".$this->url('spi-v3-form',array('action' => 'index')).">Manage SPI RT Form</a></li>";
}
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="<?php echo $this->basePath('assets/img/favicon.png'); ?>">
    <title>Malawi – Dashboard for Quality Improvement of HIV Rapid Testing </title>
    
    <style type="text/css">
      .mandatory {
        color: red;
      }
    </style>
    <!-- Latest compiled and minified CSS -->
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11,r-2.0.2,sc-1.4.1/datatables.min.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/stroke-7/style.css'); ?>"/>
        <link rel="stylesheet" href="<?php echo $this->basePath('assets/css/deforayModal.css'); ?>" type="text/css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/jquery.nanoscroller/css/nanoscroller.css'); ?>"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    
    <link rel="stylesheet" href="<?php echo $this->basePath('assets/css/style.css?v=0.2'); ?>" type="text/css"/>
    
    <script src="<?php echo $this->basePath('assets/lib/jquery/jquery.min.js'); ?>" type="text/javascript"></script>
    

  </head>
  <body>
    <div class="am-wrapper">
      <nav class="navbar navbar-default navbar-fixed-top am-top-header">
        <div class="container-fluid">
          <div class="navbar-header">
            <div class="page-title"><span>Dashboard</span></div>
            <a href="#" class="am-toggle-left-sidebar navbar-toggle collapsed">
                <span class="icon-bar"><span></span><span></span><span></span></span>
            </a>
            <a href="/" class="navbar-brand"><img src="<?php echo $this->basePath('assets/img/logo.png') ?>" style="width:100%;"/></a>
            
          </div>
          
          <div id="am-navbar-collapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right am-user-nav">
              <li class="dropdown">
                <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle"><img src="/assets/img/nobody.jpg">
                <span class="user-name">John Doe</span><span class="angle-down s7-angle-down"></span></a>
                <ul role="menu" class="dropdown-menu">
                  <li><a href="#"> <span class="icon s7-help1"></span>Help</a></li>
                  <li><a href="<?php echo $this->url('login', array('action' => 'logout')); ?>"> <span class="icon s7-power"></span>Sign Out</a></li>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav am-nav-right">
              <li><a href="/" style="font-size:1.8em;">Dashboard for Quality Improvement of HIV Rapid Testing</a></li>
            </ul>
<!--             <ul class="nav navbar-nav am-nav-right">
              <li><a href="javascript:alert('Under Construction')">Logbook Data Analysis</a></li>
              <li><a href="javascript:alert('Under Construction')">SPI M&E</a></li>
              <li><a href="javascript:alert('Under Construction')">SPI RT 2.x</a></li>
              <li><a href="/">SPI RT 3.0</a></li>
             </ul>-->
            
          </div>
        </div>
      </nav>
      <div class="am-left-sidebar">
        <div class="content">
          <div class="am-logo"><img src="<?php echo $this->basePath('assets/img/logo.png') ?>" style="width:50px;margin-left:10px;"/></div>
          <ul class="sidebar-elements">
            <?php
            if (isset($acl) && $acl->isAllowed($role, "Application\Controller\Index", "index")) {
            ?>
            <li class="parent"><a href="/"><i class="icon s7-monitor"></i><span>Dashboard</span></a></li>
            <?php } ?>
            <?php if(trim($auditMenu)!=""){ ?>
            <li class="parent"><a href="#"><i class="icon s7-ribbon"></i><span>Audit</span></a>
              <ul class="sub-menu">
                <?php echo $auditMenu; ?>
              </ul>
            </li>
            <?php } ?>
            <?php
            if (isset($acl) && $acl->isAllowed($role, "Application\Controller\Facility", "index")) {
            ?>
            <li class="parent"><a href="<?php echo $this->url('spi-facility',array('action' => 'index')); ?>"><i class="icon s7-note2"></i><span>Facility List</span></a></li>
            <?php } ?>
            
            <li class="parent"><a href="#"><i class="icon s7-graph"></i><span>Reports</span></a></li>
            <li class="parent"><a href="#"><i class="icon s7-mail"></i><span>Email</span></a></li>
            <li class="parent"><a href="#"><i class="icon s7-map-marker"></i><span>Maps</span></a></li>
            <?php
            if(trim($adminMenu)!=""){
            ?>
            <li class="parent"><a href="#"><i class="icon s7-config"></i><span>Configure</span></a>
              <ul class="sub-menu">
                <?php echo $adminMenu; ?>
              </ul>
            </li>
            <?php } ?>
          </ul>
          <!--Sidebar bottom content-->
        </div>
      </div>
      
      <?php echo $this->content; ?>
      
    </div>
    <div id="dDiv" class="dialog"> 
      <div style="text-align:center"><span onclick="closeModal();" style="float:right;clear:both;" class="closeModal"></span></div> 
      <iframe id="dFrame" src="" style="border:none;" scrolling='yes' marginwidth='0' marginheight='0' frameborder='0' vspace='0' hspace='0' >some problem</iframe> 
    </div>
    
    <script src="<?php echo $this->basePath('assets/lib/jquery.nanoscroller/javascripts/jquery.nanoscroller.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/js/main.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/bootstrap/dist/js/bootstrap.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery-flot/jquery.flot.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery-flot/jquery.flot.pie.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery-flot/jquery.flot.resize.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery-flot/plugins/jquery.flot.orderBars.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery-flot/plugins/curvedLines.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery.sparkline/jquery.sparkline.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery-ui/jquery-ui.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery.vectormap/jquery-jvectormap-1.2.2.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery.vectormap/maps/jquery-jvectormap-us-merc-en.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery.vectormap/maps/jquery-jvectormap-world-mill-en.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery.vectormap/maps/jquery-jvectormap-uk-mill-en.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery.vectormap/maps/jquery-jvectormap-fr-merc-en.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery.vectormap/maps/jquery-jvectormap-us-il-chicago-mill-en.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery.vectormap/maps/jquery-jvectormap-au-mill-en.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery.vectormap/maps/jquery-jvectormap-in-mill-en.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery.vectormap/maps/jquery-jvectormap-map.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/jquery.vectormap/maps/jquery-jvectormap-ca-lcc-en.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/countup/countUp.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/chartjs/Chart.js?v=0.1'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/js/app-dashboard.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/js/deforayValidation.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/js/deforayModal.js'); ?>" type="text/javascript"></script>
    <script type="text/javascript">
      $(document).ready(function(){
      	//initialize the javascript
      	App.init();
      	App.dashboard();
      
      });
      
      $(document).ready(function() {
            <?php
            if (isset($container->alertMsg) && $container->alertMsg != "") {
                ?>
                alert("<?php echo $container->alertMsg; ?>");
                <?php
                $container->alertMsg = "";
                unset($container->alertMsg);
            }
            ?>
      });
      function showModal(url, w, h) {
            showdefModal('dDiv', w, h);
            document.getElementById('dFrame').style.height = h + 'px';
            document.getElementById('dFrame').style.width = w + 'px';
            document.getElementById('dFrame').src = url;
        }

        function closeModal() {
            document.getElementById('dFrame').src = "";
            hidedefModal('dDiv');
        }
    </script>

  </body>
</html>