<?php
use Zend\Session\Container;
$container = new Container('alert');
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="<?php echo $this->basePath('assets/img/favicon.png'); ?>">
    <title>Malawi Dashboard for Quality Improvement of HIV Rapid Testing </title>
    
    <style type="text/css">
      .mandatory {
        color: red;
      }
    </style>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">    
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <script src="<?php echo $this->basePath('assets/lib/jquery/jquery.min.js'); ?>" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/ui-lightness/jquery-ui.css" />

  </head>
  <body>
    <div class="am-wrapper">
      <?php echo $this->content; ?>
    </div>
    <script src="<?php echo $this->basePath('assets/lib/bootstrap/dist/js/bootstrap.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/js/deforayValidation.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/js/deforayModal.js'); ?>" type="text/javascript"></script>
    <script>
      function showModal(url, w, h) {
            showdefModal('dDiv', w, h);
            document.getElementById('dFrame').style.height = h + 'px';
            document.getElementById('dFrame').style.width = w + 'px';
            document.getElementById('dFrame').src = url;
        }

        function closeModal() {
            document.getElementById('dFrame').src = "";
            hidedefModal('dDiv');
        }
    </script>
  </body>
</html>
