<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    <script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></scri    pt>
    <script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

    <div class="am-content">
        <div class="page-head">
            <h2>Edit Training</h2>
        </div>

        <div class="main-content">
            <div class="widget widget-fullwidth widget-small" style="padding:5px;">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="panel panel-default">
                            <div class="panel-body" >

                                <?php
                                $form = $this->form;
                                $form->setAttribute('action', $this->url(
                                                'training', array(
                                            'action' => 'edit',
                                            'training_id' => $this->training_id,
                                                )
                                ));
                                $form->prepare();
                                $form->get('Provider_id')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Provider',
                                    'autocomplete' => 'off'
                                ]);

                                $form->get('Start_date')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off'
                                ]);

                                $form->get('end_date')->setAttributes([
                                    'class' => 'form-control',
                                    'autocomplete' => 'off'
                                ]);
                                $form->get('type_of_training')->setAttributes([
                                    'class' => 'form-control',
                                ]);
                                $form->get('training_organization_id')->setAttributes([
                                    'class' => 'form-control'
                                ]);
                                $form->get('trainer_id')->setAttributes([
                                    'class' => 'form-control',
                                ]);
                                $form->get('score')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Score',
                                ]);

                                $form->get('Pass_fail')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Pass/fail']);
                                $form->get('training_certificate')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Training certificate']);
                                $form->get('Comments')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => 'Comments',
                                    'autocomplete' => 'off']);


                                echo $this->form()->openTag($form);
                                ?>
                                <?php echo $this->formHidden($form->get('training_id')->setAttribute('class', 'form-control')) ?>
                                <div class="form-group col-lg-6"> 
                                    <?= $this->formLabel($form->get('Provider_id')); ?>
                                    <?= $this->formElement($form->get('Provider_id')); ?>
                                    <?= $this->formElementErrors($form->get('Provider_id')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('Start_date')); ?>
                                    <?= $this->formElement($form->get('Start_date')); ?>
                                    <?= $this->formElementErrors($form->get('Start_date')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('end_date')); ?>
                                    <?= $this->formElement($form->get('end_date')); ?>
                                    <?= $this->formElementErrors($form->get('end_date')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('type_of_training')); ?>
                                    <?= $this->formElement($form->get('type_of_training')); ?>
                                    <?= $this->formElementErrors($form->get('type_of_training')); ?></div>
                                <div class="form-group col-lg-6">  
                                    <?= $this->formLabel($form->get('training_organization_id')); ?>
                                    <?= $this->formElement($form->get('training_organization_id')); ?>
                                    <?= $this->formElementErrors($form->get('training_organization_id')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('trainer_id')); ?>
                                    <?= $this->formElement($form->get('trainer_id')); ?>
                                    <?= $this->formElementErrors($form->get('trainer_id')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('score')); ?>
                                    <?= $this->formElement($form->get('score')); ?>
                                    <?= $this->formElementErrors($form->get('score')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('Pass_fail')); ?>
                                    <?= $this->formElement($form->get('Pass_fail')); ?>
                                    <?= $this->formElementErrors($form->get('Pass_fail')); ?>
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('training_certificate')); ?>
                                    <?= $this->formElement($form->get('training_certificate')); ?>
                                    <?= $this->formElementErrors($form->get('training_certificate')); ?>       
                                </div>
                                <div class="form-group col-lg-6">
                                    <?= $this->formLabel($form->get('Comments')); ?>
                                    <?= $this->formElement($form->get('Comments')); ?>
                                    <?= $this->formElementErrors($form->get('Comments')); ?>
                                </div>
                                <div class="form-group col-lg-4" ><?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                    <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('training', array('action' => 'index')); ?>" >CANCEL</a> </div>
                                    <?php echo $this->form()->closeTag();
                                    ?>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <br>
            <br>

        </div>

    </div>



    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

    <script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


    <script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>

  <script>
      $(document).ready(function() {

          $("#date").datepicker(
          {
          showButtonPanel: true
                  , dateFormat: 'yy/mm/dd'
                  , dayNamesMin: ['Di', 'Lu', 'Ma', 'Me', 'Je', 'Ve', 'Sa']
                  , dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi']
                  , monthNamesShort: ['Jan', 'Fev', 'Mar', 'Avr', 'Mai', 'Jun', 'Jul', 'Août', 'Sep', 'Oct', 'Nov', 'Déc']
                  , monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre']
                  , prevText: 'Précédent'
                  , nextText: 'Suivant'
    , closeText: 'OK'
    , currentText: "Aujour'dhui"
                    });
                
                        }); //EOf:: DOM isReady
                        
                            $(document).ready(function() {

                  $("#date2").datepicker(
          {
          showButtonPanel: true
                  , dateFormat: 'yy/mm/dd'
                  , dayNamesMin: ['Di', 'Lu', 'Ma', 'Me', 'Je', 'Ve', 'Sa']
                  , dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi']
                  , monthNamesShort: ['Jan', 'Fev', 'Mar', 'Avr', 'Mai', 'Jun', 'Jul', 'Août', 'Sep', 'Oct', 'Nov', 'Déc']
    , monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre']
                  , prevText: 'Précédent'
                  , nextText: 'Suivant'
                  , closeText: 'OK'
                  , currentText: "Aujour'dhui"
                                    });
                                    
                                        }); //EOf:: DOM isReady
        </script>




