<style>
    .highcharts-legend {
        display: none;
    }

    .highcharts-title {
        display: none;
    }
</style>
<div id="container-section-zero-protocol" style=" width: 100%; height: 465px; margin: 0 auto"></div>
<div class="row chart-info">
    <div class="col-xs-4" style="text-align:center;"><span class="title"><?= $this->translate('From Date'); ?></span><span class="number"><?php if (isset($perf1[0]['oldestDate']) && trim($perf1[0]['oldestDate']) != '') {
                                                                                                                                                echo $this->humanReadableDateFormat($perf1[0]['oldestDate']);
                                                                                                                                            } else {
                                                                                                                                                echo "-";
                                                                                                                                            } ?></span></div>
    <div class="col-xs-4" style="text-align:center;padding-left:5px;;"><span class="title"><?= $this->translate('To Date'); ?></span><span class="number"><?php if (isset($perf1[0]['newestDate']) && trim($perf1[0]['newestDate']) != '') {
                                                                                                                                                                echo $this->humanReadableDateFormat($perf1[0]['newestDate']);
                                                                                                                                                            } else {
                                                                                                                                                                echo "-";
                                                                                                                                                            } ?></span></div>
    <div class="col-xs-4" style="text-align:center;"><span class="title"><?= $this->translate('No. of Audits'); ?></span><span class="number"><?php echo $perf1[0]['totalDataPoints']; ?></span></div>
</div>
<script>
    $(document).ready(function() {
        //initialize the javascript
        radar_chart();
    });

    function radar_chart() {
        $('#container-section-zero-protocol').highcharts({

            chart: {
                polar: true,
                type: 'line'
            },

            title: {
                text: '<?= $this->translate('Audit Performance D0'); ?>',
                //x: -80
            },

            pane: {
                size: '90%'
            },

            xAxis: {
                categories: ["HIV above 15","Screened for participation", "Eligible during Review", "Eligible and declined", "Documented and refused", "Enrolled in RTRI", "Incorrectly Enrolled","Correctly Enrolled"],
                tickmarkPlacement: 'on',
                lineWidth: 0
            },


            yAxis: {
                gridLineInterpolation: 'polygon',

            },

            tooltip: {
                shared: true,
                pointFormat: '<span style="color:{series.color}">X: <b>{point.y:0f}</b><br/>'
            },
            series: [
                <?php
                foreach ($auditRoundWiseData as $auditNo => $adata) {
                ?> {
                        //name : 'Audit < ?php echo $auditNo; ?>',
                        name: 'Audit Performance',
                        pointPlacement: 'on',
                        data: [<?php echo round($adata['DIAGNOSED_HIV_ABOVE_15'], 2); ?>,
                            <?php echo round($adata['CANDIDATE_SCREENED_FOR_PARTICIPATION'], 2); ?>,
                            <?php echo round($adata['ELIGIBLE_DURING_REVIEW_PERIOD'], 2); ?>,
                            <?php echo round($adata['ELIGIBLE_AND_DECLINED_REVIEW_PERIOD'], 2); ?>,
                            <?php echo round($adata['DOCUMENTED_AND_REFUSED'], 2); ?>,
                            <?php echo round($adata['PARTICIAPANTS_ENROLLED_IN_RTRI'], 2); ?>,
                            <?php echo round($adata['PARTICIAPANTS_INCORRECTLY_ENROLLED_IN_RTRI'], 2); ?>,
                            <?php echo round($adata['PARTICIAPANTS_CORRECTLY_ENROLLED_IN_RTRI'], 2); ?>
                        ],
                    },
                <?php
                }
                ?>
            ]

        });
    }
</script>