<style>
    .highcharts-legend {
        display: none;
    }

    .highcharts-title {
        display: none;
    }
</style>
<div id="container-section-zero" style=" width: 100%; height: 465px; margin: 0 auto"></div>
<div class="row chart-info">
    <div class="col-xs-4" style="text-align:center;"><span class="title"><?= $this->translate('From Date'); ?></span><span class="number"><?php if (isset($perf1[0]['oldestDate']) && trim($perf1[0]['oldestDate']) != '') {
                                                                                                                                                echo $this->humanDateFormat($perf1[0]['oldestDate']);
                                                                                                                                            } else {
                                                                                                                                                echo "-";
                                                                                                                                            } ?></span></div>
    <div class="col-xs-4" style="text-align:center;padding-left:5px;;"><span class="title"><?= $this->translate('To Date'); ?></span><span class="number"><?php if (isset($perf1[0]['newestDate']) && trim($perf1[0]['newestDate']) != '') {
                                                                                                                                                                echo $this->humanDateFormat($perf1[0]['newestDate']);
                                                                                                                                                            } else {
                                                                                                                                                                echo "-";
                                                                                                                                                            } ?></span></div>
    <div class="col-xs-4" style="text-align:center;"><span class="title"><?= $this->translate('No. of Audits'); ?></span><span class="number"><?php echo $perf1[0]['totalDataPoints']; ?></span></div>
</div>
<script>
    $(document).ready(function() {

        $('#container-section-zero').highcharts({

            chart: {
                polar: true,
                type: 'line',
                reflow: true
            },

            title: {
                text: '<?= $this->translate('Audit Performance S0'); ?>',
                //x: -80
            },

            pane: {
                size: '90%'
            },

            xAxis: {
                categories: ["Surveilance Eligibility", "Counselor Protocol", "Recency Test Recorded", "Process Documented", "2 weeks Results", "Violation Documented", "Documented Errors"],
                tickmarkPlacement: 'on',
                lineWidth: 0
            },


            yAxis: {
                gridLineInterpolation: 'polygon',

            },

            tooltip: {
                shared: true,
                pointFormat: '<span style="color:{series.color}">X: <b>{point.y:0f}</b><br/>'
            },
            series: [
                <?php
                foreach ($auditRoundWiseData as $auditNo => $adata) {
                ?> {
                        //name : 'Audit < ?php echo $auditNo; ?>',
                        name: 'Audit Performance',
                        pointPlacement: 'on',
                        data: [<?php echo round($adata['SURVEILLANCE_STUDY_PROTOCOL_ELIGIBILITY'], 2); ?>,
                            <?php echo round($adata['COUNSELORS_FOLLOWING_PROTOCOL'], 2); ?>,
                            <?php echo round($adata['TESTS_RECORDED_RECENCY'], 2); ?>,
                            <?php echo round($adata['PROCESS_DOCUMENTED'], 2); ?>,
                            <?php echo round($adata['RESULTS_RETURNED_IN_TWO_WEEKS'], 2); ?>,
                            <?php echo round($adata['PROTOCOL_VIOLATION_DOCUMENTED'], 2); ?>,
                            <?php echo round($adata['DOCUMENTING_PROTOCOL_ERRORS'], 2); ?>
                        ],
                    },
                <?php
                }
                ?>
            ]

        });
    });
</script>