<?php
use Application\Service\FpdiExtends;
use Application\Service\TcpdfExtends;
use Application\Service\CommonService;


$configFile = CONFIG_PATH . DIRECTORY_SEPARATOR . "label-spi-v6.php";
$fileContents = file_get_contents($configFile);
//Convert the JSON string back into an array.
$decoded = json_decode($fileContents, true);
$language = $configData['language'];
// Check if the template_file is set in $configData
if (isset($configData['template_file']) && !empty($configData['template_file'])) {
    // Use FpdiExtends if the template_file is provided
    $pdf = new FpdiExtends('P', 'mm', 'A4', true, 'UTF-8', false, false);
    $pdf->setParams($configData['template_file'], $configData['template_top_margin']);
} else {
    // Use TCPDF as a fallback when template_file is not provided
    $pdf = new TcpdfExtends(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    $pdf->setSchemeName(ucwords($configData['header']), $configData['logo']);
}

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('ODK DASHBOARD');
$pdf->SetTitle('SPI-RT Checklist');
$pdf->SetSubject('ODK DASHBOARD');
$pdf->SetKeywords('odk', 'odk dashboard');


// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

// set header and footer fonts
$pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, 38, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, 45);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__) . '/lang/eng.php')) {
  require_once(dirname(__FILE__) . '/lang/eng.php');
  $pdf->setLanguageArray($l);
}
// ---------------------------------------------------------

// set font
$pdf->SetFont('times', '', 10);

// add a page
$pdf->AddPage();

//$pdf->SetY(20,true,false);

$partA = '<p style="font-weight:bold;line-height:24px;">' . $decoded[$language]['/SPI_RT/TESTSITE/FACILITY/info2:label'] . '</p>';
//$partA.='<br/>';

$pdf->writeHTML($partA, true, 0, true, 0);

$pdf->writeHTMLCell('', 12, '', '', '<p>' . $decoded[$language]['/SPI_RT/TESTSITE/FACILITY/info2:hint'] . '</p>', 0, 1, false, true, 'L', true);
if ($language == 'Portuguese') {
  $langDateFormat = '(dd/mm/aaaa)';
} else if ($language == 'Spanish') {
  $langDateFormat = '(dd/mm/aaaa)';
} else {
  $langDateFormat = '(dd/mm/yyyy)';
}
//echo '<pre>'; print_r($formData); die;
$fId = (isset($formData['facilityInfo']['ffId'])) ? ucwords($formData['facilityInfo']['ffId']) : '';
$fName = (isset($formData['facilityInfo']['fName'])) ? ucwords($formData['facilityInfo']['fName']) : '';
$testingTab = '<table border="1" cellspacing="0" cellpadding="5">';
$testingTab .= '<tr>';
$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/assesmentofaudit:label'] . '</b>' . $langDateFormat . ': ' . $this->humanReadableDateFormat($formData['assesmentofaudit']) . '</td>';
$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/auditroundno:label'] . '</b> ' . $formData['auditroundno'] . '</td>';
$testingTab .= '</tr>';

$testingTab .= '<tr>';
$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/facilityname:label'] . '</b> ' . $fName . '</td>';
if ($language == 'Portuguese') {
  $testingTab .= '<td><b>Identificacao do local de testagem </b>(se aplicavel): ' . $fId . '</td>';
} else if ($language == 'Spanish') {
  $testingTab .= '<td><b>Tipo de sitio de pruebas </b>(seleccione uno): ' . $fId . '</td>';
} else {
  $testingTab .= '<td><b>Testing Facility ID</b>(if applicable) : ' . $fId . '</td>';
}
$testingTab .= '</tr>';

$testingTab .= '<tr>';
//$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/testingpointname:label'] . '</b> ' . $formData['testingpointname'] . '</td>';
$testingTab .= '<td colspan="2"><b>' . $decoded[$language]['/SPI_RT/TESTSITE/testingpointtype:label'] . '</b> ' . $formData['testingpointtype'];
$testingTab .= ((isset($formData['testingpointtype_other']) && $formData['testingpointtype_other'] != "") ? " - " . $formData['testingpointtype_other'] : "") . '</td>';
$testingTab .= '</tr>';

$testingTab .= '<tr>';
$testingTab .= '<td colspan="2"><b>' . $decoded[$language]['/SPI_RT/TESTSITE/locationaddress:label'] . '</b> ' . $formData['physicaladdress'] . '</td>';
$testingTab .= '</tr>';

$testingTab .= '<tr>';
$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/level:label'] . '</b> <br/>' . $formData['level'];
$testingTab .= ((isset($formData['level_other']) && $formData['level_other'] != "") ? " Other - " . $formData['level_other'] : "") . ':' . $formData['level_other'];
$testingTab .= '</td>';
$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/affiliation:label'] . '</b><br/>' . $formData['affiliation'];
$testingTab .= ((isset($formData['affiliation_other']) && $formData['affiliation_other'] != "") ? " Other : " . $formData['affiliation_other'] : "");
$testingTab .= '</td>';
$testingTab .= '</tr>';

$testingTab .= '<tr>';
$testingTab .= '<td colspan="2"><b>' . $decoded[$language]['/SPI_RT/TESTSITE/NumberofTester:label'] . '</b>' . $formData['NumberofTester'] . '</td>';
//$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/avgMonthTesting:label'] . '</b>' . $formData['avgMonthTesting'] . '</td>';
$testingTab .= '</tr>';

$testingTab .= '<tr>';
$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/name_auditor_lead:label'] . '</b>' . $formData['name_auditor_lead'] . '</td>';
$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/name_auditor2:label'] . '</b>' . $formData['name_auditor2'] . '</td>';
$testingTab .= '</tr>';

$testingTab .= '<tr>';
$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/clients_tested_hiv:label'] . '</b></td>';
$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/per_month:label'] . '</b>' . $formData['client_tested_HIV_PM'] . '<br/>';
$testingTab .= '   <b>' . $decoded[$language]['/SPI_RT/TESTSITE/per_quarter:label'] . '</b>' . $formData['client_tested_HIV_PQ'] . '</td>';
$testingTab .= '</tr>';

$testingTab .= '<tr>';
$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/new_hiv:label'] . '</b></td>';
$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/per_month:label'] . '</b>' . $formData['client_newly_HIV_PM'] . '<br/>';
$testingTab .= '   <b>' . $decoded[$language]['/SPI_RT/TESTSITE/per_quarter:label'] . '</b>' . $formData['client_newly_HIV_PQ'] . '</td>';
$testingTab .= '</tr>';

$testingTab .= '<tr>';
$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/hiv_negative:label'] . '</b></td>';
$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/per_month:label'] . '</b>' . $formData['client_negative_HIV_PM'] . '<br/>';
$testingTab .= '   <b>' . $decoded[$language]['/SPI_RT/TESTSITE/per_quarter:label'] . '</br>' . $formData['client_negative_HIV_PQ'] . '</td>';
$testingTab .= '</tr>';

$testingTab .= '<tr>';
$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/newly_identified_positives:label'] . '</b></td>';
$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/per_month:label'] . '</b>' . $formData['client_positive_HIV_RTRI_PM'] . '<br/>';
$testingTab .= '   <b>' . $decoded[$language]['/SPI_RT/TESTSITE/per_quarter:label'] . '</br>' . $formData['client_positive_HIV_RTRI_PQ'] . '</td>';
$testingTab .= '</tr>';

$testingTab .= '<tr>';
$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/recent_identified_positives:label'] . '</b></td>';
$testingTab .= '<td><b>' . $decoded[$language]['/SPI_RT/TESTSITE/per_month:label'] . '</b>' . $formData['client_recent_RTRI_PM'] . '<br/>';
$testingTab .= '   <b>' . $decoded[$language]['/SPI_RT/TESTSITE/per_quarter:label'] . '</br>' . $formData['client_recent_RTRI_PQ'] . '</td>';
$testingTab .= '</tr>';
$testingTab .= '</table>';

$pdf->writeHTML($testingTab, true, 0, true, 0);


$partCTitle = '<p style="font-weight:bold;">PART C: SCORING CRITERIA</p>';
$pdf->writeHTML($partCTitle, true, 0, true, 0);
$partCtableBox1 = '<table cellpadding="2">';
$partCtableBox1 .= "<tr><td>
  <p>Each element marked will be assigned a point value: • Items marked “Yes” receive 1 point each. • Items marked “Partial”
  receive 0.5 point each. • Items marked “No” receive 0 point each.</p>
  <p>Total points scored for each section should be tallied and recorded at the end of the section</p>
  <p>The overall total points obtained by each HIV testing point audited will be weighed to correspond to a specific performance
  level.</p>
</td></tr>";
$partCtableBox1 .= '</table>';
$partCtableBox1 .= '</table>';
$pdf->writeHTML($partCtableBox1, true, 0, true, 0);

$partCTable = '<table border="1" cellspacing="0" cellpadding="5">';
$partCTable .= '<tr style="font-weight:bold;text-align:center;">';
$partCTable .= '<td style="width:15%">Levels</td>';
$partCTable .= '<td  style="width:25%">% Score</td>';
$partCTable .= '<td  style="width:60%">Description of results</td>';
$partCTable .= '</tr>';

$partCTable .= '<tr style="text-align:left;">';
$partCTable .= '<td style="width:15%;background-color:#C00000;">Level 0</td>';
$partCTable .= '<td  style="width:25%">Less than 40%</td>';
$partCTable .= '<td  style="width:60%">Needs improvement in all areas and immediate remediation</td>';
$partCTable .= '</tr>';

$partCTable .= '<tr style="text-align:left;">';
$partCTable .= '<td style="width:15%;background-color:#E36C0A;">Level 1</td>';
$partCTable .= '<td  style="width:25%">40% - 59%</td>';
$partCTable .= '<td  style="width:60%">Needs improvement in specific areas</td>';
$partCTable .= '</tr>';

$partCTable .= '<tr style="text-align:left;">';
$partCTable .= '<td style="width:15%;background-color:#FFFF00;">Level 2</td>';
$partCTable .= '<td  style="width:25%">60% - 79%</td>';
$partCTable .= '<td  style="width:60%">Partially eligible</td>';
$partCTable .= '</tr>';

$partCTable .= '<tr style="text-align:left;">';
$partCTable .= '<td style="width:15%;background-color:#92D050;">Level 3</td>';
$partCTable .= '<td  style="width:25%">80% - 89%</td>';
$partCTable .= '<td  style="width:60%">Close to national site certification</td>';
$partCTable .= '</tr>';

$partCTable .= '<tr style="text-align:left;">';
$partCTable .= '<td style="width:15%;background-color:#00B050;">Level 4</td>';
$partCTable .= '<td  style="width:25%">90% or higher</td>';
$partCTable .= '<td  style="width:60%">Eligible to national site certification</td>';
$partCTable .= '</tr>';
$partCTable .= '</table>';

$pdf->writeHTML($partCTable, true, 0, true, 0);


$partDTitle = '<p style="font-weight:bold;line-height:30px;">Part D. Auditor\'s Summation Report for SPI-RT Audit</p>';
$pdf->writeHTML($partDTitle, true, 0, true, 0);

$partDtableBox1 = '<table cellspacing="0" cellpadding="2">';
$partDtableBox1 .= "<tr><td>Facility Name:" . $formData['facilityname'] . "</td></tr><tr><td>Site Type:" . $formData['testingpointtype'];
$partDtableBox1 .= ((isset($formData['testingpointtype_other']) && $formData['testingpointtype_other'] != "") ? " - " . $formData['testingpointtype_other'] : "");
$partDtableBox1 .= "</td></tr>";
$partDtableBox1 .= "<tr><td>Staff Audited Name: " . $formData['staffaudited'] . "</td></tr>";
$partDtableBox1 .= '</table>';
$pdf->writeHTMLCell(50, 26, '', '', $partDtableBox1, 1, 0, 0, true, 'L');

$partDtableBox2 = '<table cellspacing="0" cellpadding="5">';
$partDtableBox2 .= "<tr><td>No. of Tester(s): " . $formData['NumberofTester'] . "</td></tr><tr><td>Duration of Audit: " . $formData['durationaudit'] . "</td></tr>";
$partDtableBox2 .= '</table>';

$pdf->writeHTMLCell(50, 26, 70, '', $partDtableBox2, 1, 0, 0, true, 'L', true);

$scorePer = round($formData['AUDIT_SCORE_PERCENTAGE_ROUNDED']);
$level = '';
$colorCode = '';
if ($scorePer < 40) {
  $level = "Level 0";
  $colorCode = "background-color:#C00000";
} elseif ($scorePer >= 40 && $scorePer <= 59) {
  $level = "Level 1";
  $colorCode = "background-color:#E36C0A";
} elseif ($scorePer >= 60 && $scorePer <= 79) {
  $level = "Level 2";
  $colorCode = "background-color:#FFFF00";
} elseif ($scorePer >= 80 && $scorePer <= 89) {
  $level = "Level 3";
  $colorCode = "background-color:#92D050";
} elseif ($scorePer >= 90) {
  $level = "Level 4";
  $colorCode = "background-color:#00B050";
}

$partDtableBox3 = '<table cellspacing="0" cellpadding="5">';
$partDtableBox3 .= "<tr><td>Total points scored (exclude N/A) = " . $formData['FINAL_AUDIT_SCORE'] . "</td></tr>";
$partDtableBox3 .= "<tr><td>Total score expected = " . $formData['MAX_AUDIT_SCORE'] . "</td></tr>";
$partDtableBox3 .= '<tr><td>% Score = ' . round($formData['AUDIT_SCORE_PERCENTAGE_ROUNDED'], 2) . '% &nbsp; <span style="' . $colorCode . '">  &nbsp;&nbsp;' . $level . '  &nbsp;&nbsp;</span></td></tr>';
$partDtableBox3 .= '</table>';

$pdf->writeHTMLCell(70, 26, 125, '', $partDtableBox3, 1, 1, 0, true, 'L', true);

$partDTable = '<br/><br/><table border="1" cellspacing="0" cellpadding="5" style="width:100%">';
$partDTable .= '<tr>';
$partDTable .= '<td rowspan="2" style="font-weight:bold;text-align:center;width:9%"><br/><br/>Section No.</td>';
$partDTable .= '<td rowspan="2" style="font-weight:bold;text-align:center;width:22%"><br/><br/>Deficiency/Issue observed</td>';
$partDTable .= '<td colspan="2" style="font-weight:bold;text-align:center;width:20%">Correction Actions</td>';
$partDTable .= '<td rowspan="2" style="font-weight:bold;text-align:center;width:23%">Auditor\'s <br/>Comments</td>';
$partDTable .= '<td colspan="2" style="font-weight:bold;text-align:center;width:26%">Recommendations</td>';
$partDTable .= '</tr>';
$partDTable .= '<tr>';
$partDTable .= '<td style="font-weight:bold;text-align:center;width:12%;">Immediate</td>';
$partDTable .= '<td style="font-weight:bold;text-align:center;width:8%;">Follow up</td>';
$partDTable .= '<td style="font-weight:bold;text-align:center;">Actions</td>';
$partDTable .= '<td style="font-weight:bold;text-align:center;">Timeline / Person responsible</td>';
$partDTable .= '</tr>';
if (isset($formData['correctiveaction']) && $formData['correctiveaction'] != ""  && $formData['correctiveaction'] != "[]") {
  $correctiveActions = json_decode($formData['correctiveaction'], true);
  if (isset($correctiveActions[0]['sectionno'])) {
    foreach ($correctiveActions as $ca) {
      $partDTable .= '<tr nobr="true">';
      $partDTable .= '<td style="text-align:center;">' . $ca['sectionno'] . '</td>';
      $partDTable .= '<td>' . $ca['deficiency'] . '</td>';
      $partDTable .= '<td style="text-align:center;">';
      $partDTable .= ($ca['correction'] == 'Immediate' ? '<img src="' . $this->basePath('assets/img/black-tick.png') . '" width="20">' : "");
      $partDTable .= '</td>';
      $partDTable .= '<td style="text-align:center;">';
      $partDTable .= ($ca['correction'] == 'Followup' ? '<img src="' . $this->basePath('assets/img/black-tick.png') . '" width="20">' : "");
      $partDTable .= '</td>';
      $partDTable .= '<td>' . $ca['auditorcomment'] . '</td>';
      $partDTable .= '<td>' . $ca['action'] . '</td>';
      $partDTable .= '<td>' . $ca['timeline'] . '</td>';
      $partDTable .= '</tr>';
    }
  } else {
    $categories = [
      'PERSONAL' => [
          'IMMEDIATE' => 'PERSONAL_CORRECTIVE_ACTIONS_IMMEDIATE',
          'FOLLOWUP' => 'PERSONAL_CORRECTIVE_ACTIONS_FOLLOWUP'
      ],
      'PHYSICAL' => [
          'IMMEDIATE' => 'PHYSICAL_CORRECTIVE_ACTIONS_IMMEDIATE',
          'FOLLOWUP' => 'PHYSICAL_CORRECTIVE_ACTIONS_FOLLOWUP'
      ],
      'SAFETY' => [
          'IMMEDIATE' => 'SAFETY_CORRECTIVE_ACTIONS_IMMEDIATE',
          'FOLLOWUP' =>  'SAFETY_CORRECTIVE_ACTIONS_FOLLOWUP'
      ],
      'PRETEST' => [
          'IMMEDIATE' => 'PRETEST_CORRECTIVE_ACTIONS_IMMEDIATE',
          'FOLLOWUP' =>  'PRETEST_CORRECTIVE_ACTIONS_FOLLOWUP'
      ],
      'TEST' => [
          'IMMEDIATE' => 'TEST_CORRECTIVE_ACTIONS_IMMEDIATE',
          'FOLLOWUP' =>  'TEST_CORRECTIVE_ACTIONS_FOLLOWUP'
      ],
      'POSTTEST' => [
          'IMMEDIATE' => 'POSTTEST_CORRECTIVE_ACTIONS_IMMEDIATE',
          'FOLLOWUP' =>  'POSTTEST_CORRECTIVE_ACTIONS_FOLLOWUP'
      ],
      'EQA' => [
          'IMMEDIATE' => 'EQA_CORRECTIVE_ACTIONS_IMMEDIATE',
          'FOLLOWUP' =>  'EQA_CORRECTIVE_ACTIONS_FOLLOWUP'
      ],
      'RTRI_SECTION' => [
          'IMMEDIATE' => 'RTRI_CORRECTIVE_ACTIONS_IMMEDIATE',
          'FOLLOWUP' =>  'RTRI_CORRECTIVE_ACTIONS_FOLLOWUP'
      ]
    ];
    foreach ($categories as $category => $actions) {
        foreach ($actions as $type => $key) {
            if (isset($correctiveActions[$key])) {
                $data = $correctiveActions[$key];
                $partDTable .= '<tr nobr="true">';
                $partDTable .= '<td style="text-align:center;">' . ($data[$category . '_SECTIONNO_' . $type] ?? '') . '</td>';
                $partDTable .= '<td>' . ($data[$category . '_DEFICIENCY_' . $type] ?? '') . '</td>';
                $partDTable .= '<td style="text-align:center;">';
                $partDTable .= ($type == 'IMMEDIATE' ? '<img src="' . APPLICATION_PATH . '/public/assets/img/black-tick.png' . '" width="20">' : "");
                $partDTable .= '</td>';
                $partDTable .= '<td style="text-align:center;">';
                $partDTable .= ($type == 'FOLLOWUP' ? '<img src="' . APPLICATION_PATH . '/public/assets/img/black-tick.png' . '" width="20">' : "");
                $partDTable .= '</td>';
                $partDTable .= '<td>' . ($data[$category . '_ACTION_' . $type] ?? '') . '</td>';
                $partDTable .= '<td>' . ($data[$category . '_RECOMMENDATIONS_' . $type] ?? '') . '</td>';
                $partDTable .= '<td>' . ($data[$category . '_TIMELINE_' . $type] ?? '') . '</td>';
                $partDTable .= '</tr>';
            }
        }
    }
  }
} else {
  $partDTable .= '<tr>';
  $partDTable .= '<td colspan="7">No Corrective Actions</td>';
  $partDTable .= '</tr>';
}
$partDTable .= '</table><br/><br/><br/>';
$pdf->writeHTML($partDTable, true, 0, true, 0);



$signImg = "";
$signArr = !empty($formData['auditorSignature']) ? json_decode($formData['auditorSignature']) : null;

if (
  !empty($configData['embed_signatures_in_pdf']) &&
  $configData['embed_signatures_in_pdf'] == "yes" &&
  (!empty($signArr) && isset($signArr->url) && !empty($signArr->url))
) {
  $signImg = '<img src="' . $signArr->url . '" width="90" />';
}

$signBox1 = '<table cellspacing="0" cellpadding="4">';
$signBox1 .= '<tr><td>Staff Audited Name: <br>' . $formData['staffaudited'] . '</td></tr>';
$signBox1 .= "<tr><td>Person in Charge Name: " . $formData['personincharge'] . "</td></tr>";
$signBox1 .= '</table>';
$pdf->writeHTMLCell(90, 18, '', '', $signBox1, 1, 0, 0, true, 'L');

$signBox2 = '<table cellspacing="0" cellpadding="4">';
$signBox2 .= "<tr><td>Auditor Signature:</td><td>" . $signImg . "</td></tr>";
$signBox2 .= "<tr><td>Date (dd/mm/yyyy):</td><td>" . $this->humanReadableDateFormat($formData['assesmentofaudit']) . "</td></tr>";
$signBox2 .= '</table>';
$pdf->writeHTMLCell(80, 18, 115, '', $signBox2, 1, 1, 0, true, 'L');

//Close and output PDF document
$fileName = "SPI-RT-CHECKLIST-" . date('d-M-Y-H-i-s') . ".pdf";
$filePath = TEMP_UPLOAD_PATH . DIRECTORY_SEPARATOR . $fileName;

$pdf->Output($filePath, "I");
//echo $fileName;
//============================================================+
// END OF FILE
//============================================================+
