<?php
use Application\Service\FpdiExtends;
use Application\Service\TcpdfExtends;
use Application\Service\CommonService;
// Check if the template_file is set in $configData
if (isset($configData['template_file']) && !empty($configData['template_file'])) {
    // Use FpdiExtends if the template_file is provided
    $pdf = new FpdiExtends('P', 'mm', 'A4', true, 'UTF-8', false, false);
    $pdf->setParams($configData['template_file']);
} else {
    // Use TCPDF as a fallback when template_file is not provided
    $pdf = new TcpdfExtends(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    $pdf->setSchemeName(ucwords($configData['header']), $configData['logo']);
}
// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('ODK DASHBOARD');
$pdf->SetTitle('SPI-RT Checklist');
$pdf->SetSubject('ODK DASHBOARD');
$pdf->SetKeywords('odk', 'odk dashboard');

// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

// set header and footer fonts
$pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);



// set font
$pdf->SetFont('times', '', 10);

// add a page
$pdf->AddPage();

$pdfContent = '<img src="' . $this->basePath('temporary/radar-d0-v6.png') . '" alt="PDF"/>';
$pdf->writeHTML($pdfContent, true, 0, true, 0);

//Close and output PDF document
$fileName = "SPI-D0-v6-Radar-" . date('d-M-Y-H-i-s') . ".pdf";
$filePath = TEMP_UPLOAD_PATH . DIRECTORY_SEPARATOR . $fileName;
$pdf->Output($filePath, "F");
echo $fileName;
//echo $fileName;
//============================================================+
// END OF FILE
//============================================================+
