<?php

use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;

use \Application\Service\CommonService;

$common = new CommonService();
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<div class="am-content">
  <div class="page-head">
    <h2><?= $this->translate('SPI-RT 6.0 Checklist (Possible Duplicate Audit(s))'); ?></h2>
  </div>

  <div class="main-content">
    <div class="widget widget-fullwidth widget-small" style="padding:5px;">
      <table id="example" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget">
        <thead>
          <tr>
            <th><?= $this->translate('Facility Name<'); ?>/th>
            <th style="width:8%;"><?= $this->translate('Audit Round Number'); ?></th>
            <th style="width:10%;"><?= $this->translate('Audit Date'); ?></th>
            <th style="width:10%;"><?= $this->translate('Testing Point Name'); ?></th>
            <th style="width:6%;"><?= $this->translate('Testing Point Type'); ?></th>
            <th style="width:8%;"><?= $this->translate('Level'); ?></th>
            <th><?= $this->translate('Affiliation'); ?></th>
            <th style="width:5%;"><?= $this->translate('Audit Score %'); ?></th>
            <th style="width:8%;"><?= $this->translate('Status'); ?></th>
            <th style="width:8%;"><?= $this->translate('Action'); ?></th>
          </tr>
        </thead>
        <tbody>
          <?php
          if (count($result) > 0) {
            foreach ($result as $duplicate) {
          ?>
              <tr>
                <td><?php echo $duplicate['facilityname']; ?></td>
                <td><?php echo $duplicate['auditroundno']; ?></td>
                <td><?php echo CommonService::humanReadableDateFormat($duplicate['assesmentofaudit']); ?></td>
                <td><?php echo $duplicate['testingpointname']; ?></td>
                <td><?php echo $duplicate['testingpointtype']; ?></td>
                <td><?php echo $duplicate['level']; ?></td>
                <td><?php echo $duplicate['affiliation']; ?></td>
                <td><?php echo round($duplicate['AUDIT_SCORE_PERCANTAGE'], 2); ?></td>
                <td><?php echo $duplicate['status']; ?></td>
                <td></td>
              </tr>
              <?php
              for ($i = 0; $i < ($duplicate['c'] - 1); $i++) {
              ?>
                <tr id="<?php echo $duplicate['id']; ?>">
                  <td><?php echo $duplicate['facilityname']; ?></td>
                  <td><?php echo $duplicate['auditroundno']; ?></td>
                  <td><?php echo CommonService::humanReadableDateFormat($duplicate['assesmentofaudit']); ?></td>
                  <td><?php echo $duplicate['testingpointname']; ?></td>
                  <td><?php echo $duplicate['testingpointtype']; ?></td>
                  <td><?php echo $duplicate['level']; ?></td>
                  <td><?php echo $duplicate['affiliation']; ?></td>
                  <td><?php echo round($duplicate['AUDIT_SCORE_PERCANTAGE'], 2); ?></td>
                  <td><?php echo $duplicate['status']; ?></td>
                  <td><a class="btn btn-danger btn-sm" href="javascript:void(0);" onclick="removeData('<?php echo $duplicate['id']; ?>');">Remove</a></td>
                </tr>
            <?php
              }
            }
          } else {
            ?>
            <tr>
              <td colspan="10" class="dataTables_empty"><?= $this->translate('No Data Available'); ?></td>
            </tr>
          <?php } ?>
        </tbody>
      </table>
    </div>
  </div>
</div>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
<script type="text/javascript">
  table = null;
  $(document).ready(function() {
    table = $('#example').DataTable();
  });

  function removeData(id) {
    var conf = confirm("<?= $this->translate('Are you sure you want to remove this duplicate audit?'); ?>");
    if (conf) {
        $.post("<?php echo $this->url('spi-v6-form', array('action' => 'remove-audit')); ?>", { id: id }, function(data) {
            if (data > 0) {
                alert("<?= $this->translate('Audit removed successfully'); ?>");
                $("#" + id).hide();
            }
        });
    }
}

</script>
