<style>
  th.details-control {
    background: url('<?php echo $this->basePath('assets/img/details_open.png'); ?>') no-repeat center center;
    cursor: pointer;
  }

  tr.shown th.details-control {
    background: url('<?php echo $this->basePath('assets/img/details_close.png'); ?>') no-repeat center center;
  }

  .select2-container .select2-selection--single {
    height: 40px;
  }

  .select2-container--default.select2-container--open .select2-selection--single .select2-selection__arrow b:after {
    content: ""
  }

  .select2-container--default .select2-selection--single .select2-selection__arrow b:after {
    content: ""
  }

  .select2-container--default .select2-selection--single .select2-selection__arrow b:before {
    content: ""
  }

  .select2-container--default .select2-selection--single .select2-selection__arrow b {
    margin-top: 6px;
  }

  .select2-container--default .select2-selection--single .select2-selection__rendered {
    line-height: 8px !important;
  }
</style>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>" />
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<div class="am-content">
  <div class="page-head">
    <h2><?= $this->translate('Edit SPI-RRT Form'); ?></h2>
  </div>
  <div class="main-content">
    <div class="widget widget-fullwidth widget-small" style="padding:5px;">
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default">
            <div class="panel-body">
              <form role="form" class="form-horizontal" name="editSPIRT" id="editSPIRT" method="post" action="<?php echo $this->url('spi-v6-form', array('action' => 'edit')); ?>" autocomplete="off">
                <h4><b><?= $this->translate('PART A: CHARACTERISTICS OF THE FACILITY OR TESTING POINT AUDITED'); ?></b></h4>
                <p><?= $this->translate('Before completing the checklist, it is important to characterize the testing point to be audited. Please provide relevant information in the summary table below.'); ?></p>
                <div class="form-group">
                  <label for="auditDate" class="col-sm-2 control-label"><?= $this->translate('Date of Audit (dd/mm/yyyy)'); ?></label>
                  <div class=" col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('Enter Date'); ?>" name="auditDate" class="form-control datepicker" value="<?php echo $this->humanReadableDateFormat($formData['assesmentofaudit']); ?>" readonly>
                  </div>
                  <label for="auditRound" class="col-sm-2 control-label"><?= $this->translate('Audit Round Number'); ?></label>
                  <div class=" col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('Audit Round No'); ?>" name="auditRound" class="form-control" value="<?php echo $formData['auditroundno']; ?>">
                    <input type="hidden" name="formId" id="formId" class="form-control" value="<?php echo base64_encode($formData['id']); ?>">
                  </div>
                </div>

                <div class="form-group">
                  <label for="testingFacility" class="col-sm-2 control-label"><?= $this->translate('Testing Facility'); ?></label>
                  <div class=" col-lg-4">
                    <select id="testingFacility" name="testingFacility" class="select2 form-control" onchange="getFacilityInfo();">
                      <option value=""> -- <?= $this->translate('Select'); ?> -- </option>
                      <?php
                      if (isset($facilities['allName']) && count($facilities['allName']) > 0) {
                        foreach ($facilities['allName'] as $facilities) {
                      ?>
                          <option value="<?php echo base64_encode($facilities['id']); ?>" <?php echo (isset($formData['facilityInfo']->fId) && $formData['facilityInfo']->fId == $facilities['id']) ? 'selected="selected"' : ''; ?>><?php echo ucwords($facilities['facility_name']); ?></option>
                      <?php }
                      } ?>
                    </select>
                  </div>
                  <label for="testingFacilityName" class="col-sm-2 control-label"><?= $this->translate('Testing Facility Name'); ?></label>
                  <div class=" col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('Testing Facility Name'); ?>" name="testingFacilityName" id="testingFacilityName" class="form-control" value="<?php echo (isset($formData['facilityInfo']->fName)) ? $formData['facilityInfo']->fName : ''; ?>" onblur="copyFacilityName(this.value)">
                  </div>
                </div>

                <div class="form-group">
                  <label for="testingFacilityId" class="col-sm-2 control-label"><?= $this->translate('Testing Facility ID'); ?></label>
                  <div class=" col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('Testing Facility ID'); ?>" name="testingFacilityId" id="testingFacilityId" class="form-control" value="<?php echo (isset($formData['facilityInfo']->ffId)) ? $formData['facilityInfo']->ffId : ''; ?>">
                  </div>
                  <label for="email" class="col-sm-2 control-label"><?= $this->translate('Email'); ?></label>
                  <div class=" col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('Email'); ?>" name="email" id="email" class="form-control isEmail" value="<?php echo (isset($formData['facilityInfo']->fEmail)) ? $formData['facilityInfo']->fEmail : ''; ?>">
                  </div>
                </div>

                <div class="form-group">
                  <label for="contactPerson" class="col-sm-2 control-label"><?= $this->translate('Name of the Contact Person'); ?></label>
                  <div class=" col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('Name of the Contact Person'); ?>" name="contactPerson" id="contactPerson" class="form-control" value="<?php echo (isset($formData['facilityInfo']->fCPerson)) ? $formData['facilityInfo']->fCPerson : ''; ?>">
                  </div>

                  <label for="latitude" class="col-sm-2 control-label"><?= $this->translate('Latitude'); ?></label>
                  <div class=" col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('Latitude'); ?>" name="latitude" id="latitude" class="form-control checkNum" value="<?php echo (isset($formData['facilityInfo']->fLatitude)) ? $formData['facilityInfo']->fLatitude : ''; ?>">
                  </div>
                </div>

                <div class="form-group ">
                  <label for="longitude" class="col-sm-2 control-label"><?= $this->translate('Longitude'); ?></label>
                  <div class=" col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('Longitude'); ?>" name="longitude" id="longitude" class="form-control checkNum" value="<?php echo (isset($formData['facilityInfo']->fLongitude)) ? $formData['facilityInfo']->fLongitude : ''; ?>">
                  </div>
                  <label for="testingPointType" class="col-sm-2 control-label"><?= $this->translate('Type of testing point'); ?></label>
                  <div class="col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('Type of testing point'); ?>" name="testingPointType" class="form-control" value="<?php echo $formData['testingpointtype']; ?>" onblur="copySiteType(this.value)">
                  </div>
                </div>

                <div class="form-group">
                  <label for="testingPointTypeOther" class="col-sm-2 control-label"><?= $this->translate('Testing point type other'); ?></label>
                  <div class="col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('Testing point type other'); ?>" name="testingPointTypeOther" class="form-control" value="<?php echo $formData['testingpointtype_other']; ?>">
                  </div>
                  <label for="location" class="col-sm-2 control-label"><?= $this->translate('Location/Address'); ?></label>
                  <div class="col-lg-4">
                    <textarea class="form-control" name="location" rows="5"><?php echo $formData['physicaladdress']; ?></textarea>
                  </div>
                </div>
                <div class="form-group">
                  <label for="level" class="col-sm-2 control-label"><?= $this->translate('Level'); ?></label>
                  <div class="col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('Level'); ?>" name="level" class="form-control" value="<?php echo $formData['level']; ?>">
                  </div>
                  <label for="levelOther" class="col-sm-2 control-label"><?= $this->translate('Level Other'); ?></label>
                  <div class="col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('Level Other'); ?>" name="levelOther" class="form-control" value="<?php echo $formData['level_other']; ?>">
                  </div>
                </div>
                <div class="form-group">
                  <label for="affiliation" class="col-sm-2 control-label"><?= $this->translate('Affiliation'); ?></label>
                  <div class="col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('Affiliation'); ?>" name="affiliation" class="form-control" value="<?php echo $formData['affiliation']; ?>">
                  </div>
                  <label for="affiliationOther" class="col-sm-2 control-label"><?= $this->translate('Affiliation Other'); ?></label>
                  <div class="col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('Affiliation'); ?>" name="affiliationOther" class="form-control" value="<?php echo $formData['affiliation_other']; ?>">
                  </div>
                </div>
                <div class="form-group">
                  <label for="numberOfTester" class="col-sm-2 control-label"><?= $this->translate('Number of Testers'); ?></label>
                  <div class="col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('Number of Testers'); ?>" name="numberOfTester" class="form-control" value="<?php echo $formData['NumberofTester']; ?>" onblur="copyNoOfTest(this.value)">
                  </div>
                  <label for="nameOfAuditor1" class="col-sm-2 control-label"><?= $this->translate('Name of the Auditor 1'); ?></label>
                  <div class="col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('"Name of the Auditor 1'); ?>" name="nameOfAuditor1" class="form-control" value="<?php echo $formData['name_auditor_lead']; ?>">
                  </div>
                </div>
                <div class="form-group ">
                  <label for="nameOfAuditor2" class="col-sm-2 control-label"><?= $this->translate('Name of the Auditor 2'); ?></label>
                  <div class="col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('Name of the Auditor 2'); ?>" name="nameOfAuditor2" class="form-control" value="<?php echo $formData['name_auditor2']; ?>">
                  </div>
                </div>
                <br />
                <div class="form-group col-lg-12">
                  <h4><b><?= $this->translate('PART B. SPI-RRT Checklist'); ?></b></h4>
                  <div>
                    <?= $this->translate('For each of the sections listed below, please check'); ?>
                    <b><?= $this->translate('Yes, Partial or No'); ?></b>
                    <?= $this->translate(', where applicable. Indicate "'); ?>
                    <b><?= $this->translate('Yes'); ?></b>
                    <?= $this->translate('" only when all elements are satisfactorily present. Provide comments for each "'); ?>
                    <b><?= $this->translate('Partial'); ?></b>
                    <?= $this->translate('" or "'); ?>
                    <b><?= $this->translate('No'); ?></b>
                    <?= $this->translate('" response. State N/A in the comments section if "not applicable" where appropriate (*).'); ?>
                  </div>
                  <br />


                  <table cellspacing="0" cellpadding="5" class="table table-bordered">
                    <tr id="personal1">
                      <th style="text-align:center;width:3%" class="details-control" onclick="$('#personal').slideToggle('slow'),addShowClass('shown','personal1');">

                      </th>
                      <th style="width:93%">
                        <a href="javascript:void(0);" onclick="$('#personal').slideToggle('slow'),addShowClass('shown','personal1');"><?= $this->translate('1.0 PERSONNEL TRAINING AND CERTIFICATION'); ?></a>
                      </th>
                      <th style="text-align:center;width:5%">10</th>
                    </tr>
                    <tr id="personal" style="display: none;">
                      <td colspan="7">
                        <table class="table table-bordered">
                          <tr>
                            <td style="text-align:center;font-weight:bold;width:45%;" colspan="2"><?= $this->translate('SECTION'); ?></td>
                            <th style="text-align:center;width:3%;"><?= $this->translate('YES'); ?></th>
                            <th style="text-align:center;width:4%;"><?= $this->translate('Partial'); ?></th>
                            <th style="text-align:center;width:3%;"><?= $this->translate('NO'); ?></th>
                            <th style="text-align:center;width:40%;"><?= $this->translate('Comments'); ?></th>
                            <th style="text-align:center;width:5%;"><?= $this->translate('Score'); ?></th>
                          </tr>
                          <tr>
                            <td style="width:3%;">1.1</td>
                            <td style="width:42%;"><?= $this->translate('Have all testers received a comprehensive training on HIV rapid testing using the nationally approved curriculum?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_1_HIV_TRAINING']) && $formData['PERSONAL_Q_1_1_HIV_TRAINING'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_1_HIV_TRAINING']) && $formData['PERSONAL_Q_1_1_HIV_TRAINING'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_1_HIV_TRAINING']) && $formData['PERSONAL_Q_1_1_HIV_TRAINING'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="personal_c_1_1"><?php echo ($formData['PERSONAL_C_1_1_HIV_TRAINING']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_1_HIV_TRAINING']); ?></td>
                          </tr>

                          <tr>
                            <td>1.2</td>
                            <td><?= $this->translate('Are the testers trained on the use of standardized HIV testing registers/logbooks?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_2_HIV_TESTING_REGISTER']) && $formData['PERSONAL_Q_1_2_HIV_TESTING_REGISTER'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_2_HIV_TESTING_REGISTER']) && $formData['PERSONAL_Q_1_2_HIV_TESTING_REGISTER'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_2_HIV_TESTING_REGISTER']) && $formData['PERSONAL_Q_1_2_HIV_TESTING_REGISTER'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="personal_c_1_2"><?php echo ($formData['PERSONAL_C_1_2_HIV_TESTING_REGISTER']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_2_HIV_TESTING_REGISTER']); ?></td>
                          </tr>

                          <tr>
                            <td>1.3</td>
                            <td><?= $this->translate('Are the testers trained on external quality assessment (EQA) or proficiency testing (PT) process?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_3_EQA_PT']) && $formData['PERSONAL_Q_1_3_EQA_PT'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_3_EQA_PT']) && $formData['PERSONAL_Q_1_3_EQA_PT'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_3_EQA_PT']) && $formData['PERSONAL_Q_1_3_EQA_PT'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="personal_c_1_3"><?php echo ($formData['PERSONAL_C_1_3_EQA_PT']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_3_EQA_PT']); ?></td>
                          </tr>

                          <tr>
                            <td>1.4</td>
                            <td><?= $this->translate('Are the testers trained on quality control (QC) process?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_4_QC_PROCESS']) && $formData['PERSONAL_Q_1_4_QC_PROCESS'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_4_QC_PROCESS']) && $formData['PERSONAL_Q_1_4_QC_PROCESS'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_4_QC_PROCESS']) && $formData['PERSONAL_Q_1_4_QC_PROCESS'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="personal_c_1_4"><?php echo ($formData['PERSONAL_C_1_4_QC_PROCESS']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_4_QC_PROCESS']); ?></td>
                          </tr>

                          <tr>
                            <td>1.5</td>
                            <td><?= $this->translate('Are the testers trained on safety and waste management procedures and practices?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_5_SAFETY_MANAGEMENT']) && $formData['PERSONAL_Q_1_5_SAFETY_MANAGEMENT'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_5_SAFETY_MANAGEMENT']) && $formData['PERSONAL_Q_1_5_SAFETY_MANAGEMENT'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_5_SAFETY_MANAGEMENT']) && $formData['PERSONAL_Q_1_5_SAFETY_MANAGEMENT'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="personal_c_1_5"><?php echo ($formData['PERSONAL_C_1_5_SAFETY_MANAGEMENT']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_5_SAFETY_MANAGEMENT']); ?></td>
                          </tr>

                          <tr>
                            <td>1.6</td>
                            <td><?= $this->translate('Have all testers received a refresher training within the last two years?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_6_REFRESHER_TRAINING']) && $formData['PERSONAL_Q_1_6_REFRESHER_TRAINING'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_6_REFRESHER_TRAINING']) && $formData['PERSONAL_Q_1_6_REFRESHER_TRAINING'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_6_REFRESHER_TRAINING']) && $formData['PERSONAL_Q_1_6_REFRESHER_TRAINING'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="personal_c_1_6"><?php echo ($formData['PERSONAL_C_1_6_REFRESHER_TRAINING']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_6_REFRESHER_TRAINING']); ?></td>
                          </tr>

                          <tr>
                            <td>1.7</td>
                            <td><?= $this->translate('Are there records indicating all testers have demonstrated competency in HIV rapid testing prior to client testing?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_7_HIV_COMPETENCY_TESTING']) && $formData['PERSONAL_Q_1_7_HIV_COMPETENCY_TESTING'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_7_HIV_COMPETENCY_TESTING']) && $formData['PERSONAL_Q_1_7_HIV_COMPETENCY_TESTING'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_7_HIV_COMPETENCY_TESTING']) && $formData['PERSONAL_Q_1_7_HIV_COMPETENCY_TESTING'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="personal_c_1_7"><?php echo ($formData['PERSONAL_C_1_7_HIV_COMPETENCY_TESTING']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_7_HIV_COMPETENCY_TESTING']); ?></td>
                          </tr>

                          <tr>
                            <td>1.8</td>
                            <td><?= $this->translate('Have all testers been certified through a national certification program?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_8_NATIONAL_CERTIFICATION']) && $formData['PERSONAL_Q_1_8_NATIONAL_CERTIFICATION'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_8_NATIONAL_CERTIFICATION']) && $formData['PERSONAL_Q_1_8_NATIONAL_CERTIFICATION'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_8_NATIONAL_CERTIFICATION']) && $formData['PERSONAL_Q_1_8_NATIONAL_CERTIFICATION'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="personal_c_1_8"><?php echo ($formData['PERSONAL_C_1_8_NATIONAL_CERTIFICATION']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_8_NATIONAL_CERTIFICATION']); ?></td>
                          </tr>

                          <tr>
                            <td>1.9</td>
                            <td><?= $this->translate('Are only certified testers performing HIV rapid testing at the site?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_9_CERTIFIED_TESTERS']) && $formData['PERSONAL_Q_1_9_CERTIFIED_TESTERS'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_9_CERTIFIED_TESTERS']) && $formData['PERSONAL_Q_1_9_CERTIFIED_TESTERS'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_9_CERTIFIED_TESTERS']) && $formData['PERSONAL_Q_1_9_CERTIFIED_TESTERS'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="personal_c_1_9"><?php echo ($formData['PERSONAL_C_1_9_CERTIFIED_TESTERS']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_9_CERTIFIED_TESTERS']); ?></td>
                          </tr>

                          <tr>
                            <td>1.10</td>
                            <td><?= $this->translate('Are all testers required to be re-certified periodically (e.g., every two years)?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_10_RECERTIFIED']) && $formData['PERSONAL_Q_1_10_RECERTIFIED'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_10_RECERTIFIED']) && $formData['PERSONAL_Q_1_10_RECERTIFIED'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PERSONAL_Q_1_10_RECERTIFIED']) && $formData['PERSONAL_Q_1_10_RECERTIFIED'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="personal_c_1_10"><?php echo ($formData['PERSONAL_C_1_10_RECERTIFIED']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo ($formData['PERSONAL_Q_1_10_RECERTIFIED']); ?></td>
                          </tr>

                          <tr>
                            <td colspan="6" style="font-weight:bold;"><?= $this->translate('1.0 PERSONNEL TRAINING AND CERTIFICATION SCORE'); ?> </td>
                            <td style="text-align:center;"><?php echo $formData['PERSONAL_SCORE']; ?></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>

                  <table cellspacing="0" cellpadding="5" class="table table-bordered">

                    <tr id="physical1">
                      <th style="text-align:center;width:3%" class="details-control" onclick="$('#physical').slideToggle('slow'),addShowClass('shown','physical1');">

                      </th>
                      <th style="width:93%">
                        <a href="javascript:void(0);" onclick="$('#physical').slideToggle('slow');"><?= $this->translate('2.0 PHYSICAL FACILITY'); ?></a>
                      </th>
                      <th style="text-align:center;width:5%">5</th>
                    </tr>
                    <tr id="physical" style="display: none;">
                      <td colspan="3">
                        <table class="table table-bordered">
                          <tr>
                            <td style="text-align:center;font-weight:bold;width:45%;" colspan="2"><?= $this->translate('SECTION'); ?></td>
                            <th style="text-align:center;width:3%;"><?= $this->translate('YES'); ?></th>
                            <th style="text-align:center;width:4%;"><?= $this->translate('Partial'); ?></th>
                            <th style="text-align:center;width:3%;"><?= $this->translate('NO'); ?></th>
                            <th style="text-align:center;width:40%;"><?= $this->translate('Comments'); ?></th>
                            <th style="text-align:center;width:5%;"><?= $this->translate('Score'); ?></th>
                          </tr>
                          <tr>
                            <td>2.1</td>
                            <td><?= $this->translate('Is there a designated area for HIV testing?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PHYSICAL_Q_2_1_DESIGNATED_HIV_AREA']) && $formData['PHYSICAL_Q_2_1_DESIGNATED_HIV_AREA'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PHYSICAL_Q_2_1_DESIGNATED_HIV_AREA']) && $formData['PHYSICAL_Q_2_1_DESIGNATED_HIV_AREA'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PHYSICAL_Q_2_1_DESIGNATED_HIV_AREA']) && $formData['PHYSICAL_Q_2_1_DESIGNATED_HIV_AREA'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="physical_c_2_1"><?php echo ($formData['PHYSICAL_C_2_1_DESIGNATED_HIV_AREA']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo ($formData['PHYSICAL_Q_2_1_DESIGNATED_HIV_AREA']); ?></td>
                          </tr>
                          <tr>
                            <td>2.2</td>
                            <td><?= $this->translate('Is the testing area clean and organized for HIV rapid testing?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PHYSICAL_Q_2_2_CLEAN_TESTING_AREA']) && $formData['PHYSICAL_Q_2_2_CLEAN_TESTING_AREA'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PHYSICAL_Q_2_2_CLEAN_TESTING_AREA']) && $formData['PHYSICAL_Q_2_2_CLEAN_TESTING_AREA'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PHYSICAL_Q_2_2_CLEAN_TESTING_AREA']) && $formData['PHYSICAL_Q_2_2_CLEAN_TESTING_AREA'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="physical_c_2_2"><?php echo ($formData['PHYSICAL_C_2_2_CLEAN_TESTING_AREA']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo ($formData['PHYSICAL_Q_2_2_CLEAN_TESTING_AREA']); ?></td>
                          </tr>
                          <tr>
                            <td>2.3</td>
                            <td><?= $this->translate('Is sufficient lighting available in the designated testing area?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PHYSICAL_Q_2_3_SUFFICIENT_LIGHT_AVAILABILITY']) && $formData['PHYSICAL_Q_2_3_SUFFICIENT_LIGHT_AVAILABILITY'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PHYSICAL_Q_2_3_SUFFICIENT_LIGHT_AVAILABILITY']) && $formData['PHYSICAL_Q_2_3_SUFFICIENT_LIGHT_AVAILABILITY'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PHYSICAL_Q_2_3_SUFFICIENT_LIGHT_AVAILABILITY']) && $formData['PHYSICAL_Q_2_3_SUFFICIENT_LIGHT_AVAILABILITY'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="physical_c_2_3"><?php echo ($formData['PHYSICAL_C_2_3_SUFFICIENT_LIGHT_AVAILABILITY']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo ($formData['PHYSICAL_Q_2_3_SUFFICIENT_LIGHT_AVAILABILITY']); ?></td>
                          </tr>
                          <tr>
                            <td>2.4</td>
                            <td><?= $this->translate('Are the test kits stored according to manufacturers’ instructions?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PHYSICAL_Q_2_4_TEST_KIT_STORAGE']) && $formData['PHYSICAL_Q_2_4_TEST_KIT_STORAGE'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PHYSICAL_Q_2_4_TEST_KIT_STORAGE']) && $formData['PHYSICAL_Q_2_4_TEST_KIT_STORAGE'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PHYSICAL_Q_2_4_TEST_KIT_STORAGE']) && $formData['PHYSICAL_Q_2_4_TEST_KIT_STORAGE'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="physical_c_2_4"><?php echo ($formData['PHYSICAL_C_2_4_TEST_KIT_STORAGE']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo ($formData['PHYSICAL_Q_2_4_TEST_KIT_STORAGE']); ?></td>
                          </tr>
                          <tr>
                            <td>2.5</td>
                            <td><?= $this->translate('Is there sufficient and secure storage space for test kits and other consumables?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PHYSICAL_Q_2_5_SUFFICIENT_SECURE_STORAGE']) && $formData['PHYSICAL_Q_2_5_SUFFICIENT_SECURE_STORAGE'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PHYSICAL_Q_2_5_SUFFICIENT_SECURE_STORAGE']) && $formData['PHYSICAL_Q_2_5_SUFFICIENT_SECURE_STORAGE'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PHYSICAL_Q_2_5_SUFFICIENT_SECURE_STORAGE']) && $formData['PHYSICAL_Q_2_5_SUFFICIENT_SECURE_STORAGE'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="physical_c_2_5"><?php echo ($formData['PHYSICAL_C_2_5_SUFFICIENT_SECURE_STORAGE']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo ($formData['PHYSICAL_Q_2_5_SUFFICIENT_SECURE_STORAGE']); ?></td>
                          </tr>
                          <tr>
                            <td colspan="6" style="font-weight:bold;"><?= $this->translate('2.0 PHYSICAL FACILITY SCORE'); ?></td>
                            <td style="text-align:center;"><?php echo $formData['PHYSICAL_SCORE']; ?></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>

                  <table cellspacing="0" cellpadding="5" class="table table-bordered">
                    <tr id="safetyTable1">
                      <th style="text-align:center;width:3%" class="details-control" onclick="$('#safetyTable').slideToggle('slow'),addShowClass('shown','safetyTable1');">

                      </th>
                      <th style="width:93%">
                        <a href="javascript:void(0);" onclick="$('#safetyTable').slideToggle('slow'),addShowClass('shown','safetyTable1');"><?= $this->translate('3.0 SAFETY'); ?></a>
                      </th>
                      <th style="text-align:center;width:5%">10</th>
                    </tr>
                    <tr id="safetyTable" style="display: none;">
                      <td colspan="3">
                        <table cellspacing="0" cellpadding="5" class="table table-bordered">
                          <tr>
                            <td style="text-align:center;font-weight:bold;width:45%;" colspan="2"><?= $this->translate('SECTION'); ?></td>
                            <th style="text-align:center;width:3%;"><?= $this->translate('YES'); ?></th>
                            <th style="text-align:center;width:4%;"><?= $this->translate('Partial'); ?></th>
                            <th style="text-align:center;width:3%;"><?= $this->translate('NO'); ?></th>
                            <th style="text-align:center;width:40%;"><?= $this->translate('Comments'); ?></th>
                            <th style="text-align:center;width:5%;"><?= $this->translate('Score'); ?></th>
                          </tr>
                          <tr>
                            <td>3.1</td>
                            <td><?= $this->translate('Are there SOPs and/or job aides in place to implement safety practices?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_1_IMPLEMENT_SAFETY_PRACTICES']) && $formData['SAFETY_Q_3_1_IMPLEMENT_SAFETY_PRACTICES'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_1_IMPLEMENT_SAFETY_PRACTICES']) && $formData['SAFETY_Q_3_1_IMPLEMENT_SAFETY_PRACTICES'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_1_IMPLEMENT_SAFETY_PRACTICES']) && $formData['SAFETY_Q_3_1_IMPLEMENT_SAFETY_PRACTICES'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="safety_c_3_1"><?php echo ($formData['SAFETY_C_3_1_IMPLEMENT_SAFETY_PRACTICES']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_1_IMPLEMENT_SAFETY_PRACTICES']; ?></td>
                          </tr>
                          <tr>
                            <td>3.2</td>
                            <td><?= $this->translate('Are there SOPs and/or job aides in place to address accidental exposure to potentially infectious body fluids through a needle stick injury, splash or other sharps injury?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_2_ACCIDENTAL_EXPOSURE']) && $formData['SAFETY_Q_3_2_ACCIDENTAL_EXPOSURE'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_2_ACCIDENTAL_EXPOSURE']) && $formData['SAFETY_Q_3_2_ACCIDENTAL_EXPOSURE'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_2_ACCIDENTAL_EXPOSURE']) && $formData['SAFETY_Q_3_2_ACCIDENTAL_EXPOSURE'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="safety_c_3_2"><?php echo ($formData['SAFETY_C_3_2_ACCIDENTAL_EXPOSURE']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_2_ACCIDENTAL_EXPOSURE']; ?></td>
                          </tr>
                          <tr>
                            <td>3.3</td>
                            <td><?= $this->translate('Are testers and those visiting the testing area following the safety practices outlined in the SOPs and/or job aides?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_3_PRACTICE_SAFETY_PRACTICES']) && $formData['SAFETY_Q_3_3_PRACTICE_SAFETY_PRACTICES'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_3_PRACTICE_SAFETY_PRACTICES']) && $formData['SAFETY_Q_3_3_PRACTICE_SAFETY_PRACTICES'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_3_PRACTICE_SAFETY_PRACTICES']) && $formData['SAFETY_Q_3_3_PRACTICE_SAFETY_PRACTICES'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="safety_c_3_3"><?php echo ($formData['SAFETY_C_3_3_PRACTICE_SAFETY_PRACTICES']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_3_PRACTICE_SAFETY_PRACTICES']; ?></td>
                          </tr>
                          <tr>
                            <td>3.4</td>
                            <td><?= $this->translate('Is personal protective equipment (PPE) always available to testers?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_4_PPE_AVAILABILITY']) && $formData['SAFETY_Q_3_4_PPE_AVAILABILITY'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_4_PPE_AVAILABILITY']) && $formData['SAFETY_Q_3_4_PPE_AVAILABILITY'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_4_PPE_AVAILABILITY']) && $formData['SAFETY_Q_3_4_PPE_AVAILABILITY'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="safety_c_3_4"><?php echo ($formData['SAFETY_C_3_4_PPE_AVAILABILITY']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_4_PPE_AVAILABILITY']; ?></td>
                          </tr>
                          <tr>
                            <td>3.5</td>
                            <td><?= $this->translate('Is PPE properly used by all testers consistently throughout the testing process?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_5_PPE_USED_PROPERLY']) && $formData['SAFETY_Q_3_5_PPE_USED_PROPERLY'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_5_PPE_USED_PROPERLY']) && $formData['SAFETY_Q_3_5_PPE_USED_PROPERLY'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_5_PPE_USED_PROPERLY']) && $formData['SAFETY_Q_3_5_PPE_USED_PROPERLY'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="safety_c_3_5"><?php echo ($formData['SAFETY_C_3_5_PPE_USED_PROPERLY']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_5_PPE_USED_PROPERLY']; ?></td>
                          </tr>
                          <tr>
                            <td>3.6</td>
                            <td><?= $this->translate('Is there clean water and soap available for hand washing and is it consistently used?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_6_WATER_SOAP_AVAILABILITY']) && $formData['SAFETY_Q_3_6_WATER_SOAP_AVAILABILITY'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_6_WATER_SOAP_AVAILABILITY']) && $formData['SAFETY_Q_3_6_WATER_SOAP_AVAILABILITY'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_6_WATER_SOAP_AVAILABILITY']) && $formData['SAFETY_Q_3_6_WATER_SOAP_AVAILABILITY'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="safety_c_3_6"><?php echo ($formData['SAFETY_C_3_6_WATER_SOAP_AVAILABILITY']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_6_WATER_SOAP_AVAILABILITY']; ?></td>
                          </tr>
                          <tr>
                            <td>3.7</td>
                            <td><?= $this->translate('Is there an appropriate disinfectant to clean the work area available?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_7_DISINFECTANT_AVAILABLE']) && $formData['SAFETY_Q_3_7_DISINFECTANT_AVAILABLE'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_7_DISINFECTANT_AVAILABLE']) && $formData['SAFETY_Q_3_7_DISINFECTANT_AVAILABLE'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_7_DISINFECTANT_AVAILABLE']) && $formData['SAFETY_Q_3_7_DISINFECTANT_AVAILABLE'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="safety_c_3_7"><?php echo ($formData['SAFETY_C_3_7_DISINFECTANT_AVAILABLE']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_7_DISINFECTANT_AVAILABLE']; ?></td>
                          </tr>
                          <tr>
                            <td>3.8</td>
                            <td><?= $this->translate('Is the disinfectant solution available properly labeled with content, date of preparation and date of expiration?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_8_DISINFECTANT_LABELED_PROPERLY']) && $formData['SAFETY_Q_3_8_DISINFECTANT_LABELED_PROPERLY'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_8_DISINFECTANT_LABELED_PROPERLY']) && $formData['SAFETY_Q_3_8_DISINFECTANT_LABELED_PROPERLY'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_8_DISINFECTANT_LABELED_PROPERLY']) && $formData['SAFETY_Q_3_8_DISINFECTANT_LABELED_PROPERLY'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="safety_c_3_8"><?php echo ($formData['SAFETY_C_3_8_DISINFECTANT_LABELED_PROPERLY']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_8_DISINFECTANT_LABELED_PROPERLY']; ?></td>
                          </tr>
                          <tr>
                            <td>3.9</td>
                            <td><?= $this->translate('Are sharps, infectious and non-infectious waste disposed of according to the segregation instructions?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_9_SEGREGATION_OF_WASTE']) && $formData['SAFETY_Q_3_9_SEGREGATION_OF_WASTE'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_9_SEGREGATION_OF_WASTE']) && $formData['SAFETY_Q_3_9_SEGREGATION_OF_WASTE'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_9_SEGREGATION_OF_WASTE']) && $formData['SAFETY_Q_3_9_SEGREGATION_OF_WASTE'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="safety_c_3_9"><?php echo ($formData['SAFETY_C_3_9_SEGREGATION_OF_WASTE']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_9_SEGREGATION_OF_WASTE']; ?></td>
                          </tr>
                          <tr>
                            <td>3.10</td>
                            <td><?= $this->translate('Are infectious and non-infectious waste containers emptied regularly per the SOP and/or job aides?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_10_INFECTIOUS_WASTE_EMPTIED']) && $formData['SAFETY_Q_3_10_INFECTIOUS_WASTE_EMPTIED'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_10_INFECTIOUS_WASTE_EMPTIED']) && $formData['SAFETY_Q_3_10_INFECTIOUS_WASTE_EMPTIED'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['SAFETY_Q_3_10_INFECTIOUS_WASTE_EMPTIED']) && $formData['SAFETY_Q_3_10_INFECTIOUS_WASTE_EMPTIED'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="safety_c_3_10"><?php echo ($formData['SAFETY_C_3_10_INFECTIOUS_WASTE_EMPTIED']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['SAFETY_Q_3_10_INFECTIOUS_WASTE_EMPTIED']; ?></td>
                          </tr>
                          <tr>
                            <th colspan="6"><?= $this->translate('3.0 SAFETY SCORE'); ?> </th>
                            <td style="text-align:center;"><?php echo $formData['SAFETY_SCORE']; ?></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>

                  <table cellspacing="0" cellpadding="5" class="table table-bordered">
                    <tr id="preTestingTable1">
                      <th style="text-align:center;width:3%" class="details-control" onclick="$('#preTestingTable').slideToggle('slow'),addShowClass('shown','preTestingTable1');">

                      </th>
                      <th style="width:93%">
                        <a href="javascript:void(0);" onclick="$('#preTestingTable').slideToggle('slow'),addShowClass('shown','preTestingTable1');"><?= $this->translate('4.0 PRE-TESTING PHASE'); ?></a>
                      </th>
                      <th style="text-align:center;width:5%">13</th>
                    </tr>
                    <tr id="preTestingTable" style="display: none;">
                      <td colspan="3">
                        <table cellspacing="0" cellpadding="5" class="table table-bordered">
                          <tr>
                            <td style="text-align:center;font-weight:bold;width:45%;" colspan="2"><?= $this->translate('SECTION'); ?></td>
                            <th style="text-align:center;width:3%;"><?= $this->translate('YES'); ?></th>
                            <th style="text-align:center;width:4%;"><?= $this->translate('Partial'); ?></th>
                            <th style="text-align:center;width:3%;"><?= $this->translate('NO'); ?></th>
                            <th style="text-align:center;width:40%;"><?= $this->translate('Comments'); ?></th>
                            <th style="text-align:center;width:5%;"><?= $this->translate('Score'); ?></th>
                          </tr>
                          <tr>
                            <td>4.1</td>
                            <td><?= $this->translate('Are there national testing guidelines specific to the program (e.g. HTS, PMTCT, TB, etc.) available at the testing point?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_1_NATIONAL_GUIDELINES']) && $formData['PRE_Q_4_1_NATIONAL_GUIDELINES'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_1_NATIONAL_GUIDELINES']) && $formData['PRE_Q_4_1_NATIONAL_GUIDELINES'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_1_NATIONAL_GUIDELINES']) && $formData['PRE_Q_4_1_NATIONAL_GUIDELINES'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="pre_c_4_1"><?php echo ($formData['PRE_C_4_1_NATIONAL_GUIDELINES']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['PRE_Q_4_1_NATIONAL_GUIDELINES']; ?></td>
                          </tr>
                          <tr>
                            <td>4.2</td>
                            <td><?= $this->translate('Is the national HIV testing algorithm(s) consistently being used at the testing site?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_2_HIV_TESTING_ALGORITHM']) && $formData['PRE_Q_4_2_HIV_TESTING_ALGORITHM'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_2_HIV_TESTING_ALGORITHM']) && $formData['PRE_Q_4_2_HIV_TESTING_ALGORITHM'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_2_HIV_TESTING_ALGORITHM']) && $formData['PRE_Q_4_2_HIV_TESTING_ALGORITHM'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="pre_c_4_2"><?php echo ($formData['PRE_C_4_2_HIV_TESTING_ALGORITHM']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['PRE_Q_4_2_HIV_TESTING_ALGORITHM']; ?></td>
                          </tr>
                          <tr>
                            <td>4.3</td>
                            <td><?= $this->translate('Are SOPs and/or job aides on HIV rapid test procedures and the national HIV rapid test algorithm(s) available and easily accessible at the testing site?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_3_TEST_PROCEDURES_ACCESSIBLE']) && $formData['PRE_Q_4_3_TEST_PROCEDURES_ACCESSIBLE'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_3_TEST_PROCEDURES_ACCESSIBLE']) && $formData['PRE_Q_4_3_TEST_PROCEDURES_ACCESSIBLE'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_3_TEST_PROCEDURES_ACCESSIBLE']) && $formData['PRE_Q_4_3_TEST_PROCEDURES_ACCESSIBLE'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="pre_c_4_3"><?php echo ($formData['PRE_C_4_3_TEST_PROCEDURES_ACCESSIBLE']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['PRE_Q_4_3_TEST_PROCEDURES_ACCESSIBLE']; ?></td>
                          </tr>
                          <tr>
                            <td>4.4</td>
                            <td><?= $this->translate('Are SOPs and/or job aides on HIV rapid test procedures and the national testing algorithm up-to-date and accurate?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_4_TEST_PROCEDURES_ACCURATE']) && $formData['PRE_Q_4_4_TEST_PROCEDURES_ACCURATE'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_4_TEST_PROCEDURES_ACCURATE']) && $formData['PRE_Q_4_4_TEST_PROCEDURES_ACCURATE'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_4_TEST_PROCEDURES_ACCURATE']) && $formData['PRE_Q_4_4_TEST_PROCEDURES_ACCURATE'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="pre_c_4_4"><?php echo ($formData['PRE_C_4_4_TEST_PROCEDURES_ACCURATE']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['PRE_Q_4_4_TEST_PROCEDURES_ACCURATE']; ?></td>
                          </tr>
                          <tr>
                            <td>4.5</td>
                            <td><?= $this->translate('Are only nationally approved HIV rapid test kits available for use?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_5_APPROVED_KITS_AVAILABLE']) && $formData['PRE_Q_4_5_APPROVED_KITS_AVAILABLE'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_5_APPROVED_KITS_AVAILABLE']) && $formData['PRE_Q_4_5_APPROVED_KITS_AVAILABLE'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_5_APPROVED_KITS_AVAILABLE']) && $formData['PRE_Q_4_5_APPROVED_KITS_AVAILABLE'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="pre_c_4_5"><?php echo ($formData['PRE_C_4_5_APPROVED_KITS_AVAILABLE']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['PRE_Q_4_5_APPROVED_KITS_AVAILABLE']; ?></td>
                          </tr>
                          <tr>
                            <td>4.6</td>
                            <td><?= $this->translate('Are all the test kits currently in use within the expiration date?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_6_HIV_KITS_EXPIRATION']) && $formData['PRE_Q_4_6_HIV_KITS_EXPIRATION'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_6_HIV_KITS_EXPIRATION']) && $formData['PRE_Q_4_6_HIV_KITS_EXPIRATION'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_6_HIV_KITS_EXPIRATION']) && $formData['PRE_Q_4_6_HIV_KITS_EXPIRATION'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="pre_c_4_6"><?php echo ($formData['PRE_C_4_6_HIV_KITS_EXPIRATION']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['PRE_Q_4_6_HIV_KITS_EXPIRATION']; ?></td>
                          </tr>
                          <tr>
                            <td>4.7</td>
                            <td><?= $this->translate('Are all required test kit components (i.e. test device, buffer, sample collection device, etc.) and supplies available prior to testing?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_7_KIT_SUPPLIES_AVAILABILITY']) && $formData['PRE_Q_4_7_KIT_SUPPLIES_AVAILABILITY'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_7_KIT_SUPPLIES_AVAILABILITY']) && $formData['PRE_Q_4_7_KIT_SUPPLIES_AVAILABILITY'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_7_KIT_SUPPLIES_AVAILABILITY']) && $formData['PRE_Q_4_7_KIT_SUPPLIES_AVAILABILITY'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="pre_c_4_7"><?php echo ($formData['PRE_C_4_7_KIT_SUPPLIES_AVAILABILITY']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['PRE_Q_4_7_KIT_SUPPLIES_AVAILABILITY']; ?></td>
                          </tr>
                          <tr>
                            <td>4.8</td>
                            <td><?= $this->translate('Is there a process in place for stock management?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_8_STOCK_MANAGEMENT']) && $formData['PRE_Q_4_8_STOCK_MANAGEMENT'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_8_STOCK_MANAGEMENT']) && $formData['PRE_Q_4_8_STOCK_MANAGEMENT'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_8_STOCK_MANAGEMENT']) && $formData['PRE_Q_4_8_STOCK_MANAGEMENT'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="pre_c_4_8"><?php echo ($formData['PRE_C_4_8_STOCK_MANAGEMENT']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['PRE_Q_4_8_STOCK_MANAGEMENT']; ?></td>
                          </tr>
                          <tr>
                            <td>4.9</td>
                            <td><?= $this->translate('Is there a documented inventory system in place at the testing point for test kits received (i.e. who received them, date of receipt, etc.)?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_9_DOCUMENTED_INVENTORY']) && $formData['PRE_Q_4_9_DOCUMENTED_INVENTORY'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_9_DOCUMENTED_INVENTORY']) && $formData['PRE_Q_4_9_DOCUMENTED_INVENTORY'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_9_DOCUMENTED_INVENTORY']) && $formData['PRE_Q_4_9_DOCUMENTED_INVENTORY'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="pre_c_4_9"><?php echo ($formData['PRE_C_4_9_DOCUMENTED_INVENTORY']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['PRE_Q_4_9_DOCUMENTED_INVENTORY']; ?></td>
                          </tr>
                          <tr>
                            <td>4.10</td>
                            <td><?= $this->translate('Are job aides on finger prick or venous blood collection available and posted at the testing point?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_10_SOPS_BLOOD_COLLECTION']) && $formData['PRE_Q_4_10_SOPS_BLOOD_COLLECTION'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_10_SOPS_BLOOD_COLLECTION']) && $formData['PRE_Q_4_10_SOPS_BLOOD_COLLECTION'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_10_SOPS_BLOOD_COLLECTION']) && $formData['PRE_Q_4_10_SOPS_BLOOD_COLLECTION'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="pre_c_4_10"><?php echo ($formData['PRE_C_4_10_SOPS_BLOOD_COLLECTION']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['PRE_Q_4_10_SOPS_BLOOD_COLLECTION']; ?></td>
                          </tr>
                          <tr>
                            <td>4.11</td>
                            <td><?= $this->translate('Are there sufficient supplies available for finger prick or venous blood collection (i.e. lancet, gauze, alcohol swab, etc.)?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_11_BLOOD_COLLECTION_SUPPLIES']) && $formData['PRE_Q_4_11_BLOOD_COLLECTION_SUPPLIES'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_11_BLOOD_COLLECTION_SUPPLIES']) && $formData['PRE_Q_4_11_BLOOD_COLLECTION_SUPPLIES'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_11_BLOOD_COLLECTION_SUPPLIES']) && $formData['PRE_Q_4_11_BLOOD_COLLECTION_SUPPLIES'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="pre_c_4_11"><?php echo ($formData['PRE_C_4_11_BLOOD_COLLECTION_SUPPLIES']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['PRE_Q_4_11_BLOOD_COLLECTION_SUPPLIES']; ?></td>
                          </tr>
                          <tr>
                            <td>4.12</td>
                            <td><?= $this->translate('Are there SOPs and/or job aides describing how client identification should be recorded in the HIV testing register?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_12_CLIENT_IDENTIFICATION']) && $formData['PRE_Q_4_12_CLIENT_IDENTIFICATION'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_12_CLIENT_IDENTIFICATION']) && $formData['PRE_Q_4_12_CLIENT_IDENTIFICATION'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_12_CLIENT_IDENTIFICATION']) && $formData['PRE_Q_4_12_CLIENT_IDENTIFICATION'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="pre_c_4_12"><?php echo ($formData['PRE_C_4_12_CLIENT_IDENTIFICATION']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['PRE_Q_4_12_CLIENT_IDENTIFICATION']; ?></td>
                          </tr>
                          <tr>
                            <td>4.13</td>
                            <td><?= $this->translate('Are client identifiers recorded in the HIV testing register and on test devices per SOPs and/or job aide?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_13_CLIENT_ID_RECORDED']) && $formData['PRE_Q_4_13_CLIENT_ID_RECORDED'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_13_CLIENT_ID_RECORDED']) && $formData['PRE_Q_4_13_CLIENT_ID_RECORDED'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['PRE_Q_4_13_CLIENT_ID_RECORDED']) && $formData['PRE_Q_4_13_CLIENT_ID_RECORDED'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="pre_c_4_12"><?php echo ($formData['PRE_C_4_13_CLIENT_ID_RECORDED']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['PRE_Q_4_13_CLIENT_ID_RECORDED']; ?></td>
                          </tr>
                          <tr>
                            <th colspan="6"><?= $this->translate('4.0 PRE-TESTING PHASE SCORE'); ?></th>
                            <td style="text-align:center;"><?php echo $formData['PRETEST_SCORE']; ?></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>

                  <table cellspacing="0" cellpadding="5" class="table table-bordered">
                    <tr id="testingPhaseTable1">
                      <th style="text-align:center;width:3%" class="details-control" onclick="$('#testingPhaseTable').slideToggle('slow'),addShowClass('shown','testingPhaseTable1');">

                      </th>
                      <th style="width:93%">
                        <a href="javascript:void(0);" onclick="$('#testingPhaseTable').slideToggle('slow'),addShowClass('shown','testingPhaseTable1');"><?= $this->translate('5.0 TESTING PHASE'); ?></a>
                      </th>
                      <th style="text-align:center;width:5%">9</th>
                    </tr>
                    <tr id="testingPhaseTable" style="display: none;">
                      <td colspan="3">
                        <table cellspacing="0" cellpadding="5" class="table table-bordered">
                          <tr>
                            <td style="text-align:center;font-weight:bold;width:45%;" colspan="2"><?= $this->translate('SECTION'); ?></td>
                            <th style="text-align:center;width:3%;"><?= $this->translate('YES'); ?></th>
                            <th style="text-align:center;width:4%;"><?= $this->translate('Partial'); ?></th>
                            <th style="text-align:center;width:3%;"><?= $this->translate('NO'); ?></th>
                            <th style="text-align:center;width:40%;"><?= $this->translate('Comments'); ?></th>
                            <th style="text-align:center;width:5%;"><?= $this->translate('Score'); ?></th>
                          </tr>
                          <tr>
                            <td>5.1</td>
                            <td><?= $this->translate('Are SOPs and/or job aides on HIV testing procedures and the national testing algorithm being referred to and followed during testing?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_1_PROCEDURES_TESTING_ALGORITHM']) && $formData['TEST_Q_5_1_PROCEDURES_TESTING_ALGORITHM'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_1_PROCEDURES_TESTING_ALGORITHM']) && $formData['TEST_Q_5_1_PROCEDURES_TESTING_ALGORITHM'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_1_PROCEDURES_TESTING_ALGORITHM']) && $formData['TEST_Q_5_1_PROCEDURES_TESTING_ALGORITHM'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="test_c_5_1"><?php echo ($formData['TEST_C_5_1_PROCEDURES_TESTING_ALGORITHM']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['TEST_Q_5_1_PROCEDURES_TESTING_ALGORITHM']; ?></td>
                          </tr>
                          <tr>
                            <td>5.2</td>
                            <td><?= $this->translate('Are timers available and used routinely for HIV rapid testing?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_2_TIMERS_AVAILABILITY']) && $formData['TEST_Q_5_2_TIMERS_AVAILABILITY'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_2_TIMERS_AVAILABILITY']) && $formData['TEST_Q_5_2_TIMERS_AVAILABILITY'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_2_TIMERS_AVAILABILITY']) && $formData['TEST_Q_5_2_TIMERS_AVAILABILITY'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="test_c_5_2"><?php echo ($formData['TEST_C_5_2_TIMERS_AVAILABILITY']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['TEST_Q_5_2_TIMERS_AVAILABILITY']; ?></td>
                          </tr>
                          <tr>
                            <td>5.3</td>
                            <td><?= $this->translate('Are sample collection devices (e.g., capillary tube, loop, disposable pipettes, etc.) used accurately to perform the test?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_3_SAMPLE_DEVICE_ACCURACY']) && $formData['TEST_Q_5_3_SAMPLE_DEVICE_ACCURACY'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_3_SAMPLE_DEVICE_ACCURACY']) && $formData['TEST_Q_5_3_SAMPLE_DEVICE_ACCURACY'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_3_SAMPLE_DEVICE_ACCURACY']) && $formData['TEST_Q_5_3_SAMPLE_DEVICE_ACCURACY'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="test_c_5_3"><?php echo ($formData['TEST_C_5_3_SAMPLE_DEVICE_ACCURACY']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['TEST_Q_5_3_SAMPLE_DEVICE_ACCURACY']; ?></td>
                          </tr>
                          <tr>
                            <td>5.4</td>
                            <td><?= $this->translate('Are testing procedures adequately followed?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_4_TESTING_PROCEDURE_FOLLOWED']) && $formData['TEST_Q_5_4_TESTING_PROCEDURE_FOLLOWED'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_4_TESTING_PROCEDURE_FOLLOWED']) && $formData['TEST_Q_5_4_TESTING_PROCEDURE_FOLLOWED'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_4_TESTING_PROCEDURE_FOLLOWED']) && $formData['TEST_Q_5_4_TESTING_PROCEDURE_FOLLOWED'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="test_c_5_4"><?php echo ($formData['TEST_C_5_4_TESTING_PROCEDURE_FOLLOWED']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['TEST_Q_5_4_TESTING_PROCEDURE_FOLLOWED']; ?></td>
                          </tr>
                          <tr>
                            <td>5.5</td>
                            <td><?= $this->translate('Are external positive and negative quality control (QC) specimens routinely used (e.g., daily, weekly or monthly) according to SOPs or guidelines?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_5_QUALITY_CONTROL']) && $formData['TEST_Q_5_5_QUALITY_CONTROL'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_5_QUALITY_CONTROL']) && $formData['TEST_Q_5_5_QUALITY_CONTROL'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_5_QUALITY_CONTROL']) && $formData['TEST_Q_5_5_QUALITY_CONTROL'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="test_c_5_5"><?php echo ($formData['TEST_C_5_5_QUALITY_CONTROL']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['TEST_Q_5_5_QUALITY_CONTROL']; ?></td>
                          </tr>
                          <tr>
                            <td>5.6</td>
                            <td><?= $this->translate('Are QC results properly recorded?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_6_QC_RESULTS_RECORDED']) && $formData['TEST_Q_5_6_QC_RESULTS_RECORDED'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_6_QC_RESULTS_RECORDED']) && $formData['TEST_Q_5_6_QC_RESULTS_RECORDED'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_6_QC_RESULTS_RECORDED']) && $formData['TEST_Q_5_6_QC_RESULTS_RECORDED'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="test_c_5_6"><?php echo ($formData['TEST_C_5_6_QC_RESULTS_RECORDED']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['TEST_Q_5_6_QC_RESULTS_RECORDED']; ?></td>
                          </tr>
                          <tr>
                            <td>5.7</td>
                            <td><?= $this->translate('Are incorrect/invalid QC results properly recorded?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_7_INCORRECT_QC_RESULTS']) && $formData['TEST_Q_5_7_INCORRECT_QC_RESULTS'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_7_INCORRECT_QC_RESULTS']) && $formData['TEST_Q_5_7_INCORRECT_QC_RESULTS'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_7_INCORRECT_QC_RESULTS']) && $formData['TEST_Q_5_7_INCORRECT_QC_RESULTS'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="test_c_5_7"><?php echo ($formData['TEST_C_5_7_INCORRECT_QC_RESULTS']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['TEST_Q_5_7_INCORRECT_QC_RESULTS']; ?></td>
                          </tr>
                          <tr>
                            <td>5.8</td>
                            <td><?= $this->translate('Are appropriate steps taken and documented when QC results are incorrect and/or invalid?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_8_APPROPRIATE_STEPS_TAKEN']) && $formData['TEST_Q_5_8_APPROPRIATE_STEPS_TAKEN'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_8_APPROPRIATE_STEPS_TAKEN']) && $formData['TEST_Q_5_8_APPROPRIATE_STEPS_TAKEN'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_8_APPROPRIATE_STEPS_TAKEN']) && $formData['TEST_Q_5_8_APPROPRIATE_STEPS_TAKEN'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="test_c_5_8"><?php echo ($formData['TEST_C_5_8_APPROPRIATE_STEPS_TAKEN']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['TEST_Q_5_8_APPROPRIATE_STEPS_TAKEN']; ?></td>
                          </tr>
                          <tr>
                            <td>5.9</td>
                            <td><?= $this->translate('Are QC records reviewed by the person in charge routinely?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_9_REVIEW_QC_RECORDS']) && $formData['TEST_Q_5_9_REVIEW_QC_RECORDS'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_9_REVIEW_QC_RECORDS']) && $formData['TEST_Q_5_9_REVIEW_QC_RECORDS'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['TEST_Q_5_9_REVIEW_QC_RECORDS']) && $formData['TEST_Q_5_9_REVIEW_QC_RECORDS'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="test_c_5_9"><?php echo ($formData['TEST_C_5_9_REVIEW_QC_RECORDS']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['TEST_Q_5_9_REVIEW_QC_RECORDS']; ?></td>
                          </tr>

                          <tr>
                            <th colspan="6"><?= $this->translate('5.0 TESTING PHASE SCORE'); ?></th>
                            <td style="text-align:center;"><?php echo $formData['TEST_SCORE']; ?></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>

                  <table cellspacing="0" cellpadding="5" class="table table-bordered">
                    <tr id="postTestingTable1">
                      <th style="text-align:center;width:3%" class="details-control" onclick="$('#postTestingTable').slideToggle('slow'),addShowClass('shown','postTestingTable1');">

                      </th>
                      <th style="width:93%">
                        <a href="javascript:void(0);" onclick="$('#postTestingTable').slideToggle('slow'),addShowClass('shown','postTestingTable1');"><?= $this->translate('6.0 POST TESTING PHASE - DOCUMENTS AND RECORDS'); ?></a>
                      </th>
                      <th style="text-align:center;width:5%">9</th>
                    </tr>
                    <tr id="postTestingTable" style="display: none;">
                      <td colspan="3">
                        <table cellspacing="0" cellpadding="5" class="table table-bordered">
                          <tr>
                            <td style="text-align:center;font-weight:bold;width:45%;" colspan="2"><?= $this->translate('SECTION'); ?></td>
                            <th style="text-align:center;width:3%;"><?= $this->translate('YES'); ?></th>
                            <th style="text-align:center;width:4%;"><?= $this->translate('Partial'); ?></th>
                            <th style="text-align:center;width:3%;"><?= $this->translate('NO'); ?></th>
                            <th style="text-align:center;width:40%;"><?= $this->translate('Comments'); ?></th>
                            <th style="text-align:center;width:5%;"><?= $this->translate('Score'); ?></th>
                          </tr>
                          <tr>
                            <td>6.1</td>
                            <td><?= $this->translate('Is there a national standardized HIV rapid testing register/logbook that includes all of the key quality elements available and in use?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_1_STANDARDIZED_HIV_REGISTER']) && $formData['POST_Q_6_1_STANDARDIZED_HIV_REGISTER'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_1_STANDARDIZED_HIV_REGISTER']) && $formData['POST_Q_6_1_STANDARDIZED_HIV_REGISTER'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_1_STANDARDIZED_HIV_REGISTER']) && $formData['POST_Q_6_1_STANDARDIZED_HIV_REGISTER'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="post_C_6_1"><?php echo ($formData['POST_C_6_1_STANDARDIZED_HIV_REGISTER']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['POST_Q_6_1_STANDARDIZED_HIV_REGISTER']; ?></td>
                          </tr>
                          <tr>
                            <td>6.2</td>
                            <td><?= $this->translate('Are all the elements in the register/ logbook recorded/captured correctly? (e.g., client demographics, kit names, lot numbers, expiration dates, tester name, individual and final HIV results, etc.)?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_2_ELEMENTS_CAPTURED_CORRECTLY']) && $formData['POST_Q_6_2_ELEMENTS_CAPTURED_CORRECTLY'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_2_ELEMENTS_CAPTURED_CORRECTLY']) && $formData['POST_Q_6_2_ELEMENTS_CAPTURED_CORRECTLY'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_2_ELEMENTS_CAPTURED_CORRECTLY']) && $formData['POST_Q_6_2_ELEMENTS_CAPTURED_CORRECTLY'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="post_C_6_2"><?php echo ($formData['POST_C_6_2_ELEMENTS_CAPTURED_CORRECTLY']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['POST_Q_6_2_ELEMENTS_CAPTURED_CORRECTLY']; ?></td>
                          </tr>
                          <tr>
                            <td>6.3</td>
                            <td><?= $this->translate('Is the total summary at the end of each page of the register/logbooks complied accurately?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_3_PAGE_TOTAL_SUMMARY']) && $formData['POST_Q_6_3_PAGE_TOTAL_SUMMARY'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_3_PAGE_TOTAL_SUMMARY']) && $formData['POST_Q_6_3_PAGE_TOTAL_SUMMARY'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_3_PAGE_TOTAL_SUMMARY']) && $formData['POST_Q_6_3_PAGE_TOTAL_SUMMARY'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="post_C_6_3"><?php echo ($formData['POST_C_6_3_PAGE_TOTAL_SUMMARY']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['POST_Q_6_3_PAGE_TOTAL_SUMMARY']; ?></td>
                          </tr>
                          <tr>
                            <td>6.4</td>
                            <td><?= $this->translate('Are invalid test results recorded properly in the register/logbook?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_4_INVALID_TEST_RESULT_RECORDED']) && $formData['POST_Q_6_4_INVALID_TEST_RESULT_RECORDED'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_4_INVALID_TEST_RESULT_RECORDED']) && $formData['POST_Q_6_4_INVALID_TEST_RESULT_RECORDED'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_4_INVALID_TEST_RESULT_RECORDED']) && $formData['POST_Q_6_4_INVALID_TEST_RESULT_RECORDED'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="post_C_6_4"><?php echo ($formData['POST_C_6_4_INVALID_TEST_RESULT_RECORDED']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['POST_Q_6_4_INVALID_TEST_RESULT_RECORDED']; ?></td>
                          </tr>
                          <tr>
                            <td>6.5</td>
                            <td><?= $this->translate('Are appropriate steps taken and documented when a result is invalid?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_5_APPROPRIATE_STEPS_TAKEN']) && $formData['POST_Q_6_5_APPROPRIATE_STEPS_TAKEN'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_5_APPROPRIATE_STEPS_TAKEN']) && $formData['POST_Q_6_5_APPROPRIATE_STEPS_TAKEN'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_5_APPROPRIATE_STEPS_TAKEN']) && $formData['POST_Q_6_5_APPROPRIATE_STEPS_TAKEN'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="post_C_6_5"><?php echo ($formData['POST_C_6_5_APPROPRIATE_STEPS_TAKEN']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['POST_Q_6_5_APPROPRIATE_STEPS_TAKEN']; ?></td>
                          </tr>
                          <tr>
                            <td>6.6</td>
                            <td><?= $this->translate('Are the register/logbook pages routinely reviewed for accuracy and completeness by the person in charge?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_6_REGISTERS_REVIEWED']) && $formData['POST_Q_6_6_REGISTERS_REVIEWED'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_6_REGISTERS_REVIEWED']) && $formData['POST_Q_6_6_REGISTERS_REVIEWED'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_6_REGISTERS_REVIEWED']) && $formData['POST_Q_6_6_REGISTERS_REVIEWED'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="post_C_6_6"><?php echo ($formData['POST_C_6_6_REGISTERS_REVIEWED']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['POST_Q_6_6_REGISTERS_REVIEWED']; ?></td>
                          </tr>
                          <tr>
                            <td>6.7</td>
                            <td><?= $this->translate('Are all client documents and records securely kept throughout all phases of the testing process?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_7_DOCUMENTS_SECURELY_KEPT']) && $formData['POST_Q_6_7_DOCUMENTS_SECURELY_KEPT'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_7_DOCUMENTS_SECURELY_KEPT']) && $formData['POST_Q_6_7_DOCUMENTS_SECURELY_KEPT'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_7_DOCUMENTS_SECURELY_KEPT']) && $formData['POST_Q_6_7_DOCUMENTS_SECURELY_KEPT'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="post_C_6_7"><?php echo ($formData['POST_C_6_7_DOCUMENTS_SECURELY_KEPT']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['POST_Q_6_7_DOCUMENTS_SECURELY_KEPT']; ?></td>
                          </tr>
                          <tr>
                            <td>6.8</td>
                            <td><?= $this->translate('Are all registers/logbooks and other documents kept in a secure location when not in use?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_8_REGISTER_SECURE_LOCATION']) && $formData['POST_Q_6_8_REGISTER_SECURE_LOCATION'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_8_REGISTER_SECURE_LOCATION']) && $formData['POST_Q_6_8_REGISTER_SECURE_LOCATION'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_8_REGISTER_SECURE_LOCATION']) && $formData['POST_Q_6_8_REGISTER_SECURE_LOCATION'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="post_C_6_8"><?php echo ($formData['POST_C_6_8_REGISTER_SECURE_LOCATION']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['POST_Q_6_8_REGISTER_SECURE_LOCATION']; ?></td>
                          </tr>
                          <tr>
                            <td>6.9</td>
                            <td><?= $this->translate('Are registers/logbooks properly labeled and archived when full?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_9_REGISTERS_PROPERLY_LABELED']) && $formData['POST_Q_6_9_REGISTERS_PROPERLY_LABELED'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_9_REGISTERS_PROPERLY_LABELED']) && $formData['POST_Q_6_9_REGISTERS_PROPERLY_LABELED'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['POST_Q_6_9_REGISTERS_PROPERLY_LABELED']) && $formData['POST_Q_6_9_REGISTERS_PROPERLY_LABELED'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="post_C_6_9"><?php echo ($formData['POST_C_6_9_REGISTERS_PROPERLY_LABELED']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['POST_Q_6_9_REGISTERS_PROPERLY_LABELED']; ?></td>
                          </tr>

                          <tr>
                            <th colspan="6"><?= $this->translate('6.0 POST TESTING PHASE - DOCUMENTS AND RECORDS SCORE'); ?></th>
                            <td style="text-align:center;"><?php echo $formData['POST_SCORE']; ?></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>

                  <table cellspacing="0" cellpadding="5" class="table table-bordered">
                    <tr id="externalTable1">
                      <th style="text-align:center;width:3%" class="details-control" onclick="$('#externalTable').slideToggle('slow'),addShowClass('shown','externalTable1');">

                      </th>
                      <th style="width:93%">
                        <a href="javascript:void(0);" onclick="$('#externalTable').slideToggle('slow'),addShowClass('shown','externalTable1');"><?= $this->translate('7.0 EXTERNAL QUALITY AUDIT (PT, SUPERVISION AND RETESTING)'); ?></a>
                      </th>
                      <th style="text-align:center;width:5%">8</th>
                    </tr>
                    <tr id="externalTable" style="display: none;">
                      <td colspan="3">
                        <table cellspacing="0" cellpadding="5" class="table table-bordered">
                          <tr>
                            <td style="text-align:center;font-weight:bold;width:45%;" colspan="2"><?= $this->translate('SECTION'); ?></td>
                            <th style="text-align:center;width:3%;"><?= $this->translate('YES'); ?></th>
                            <th style="text-align:center;width:4%;"><?= $this->translate('Partial'); ?></th>
                            <th style="text-align:center;width:3%;"><?= $this->translate('NO'); ?></th>
                            <th style="text-align:center;width:40%;"><?= $this->translate('Comments'); ?></th>
                            <th style="text-align:center;width:5%;"><?= $this->translate('Score'); ?></th>
                          </tr>
                          <tr>
                            <td>7.1</td>
                            <td><?= $this->translate('Is the testing point enrolled in an EQA/PT program?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_1_PT_ENROLLMENT']) && $formData['EQA_Q_7_1_PT_ENROLLMENT'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_1_PT_ENROLLMENT']) && $formData['EQA_Q_7_1_PT_ENROLLMENT'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_1_PT_ENROLLMENT']) && $formData['EQA_Q_7_1_PT_ENROLLMENT'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="eqa_c_7_1"><?php echo ($formData['EQA_C_7_1_PT_ENROLLMENT']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['EQA_Q_7_1_PT_ENROLLMENT']; ?></td>
                          </tr>
                          <tr>
                            <td>7.2</td>
                            <td><?= $this->translate('Do all testers at the testing point test the EQA/PT samples?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_2_TESTING_EQAPT_SAMPLES']) && $formData['EQA_Q_7_2_TESTING_EQAPT_SAMPLES'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_2_TESTING_EQAPT_SAMPLES']) && $formData['EQA_Q_7_2_TESTING_EQAPT_SAMPLES'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_2_TESTING_EQAPT_SAMPLES']) && $formData['EQA_Q_7_2_TESTING_EQAPT_SAMPLES'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="eqa_c_7_2"><?php echo ($formData['EQA_C_7_2_TESTING_EQAPT_SAMPLES']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['EQA_Q_7_2_TESTING_EQAPT_SAMPLES']; ?></td>
                          </tr>
                          <tr>
                            <td>7.3</td>
                            <td><?= $this->translate('Does the person in charge at the testing point review the /PT results before submission to NRL or designee?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_3_REVIEW_BEFORE_SUBMISSION']) && $formData['EQA_Q_7_3_REVIEW_BEFORE_SUBMISSION'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_3_REVIEW_BEFORE_SUBMISSION']) && $formData['EQA_Q_7_3_REVIEW_BEFORE_SUBMISSION'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_3_REVIEW_BEFORE_SUBMISSION']) && $formData['EQA_Q_7_3_REVIEW_BEFORE_SUBMISSION'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="eqa_c_7_3"><?php echo ($formData['EQA_C_7_3_REVIEW_BEFORE_SUBMISSION']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['EQA_Q_7_3_REVIEW_BEFORE_SUBMISSION']; ?></td>
                          </tr>
                          <tr>
                            <td>7.4</td>
                            <td><?= $this->translate('Is an EQA/PT report received from NRL and reviewed by testers and/or the person in charge at the testing point?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_4_FEEDBACK_RECEIVED_REVIEWED']) && $formData['EQA_Q_7_4_FEEDBACK_RECEIVED_REVIEWED'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_4_FEEDBACK_RECEIVED_REVIEWED']) && $formData['EQA_Q_7_4_FEEDBACK_RECEIVED_REVIEWED'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_4_FEEDBACK_RECEIVED_REVIEWED']) && $formData['EQA_Q_7_4_FEEDBACK_RECEIVED_REVIEWED'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="eqa_c_7_4"><?php echo ($formData['EQA_C_7_4_FEEDBACK_RECEIVED_REVIEWED']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['EQA_Q_7_4_FEEDBACK_RECEIVED_REVIEWED']; ?></td>
                          </tr>
                          <tr>
                            <td>7.5</td>
                            <td><?= $this->translate('Does the testing point implement corrective action in case of unsatisfactory results?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_5_IMPLEMENT_CORRECTIVE_ACTION']) && $formData['EQA_Q_7_5_IMPLEMENT_CORRECTIVE_ACTION'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_5_IMPLEMENT_CORRECTIVE_ACTION']) && $formData['EQA_Q_7_5_IMPLEMENT_CORRECTIVE_ACTION'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_5_IMPLEMENT_CORRECTIVE_ACTION']) && $formData['EQA_Q_7_5_IMPLEMENT_CORRECTIVE_ACTION'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="eqa_c_7_5"><?php echo ($formData['EQA_C_7_5_IMPLEMENT_CORRECTIVE_ACTION']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['EQA_Q_7_5_IMPLEMENT_CORRECTIVE_ACTION']; ?></td>
                          </tr>
                          <tr>
                            <td>7.6</td>
                            <td><?= $this->translate('Does the testing point receive periodic supervisory visits?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_6_RECEIVE_PERIODIC_VISITS']) && $formData['EQA_Q_7_6_RECEIVE_PERIODIC_VISITS'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_6_RECEIVE_PERIODIC_VISITS']) && $formData['EQA_Q_7_6_RECEIVE_PERIODIC_VISITS'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_6_RECEIVE_PERIODIC_VISITS']) && $formData['EQA_Q_7_6_RECEIVE_PERIODIC_VISITS'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="eqa_c_7_6"><?php echo ($formData['EQA_C_7_6_RECEIVE_PERIODIC_VISITS']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['EQA_Q_7_6_RECEIVE_PERIODIC_VISITS']; ?></td>
                          </tr>
                          <tr>
                            <td>7.7</td>
                            <td><?= $this->translate('Is feedback provided during supervisory visit and documented?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_7_FEEDBACK_PROVIDED_DOCUMENTED']) && $formData['EQA_Q_7_7_FEEDBACK_PROVIDED_DOCUMENTED'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_7_FEEDBACK_PROVIDED_DOCUMENTED']) && $formData['EQA_Q_7_7_FEEDBACK_PROVIDED_DOCUMENTED'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_7_FEEDBACK_PROVIDED_DOCUMENTED']) && $formData['EQA_Q_7_7_FEEDBACK_PROVIDED_DOCUMENTED'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="eqa_c_7_7"><?php echo ($formData['EQA_C_7_7_FEEDBACK_PROVIDED_DOCUMENTED']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['EQA_Q_7_7_FEEDBACK_PROVIDED_DOCUMENTED']; ?></td>
                          </tr>
                          <tr>
                            <td>7.8</td>
                            <td><?= $this->translate('If testers need to be retrained, are they being retrained during the supervisory visit?'); ?></td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_8_TESTERS_RETRAINED_IN_VISITS']) && $formData['EQA_Q_7_8_TESTERS_RETRAINED_IN_VISITS'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_8_TESTERS_RETRAINED_IN_VISITS']) && $formData['EQA_Q_7_8_TESTERS_RETRAINED_IN_VISITS'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td style="text-align:center;">
                              <?php echo (isset($formData['EQA_Q_7_8_TESTERS_RETRAINED_IN_VISITS']) && $formData['EQA_Q_7_8_TESTERS_RETRAINED_IN_VISITS'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                            </td>
                            <td><textarea class="form-control" name="eqa_c_7_8"><?php echo ($formData['EQA_C_7_8_TESTERS_RETRAINED_IN_VISITS']); ?></textarea></td>
                            <td style="text-align:center;"><?php echo $formData['EQA_Q_7_8_TESTERS_RETRAINED_IN_VISITS']; ?></td>
                          </tr>
                          <tr>
                            <th colspan="6"><?= $this->translate('7.0 EXTERNAL QUALITY AUDIT (PT, SUPERVISION AND RETESTING) SCORE'); ?></th>
                            <td style="text-align:center;"><?php echo $formData['EQA_SCORE']; ?></td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                  <?php if (isset($formData['performrtritesting']) && strtolower($formData['performrtritesting']) == 'yes') { ?>
                    <table cellspacing="0" cellpadding="5" class="table table-bordered">
                      <tr id="rapidTestingTable1">
                        <th style="text-align:center;width:3%" class="details-control" onclick="$('#rapidTestingTable').slideToggle('slow'),addShowClass('shown','rapidTestingTable1');">

                        </th>
                        <th style="width:93%">
                          <a href="javascript:void(0);" onclick="$('#rapidTestingTable').slideToggle('slow'),addShowClass('shown','rapidTestingTable1');">8.0 <?= $this->translate('HIV-1 RECENT INFECTION SURVEILLANCE USING THE RAPID TEST FOR RECENT INFECTION'); ?> </a>
                        </th>
                        <th style="text-align:center;width:5%">11</th>
                      </tr>
                      <tr id="rapidTestingTable" style="display: none;">
                        <td colspan="3">
                          <table cellspacing="0" cellpadding="5" class="table table-bordered">
                            <tr>
                              <td style="text-align:center;font-weight:bold;width:45%;" colspan="2"><?= $this->translate('SECTION'); ?></td>
                              <th style="text-align:center;width:3%;"><?= $this->translate('YES'); ?></th>
                              <th style="text-align:center;width:4%;"><?= $this->translate('Partial'); ?></th>
                              <th style="text-align:center;width:3%;"><?= $this->translate('NO'); ?></th>
                              <th style="text-align:center;width:40%;"><?= $this->translate('Comments'); ?></th>
                              <th style="text-align:center;width:5%;"><?= $this->translate('Score'); ?></th>
                            </tr>
                            <tr>
                              <td>8.1</td>
                              <td><?= $this->translate('Have all testers received a comprehensive training on RTRI?'); ?></td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_1_TESTERS_RECEIVED_RTRI_TRAINING']) && $formData['RTRI_Q_8_1_TESTERS_RECEIVED_RTRI_TRAINING'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_1_TESTERS_RECEIVED_RTRI_TRAINING']) && $formData['RTRI_Q_8_1_TESTERS_RECEIVED_RTRI_TRAINING'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_1_TESTERS_RECEIVED_RTRI_TRAINING']) && $formData['RTRI_Q_8_1_TESTERS_RECEIVED_RTRI_TRAINING'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="rtri_C_8_1"><?php echo ($formData['RTRI_C_8_1_TESTERS_RECEIVED_RTRI_TRAINING']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['RTRI_Q_8_1_TESTERS_RECEIVED_RTRI_TRAINING']; ?></td>
                            </tr>
                            <tr>
                              <td>8.2</td>
                              <td><?= $this->translate('Are there records indicating all testers have demonstrated competency in RTRI prior to testing?'); ?></td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_2_TESTERS_DEMONSTRATED_COMPETENCY']) && $formData['RTRI_Q_8_2_TESTERS_DEMONSTRATED_COMPETENCY'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_2_TESTERS_DEMONSTRATED_COMPETENCY']) && $formData['RTRI_Q_8_2_TESTERS_DEMONSTRATED_COMPETENCY'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_2_TESTERS_DEMONSTRATED_COMPETENCY']) && $formData['RTRI_Q_8_2_TESTERS_DEMONSTRATED_COMPETENCY'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="rtri_C_8_2"><?php echo ($formData['RTRI_C_8_2_TESTERS_DEMONSTRATED_COMPETENCY']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['RTRI_Q_8_2_TESTERS_DEMONSTRATED_COMPETENCY']; ?></td>
                            </tr>
                            <tr>
                              <td>8.3</td>
                              <td><?= $this->translate('Are all current versions of recency/RTRI SOPs and/or job aids readily available at the site?'); ?> </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_3_JOBAIDS_READILY_AVAILABLE']) && $formData['RTRI_Q_8_3_JOBAIDS_READILY_AVAILABLE'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_3_JOBAIDS_READILY_AVAILABLE']) && $formData['RTRI_Q_8_3_JOBAIDS_READILY_AVAILABLE'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_3_JOBAIDS_READILY_AVAILABLE']) && $formData['RTRI_Q_8_3_JOBAIDS_READILY_AVAILABLE'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="rtri_C_8_3"><?php echo ($formData['RTRI_C_8_3_JOBAIDS_READILY_AVAILABLE']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['RTRI_Q_8_3_JOBAIDS_READILY_AVAILABLE']; ?></td>
                            </tr>
                            <tr>
                              <td>8.4</td>
                              <td><?= $this->translate('Is there a sufficient supply of RTRI tests available at the site?'); ?>
                                <?= $this->translate('Please provide number of tests currently available…….'); ?></td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_4_SUFFICIENT_SUPPLY_AVAILABLE']) && $formData['RTRI_Q_8_4_SUFFICIENT_SUPPLY_AVAILABLE'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_4_SUFFICIENT_SUPPLY_AVAILABLE']) && $formData['RTRI_Q_8_4_SUFFICIENT_SUPPLY_AVAILABLE'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_4_SUFFICIENT_SUPPLY_AVAILABLE']) && $formData['RTRI_Q_8_4_SUFFICIENT_SUPPLY_AVAILABLE'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="rtri_C_8_4"><?php echo ($formData['RTRI_C_8_4_SUFFICIENT_SUPPLY_AVAILABLE']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['RTRI_Q_8_4_SUFFICIENT_SUPPLY_AVAILABLE']; ?></td>
                            </tr>
                            <tr>
                              <td>8.5</td>
                              <td><?= $this->translate('Are the test kits kept in a temperature controlled environment based on the manufacturers instructions?'); ?></td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_5_RTRI_KIT_STORAGE']) && $formData['RTRI_Q_8_5_RTRI_KIT_STORAGE'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_5_RTRI_KIT_STORAGE']) && $formData['RTRI_Q_8_5_RTRI_KIT_STORAGE'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_5_RTRI_KIT_STORAGE']) && $formData['RTRI_Q_8_5_RTRI_KIT_STORAGE'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="rtri_C_8_5"><?php echo ($formData['RTRI_C_8_5_RTRI_KIT_STORAGE']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['RTRI_Q_8_5_RTRI_KIT_STORAGE']; ?></td>
                            </tr>
                            <tr>
                              <td>8.6</td>
                              <td><?= $this->translate('Are RTRI testing procedures being followed (i.e. right volume of sample using correct sample application device, correct read time, correct result interpretation)?'); ?></td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_6_RTRI_TESTING_PROCEDURE_FOLLOWED']) && $formData['RTRI_Q_8_6_RTRI_TESTING_PROCEDURE_FOLLOWED'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_6_RTRI_TESTING_PROCEDURE_FOLLOWED']) && $formData['RTRI_Q_8_6_RTRI_TESTING_PROCEDURE_FOLLOWED'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_6_RTRI_TESTING_PROCEDURE_FOLLOWED']) && $formData['RTRI_Q_8_6_RTRI_TESTING_PROCEDURE_FOLLOWED'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="rtri_C_8_6"><?php echo ($formData['RTRI_C_8_6_RTRI_TESTING_PROCEDURE_FOLLOWED']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['RTRI_Q_8_6_RTRI_TESTING_PROCEDURE_FOLLOWED']; ?></td>
                            </tr>
                            <tr>
                              <td>8.7</td>
                              <td><?= $this->translate('Are the RTRI results documented in the data capture form or logbook correctly (e.g. client demographics, kit name, lot number, expiration dates, tester name, RTRI visual results and recency interpretation) and reviewed by the person in charge?'); ?></td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_7_RTRI_TESTING_RESULTS_DOCUMENTED']) && $formData['RTRI_Q_8_7_RTRI_TESTING_RESULTS_DOCUMENTED'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_7_RTRI_TESTING_RESULTS_DOCUMENTED']) && $formData['RTRI_Q_8_7_RTRI_TESTING_RESULTS_DOCUMENTED'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_7_RTRI_TESTING_RESULTS_DOCUMENTED']) && $formData['RTRI_Q_8_7_RTRI_TESTING_RESULTS_DOCUMENTED'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="rtri_C_8_7"><?php echo ($formData['RTRI_C_8_7_RTRI_TESTING_RESULTS_DOCUMENTED']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['RTRI_Q_8_7_RTRI_TESTING_RESULTS_DOCUMENTED']; ?></td>
                            </tr>
                            <tr>
                              <td>8.8</td>
                              <td> <?= $this->translate('Are external quality control (QC) specimens (i.e. long-term (LT), recent and negative) routinely used (i.e. monthly) for RTRI?'); ?></td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_8_QC_ROUTINELY_USED']) && $formData['RTRI_Q_8_8_QC_ROUTINELY_USED'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_8_QC_ROUTINELY_USED']) && $formData['RTRI_Q_8_8_QC_ROUTINELY_USED'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_8_QC_ROUTINELY_USED']) && $formData['RTRI_Q_8_8_QC_ROUTINELY_USED'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="rtri_C_8_8"><?php echo ($formData['RTRI_C_8_8_QC_ROUTINELY_USED']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['RTRI_Q_8_8_QC_ROUTINELY_USED']; ?></td>
                            </tr>
                            <tr>
                              <td>8.9</td>
                              <td><?= $this->translate('Are QC results for RTRI properly recorded (e.g. kit name, lot number, expiration dates, tester name, RTRI visual results and recency interpretation for each level of QC) and reviewed by person in charge?'); ?></td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_9_QC_RESULTS_RECORDED']) && $formData['RTRI_Q_8_9_QC_RESULTS_RECORDED'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_9_QC_RESULTS_RECORDED']) && $formData['RTRI_Q_8_9_QC_RESULTS_RECORDED'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_9_QC_RESULTS_RECORDED']) && $formData['RTRI_Q_8_9_QC_RESULTS_RECORDED'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="rtri_C_8_9"><?php echo ($formData['RTRI_C_8_9_QC_RESULTS_RECORDED']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['RTRI_Q_8_9_QC_RESULTS_RECORDED']; ?></td>
                            </tr>
                            <tr>
                              <td>8.10</td>
                              <td><?= $this->translate('Are appropriate steps taken and documented when RTRI QC results are incorrect?'); ?></td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_10_INCORRECT_QC_DOCUMENTED']) && $formData['RTRI_Q_8_10_INCORRECT_QC_DOCUMENTED'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_10_INCORRECT_QC_DOCUMENTED']) && $formData['RTRI_Q_8_10_INCORRECT_QC_DOCUMENTED'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_10_INCORRECT_QC_DOCUMENTED']) && $formData['RTRI_Q_8_10_INCORRECT_QC_DOCUMENTED'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="rtri_C_8_10"><?php echo ($formData['RTRI_C_8_10_INCORRECT_QC_DOCUMENTED']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['RTRI_Q_8_10_INCORRECT_QC_DOCUMENTED']; ?></td>
                            </tr>
                            <tr>
                              <td>8.11</td>
                              <td><?= $this->translate('Are appropriate steps taken and documented according to the SOP or guidelines for invalid RTRI test results? If yes, how many in the last 3 months…………(use comments)'); ?></td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_11_INVALID_RTRI_RESULTS']) && $formData['RTRI_Q_8_11_INVALID_RTRI_RESULTS'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_11_INVALID_RTRI_RESULTS']) && $formData['RTRI_Q_8_11_INVALID_RTRI_RESULTS'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['RTRI_Q_8_11_INVALID_RTRI_RESULTS']) && $formData['RTRI_Q_8_11_INVALID_RTRI_RESULTS'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="rtri_C_8_11"><?php echo ($formData['RTRI_C_8_11_INVALID_RTRI_RESULTS']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['RTRI_Q_8_11_INVALID_RTRI_RESULTS']; ?></td>
                            </tr>
                            <tr>
                              <th colspan="6">8.0 <?= $this->translate('HIV-1 RECENT INFECTION SURVEILLANCE USING THE RAPID TEST FOR RECENT INFECTION SCORE
                                If the country has implemented HIV-1 Recent Infection Surveillance under a study protocol proceed with Section S.0 and D.0 Otherwise, STOP here.
                                Please note that Section S.0 and D.0 are for study purposes only and are not to be included in the overall SPI-RRT score.'); ?></th>
                              <td style="text-align:center;"><?php echo $formData['RTRI_SCORE']; ?></td>
                            </tr>
                          </table>
                        </td>
                      </tr>
                    </table>
                  <?php }
                  if (isset($formData['DO_SURVEILLANCE']) && strtolower($formData['DO_SURVEILLANCE']) == 'yes') { ?>
                    <table cellspacing="0" cellpadding="5" class="table table-bordered">
                      <tr id="surveillanceTable1">
                        <th style="text-align:center;width:3%" class="details-control" onclick="$('#surveillanceTable').slideToggle('slow'),addShowClass('shown','surveillanceTable1');">

                        </th>
                        <th style="width:93%">
                          <a href="javascript:void(0);" onclick="$('#surveillanceTable').slideToggle('slow'),addShowClass('shown','surveillanceTable1');">S.0 <?= $this->translate('HIV-1 RECENT INFECTION SURVEILLANCE STUDY PROTOCOL'); ?></a>
                        </th>
                        <th style="text-align:center;width:5%">S</th>
                      </tr>
                      <tr id="surveillanceTable" style="display: none;">
                        <td colspan="3">
                          <table cellspacing="0" cellpadding="5" class="table table-bordered">
                            <tr>
                              <td style="text-align:center;font-weight:bold;width:45%;" colspan="2"><?= $this->translate('SECTION'); ?></td>
                              <th style="text-align:center;width:3%;"><?= $this->translate('YES'); ?></th>
                              <th style="text-align:center;width:4%;"><?= $this->translate('Partial'); ?></th>
                              <th style="text-align:center;width:3%;"><?= $this->translate('NO'); ?></th>
                              <th style="text-align:center;width:40%;"><?= $this->translate('Comments'); ?></th>
                              <th style="text-align:center;width:5%;"><?= $this->translate('Score'); ?></th>
                            </tr>
                            <tr>
                              <td>S.1</td>
                              <td><?= $this->translate('Are counselors adhering to the study protocol for eligibility, consent, and counseling?'); ?></td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_1_SURVEILLANCE_STUDY_PROTOCOL_ELIGIBILITY']) && $formData['S0_Q_1_SURVEILLANCE_STUDY_PROTOCOL_ELIGIBILITY'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_1_SURVEILLANCE_STUDY_PROTOCOL_ELIGIBILITY']) && $formData['S0_Q_1_SURVEILLANCE_STUDY_PROTOCOL_ELIGIBILITY'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_1_SURVEILLANCE_STUDY_PROTOCOL_ELIGIBILITY']) && $formData['S0_Q_1_SURVEILLANCE_STUDY_PROTOCOL_ELIGIBILITY'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="sur_c_s_1"><?php echo ($formData['S0_C_1_SURVEILLANCE_STUDY_PROTOCOL_ELIGIBILITY']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['S0_Q_1_SURVEILLANCE_STUDY_PROTOCOL_ELIGIBILITY']; ?></td>
                            </tr>
                            <tr>
                              <td>S.2</td>
                              <td><?= $this->translate('Are counselors following the study protocol for confirming new diagnosis?'); ?></td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_2_COUNSELORS_FOLLOWING_PROTOCOL']) && $formData['S0_Q_2_COUNSELORS_FOLLOWING_PROTOCOL'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_2_COUNSELORS_FOLLOWING_PROTOCOL']) && $formData['S0_Q_2_COUNSELORS_FOLLOWING_PROTOCOL'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_2_COUNSELORS_FOLLOWING_PROTOCOL']) && $formData['S0_Q_2_COUNSELORS_FOLLOWING_PROTOCOL'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="sur_c_s_2"><?php echo ($formData['S0_C_2_COUNSELORS_FOLLOWING_PROTOCOL']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['S0_Q_2_COUNSELORS_FOLLOWING_PROTOCOL']; ?></td>
                            </tr>
                            <tr>
                              <td>S.3</td>
                              <td><?= $this->translate('For those patients with RTRI recent, are VL tests requested, samples collected and sent to VL testing lab, and VL test requests recorded in the recency VL order form?'); ?></td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_3_TESTS_RECORDED_RECENCY']) && $formData['S0_Q_3_TESTS_RECORDED_RECENCY'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_3_TESTS_RECORDED_RECENCY']) && $formData['S0_Q_3_TESTS_RECORDED_RECENCY'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_3_TESTS_RECORDED_RECENCY']) && $formData['S0_Q_3_TESTS_RECORDED_RECENCY'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="sur_c_s_3"><?php echo ($formData['S0_C_3_TESTS_RECORDED_RECENCY']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['S0_Q_3_TESTS_RECORDED_RECENCY']; ?></td>
                            </tr>
                            <tr>
                              <td>S.4</td>
                              <td><?= $this->translate('Are processes in place and well documented (Job Aid, SOP, etc.) for returning RTRI results? (if applicable)'); ?></td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_4_PROCESS_DOCUMENTED']) && $formData['S0_Q_4_PROCESS_DOCUMENTED'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_4_PROCESS_DOCUMENTED']) && $formData['S0_Q_4_PROCESS_DOCUMENTED'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_4_PROCESS_DOCUMENTED']) && $formData['S0_Q_4_PROCESS_DOCUMENTED'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="sur_c_s_4"><?php echo ($formData['S0_C_4_PROCESS_DOCUMENTED']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['S0_Q_4_PROCESS_DOCUMENTED']; ?></td>
                            </tr>
                            <tr>
                              <td>S.5</td>
                              <td><?= $this->translate('Are RITA results returned to the facility/client within 2 weeks (dependent on protocol)?'); ?> </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_5_RESULTS_RETURNED_IN_TWO_WEEKS']) && $formData['S0_Q_5_RESULTS_RETURNED_IN_TWO_WEEKS'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_5_RESULTS_RETURNED_IN_TWO_WEEKS']) && $formData['S0_Q_5_RESULTS_RETURNED_IN_TWO_WEEKS'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_5_RESULTS_RETURNED_IN_TWO_WEEKS']) && $formData['S0_Q_5_RESULTS_RETURNED_IN_TWO_WEEKS'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="sur_c_s_5"><?php echo ($formData['S0_C_5_RESULTS_RETURNED_IN_TWO_WEEKS']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['S0_Q_5_RESULTS_RETURNED_IN_TWO_WEEKS']; ?></td>
                            </tr>
                            <tr>
                              <td>S.6</td>
                              <td><?= $this->translate('Are protocol violations documented?'); ?></td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_6_PROTOCOL_VIOLATION_DOCUMENTED']) && $formData['S0_Q_6_PROTOCOL_VIOLATION_DOCUMENTED'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_6_PROTOCOL_VIOLATION_DOCUMENTED']) && $formData['S0_Q_6_PROTOCOL_VIOLATION_DOCUMENTED'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_6_PROTOCOL_VIOLATION_DOCUMENTED']) && $formData['S0_Q_6_PROTOCOL_VIOLATION_DOCUMENTED'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="sur_c_s_6"><?php echo ($formData['S0_C_6_PROTOCOL_VIOLATION_DOCUMENTED']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['S0_Q_6_PROTOCOL_VIOLATION_DOCUMENTED']; ?></td>
                            </tr>
                            <tr>
                              <td>S.7</td>
                              <td><?= $this->translate('Are appropriate steps taken and documented according to the study procedures when a protocol violation occurs?'); ?></td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_7_DOCUMENTING_PROTOCOL_ERRORS']) && $formData['S0_Q_7_DOCUMENTING_PROTOCOL_ERRORS'] == 1) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_7_DOCUMENTING_PROTOCOL_ERRORS']) && $formData['S0_Q_7_DOCUMENTING_PROTOCOL_ERRORS'] == 0.5) ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td style="text-align:center;">
                                <?php echo (isset($formData['S0_Q_7_DOCUMENTING_PROTOCOL_ERRORS']) && $formData['S0_Q_7_DOCUMENTING_PROTOCOL_ERRORS'] == "0") ? "<img src='" . $this->basePath('assets/img/black-tick.png') . "' width='20'>" : ""; ?>
                              </td>
                              <td><textarea class="form-control" name="sur_c_s_7"><?php echo ($formData['S0_C_7_DOCUMENTING_PROTOCOL_ERRORS']); ?></textarea></td>
                              <td style="text-align:center;"><?php echo $formData['S0_Q_7_DOCUMENTING_PROTOCOL_ERRORS']; ?></td>
                            </tr>
                            <tr>
                              <th colspan="7">S.0 <?= $this->translate('HIV-1 RECENT INFECTION SURVEILLANCE STUDY PROTOCOL'); ?></th>
                            </tr>
                          </table>
                        </td>
                      </tr>
                    </table>
                    <table cellspacing="0" cellpadding="5" class="table table-bordered">
                      <tr id="dataIndicatorTable1">
                        <th style="text-align:center;width:3%" class="details-control" onclick="$('#dataIndicatorTable').slideToggle('slow'),addShowClass('shown','dataIndicatorTable1');">

                        </th>
                        <th style="width:93%">
                          <a href="javascript:void(0);" onclick="$('#dataIndicatorTable').slideToggle('slow'),addShowClass('shown','dataIndicatorTable1');">D.0 <?= $this->translate('HIV-1 RECENT INFECTION SURVEILLANCE USING DATA INDICATORS'); ?></a>
                        </th>
                        <th style="text-align:center;width:5%">D</th>
                      </tr>
                      <tr id="dataIndicatorTable" style="display: none;">
                        <td colspan="3">
                          <table cellspacing="0" cellpadding="5" class="table table-bordered">
                            <tr>
                              <td style="text-align:center;font-weight:bold;width:45%;" colspan="2"><?= $this->translate('SECTION'); ?></td>
                              <th style="text-align:center;width:3%;"><?= $this->translate('Number'); ?></th>
                              <th style="text-align:center;width:4%;"><?= $this->translate('Denominator'); ?></th>
                              <th style="text-align:center;width:3%;"><?= $this->translate('Score'); ?></th>
                              <!-- <th style="text-align:center;width:40%;">Comments</th>
                                <th style="text-align:center;width:5%;">Score</th> -->
                            </tr>
                            <tr>
                              <td>D.1</td>
                              <td><?= $this->translate('Number of persons aged > 15 newly diagnosed with HIV at service delivery point during review period'); ?></td>
                              <td><input type="text" class="form-control" name="dati_n_1" value="<?php echo ($formData['D0_N_1_DIAGNOSED_HIV_ABOVE_15']); ?>" /></td>
                              <td><input type="text" class="form-control" name="dati_d_1" value="<?php echo ($formData['D0_D_1_DIAGNOSED_HIV_ABOVE_15']); ?>" /></td>
                              <td><input type="text" class="form-control" name="dati_s_1" value="<?php echo ($formData['D0_S_1_DIAGNOSED_HIV_ABOVE_15']); ?>" /></td>
                            </tr>
                            <tr>
                              <td>D.2</td>
                              <td><?= $this->translate('Number of candidates screened for participation in RTRI at service delivery point during review period'); ?></td>
                              <td><input type="text" class="form-control" name="dati_n_2" value="<?php echo ($formData['D0_N_2_CANDIDATE_SCREENED_FOR_PARTICIPATION']); ?>" /></td>
                              <td><input type="text" class="form-control" name="dati_d_2" value="<?php echo ($formData['D0_D_2_CANDIDATE_SCREENED_FOR_PARTICIPATION']); ?>" /></td>
                              <td><input type="text" class="form-control" name="dati_s_2" value="<?php echo ($formData['D0_S_2_CANDIDATE_SCREENED_FOR_PARTICIPATION']); ?>" /></td>
                            </tr>
                            <tr>
                              <td>D.3</td>
                              <td><?= $this->translate('Number of total eligible candidates at service delivery point during review period'); ?></td>
                              <td><input type="text" class="form-control" name="dati_n_3" value="<?php echo ($formData['D0_N_3_ELIGIBLE_DURING_REVIEW_PERIOD']); ?>" /></td>
                              <td><input type="text" class="form-control" name="dati_d_3" value="<?php echo ($formData['D0_D_3_ELIGIBLE_DURING_REVIEW_PERIOD']); ?>" /></td>
                              <td><input type="text" class="form-control" name="dati_s_3" value="<?php echo ($formData['D0_S_3_ELIGIBLE_DURING_REVIEW_PERIOD']); ?>" /></td>
                            </tr>
                            <tr>
                              <td>D.4</td>
                              <td><?= $this->translate('Number of eligible candidates at service delivery point who declined during review period'); ?></td>
                              <td><input type="text" class="form-control" name="dati_n_4" value="<?php echo ($formData['D0_N_4_ELIGIBLE_AND_DECLINED_REVIEW_PERIOD']); ?>" /></td>
                              <td><input type="text" class="form-control" name="dati_d_4" value="<?php echo ($formData['D0_D_4_ELIGIBLE_AND_DECLINED_REVIEW_PERIOD']); ?>" /></td>
                              <td><input type="text" class="form-control" name="dati_s_4" value="<?php echo ($formData['D0_S_4_ELIGIBLE_AND_DECLINED_REVIEW_PERIOD']); ?>" /></td>
                            </tr>
                            <tr>
                              <td>D.5</td>
                              <td><?= $this->translate('Number of candidates with documented reason for refusal at service delivery point during review period'); ?></td>
                              <td><input type="text" class="form-control" name="dati_n_5" value="<?php echo ($formData['D0_N_5_DOCUMENTED_AND_REFUSED']); ?>" /></td>
                              <td><input type="text" class="form-control" name="dati_d_5" value="<?php echo ($formData['D0_D_5_DOCUMENTED_AND_REFUSED']); ?>" /></td>
                              <td><input type="text" class="form-control" name="dati_s_5" value="<?php echo ($formData['D0_S_5_DOCUMENTED_AND_REFUSED']); ?>" /></td>
                            </tr>
                            <tr>
                              <td>D.6</td>
                              <td><?= $this->translate('Number of participants enrolled in RTRI testing at service delivery point during review period'); ?></td>
                              <td><input type="text" class="form-control" name="dati_n_6" value="<?php echo ($formData['D0_N_6_PARTICIAPANTS_ENROLLED_IN_RTRI']); ?>" /></td>
                              <td><input type="text" class="form-control" name="dati_d_6" value="<?php echo ($formData['D0_D_6_PARTICIAPANTS_ENROLLED_IN_RTRI']); ?>" /></td>
                              <td><input type="text" class="form-control" name="dati_s_6" value="<?php echo ($formData['D0_S_6_PARTICIAPANTS_ENROLLED_IN_RTRI']); ?>" /></td>
                            </tr>
                            <tr>
                              <td>D.7</td>
                              <td><?= $this->translate('Number of participants incorrectly enrolled (i.e. ineligible) at service delivery point during review period'); ?></td>
                              <td><input type="text" class="form-control" name="dati_n_7" value="<?php echo ($formData['D0_N_7_PARTICIAPANTS_INCORRECTLY_ENROLLED_IN_RTRI']); ?>" /></td>
                              <td><input type="text" class="form-control" name="dati_d_7" value="<?php echo ($formData['D0_D_7_PARTICIAPANTS_INCORRECTLY_ENROLLED_IN_RTRI']); ?>" /></td>
                              <td><input type="text" class="form-control" name="dati_s_7" value="<?php echo ($formData['D0_S_7_PARTICIAPANTS_INCORRECTLY_ENROLLED_IN_RTRI']); ?>" /></td>
                            </tr>
                            <tr>
                              <td>D.8</td>
                              <td><?= $this->translate('Number of eligible participants enrolled with correct consent documentation at service delivery point during review period'); ?></td>
                              <td><input type="text" class="form-control" name="dati_n_8" value="<?php echo ($formData['D0_N_8_PARTICIAPANTS_CORRECTLY_ENROLLED_IN_RTRI']); ?>" /></td>
                              <td><input type="text" class="form-control" name="dati_d_8" value="<?php echo ($formData['D0_D_8_PARTICIAPANTS_CORRECTLY_ENROLLED_IN_RTRI']); ?>" /></td>
                              <td><input type="text" class="form-control" name="dati_s_8" value="<?php echo ($formData['D0_S_8_PARTICIAPANTS_CORRECTLY_ENROLLED_IN_RTRI']); ?>" /></td>
                            </tr>
                            <tr>
                              <th colspan="5"><?= $this->translate('D.0 HIV-1 RECENT INFECTION SURVEILLANCE USING DATA INDICATORS'); ?> </th>
                            </tr>
                          </table>
                        </td>
                      </tr>
                    </table>
                  <?php } ?>
                  <h4><b><?= $this->translate('PART C: SCORING CRITERIA'); ?></b></h4>
                  <p><?= $this->translate('Each element marked will be assigned a point value:'); ?></p>
                  <div style="margin-left:10px;">
                    <p>* <?= $this->translate('Items marked "Yes" receive 1 point each.'); ?></p>
                    <p>* <?= $this->translate('Items marked "Partial" receive 0.5 point each.'); ?></p>
                    <p>* <?= $this->translate('Items marked "No" receive 0 point each.'); ?></p>
                  </div>
                  <p><?= $this->translate('Total points scored for each section should be tallied and recorded at the end of the section.'); ?></p>
                  <p><?= $this->translate('The overall total points obtained by each HIV testing point audited will be weighed to correspond to a specific performance level.'); ?></p>

                  <table class="table table-bordered" cellspacing="0" cellpadding="5">
                    <tr style="text-align:center;">
                      <th><?= $this->translate('Levels'); ?></th>
                      <th>% <?= $this->translate('Score'); ?></th>
                      <th><?= $this->translate('Description of results'); ?></th>
                    </tr>
                    <tr>
                      <td style="background-color:#C00000;color:#000000;">Level 0'); ?></td>
                      <td><?= $this->translate('Less than 40%'); ?></td>
                      <td><?= $this->translate('Needs improvement in all areas and immediate remediation'); ?></td>
                    </tr>
                    <tr>
                      <td style="background-color:#E36C0A;color:#000000;"><?= $this->translate('Level 1'); ?></td>
                      <td>40% - 59%'</td>
                      <td><?= $this->translate('Needs improvement in specific areas'); ?></td>
                    </tr>
                    <tr>
                      <td style="background-color:#FFFF00;color:#000000;"><?= $this->translate('Level 2'); ?></td>
                      <td><?= $this->translate('60% - 79%'); ?></td>
                      <td><?= $this->translate('Partially eligible'); ?></td>
                    </tr>
                    <tr>
                      <td style="background-color:#92D050;color:#000000;"><?= $this->translate('Level 3'); ?></td>
                      <td>80% - 89%</td>
                      <td><?= $this->translate('Close to national site certification'); ?></td>
                    </tr>
                    <tr>
                      <td style="background-color:#00B050;color:#000000;"><?= $this->translate('Level 4'); ?></td>
                      <td>90% or higher</td>
                      <td><?= $this->translate('Eligible to national site certification'); ?></td>
                    </tr>
                  </table>

                  <h4><b><?= $this->translate("Part D. Auditor's Summation Report for SPI-RRT Audit"); ?></b></h4>

                  <div class="form-group col-lg-6">
                    <label><?= $this->translate('Facility Name'); ?></label>
                    <p class="form-control" id="facilityName"><?php echo $formData['facilityInfo']->fName; ?></p>
                  </div>
                  <div class="form-group col-lg-6">
                    <label><?= $this->translate('Site Type'); ?></label>
                    <p class="form-control" id="siteType"><?php echo $formData['testingpointtype']; ?></p>
                  </div>
                  <div class="form-group col-lg-6">
                    <label><?= $this->translate('Staff Audited Name'); ?></label>
                    <input type="text" placeholder="<?= $this->translate('Staff Audited Name'); ?>" name="staffAuditedName" class="form-control" value="<?php echo $formData['staffaudited']; ?>">
                  </div>
                  <div class="form-group col-lg-6">
                    <label><?= $this->translate('No. of Tester(s)'); ?></label>
                    <p class="form-control" id="noOfTesterId"><?php echo $formData['NumberofTester']; ?></p>
                  </div>

                  <div class="form-group col-lg-6">
                    <label><?= $this->translate('Duration of Audit'); ?></label>
                    <input type="text" placeholder="<?= $this->translate('Duration of Audit'); ?>" name="durationaudit" class="form-control" value="<?php echo $formData['durationaudit']; ?>">
                  </div>

                  <div class="form-group col-lg-6">
                    <label><?= $this->translate('Total points scored (exclude N/A)'); ?></label>
                    <p class="form-control"><?php echo $formData['FINAL_AUDIT_SCORE']; ?></p>
                  </div>


                  <div class="form-group col-lg-6">
                    <label><?= $this->translate('Total score expected'); ?></label>
                    <p class="form-control"><?php echo $formData['MAX_AUDIT_SCORE']; ?></p>
                  </div>
                  <div class="form-group col-lg-3">
                    <label>%<?= $this->translate('Score'); ?></label>
                    <p class="form-control"><?php echo round($formData['AUDIT_SCORE_PERCENTAGE'], 2); ?></p>
                  </div>
                  <div class="form-group col-lg-3">
                    <label>&nbsp;</label>
                    <?php
                    $level = '';
                    $colorCode = '';
                    $scorePer = round($formData['AUDIT_SCORE_PERCENTAGE']);
                    if ($scorePer < 40) {
                      $level = "Level 0";
                      $colorCode = "background-color:#C00000";
                    } elseif ($scorePer >= 40 && $scorePer <= 59) {
                      $level = "Level 1";
                      $colorCode = "background-color:#E36C0A";
                    } elseif ($scorePer >= 60 && $scorePer <= 79) {
                      $level = "Level 2";
                      $colorCode = "background-color:#FFFF00";
                    } elseif ($scorePer >= 80 && $scorePer <= 89) {
                      $level = "Level 3";
                      $colorCode = "background-color:#92D050";
                    } elseif ($scorePer >= 90) {
                      $level = "Level 4";
                      $colorCode = "background-color:#00B050";
                    }
                    ?>
                    <p class="form-control" style="color:#000000;<?php echo $colorCode; ?>; border:0;"><?php echo $level; ?></p>
                  </div>

                  <table id="correctiveActionTable" class="table table-bordered" cellspacing="0" cellpadding="5" style="width:100%">
                    <tr>
                      <th rowspan="2" style="text-align:center;width:3%"><?= $this->translate('Section No.'); ?></th>
                      <th rowspan="2" style="text-align:center;width:20%"><?= $this->translate('Deficiency/Issue observed'); ?></th>
                      <th colspan="2" style="text-align:center;width:8%"><?= $this->translate('Correction'); ?> <br /><?= $this->translate('Actions'); ?></th>
                      <th rowspan="2" style="text-align:center;width:33%"><?= $this->translate("Auditor's"); ?> <br /><?= $this->translate('Comments'); ?></th>
                      <th colspan="2" style="text-align:center;width:36%"><?= $this->translate('Recommendations'); ?></th>
                      <th rowspan="2"><?= $this->translate('Add/'); ?><br /><?= $this->translate('Remove'); ?></th>
                    </tr>
                    <tr>
                      <th style="text-align:center;width:4%;"><?= $this->translate('Immediate'); ?></th>
                      <th style="text-align:center;width:4%;"><?= $this->translate('Follow up'); ?></th>
                      <th style="text-align:center;width:30%;"><?= $this->translate('Actions'); ?></th>
                      <th style="text-align:center;width:4%;"><?= $this->translate('Timeline / Person responsible'); ?></th>
                    </tr>
                    <?php
                    $i = 3;
                    if (isset($formData['correctiveaction']) && trim($formData['correctiveaction']) != "" && $formData['correctiveaction'] != "[]" && is_array(json_decode($formData['correctiveaction'], true))) {
                      $correctiveActions = json_decode($formData['correctiveaction'], true);
                      foreach ($correctiveActions as $ca) {
                    ?>
                        <tr>
                          <td style="text-align:center;">
                            <input type="text" name="sectionNo[]" class="form-control" value="<?php if (empty($ca['sectionno'])) {
                                                                                                '';
                                                                                              } else {
                                                                                                echo $ca['sectionno'];
                                                                                              } ?>">
                            <input type="hidden" name="rowId[]" class="form-control" value="<?php echo $i; ?>">
                          </td>
                          <td>
                            <input type="text" name="deficiency[]" class="form-control" value="<?php if (empty($ca['deficiency'])) {
                                                                                                  '';
                                                                                                } else {
                                                                                                  echo $ca['deficiency'];
                                                                                                } ?>">
                          </td>
                          <td align="center">
                            <input type="radio" class="isRequired" name="correction<?php echo $i; ?>" value="Immediate" <?php if ($ca['correction'] == 'Immediate') {
                                                                                                                          echo "checked";
                                                                                                                        } ?> title="Please select the corrective action">
                          </td>
                          <td align="center">
                            <input type="radio" class="isRequired" name="correction<?php echo $i; ?>" value="Followup" <?php if ($ca['correction'] == 'Followup') {
                                                                                                                          echo "checked";
                                                                                                                        } ?> title="Please select the corrective action">
                          </td>
                          <td><textarea class="form-control" name="auditorComment[]"><?php if (empty($ca['auditorcomment'])) {
                                                                                        '';
                                                                                      } else {
                                                                                        echo $ca['auditorcomment'];
                                                                                      } ?></textarea></td>
                          <td><textarea class="form-control" name="action[]"><?php if (empty($ca['action'])) {
                                                                                '';
                                                                              } else {
                                                                                echo $ca['action'];
                                                                              } ?></textarea></td>
                          <td>
                            <input type="text" name="timeline[]" class="form-control" value="<?php if (empty($ca['timeline'])) {
                                                                                                '';
                                                                                              } else {
                                                                                                echo $ca['timeline'];
                                                                                              } ?>">
                          </td>
                          <td align="center">
                            <a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a>
                            <a class="btn btn-xs btn-warning" href="javascript:void(0);" onclick="removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>
                          </td>
                        </tr>
                      <?php
                        $i++;
                      }
                      ?>

                    <?php
                    } else {
                    ?>
                      <tr>
                        <td style="text-align:center;">
                          <input type="text" name="sectionNo[]" class="form-control">
                          <input type="hidden" name="rowId[]" class="form-control" value="3">
                        </td>
                        <td>
                          <input type="text" name="deficiency[]" class="form-control">
                        </td>
                        <td style="text-align:center;">
                          <input type="radio" name="correction3" value="Immediate">
                        </td>
                        <td style="text-align:center;">
                          <input type="radio" name="correction3" value="Followup">
                        </td>
                        <td><textarea class="form-control" name="auditorComment[]"></textarea></td>
                        <td><textarea class="form-control" name="action[]"></textarea></td>
                        <td>
                          <input type="text" name="timeline[]" class="form-control">
                        </td>
                        <td align="center">
                          <a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a>
                          <a class="btn btn-xs btn-warning" href="javascript:void(0);" onclick="removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>
                        </td>
                      </tr>
                    <?php
                    }
                    ?>
                  </table>
                  <div class="spacer  col-lg-12">

                    <button type="button" onclick="validateNow()" class="btn btn-space btn-primary"><?= $this->translate('Save'); ?></button>
                    <a href="<?php echo $this->url('spi-v6-form', array('action' => 'manage-facility')); ?>" class="btn btn-space btn-default"><?= $this->translate('Cancel'); ?></a>
                  </div>

              </form>
            </div>
          </div>
        </div>
      </div>

      <br />



    </div>
  </div>
  <script src="<?php echo $this->basePath('assets/js/bootstrap-typeahead.js'); ?>" type="text/javascript"></script>
  <script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
  <script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      $(".select2").select2({
        width: '100%',
        placeholder: '',
        allowClear: true,
        tags: false
      });
    });
    duplicateName = true;
    rowCount = '<?php echo $i; ?>';

    function validateNow() {
      flag = deforayValidator.init({
        formId: 'editSPIRT'
      });
      if (flag) {
        if (duplicateName) {
          document.getElementById('editSPIRT').submit();
        }
      }
    }

    $(function() {

      //$('.datepicker').datepicker({
      //    changeMonth: true,
      //    changeYear: true,
      //    dateFormat: 'dd-M-yy',
      //    yearRange: < ?php echo ( date('Y') - 50); ?> + ":" + "< ?php echo (date('Y')) ?>"
      //});
    });

    function copyFacilityName(objVal) {
      $("#facilityName").html(objVal);
    }

    function copySiteType(objVal) {
      $("#siteType").html(objVal);
    }

    function copyNoOfTest(objVal) {
      $("#noOfTesterId").html(objVal);
    }

    function insRow() {
      rowCount++;
      rl = document.getElementById("correctiveActionTable").rows.length;
      var a = document.getElementById("correctiveActionTable").insertRow(rl);
      a.setAttribute("style", "display:none;");
      a.setAttribute("class", "data");
      var b = a.insertCell(0);
      var c = a.insertCell(1);
      var d = a.insertCell(2);
      var e = a.insertCell(3);
      var f = a.insertCell(4);
      var g = a.insertCell(5);
      var h = a.insertCell(6);
      var i = a.insertCell(7);

      d.setAttribute("align", "center");
      e.setAttribute("align", "center");
      i.setAttribute("align", "center");

      rl = document.getElementById("correctiveActionTable").rows.length - 1;
      b.innerHTML = '<input type="text" class="form-control" id="sectionNo' + rowCount + '" name="sectionNo[]" /><input type="hidden" name="rowId[]" class="form-control" value="' + rowCount + '">';
      c.innerHTML = '<input type="text" class="form-control" id="deficiency' + rowCount + '" name="deficiency[]" />';
      d.innerHTML = '<input type="radio" class="isRequired" name="correction' + rowCount + '" value="Immediate" title="Please select the corrective action">';
      e.innerHTML = '<input type="radio" class="isRequired" name="correction' + rowCount + '" value="Followup" title="Please select the corrective action">';
      f.innerHTML = '<textarea class="form-control" name="auditorComment[]"></textarea>';
      g.innerHTML = '<textarea class="form-control" name="action[]"></textarea>';
      h.innerHTML = '<input type="text" name="timeline[]" class="form-control">';
      i.innerHTML = '<a class="btn btn-xs btn-success" href="javascript:void(0);" onclick="insRow();"><i class="fa fa-plus"></i></a> <a class="btn btn-xs btn-warning" href="javascript:void(0);" onclick="removeRow(this.parentNode.parentNode);"><i class="fa fa-minus"></i></a>';
      $(a).fadeIn(800);

    }

    function removeRow(el) {
      $(el).fadeOut("slow", function() {
        el.parentNode.removeChild(el);
        rl = document.getElementById("correctiveActionTable").rows.length;
        if (rl == 2) {
          insRow();
        }
      });
    }

    function addShowClass(className, idName) {
      $('#' + idName).toggleClass(className);
    }

    function getFacilityInfo() {
      if ($('#testingFacility').val() != '') {
        $.blockUI();
        $.post("<?php echo $this->url('spi-facility', array('action' => 'get-facility-details')); ?>", {
            id: $('#testingFacility').val()
          },
          function(data) {
            splitData = data.split('##');
            if (splitData.length == 8) {
              $('#testingFacilityName').val(splitData[1]);
              $('#testingFacilityId').val(splitData[0]);
              $('#email').val(splitData[2]);
              $('#contactPerson').val(splitData[3]);
              $('#district').val(splitData[4]);
              $('#province').val(splitData[5]);
              $('#latitude').val(splitData[6]);
              $('#longitude').val(splitData[7]);
              copyFacilityName(splitData[1]);
            } else {
              $('#testingFacilityName').val('');
              $('#testingFacilityId').val('');
              $('#email').val('');
              $('#contactPerson').val('');
              $('#district').val('');
              $('#province').val('');
              $('#latitude').val('');
              $('#longitude').val('');
              copyFacilityName('');
            }
            $.unblockUI();
          });
      } else {
        $('#testingFacilityName').val('');
        $('#testingFacilityId').val('');
        $('#email').val('');
        $('#contactPerson').val('');
        $('#district').val('');
        $('#province').val('');
        $('#latitude').val('');
        $('#longitude').val('');
        copyFacilityName('');
      }
    }

    function showTextBox(obj, textBoxId) {
      if (obj.value == 'other') {
        $("#" + textBoxId).show();
        $("#" + obj.id).hide();
      } else {
        $("#" + textBoxId).hide().val('');
        $("#" + obj.id).show();
      }
    }
  </script>
