<select class="" id="district" multiple="multiple" placeholder="Select District(s)">
    <?php
    foreach($result as $districtName){
    ?>
    <option value="<?php echo $districtName['district']; ?>"><?php echo ucwords($districtName['district']); ?></option>
    <?php
        }
    ?>
</select>
<script>
    $(document).ready(function () {
        new TomSelect('#district', {
            plugins: ['remove_button'],
            placeholder: 'Select District(s)',
            maxItems: null
        });
    });
</script>