<?php

use Laminas\Session\Container;

$sessionLogin = new Container('credo');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
if ($acl->isAllowed($role, 'Application\Controller\SpiV6Controller', 'download-pdf') || $acl->isAllowed($role, 'Application\Controller\SpiV6Controller', 'approve-status')) {
  $editAction = '{"sClass":"center details-control","bSortable":false},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false}';
} else {
  $editAction = '{"sClass":"center details-control","bSortable":false},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
}
$userMappingType = $sessionLogin->userMappingType;
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<style>
  .select2-container--default .select2-selection--single .select2-selection__arrow b:after {
    content: ""
  }

  .select2-container--default.select2-container--open .select2-selection--single .select2-selection__arrow b:after {
    content: ""
  }

  .select2-container .select2-selection--single {
    height: 40px;
  }

  .select2-container--default .select2-selection--single .select2-selection__rendered {
    line-height: 7px !important;
  }
</style>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css" />
<style>
  td.details-control {
    background: url('<?php echo $this->basePath('assets/img/details_open.png'); ?>') no-repeat center center;
    cursor: pointer;
  }

  tr.shown td.details-control {
    background: url('<?php echo $this->basePath('assets/img/details_close.png'); ?>') no-repeat center center;
  }

  .btn-success:hover {
    background-color: #5cb85c !important;
  }
</style>
<div class="am-content">
  <div class="page-head">
    <h2><?= $this->translate('SPI-RRT Checklist V6'); ?></h2>
  </div>

  <div class="main-content">
    <div class="widget widget-fullwidth widget-small" style="padding:5px;">
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default">
            <div class="panel-body">
              <form role="form" class="form-horizontal">
                <div class="form-group">
                  <label for="date" class="col-sm-2 control-label"><?= $this->translate('Date Range'); ?></label>
                  <div class=" col-lg-4">
                    <input type="text" placeholder="<?= $this->translate('Select Date Range'); ?>" class="form-control" id="date" readonly>
                  </div>
                  <label for="auditRndNo" class="col-sm-2 control-label"><?= $this->translate('Audit Round No.'); ?></label>
                  <div class=" col-lg-4">
                    <select class="form-control" id="auditRndNo">
                      <option value=''><?= $this->translate('All'); ?></option>
                      <?php for ($i = 1; $i <= 100; $i++) {
                        echo "<option value='" . $i . "'>" . $i . "</option>";
                      } ?>
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label for="affiliation" class="col-sm-2 control-label"><?= $this->translate('Affiliation'); ?></label>
                  <div class=" col-lg-4">
                    <select class="form-control" id="affiliation">
                      <option value=""><?= $this->translate('All'); ?></option>
                      <option value="Government"><?= $this->translate('Government'); ?></option>
                      <option value="Private"><?= $this->translate('Private'); ?></option>
                      <option value="faith"><?= $this->translate('Faith-based Organization'); ?></option>
                      <option value="nongovt"><?= $this->translate('Non-governmental organization'); ?></option>
                      <option value="Other"><?= $this->translate('Other'); ?></option>
                    </select>
                  </div>
                  <label for="scoreLevel" class="col-sm-2 control-label"><?= $this->translate('Score Level'); ?></label>
                  <div class=" col-lg-4">
                    <select class="form-control" id="scoreLevel">
                      <option value=""><?= $this->translate('All'); ?></option>
                      <option value="0">0</option>
                      <option value="1">1</option>
                      <option value="2">2</option>
                      <option value="3">3</option>
                      <option value="4">4</option>
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label for="country" class="col-sm-2 control-label country"><?= $this->translate('Country'); ?></label>
                  <div class=" col-lg-4 country">
                    <select class="form-control" multiple="multiple" name="country" id="country" title="<?= $this->translate('Please select the country'); ?>">
                        <option value=""><?= $this->translate('All'); ?></option>  
                        <?php foreach($locationResult['countries'] as $row){ ?>
                          <option value="<?php echo $row['country_id'];?>"><?php echo ucwords($row['country_name']);?></option>
                        <?php } ?>
                    </select>
                  </div>
                  <label for="province" class="col-sm-2 control-label province"><?= $this->translate('Province'); ?></label>
                  <div class=" col-lg-4 province">
                    <select class="form-control" multiple="multiple" id="province">
                      <option value=""><?= $this->translate('All'); ?></option>
                      <?php foreach ($locationResult['provinces'] as $val) { ?>
                        <option value="<?php echo $val['geo_id']; ?>"><?php echo ucwords($val['geo_name']); ?></option>
                      <?php } ?>
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label for="district" class="col-sm-2 control-label district"><?= $this->translate('District'); ?></label>
                  <div class=" col-lg-4 district">
                    <select class="form-control" id="district" multiple="multiple">
                      <option value=""><?= $this->translate('All'); ?></option>
                      <?php foreach ($locationResult['districts'] as $val) { ?>
                          <option value="<?php echo $val['geo_id']; ?>"><?php echo ucwords($val['geo_name']); ?></option>
                      <?php } ?>
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label for="testPoint" class="col-sm-2 control-label"><?= $this->translate('Type of Testing Point'); ?></label>
                  <div class=" col-lg-4">
                    <select class="form-control" id="testPoint" onchange="getTestingPointTypeNames();">
                      <option value=""><?= $this->translate('All'); ?></option>
                      <?php foreach ($testingPointResult as $val) { ?>
                        <option value="<?php echo $val['testingPointType']; ?>"><?php echo ucwords($val['testingPointType']); ?></option>
                      <?php } ?>
                    </select>
                  </div>
                  <div class="form-group">
                    <div class="testPointNameSection"></div>
                  </div>
                </div>
                <div class="form-group">
                  <label for="showAudits" class="col-sm-2 control-label"><?= $this->translate('Show Audits'); ?></label>
                  <div class=" col-lg-4">
                    <select class="form-control" id="showAudits">
                    <option value=""><?= $this->translate('All'); ?></option>
                      <option value="yes"><?= $this->translate('Already Printed'); ?></option>
                      <option value="no"><?= $this->translate('Not yet Printed'); ?></option>
                    </select>
                  </div>
                </div>
                <div class="form-group" style="text-align:center;">
                  <button type="button" onclick="search();" class="btn btn-space btn-primary"><?= $this->translate('Search'); ?></button>&nbsp;
                  <button type="button" onclick="exportSearchPDFData();" class="btn btn-space btn-success"><?= $this->translate('Export as PDF'); ?></button>
                  <?php if ($acl->isAllowed($role, 'Application\Controller\SpiV6Controller', 'view-bulk-downloads')) { ?>
                    <a href="/spi-v6/view-bulk-downloads" class="btn btn-space btn-success">View Bulk Downloads </a>
                  <?php } ?>
                </div>
              </form>
            </div>
            <?php if ($acl->isAllowed($role, 'Application\Controller\SpiV6Controller', 'duplicate')) { ?>
              <a id="duplicate" href="/spi-v6/duplicate" class="btn btn-danger btn-sm"><?= $this->translate('Duplicates'); ?> (0)</a>&nbsp;&nbsp;
            <?php } ?>
            <a href="/spi-v6/download-files" target="_blank" class="btn btn-success btn-sm" style="text-decoration:none;float:right;"><i class="fa fa-cloud-download" aria-hidden="true"></i> Download Audits in Bulk </a>
          </div>
        </div>
      </div>

      <table id="example" class="datatables table table-bordered table-condensed table-striped table-hover table-fw-widget">
        <thead>
          <tr>
            <th></th>
            <th><?= $this->translate('Facility Name'); ?></th>

            <th style="width:8%;"><?= $this->translate('Audit Round No.'); ?></th>
            <th style="width:10%;"><?= $this->translate('Audit Date'); ?></th>

            <th style="width:6%;"><?= $this->translate('Testing Point Type'); ?></th>
            <th><?= $this->translate('Affiliation'); ?></th>
            <th style="width:5%;"><?= $this->translate('Audit Score %'); ?></th>
            <th style="width:8%;"><?= $this->translate('Status'); ?></th>
            <?php if ($acl->isAllowed($role, 'Application\Controller\SpiV3Controller', 'download-pdf') || $acl->isAllowed($role, 'Application\Controller\SpiV3Controller', 'approve-status')) { ?>
              <th><?= $this->translate('Action'); ?></th>
            <?php } ?>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td colspan="11" class="dataTables_empty"><?= $this->translate('Loading data from server'); ?></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="spacer col-lg-12">
      <table style="width:100%;background-color:#fff;margin-bottom:20px;font-size:13px;">
        <tr>
          <td>&nbsp;<strong><?= $this->translate('No.of Audit(s)'); ?></strong></td>
          <td style="text-align:center;">:&nbsp;</td>
          <td id="totalAudit" style=""></td>
          <td style="padding-left:1%;"><strong><?= $this->translate('Avg. Audit Score'); ?></strong></td>
          <td style="text-align:center;">:&nbsp;</td>
          <td id="avgAuditScore"></td>
          <td style="width:2%;"></td>
          <td style="width:2%;background-color:red;"></td>
          <td style="padding-left:1%;"><strong><?= $this->translate('Level 0<br>(Below 40)'); ?></strong></td>
          <td style="text-align:center;">:&nbsp;</td>
          <td id="level0"></td>
          <td style="width:2%;"></td>
          <td style="width:2%;background-color:orange;"></td>
          <td style="padding-left:1%;"><strong><?= $this->translate('Level 1<br>(40-59)'); ?></strong></td>
          <td style="text-align:center;">:&nbsp;</td>
          <td id="level1"></td>
          <td style="width:2%;"></td>
          <td style="width:2%;background-color:yellow;"></td>
          <td style="padding-left:1%;"><strong><?= $this->translate('Level 2<br>(60-79)'); ?></strong></td>
          <td style="text-align:center;">:&nbsp;</td>
          <td id="level2"></td>
          <td style="width:2%;"></td>
          <td style="width:2%;background-color:#8DD63E;"></td>
          <td style="padding-left:1%;"><strong><?= $this->translate('Level 3<br>(80-89)'); ?></strong></td>
          <td style="text-align:center;">:&nbsp;</td>
          <td id="level3"></td>
          <td style="width:2%;"></td>
          <td style="width:2%;background-color:#528A16;"></td>
          <td style="padding-left:1%;"><strong><?= $this->translate('Level 4<br>(90 and above)'); ?></strong></td>
          <td style="text-align:center;">:&nbsp;</td>
          <td id="level4"></td>
        </tr>
      </table>
    </div>
    <div class="spacer col-lg-12">
      <!--<button type="button" onclick="window.location.href='< ?php echo $this->url('spi-v3-form',array('action'=>'export')); ?>'" class="btn btn-space btn-primary">Export All Data</button>-->
      <button type="button" onclick="exportData();" class="btn btn-space btn-primary"><?= $this->translate('Export All Data'); ?></button>
      <button type="button" onclick="exportSAndDData();" class="btn btn-space btn-primary"><?= $this->translate('Export D and S Data'); ?></button>
      &nbsp;&nbsp;<button type="button" onclick="exportPDFData();" class="btn btn-space btn-primary"><?= $this->translate('Export Summary Table as PDF'); ?></button>
    </div>
    <br>
    <br>
    <br>
    <br>
  </div>
</div>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.blockUI.min.js'); ?>"></script>
<script type="text/javascript">
  table = null;

  function formatValue(value) {
    //return '<a href="/spi-v3/print/'+value+'" target="_blank"><i class="fa fa-print"></i> Print Full Survey</a>'
    return '<a href="javascript:void(0);" onclick="downloadPdf(' + value + ')" ><i class="fa fa-print"></i> <?= $this->translate('Print Full Survey'); ?></a>' +
      '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;' +
      '<a href="javascript:void(0)" onclick="downloadCorrectiveActionPdf(' + value + ')" ><i class="fa fa-print"></i> <?= $this->translate('Print Corrective Actions'); ?></a>';
  }
  $(document).ready(function() {
    var startDate = "";
    var endDate = "";
    // $("#province").multipleSelect({
    //   placeholder: '< ?= $this->translate('Select Province/District(s)'); ?>',
    //   width: '100%'
    // });
    $('#date').daterangepicker({
        format: 'DD-MMM-YYYY',
        startDate: moment().subtract('days', 29),
        endDate: moment(),
        maxDate: moment(),
        ranges: {
          'Today': [moment(), moment()],
          'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
          'Last 7 Days': [moment().subtract('days', 6), moment()],
          'Last 30 Days': [moment().subtract('days', 29), moment()],
          'This Month': [moment().startOf('month'), moment().endOf('month')],
          'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
        }
      },
      function(start, end) {
        startDate = start.format('YYYY-MM-DD');
        endDate = end.format('YYYY-MM-DD');
      });
    table = $('#example').DataTable({
      "bProcessing": true,
      "bServerSide": true,
      "aoColumns": [
        <?php echo $editAction; ?>
      ],
      "iDisplayLength": 50,
      "pageLength": 50,
      "aaSorting": [
        [3, "desc"]
      ],
      "sAjaxSource": "<?php echo $this->url('spi-v6-form', array('action' => 'index')); ?>",
      "fnServerData": function(sSource, aoData, fnCallback) {
        aoData.push({
          "name": "auditRndNo",
          "value": $("#auditRndNo").val()
        });
        aoData.push({
          "name": "dateRange",
          "value": $("#date").val()
        });
        aoData.push({
          "name": "testPoint",
          "value": $("#testPoint").val()
        });
        aoData.push({
          "name": "testPointName",
          "value": $("#testPointName").val()
        });
        aoData.push({
          "name": "affiliation",
          "value": $("#affiliation").val()
        });

        aoData.push({
          "name": "scoreLevel",
          "value": $("#scoreLevel").val()
        });
        aoData.push({
            "name": "country",
            "value": $("#country").val()
        });
        aoData.push({
          "name": "province",
          "value": $("#province").val()
        });
        aoData.push({
          "name": "district",
          "value": $("#district").val()
        });
        aoData.push({
          "name": "showAudits",
          "value": $("#showAudits").val()
        });
        $.ajax({
          "dataType": 'json',
          "type": "POST",
          "url": sSource,
          "data": aoData,
          "success": function(json) {
            $.unblockUI();
            $("#totalAudit").html(json.iTotalDisplayRecords);
            $("#avgAuditScore").html(json.avgAuditScore + "%");
            $("#level0").html(json.levelZeroCount);
            $("#level1").html(json.levelOneCount);
            $("#level2").html(json.levelTwoCount);
            $("#level3").html(json.levelThreeCount);
            $("#level4").html(json.levelFourCount + "&nbsp;");
            $("#duplicate").html("Duplicates (" + json.duplicate + ")");
            fnCallback(json);
          }
        });
      }
    });
    //
    //var table = $('#example').DataTable({"order": [[1, 'asc']]});
    //
    // Add event listener for opening and closing details
    $('#example').on('click', 'td.details-control', function() {
      var tr = $(this).closest('tr');
      var row = table.row(tr);

      if (row.child.isShown()) {
        // This row is already open - close it
        row.child.hide();
        tr.removeClass('shown');
      } else {
        // Open this row
        row.child(formatValue(tr.attr('id'))).show();
        tr.addClass('shown');
      }
    });

    $("#country").select2({
      width: '100%',
      placeholder: 'All',
      allowClear: true,
      tags: false
    });

    $("#province").select2({
      width: '100%',
      placeholder: 'All',
      allowClear: true,
      tags: false
    });

    $("#district").select2({
      width: '100%',
      placeholder: 'All',
      allowClear: true,
      tags: false
    });
    getLocations();
  });

  function approveStatus(id) {
    conf = confirm("<?= $this->translate('Are you sure you want to approve this audit ?'); ?>");
    if (conf) {
      $.post("<?php echo $this->url('spi-v6-form', array('action' => 'approve-status')); ?>", {
          id: id
        },
        function(data) {
          if (data > 0) {
            alert("<?= $this->translate('Audit updated successfully'); ?>");
            table.draw();
          }
        });
    }
  }

  function downloadPdf(formId) {
    window.open('<?php echo $this->url('spi-v6-form', array('action' => 'download-pdf')) ?>' + formId);
    return false;
  }

  function downloadCorrectiveActionPdf(formId) {
    window.open('<?php echo $this->url('spi-v6-form', array('action' => 'corrective-action-pdf')) ?>' + formId);
    return false;
  }

  function search() {
    $.blockUI({
      message: '<h1><?= $this->translate('Loading...'); ?></h1>'
    });
    table.draw();
  }

  function getTestingPointTypeNames() {
    $.blockUI();
    var testingPointType = $('#testPoint').val();
    $.post("<?php echo $this->url('spi-v6-form', array('action' => 'get-testing-point-type-names')); ?>", {
        testingPointType: testingPointType
      },
      function(data) {
        $('.testPointNameSection').html(data);
        $.unblockUI();
      });
  }

  function exportData() {
    $.blockUI();
    var dateRange = $('#date').val();
    var auditRndNo = $('#auditRndNo').val();
    var level = $('#level').val();
    var affiliation = $('#affiliation').val();
    //var province = $('#province').val();
    var scoreLevel = $('#scoreLevel').val();
    var testPoint = $('#testPoint').val();
    $.post("<?php echo $this->url('spi-v6-form', array('action' => 'export')); ?>", {
        dateRange: dateRange,
        auditRndNo: auditRndNo,
        level: level,
        affiliation: affiliation,
        // province: province,
        scoreLevel: scoreLevel,
        testPoint: testPoint
      },
      function(data) {
        // console.log(data);return false;
        if (data == "" || data == null || data == undefined) {
          $.unblockUI();
          alert('<?= $this->translate('Unable to generate download'); ?>');
        } else {
          console.log(data);
          $.unblockUI();
          document.location.href = '/temporary/' + data;
        }
      });
  }

  function exportSAndDData() {
    $.blockUI();
    var dateRange = $('#date').val();
    var auditRndNo = $('#auditRndNo').val();
    var level = $('#level').val();
    var affiliation = $('#affiliation').val();
    //var province = $('#province').val();
    var scoreLevel = $('#scoreLevel').val();
    var testPoint = $('#testPoint').val();
    $.post("<?php echo $this->url('spi-v6-form', array('action' => 'exportSAndD')); ?>", {
        dateRange: dateRange,
        auditRndNo: auditRndNo,
        level: level,
        affiliation: affiliation,
        // province: province,
        scoreLevel: scoreLevel,
        testPoint: testPoint
      },
      function(data) {
        if (data == "" || data == null || data == undefined) {
          $.unblockUI();
          alert('<?= $this->translate('Unable to generate download'); ?>');
        } else {
          console.log(data);
          $.unblockUI();
          document.location.href = '/temporary/' + data;
        }
      });
  }

  function exportPDFData() {
    // $.blockUI();
    var dateRange = $('#date').val();
    var auditRndNo = $('#auditRndNo').val();
    var level = $('#level').val();
    var affiliation = $('#affiliation').val();
    // var province = $('#province').val();
    // var district = $('#district').val();
    var scoreLevel = $('#scoreLevel').val();
    var testPoint = $('#testPoint').val();
    $.post("<?php echo $this->url('spi-v6-form', array('action' => 'export-as-pdf')); ?>", {
        dateRange: dateRange,
        auditRndNo: auditRndNo,
        level: level,
        affiliation: affiliation,
        //province: province,
        //district: district,
        scoreLevel: scoreLevel,
        testPoint: testPoint
      },
      function(data) {
        console.log(data);
        if (data == "" || data == null || data == undefined) {
          $.unblockUI();
          alert('<?= $this->translate('Unable to generate download'); ?>');
        } else {
          $.unblockUI();
          window.open('/temporary/' + data, '_blank');
        }
      });
  }

  function exportSearchPDFData() {
    $.blockUI();
    var dateRange = $('#date').val();
    var auditRndNo = $('#auditRndNo').val();
    var level = $('#level').val();
    var affiliation = $('#affiliation').val();
    //var province = ($('#province').val() == null) ? '' : $('#province').val();
    //var district = ($('#district').val() == null) ? '' : $('#district').val();
    var scoreLevel = $('#scoreLevel').val();
    var testPoint = $('#testPoint').val();
    //var testPointName = ($('#testPointName').length > 0) ? $('#testPointName').val() : '';
    $.post("<?php echo $this->url('spi-v6-form', array('action' => 'save-download-data')); ?>", {
        dateRange: dateRange,
        auditRndNo: auditRndNo,
        level: level,
        affiliation: affiliation,
        //province: province,
        //district: district,
        scoreLevel: scoreLevel,
        testPoint: testPoint

        //testPointName: testPointName
      },
      function(data) {
        if (data == "" || data == null || data == undefined) {
          $.unblockUI();
          alert('<?= $this->translate('Unable to generate download'); ?>');
        } else {
          $.unblockUI();
          alert('<?= $this->translate('Your download is processing'); ?>');
        }
      });
  }

  function getDistrictList() {
    $.blockUI();
    $.post("<?php echo $this->url('spi-v6-form', array('action' => 'get-district-based-province')); ?>", {
        provinceId: $("#province").val()
      },
      function(data) {
        $.unblockUI();
        $('#district').html(data);
      });
  }

  function getLocations() {
    var mappingType = <?php echo json_encode($userMappingType); ?>;

    var types = ['country', 'province', 'district'];
    if(mappingType != ""){
      types.forEach(function(type) {
          if (mappingType === 'country' && (type === 'country' || type === 'province' || type === 'district')) {
              $("." + type).show();
          } else if (mappingType === 'province' && type === 'province') {
              $("." + type).show();
          } else if (mappingType === 'district' && type === 'district') {
              $("." + type).show();
          } else {
              // Hide the type that doesn't match the mappingType
              $("." + type).hide();
              // Reset the select values for hidden fields
              $("." + type + " select").val([]);
          }
      });
    }
  }
</script>
