<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/lib/select2/css/select2.min.css'); ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/css/dataTables.bootstrap.min.css'); ?>"/>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/daterangepicker-bs3.css'); ?>" type="text/css"/>

<link rel="stylesheet" href="<?php echo $this->basePath('assets/css/jquery.multiselect.css'); ?>" type="text/css"/>
<script src="<?php echo $this->basePath('assets/js/jquery.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery-ui.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/js/jquery.multiselect.js'); ?>" type="text/javascript"></script>

<div class="am-content">
    <div class="page-head">
        <h2>Add  a ReCertification</h2>
    </div>


    <div class="main-content">
        <div class="widget widget-fullwidth widget-small" style="padding:5px;">
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body" >



                            <?php
                            $form->setAttribute('action', $this->url('recertification', array('action' => 'edit', 'recertification_id'=>$this->recertification_id)));
                            $form->prepare();
                            
                            $form->get('due_date')->setAttributes([
                                'class' => 'form-control',
//                                'value' => $this->id,
//                                'readonly' => true,
                                'autocomplete' => 'off',
                            ]);
                            $form->get('certification_id')->setAttributes([
                                'class' => 'form-control',
                                'autocomplete' => 'off',
                                
                            ]);

                            $form->get('reminder_type')->setAttributes([
                                'class' => 'form-control',
                                'autocomplete' => 'off',
                                ]);
                            
                            $form->get('reminder_sent_to')->setAttributes([
                                'class' => 'form-control',
                                'autocomplete' => 'off',
                                ]);

                            $form->get('name_of_recipient')->setAttributes([
                                'class' => 'form-control',
                                'autocomplete' => 'off',
                                ]);
                            $form->get('date_reminder_sent')->setAttributes([
                                'class' => 'form-control',
                                'autocomplete' => 'off',
                                ]);
                            
                            
                            echo $this->form()->openTag($form);
                            ?>
                            <?php echo $this->formHidden($form->get('recertification_id')->setAttribute('class', 'form-control')) ?>
                             <div class="form-group col-lg-6"> 
                                <?= $this->formLabel($form->get('due_date')); ?>
                                <?= $this->formElement($form->get('due_date')); ?>
                                <?= $this->formElementErrors($form->get('due_date')); ?>
                            </div>
                            <div class="form-group col-lg-6"> 
                                <?= $this->formLabel($form->get('certification_id')); ?>
                                <?= $this->formElement($form->get('certification_id')); ?>
                                <?= $this->formElementErrors($form->get('certification_id')); ?>
                            </div>
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('reminder_type')); ?>
                                <?= $this->formElement($form->get('reminder_type')); ?>
                                <?= $this->formElementErrors($form->get('reminder_type')); ?>
                            </div>
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('reminder_sent_to')); ?>
                                <?= $this->formElement($form->get('reminder_sent_to')); ?>
                                <?= $this->formElementErrors($form->get('reminder_sent_to')); ?>
                            </div>
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('name_of_recipient')); ?>
                                <?= $this->formElement($form->get('name_of_recipient')); ?>
                                <?= $this->formElementErrors($form->get('name_of_recipient')); ?>
                            </div>
                            <div class="form-group col-lg-6">
                                <?= $this->formLabel($form->get('date_reminder_sent')); ?>
                                <?= $this->formElement($form->get('date_reminder_sent')); ?>
                                <?= $this->formElementErrors($form->get('date_reminder_sent')); ?></div>
                            
                           
                            <div class="form-group col-lg-6" style="margin-top: 30px"><?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn  btn-space btn-primary')); ?>
                                 <a class="btn  btn-space btn-default" role="button" href="<?php echo $this->url('recertification', array('action' => 'index')); ?>" >CANCEL</a> </div>
                                <?php echo $this->form()->closeTag();
                                ?>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <br>
        <br>

    </div>

</div>

</script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places"></script>

<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/lib/select2/js/select2.min.js'); ?>" type="text/javascript"></script>


<script src="<?php echo $this->basePath('assets/js/highcharts.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/highcharts-more.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/pattern-fill.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->basePath('assets/js/jquery.dataTables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/dataTables.bootstrap.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('assets/js/daterangepicker.js'); ?>" type="text/javascript"></script>




