      <div class="am-content">
        <div class="main-content">
          <!--+general-chart("classes", "title", "height", "id", "counter value", "counter desc", tools enabled (use true or false))-->
          <div class="row">
            <div class="col-md-4">
              <div class="widget widget-pie">
                <div class="widget-head"><span class="title">SPI Form v3 Overall</span></div>
                <div class="row chart-container">
                  <div class="col-md-6">
                    <div id="widget-top-1" class="chart" style="height:170px"></div>
                  </div>
                  <div class="col-md-6">
                    <div class="legend"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="widget widget-pie">
                <div class="widget-head"><span class="title">SPI Form v3 Last 30 days</span></div>
                <div class="row chart-container">
                  <div class="col-md-6">
                    <div id="widget-top-2" class="chart" style="height:170px"></div>
                  </div>
                  <div class="col-md-6">
                    <div class="legend"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="widget widget-pie widget-pie-stats">
                <div class="widget-head"><span class="title">SPI Form v3 Last 180 days</span></div>
                <div class="row chart-container">
                  <div class="col-md-6">
                    <div id="widget-top-3" class="chart" style="height:170px"></div>
                  </div>
                  <div class="col-md-6">
                    <div class="legend">
                     
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="widget widget-map">
                <div class="widget-head"><span class="title"></span></div>
                <div class="map-container">
                  <div class="gmap" id="gmap" style="height: 400px;"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM&libraries=drawing,geometry,places">
</script>
<script src="<?php echo $this->basePath('assets/js/maplace.min.js'); ?>" type="text/javascript"></script>
    <script type="text/javascript">
      
      var color1 = "red";
      var color2 = "orange";
      var color3 = "yellow";
      var color4 = "#8DD63E";
      var color5 = "#528A16";
      
function widget_top_1(){
	    var data = [
	    	{ label: "Level 0 (Below 40)", data: <?php echo $perf1[0]['level0']; ?> },
	    	{ label: "Level 1 (40-60)", data: <?php echo $perf1[0]['level1']; ?> },
	    	{ label: "Level 2 (60-80)", data: <?php echo $perf1[0]['level2']; ?> },
	    	{ label: "Level 3 (80-90)", data: <?php echo $perf1[0]['level3']; ?> },
	    	{ label: "Level 4 (90 and above)", data: <?php echo $perf1[0]['level4']; ?> }
	    ];
        
        

      var legendContainer = $("#widget-top-1").parent().next().find(".legend");

	    $.plot('#widget-top-1', data, {
		    series: {
					pie: {
						show: true,
						highlight: {
							opacity: 0.1
						}
		      }
		    },
		    grid:{
		    	hoverable: true
		    },
		    legend:{
		    	container: legendContainer
		    },
            colors: [ color1, color2, color3, color4, color5]  
			});        
        
        
        
    }
    
    function widget_top_2(){
	    var dataLast30 = [
	    	{ label: "Level 0 (Below 40)", data: <?php echo $perflast30[0]['level0']; ?> },
	    	{ label: "Level 1 (40-60)", data: <?php echo $perflast30[0]['level1']; ?> },
	    	{ label: "Level 2 (60-80)", data: <?php echo $perflast30[0]['level2']; ?> },
	    	{ label: "Level 3 (80-90)", data: <?php echo $perflast30[0]['level3']; ?> },
	    	{ label: "Level 4 (90 and above)", data: <?php echo $perflast30[0]['level4']; ?> }
	    ];
        var legendContainer = $("#widget-top-2").parent().next().find(".legend");
	    $.plot('#widget-top-2', dataLast30, {
		    series: {
					pie: {
						show: true,
						highlight: {
							opacity: 0.1
						}
		      }
		    },
		    grid:{
		    	hoverable: true
		    },
		    legend:{
		    	container: legendContainer
		    },
            colors: [ color1, color2, color3, color4, color5]  
			});
    }
    
    function widget_top_3(){
	    var dataLast180 = [
	    	{ label: "Level 0 (Below 40)", data: <?php echo $perflast180[0]['level0']; ?> },
	    	{ label: "Level 1 (40-60)", data: <?php echo $perflast180[0]['level1']; ?> },
	    	{ label: "Level 2 (60-80)", data: <?php echo $perflast180[0]['level2']; ?> },
	    	{ label: "Level 3 (80-90)", data: <?php echo $perflast180[0]['level3']; ?> },
	    	{ label: "Level 4 (90 and above)", data: <?php echo $perflast180[0]['level4']; ?> }
	    ];
        var legendContainer = $("#widget-top-3").parent().next().find(".legend");
	    $.plot('#widget-top-3', dataLast180, {
		    series: {
					pie: {
						show: true,
						highlight: {
							opacity: 0.1
						}
		      }
		    },
		    grid:{
		    	hoverable: true
		    },
		    legend:{
		    	container: legendContainer
		    },
            colors: [ color1, color2, color3, color4, color5]  
			});
    }
    
    
function world_map(){

      var color = "#95D9F0";

      $('#gmap').vectorMap({
        map: 'world_mill_en',
        backgroundColor: 'transparent',
        
        regionStyle: {
          initial: {
            fill: color,
          },
          hover: {
            "fill-opacity": 0.8
          }
        },
        markerStyle:{
            initial:{
              r: 10
            },
             hover: {
              r: 12,
              stroke: 'rgba(255,255,255,0.8)',
              "stroke-width": 4
            }
          },
          markers: [
			 <?php foreach($allSubmissions as $row) { ?>
              {
				latLng: [<?php echo $row['Latitude'] ?>, <?php echo $row['Longitude'] ?>],
				name: '<?php echo $row['facilityname'] ?>',
				style: {
				  fill: '#F07878',
				  stroke:'rgba(255,255,255,0.7)',
				  "stroke-width": 3
				  }
			  },
			  <?php } ?>
              
          ]
      });
    }    
      
	  
	var LocsA = [
	  <?php foreach($allSubmissions as $row) { ?>
		{
			lat: <?php echo $row['Latitude'] ?>,
			lon: <?php echo $row['Longitude'] ?>,
			title: '<?php echo $row['facilityname'] ?>',
			html: '<strong><?php echo $row['facilityname'] ?></strong>',
			animation: google.maps.Animation.DROP
		},
	  <?php } ?>
	];
	  
      
      $(document).ready(function(){
      	//initialize the javascript
        widget_top_1();
        widget_top_2();
        widget_top_3();
        //world_map();
		
		new Maplace({
		  locations: LocsA,
		  map_div: '#gmap',
	      controls_on_map: true,
		  map_options : {
			  mapTypeId: google.maps.MapTypeId.ROADMAP,
			  zoom: 4
		  }
		}).Load();
		

      });
    </script>